--[[
-- XUiLineArithmetic3PopupSettlementGridTarget.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-02-03 19:58:15
--]]

---@class XUiLineArithmetic3PopupSettlementGridTarget : XUiNode
---@field _Control XLineArithmetic3Control
---@field Normal UnityEngine.RectTransform
---@field Select UnityEngine.RectTransform
---@field TxtTargetOn UnityEngine.UI.Text
---@field TxtTargetOff UnityEngine.UI.Text
local XUiLineArithmetic3PopupSettlementGridTarget = XClass(XUiNode, "XUiLineArithmetic3PopupSettlementGridTarget")

--- 更新目标数据
---@param data XLineArithmetic3ControlDataStarDesc
function XUiLineArithmetic3PopupSettlementGridTarget:Update(data)
    if data.IsFinish then
        if self._IsFinish ~= true then
            self._IsFinish = true
            self:PlayAnimation("SelectEnable")
        end
        self.Normal.gameObject:SetActiveEx(false)
        self.Select.gameObject:SetActiveEx(true)
        self.TxtTargetOn.text = data.Desc
        if self.TxtTargetTl2 then
            self.TxtTargetTl2.text = XUiHelper.GetText("LineArithmeticTarget", data.Index)
        end
    else
        self._IsFinish = false
        self.Normal.gameObject:SetActiveEx(true)
        self.Select.gameObject:SetActiveEx(false)
        self.TxtTargetOff.text = data.Desc
        if self.TxtTargetTl1 then
            self.TxtTargetTl1.text = XUiHelper.GetText("LineArithmeticTarget", data.Index)
        end
    end
end

return XUiLineArithmetic3PopupSettlementGridTarget
