--[[
-- XUiTheatre6BubbleAttackDetail.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-03-25 14:08:57
--]]

---@class XUiTheatre6BubbleAttackDetail : XLuaUi
---@field _Control XTheatre6Control
---@field BubbleAttackDetail UnityEngine.RectTransform
---@field BtnClose XUiComponent.XUiButton
local XUiTheatre6BubbleAttackDetail = XLuaUiManager.Register(XLuaUi, "UiTheatre6BubbleAttackDetail")
local XUiPanelTheatre6AttackDetail = require("XUi/XUiTheatre6/Settlement/Panel/XUiPanelTheatre6AttackDetail")
function XUiTheatre6BubbleAttackDetail:OnAwake()
    self:InitComponents()
end

function XUiTheatre6BubbleAttackDetail:InitComponents()
    -- Button
    self.BtnClose:AddEventListener(function() self:Close() end)
    ---@type XUiPanelTheatre6AttackDetail
    self._AttackDetail = XUiPanelTheatre6AttackDetail.New(self.BubbleAttackDetail, self)
    self._AttackDetail:Open()
    
    if self._AttackDetail.BtnClose then
        self._AttackDetail.BtnClose.gameObject:SetActiveEx(false)
    end
end

function XUiTheatre6BubbleAttackDetail:OnStart(skillId, target)
    self._AttackDetail:Refresh(skillId)
    XUiHelper.ShowBubbleToTarget(self._AttackDetail.PanelDetail.transform, target, self.Transform)
end

function XUiTheatre6BubbleAttackDetail:OnEnable()
end

function XUiTheatre6BubbleAttackDetail:OnDisable()
    XEventManager.DispatchEvent(XEventId.EVENT_THEATRE6_SKILL_BUBBLE_CLOSE)
end

function XUiTheatre6BubbleAttackDetail:OnDestroy()
end

function XUiTheatre6BubbleAttackDetail:Refresh()
end



return XUiTheatre6BubbleAttackDetail
