--[[
-- XUiLineArithmetic3PopupSettlement.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-02-03 19:58:14
--]]

local XUiLineArithmetic3PopupSettlementGridTarget = require("XUi/XUiLineArithmetic3/XUiLineArithmetic3PopupSettlement/XUiLineArithmetic3PopupSettlementGridTarget")

---@class XUiLineArithmetic3PopupSettlement : XLuaUi
---@field _Control XLineArithmetic3Control
---@field TxtTitle UnityEngine.UI.Text
---@field GridTarget UnityEngine.RectTransform
---@field BtnNext XUiButton
---@field BtnAgain XUiButton
---@field BtnTanchuangCloseBig XUiButton
---@field RImgCharacter UnityEngine.UI.RawImage
---@field TxtSpeak UnityEngine.UI.Text
local XUiLineArithmetic3PopupSettlement = XLuaUiManager.Register(XLuaUi, "UiLineArithmetic3PopupSettlement")

function XUiLineArithmetic3PopupSettlement:Ctor()
    ---@type XUiLineArithmetic3PopupSettlementGridTarget[]
    self._StarGrids = {}
end

function XUiLineArithmetic3PopupSettlement:OnAwake()
    self.GridTarget.gameObject:SetActiveEx(false)
    XUiHelper.RegisterClickEvent(self, self.BtnTanchuangCloseBig, self.OnClickClose)
    XUiHelper.RegisterClickEvent(self, self.BtnNext, self.OnClickNext)
    XUiHelper.RegisterClickEvent(self, self.BtnAgain, self.OnClickAgain)
end

function XUiLineArithmetic3PopupSettlement:OnStart()
    self:UpdateStarTarget()
    self:UpdateDesc()
end

function XUiLineArithmetic3PopupSettlement:UpdateStarTarget()
    self._Control:UpdateStarTarget()

    local uiData = self._Control:GetUiData()
    local stars = uiData.StarDescData

    for i = 1, #stars do
        local starDesc = stars[i]
        local uiGrid = self._StarGrids[i]
        if not uiGrid then
            local ui = CS.UnityEngine.Object.Instantiate(self.GridTarget, self.GridTarget.parent)
            uiGrid = XUiLineArithmetic3PopupSettlementGridTarget.New(ui, self)
            self._StarGrids[i] = uiGrid
        end
        uiGrid:Open()
        uiGrid:Update(starDesc)
    end
    for i = #stars + 1, #self._StarGrids do
        local uiGrid = self._StarGrids[i]
        uiGrid:Close()
    end
end

function XUiLineArithmetic3PopupSettlement:OnClickAgain()
    self._Control:RestartCurrentStage()
    XEventManager.DispatchEvent(XEventId.EVENT_LINE_ARITHMETIC_UPDATE_GAME)
    self:Close()
end

function XUiLineArithmetic3PopupSettlement:OnClickNext()
    self._Control:ChallengeNextStage()
end

function XUiLineArithmetic3PopupSettlement:OnClickClose()
    self:Close()
    XLuaUiManager.Close("UiLineArithmetic3Game")
end

function XUiLineArithmetic3PopupSettlement:UpdateDesc()
    self._Control:UpdateSettleDesc()
    local uiData = self._Control:GetUiData()
    if self.RImgCharacter then
        self.RImgCharacter:SetRawImage(uiData.Settle.RoleIcon)
    end
    if self.TxtSpeak then
        self.TxtSpeak.text = uiData.Settle.Tip
    end
end

function XUiLineArithmetic3PopupSettlement:OnEnable()
end

function XUiLineArithmetic3PopupSettlement:OnDisable()
end

function XUiLineArithmetic3PopupSettlement:OnDestroy()
end

return XUiLineArithmetic3PopupSettlement
