--region Global
require("XManager/XUi/XLuaUiManager") --Global
require("XManager/XUIEventBind") --Global
require("XManager/XUiManager") --Global
require("XManager/XUserManager") --Global
require("XManager/CsCallLua") --Global
require("XManager/XAgreementManager") --Global
require("XManager/XAppEventManager") --Global
require("XManager/XAttribManager") --Global
require("XManager/XConditionManager") --Global
require("XManager/XDataCenter") --Global
require("XManager/XDeeplinkManager") --Global
require("XManager/XEventManager") --Global
require("XManager/XFightCharacterManager") --Global
require("XManager/XFightEquipManager") --Global
require("XManager/XFightPartnerManager") --Global
require("XManager/XFightUiManager") --Global
require("XManager/XFunctionManager") --Global
require("XManager/XGmTestManager") --Global
require("XManager/XGoodsCommonManager") --Global
require("XManager/XHardwareManager") --Global
require("XManager/XHaruUserManager") --Global
require("XManager/XHeroSdkManager") --Global
require("XManager/XHudManager") --Global
require("XManager/XKeyPadManager") --Global
require("XManager/XLoginManager") --Global
require("XManager/XLuaAudioManager") --Global
require("XManager/XLuaVideoManager") --Global
require("XManager/XMagicSkillManager") --Global
require("XManager/XModelManager") --Global
require("XManager/XNotifyManager") --Global
require("XManager/XOverseaManager") --Global
require("XManager/XPgsAchievementManager") --Global
require("XManager/XPermissionManager") --Global
require("XManager/XPlatformShareManager") --Global
require("XManager/XPlayerManager") --Global
require("XManager/XQuitHandler") --Global
require("XManager/XRedPointManager") --Global
require("XManager/XResetManager") --Global
require("XManager/XRewardManager") --Global
require("XManager/XRobotManager") --Global
require("XManager/XRoomSingleManager") --Global
require("XManager/XRTextureManager") --Global
require("XManager/XServerManager") --Global
require("XManager/XShopManager") --Global
require("XManager/XTableManager") --Global
require("XManager/XTipManager") --Global
require("XManager/XTypeManager") --Global
--endregion Global

--region XDataCenter
require("XManager/XAccumulatedConsumeManager") --XDataCenter
require("XManager/XAchievement/XAchievementManager") --XDataCenter
require("XManager/XActivityBriefManager") --XDataCenter
require("XManager/XActivityCalendarManager") --XDataCenter
require("XManager/XActivityManager") --XDataCenter
require("XManager/XAntiAddictionManager") --XDataCenter
require("XManager/XAreaWarManager") --XDataCenter
require("XManager/XAssistManager") --XDataCenter
require("XManager/XAutoFightManager") --XDataCenter
require("XManager/XAutoWindowManager") --XDataCenter
require("XManager/XBackManager") --XDataCenter
--require("XManager/XBaseEquipManager") --XDataCenter
require("XManager/XBfrtManager") --XDataCenter
require("XManager/XBiancaTheatreManager") --XDataCenter
require("XManager/XBodyCombineGameManager") --XDataCenter
require("XManager/XBountyTaskManager") --XDataCenter
require("XManager/XCdKeyManager") --XDataCenter
require("XManager/XChatManager") --XDataCenter
require("XManager/XChristmasTreeManager") --XDataCenter
require("XManager/XClickClearGameManager") --XDataCenter
require("XManager/XCloudGameManager") --XDataCenter
require("XManager/XCollectionWallManager") --XDataCenter
require("XManager/XColorTableManager") --XDataCenter
require("XManager/XComeAcrossManager") --XDataCenter
require("XManager/XCommonCharacterFiltManager") --XDataCenter
require("XManager/XComposeGameManager") --XDataCenter
require("XManager/XCoupletGameManager") --XDataCenter
require("XManager/XCourseManager") --XDataCenter
require("XManager/XDiceGameManager") --XDataCenter
require("XManager/XDisplayManager") --XDataCenter
require("XManager/XDlcHuntAttrManager") --XDataCenter
require("XManager/XDlcHuntCharacterManager") --XDataCenter
require("XManager/XDlcHuntChipManager") --XDataCenter
require("XManager/XDlcHuntManager") --XDataCenter
require("XManager/XDlcRoomManager") --XDataCenter
require("XManager/XDoomsdayManager") --XDataCenter
require("XManager/XDormManager") --XDataCenter
require("XManager/XDormQuestManager") --XDataCenter
require("XManager/XDrawManager") --XDataCenter
require("XManager/XEliminateGameManager") --XDataCenter
require("XManager/XEquipGuideManager") --XDataCenter
require("XManager/XEscapeManager") --XDataCenter
require("XManager/XExhibitionManager") --XDataCenter
require("XManager/XFashionManager") --XDataCenter
require("XManager/XFightInfestorExploreManager") --XDataCenter
require("XManager/XFightWordsManager") --XDataCenter
require("XManager/XFingerGuessingManager") --XDataCenter
require("XManager/XFubenActivityBossSingleManager") --XDataCenter
require("XManager/XFuBenActivityPuzzleManager") --XDataCenter
require("XManager/XFubenAssignManager") --XDataCenter
require("XManager/XFubenAwarenessManager") --XDataCenter
require("XManager/XFubenBabelTowerManager") --XDataCenter
require("XManager/XFubenCharacterTowerManager") --XDataCenter
require("XManager/XFubenDailyManager") --XDataCenter
require("XManager/XFubenExperimentManager") --XDataCenter
require("XManager/XFubenExploreManager") --XDataCenter
require("XManager/XFubenExtraChapterManager") --XDataCenter
require("XManager/XFubenFestivalActivityManager") --XDataCenter
require("XManager/XFubenMainLineManager") --XDataCenter
require("XManager/XFubenManager") --XDataCenter
require("XManager/XFubenManagerEx") --XDataCenter
require("XManager/XFubenNewCharActivityManager") --XDataCenter
require("XManager/XFubenRepeatChallengeManager") --XDataCenter
require("XManager/XFubenResourceManager") --XDataCenter
require("XManager/XFubenShortStoryChapterManager") --XDataCenter
require("XManager/XFubenSpecialTrainManager") --XDataCenter
require("XManager/XFubenZhouMuManager") --XDataCenter
require("XManager/XFunctionalSkipManager") --XDataCenter
require("XManager/XFunctionCommunicationManager") --XDataCenter
require("XManager/XFunctionEventManager") --XDataCenter
require("XManager/XFurnitureManager") --XDataCenter
require("XManager/XGachaManager") --XDataCenter
require("XManager/XGuardCampManager") --XDataCenter
require("XManager/XGuideManager") --XDataCenter
require("XManager/XGuildBossManager") --XDataCenter
require("XManager/XGuildDorm/XGuildDormManager") --XDataCenter
require("XManager/XGuildManager") --XDataCenter
require("XManager/XGuildWar/XGuildWarManager") --XDataCenter
require("XManager/XHeadPortraitManager") --XDataCenter
require("XManager/XHitMouseManager") --XDataCenter
require("XManager/XHostelDelegateManager") --XDataCenter
require("XManager/XHostelManager") --XDataCenter
require("XManager/XInputManagerPc") --XDataCenter
require("XManager/XInvertCardGameManager") --XDataCenter
require("XManager/XItemManager") --XDataCenter
require("XManager/XKickOutManager") --XDataCenter
require("XManager/XKujiequManager") --XDataCenter
require("XManager/XLivWarmActivityManager") --XDataCenter
require("XManager/XLivWarmExtActivityManager") --XDataCenter
require("XManager/XLivWarmSoundsActivityManager") --XDataCenter
require("XManager/XLoadingManager") --XDataCenter
require("XManager/XLottoManager") --XDataCenter
require("XManager/XMaintainerActionManager") --XDataCenter
require("XManager/XMaverick2Manager") --XDataCenter
require("XManager/XMazeManager") --XDataCenter
require("XManager/XMedalManager") --XDataCenter
require("XManager/XMemorySaveManager") --XDataCenter
require("XManager/XMentorSystemManager") --XDataCenter
require("XManager/XMineSweepingManager") --XDataCenter
require("XManager/XMovieAssembleManager") --XDataCenter
require("XManager/XMovieManager") --XDataCenter
require("XManager/XNewbieTaskManager") --XDataCenter
require("XManager/XNewRegressionManager") --XDataCenter
require("XManager/XNewYearLuckManager") --XDataCenter
require("XManager/XNoticeManager") --XDataCenter
require("XManager/XPartnerManager") --XDataCenter
require("XManager/XPartnerTeachingManager") --XDataCenter
require("XManager/XPayManager") --XDataCenter
require("XManager/XPersonalInfoManager") --XDataCenter
require("XManager/XPhotographManager") --XDataCenter
require("XManager/XPickFlipManager") --XDataCenter
require("XManager/XPivotCombatManager") --XDataCenter
require("XManager/XPlayerInfoManager") --XDataCenter
require("XManager/XPokerGuessingManager") --XDataCenter
require("XManager/XPracticeManager") --XDataCenter
require("XManager/XPrequelManager") --XDataCenter
require("XManager/XPurchaseManager") --XDataCenter
require("XManager/XPuzzleActivityManager") --XDataCenter
require("XManager/XQualityManager") --XDataCenter
require("XManager/XReform2ndManager") --XDataCenter
require("XManager/XRegression3rdManager") --XDataCenter
require("XManager/XRegressionManager") --XDataCenter
require("XManager/XReportManager") --XDataCenter
require("XManager/XRoomCharFilterTipsManager") --XDataCenter
require("XManager/XRoomManager") --XDataCenter
require("XManager/XRpgMakerGameManager") --XDataCenter
require("XManager/XRpgTowerManager") --XDataCenter
require("XManager/XSameColorGameActivityManager") --XDataCenter
require("XManager/XScratchTicketManager") --XDataCenter
require("XManager/XSetManager") --XDataCenter
require("XManager/XSignInManager") --XDataCenter
require("XManager/XSkinVoteManager") --XDataCenter
require("XManager/XSlotMachineManager") --XDataCenter
require("XManager/XSocialManager") --XDataCenter
require("XManager/XSpecialShopManager") --XDataCenter
require("XManager/XSpringFestivalActivityManager") --XDataCenter
require("XManager/XStrongholdManager") --XDataCenter
require("XManager/XSummerSignInManager") --XDataCenter
require("XManager/XTaskForceManager") --XDataCenter
require("XManager/XTaskManager") --XDataCenter
require("XManager/XTeamManager") --XDataCenter
require("XManager/XTheatreManager") --XDataCenter
require("XManager/XTransfiniteManager") --XDataCenter
require("XManager/XTrialManager") --XDataCenter
require("XManager/XTRPGManager") --XDataCenter
require("XManager/XUiPcManager") --XDataCenter
require("XManager/XUiQueueManager") --XDataCenter
require("XManager/XUploadLogManager") --XDataCenter
require("XManager/XVoteManager") --XDataCenter
require("XManager/XWeaponFashionManager") --XDataCenter
require("XManager/XWeekChallengeManager") --XDataCenter
require("XManager/XWhiteValentineManager") --XDataCenter
require("XManager/XSuperSmashBrosManager") --XDataCenter
--endregion XDataCenter

--region Local - 不需要初始就require
--require("XManager/XGuildDorm/XGuildDormMapGridManager") --Local
--require("XManager/XGuildDorm/XGuildDormSceneManager") --Local
--require("XManager/XTableLoaders/XTableBytesLoader") --Local
--require("XManager/XTableLoaders/XTableLoadRouter") --Local
--require("XManager/XTableLoaders/XTablePackLoader") --Local
--require("XManager/XTableLoaders/XTableTabLoader") --Local
--endregion Local

--region 代码屏蔽
--require("XManager/XChessPursuitManager") --已经屏蔽
--require("XManager/XDoubleTowersManager") --已经屏蔽
--require("XManager/XExpeditionManager") --已经屏蔽
--require("XManager/XFubenActivityBranchManager") --已经屏蔽
--require("XManager/XFubenCoupleCombatManager") --已经屏蔽
--require("XManager/XFubenHackManager") --已经屏蔽
--require("XManager/XFubenInfestorExploreManager") --已经屏蔽
--require("XManager/XFubenRogueLikeManager") --已经屏蔽
--require("XManager/XFubenSimulatedCombatManager") --已经屏蔽
--require("XManager/XFubenUnionKillManager") --已经屏蔽
--require("XManager/XFubenUrgentEventManager") --已经屏蔽
--require("XManager/XKillZoneManager") --已经屏蔽
--require("XManager/XLivWarmRaceManager") --已经屏蔽
--require("XManager/XMaverickManager") --已经屏蔽
--require("XManager/XMonsterCombatManager") --已经屏蔽
--require("XManager/XNieRManager") --已经屏蔽
--require("XManager/XPlanetExploreManager") --已经屏蔽
--require("XManager/XPlanetManager") --已经屏蔽
--require("XManager/XReformActivityManager") --已经屏蔽
--require("XManager/XStoryManager") --已经屏蔽

--require("XManager/XWorldBossManager") --已经屏蔽
--require("XManager/XMoeWarManager") --XDataCenter --已经屏蔽
--require("XManager/XFubenUnionKillRoomManager") --已经屏蔽
--endregion 代码屏蔽