--[[
-- XUiLifeTreeCardGridRegularCard.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-03-02 14:53:19
--]]

local XUiLifeTreeCardGridCard = require("XUi/XUiLifeTree/XUiLifeTreeCard/XUiLifeTreeCardGridCard")
---@class XUiLifeTreeCardGridRegularCard : XUiLifeTreeCardGridCard
---@field _Control XLifeTreeControl
---@field Parent XUiLifeTreeCard
local XUiLifeTreeCardGridRegularCard = XClass(XUiLifeTreeCardGridCard, "XUiLifeTreeCardGridRegularCard")

function XUiLifeTreeCardGridRegularCard:OnStart(catalogId)
    self.CatalogId = catalogId
    
    self:InitComponents()
    self:Refresh()
    self:PlayEnableAnim()
end

function XUiLifeTreeCardGridRegularCard:OnEnable()
end

function XUiLifeTreeCardGridRegularCard:OnDisable()
end

function XUiLifeTreeCardGridRegularCard:OnDestroy()
end

function XUiLifeTreeCardGridRegularCard:InitComponents()
    self.Button:AddEventListener(function() self:OnBtnButtonClick() end)

    self:InitLine()
end

function XUiLifeTreeCardGridRegularCard:GetCardType()
    local catalogConfig = self._Control:GetLifeTreeCharacterCatalogConfigById(self.CatalogId)
    return catalogConfig.CardType
end

function XUiLifeTreeCardGridRegularCard:Refresh()
    self.ImgOffline.gameObject:SetActiveEx(false)
    self.ImgLocked.gameObject:SetActiveEx(false)
    self.ImgUnlocked.gameObject:SetActiveEx(false)
    self.EffectUnlock.gameObject:SetActiveEx(false)

    -- 角色状态
    local unlockCount, state = XMVCA.XLifeTree:GetCharacterStateByCatalogId(self.CatalogId) -- 解锁次数和状态
    local isOffline = state == XMVCA.XLifeTree.EnumConst.CHARACTER_STATE.OFFLINE -- 是否未上线
    local isUnlocked = unlockCount > 0
    local isUnlockable = state == XMVCA.XLifeTree.EnumConst.CHARACTER_STATE.NEXT_UNLOCKABLE -- 是否可解锁下一状态

    -- 刷新UI
    if isOffline then
        self.ImgOffline.gameObject:SetActiveEx(true)
    elseif isUnlocked then
        self.ImgUnlocked.gameObject:SetActiveEx(true)
        local catalogConfig = self._Control:GetLifeTreeCharacterCatalogConfigById(self.CatalogId)
        local icon = XMVCA.XCharacter:GetCharSmallHeadIcon(catalogConfig.CharacterId)
        self.RawImgCard:SetRawImage(icon)
        self.TxtName.text = catalogConfig.Name
        self.TxtDesc.text = catalogConfig.Descs[1]
    else
        self.ImgLocked.gameObject:SetActiveEx(true)
    end

    -- 可解锁特效
    self.EffectUnlock.gameObject:SetActiveEx(isUnlockable)
end

function XUiLifeTreeCardGridRegularCard:OnBtnButtonClick()
    if self.Parent:IsCardInAnimPlaying() then return end

    local unlockCount, state = XMVCA.XLifeTree:GetCharacterStateByCatalogId(self.CatalogId) -- 解锁次数和状态
    if state == XMVCA.XLifeTree.EnumConst.CHARACTER_STATE.OFFLINE then
        local config = self._Control:GetLifeTreeClientConfigConfigById("OfflineTips")
        XUiManager.TipError(config.Values[1])
    elseif state == XMVCA.XLifeTree.EnumConst.CHARACTER_STATE.NEXT_UNLOCKABLE then
        local nextUnlockIndex = unlockCount + 1
        XMVCA.XLifeTree:RequestLifeTreeUnlockCharacter(self.CatalogId, nextUnlockIndex, function()
            self:OnCharacterUnlock(nextUnlockIndex) -- 解锁成功回调
        end)
    elseif state == XMVCA.XLifeTree.EnumConst.CHARACTER_STATE.NEXT_LOCKED then
        XLuaUiManager.Open("UiLifeTreeUnlockType", self.CatalogId)
    end
end

-- 解锁成功回调
function XUiLifeTreeCardGridRegularCard:OnCharacterUnlock(unlockIndex)
    self:PlayAnimation("AnimUnlock")
    self:Refresh()
end

return XUiLifeTreeCardGridRegularCard
