--[[
-- XUiLuckyTenant2GameAnimationGetScore.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2025-12-31 16:39:51
--]]

---@class XUiLuckyTenant2GameAnimationGetScore : XUiNode
local XUiLuckyTenant2GameAnimationGetScore = XClass(XUiNode, "XUiLuckyTenant2GameAnimationGetScore")

function XUiLuckyTenant2GameAnimationGetScore:OnAwake()
    self:InitComponents()
end

function XUiLuckyTenant2GameAnimationGetScore:InitComponents()
end

function XUiLuckyTenant2GameAnimationGetScore:OnStart(...)
    self:Update()
end

function XUiLuckyTenant2GameAnimationGetScore:OnEnable()
end

function XUiLuckyTenant2GameAnimationGetScore:OnDisable()
end

function XUiLuckyTenant2GameAnimationGetScore:OnDestroy()
end

function XUiLuckyTenant2GameAnimationGetScore:Update()
    self.TextGetScore.text = "+99999"
end

return XUiLuckyTenant2GameAnimationGetScore
