--[[
-- XUiLuckyTenant2GameUiLuckyTenant2ChessDetail.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2025-12-31 16:39:51
--]]

local XUiLuckyTenant2GameGridChess = require("XUi/XUiLuckyTenant2/XUiLuckyTenant2Game/XUiLuckyTenant2GameGridChess")
local XUiLuckyTenant2ChessGridBuff = require("XUi/XUiLuckyTenant2/XUiLuckyTenant2Chess/XUiLuckyTenant2ChessGridBuff")

---@class XUiLuckyTenant2GameUiLuckyTenant2ChessDetail : XUiNode
---@field _BagUI XLuaUi|nil 背包 UI 引用（如果此 Detail 来自背包界面）
---@field _Buffs XUiLuckyTenant2ChessGridBuff[] 状态列表（用于动态Buff列表）
---@field _GridChess XUiLuckyTenant2GameGridChess|nil GridChess组件引用
local XUiLuckyTenant2GameUiLuckyTenant2ChessDetail = XClass(XUiNode, "XUiLuckyTenant2GameUiLuckyTenant2ChessDetail")

function XUiLuckyTenant2GameUiLuckyTenant2ChessDetail:InitComponents()
    -- Button
    if self.BtnDelete then
        self.BtnDelete:AddEventListener(function() self:OnBtnDeleteClick() end)
    end

    -- XUiNode - 使用合并后的GridChess组件（支持游戏界面和选棋界面）
    ---@type XUiLuckyTenant2GameGridChess
    if self.GridChess then
        self.GridChess = XUiLuckyTenant2GameGridChess.New(self.GridChess, self)
        -- 同时保存为_GridChess以兼容旧代码
        self._GridChess = self.GridChess
    end

    -- 统一使用动态Buff列表支持多个状态显示
    -- PanelBuff作为动态列表的模板
    if self.PanelBuff and self.PanelBuff.gameObject then
        self.PanelBuff.gameObject:SetActiveEx(false)
    end

    -- 初始化状态列表（用于动态Buff列表）
    self._Buffs = {}

    self.PanelNew = self.PanelNew or XUiHelper.TryGetComponent(self.Transform, "PanelNew", "RectTransform")
    if self.PanelNew then
        self.PanelNew.gameObject:SetActiveEx(false)
    end
end

function XUiLuckyTenant2GameUiLuckyTenant2ChessDetail:OnStart(...)
    self:InitComponents()
end

function XUiLuckyTenant2GameUiLuckyTenant2ChessDetail:OnEnable()
end

function XUiLuckyTenant2GameUiLuckyTenant2ChessDetail:OnDisable()
end

function XUiLuckyTenant2GameUiLuckyTenant2ChessDetail:OnDestroy()
end

---@param data table 棋子数据
function XUiLuckyTenant2GameUiLuckyTenant2ChessDetail:Update(data)
    if not data then
        return
    end

    self._Data = data

    -- 更新基本信息
    if self.TxtName then
        self.TxtName.text = data.Name or ""
    end

    if self.RImgIcon then
        self.RImgIcon:SetImage(data.Icon or "")
    end

    -- 更新品质
    if self.ImgQuality then
        if data.QualityValue then
            local qualityIcon = self._Control:GetQualityIconCircle(data.QualityValue)
            if qualityIcon then
                self.ImgQuality:SetSprite(qualityIcon)
            end
        elseif data.Quality and type(data.Quality) == "string" then
            self.ImgQuality:SetSprite(data.Quality)
        end
    end

    -- 更新详情背景（按品质ID取 BgChessDetail；Control 中 Quality 为图标路径，QualityValue 为品质ID）
    if self.BgChessQuality and data.QualityValue and self._Control then
        local bgPath = self._Control:GetChessDetailBgPath(data.QualityValue)
        if bgPath and bgPath ~= "" then
            self.BgChessQuality:SetImage(bgPath)
        end
    end

    if self.TxtCost then
        self.TxtCost.text = tostring(data.Value or 0)
    end

    -- 更新描述
    if self.TxtChessDoc then
        if data.Desc and type(data.Desc) == "table" and #data.Desc > 0 then
            self.TxtChessDoc.text = data.Desc[1] or ""
        elseif type(data.Desc) == "string" then
            self.TxtChessDoc.text = data.Desc
        else
            self.TxtChessDoc.text = ""
        end
    end

    -- 更新删除价值
    if self.TxtCostDeletion then
        self.TxtCostDeletion.text = tostring(data.ValueUponDeletion or 0)
    end

    -- 更新删除按钮
    if self.BtnDelete then
        -- 在game界面和选棋界面都不显示删除按钮
        self.BtnDelete.gameObject:SetActiveEx(false)
    end

    if self.TxtDeleteScore then
        self.TxtDeleteScore.text = tostring(data.ValueUponDeletion or 0)
    end

    local canDelete = data.CanBeEliminated
    if canDelete == nil then
        canDelete = data.IsCanDelete
    end
    local showDeleteCost = false
    if type(canDelete) == "number" then
        showDeleteCost = canDelete ~= 0
    else
        showDeleteCost = canDelete or false
    end
    local showCannotDelete = not showDeleteCost

    -- 更新提示文本
    if self.TxtTipsCannotBeEliminated then
        self.TxtTipsCannotBeEliminated.gameObject:SetActiveEx(showCannotDelete)
    end

    if self.TxtCostDeletion then
        self.TxtCostDeletion.gameObject:SetActiveEx(showDeleteCost)
        local parent = self.TxtCostDeletion.transform and self.TxtCostDeletion.transform.parent
        if parent and parent.gameObject then
            parent.gameObject:SetActiveEx(showDeleteCost)
        end
    end

    if self.TxtDeleteScore then
        self.TxtDeleteScore.gameObject:SetActiveEx(showDeleteCost)
        local parent = self.TxtDeleteScore.transform and self.TxtDeleteScore.transform.parent
        if parent and parent.gameObject then
            parent.gameObject:SetActiveEx(showDeleteCost)
        end
    end

    if self.PanelNoUpgrade then
        self.PanelNoUpgrade.gameObject:SetActiveEx(not (data.IsCanUpgrade or false))
    end
    
    -- 更新"新"标记
    if self.PanelNew then
        self.PanelNew.gameObject:SetActiveEx(data.IsNew or false)
    end

    -- 更新类型名称
    if self.TxtTag then
        self.TxtTag.text = data.TypeName or ""
    end

    -- 更新羁绊名称（game界面和背包界面都使用）
    if self.TxtBonds then
        local bondsText = data.BondsText
        -- 如果数据中没有羁绊名字，尝试从Control获取（game界面打开时）
        if bondsText == "" or not bondsText then
            bondsText = self._Control:GetPieceBondsTextByData(data)
        end
        if string.IsNilOrEmpty(bondsText) then
            self.TxtBonds.gameObject:SetActiveEx(false)
        else
            self.TxtBonds.text = bondsText or ""
            self.TxtBonds.gameObject:SetActiveEx(true)
        end
    end

    -- 更新羁绊图标（选棋界面使用）
    if self.IconBond then
        local bondIcon = data.BondIcon or ""
        if bondIcon ~= "" then
            if self.IconBond.SetImage then
                self.IconBond:SetImage(bondIcon)
            elseif self.IconBond.SetSprite then
                self.IconBond:SetSprite(bondIcon)
            end
        else
            if self.IconBond.SetImage then
                self.IconBond:SetImage("")
            elseif self.IconBond.SetSprite then
                self.IconBond:SetSprite("")
            end
        end
    end

    -- 更新GridChess
    if self._GridChess then
        self._GridChess:Update(data)
    end

    -- 更新Buff/PanelBuff - 统一使用动态Buff列表
    if self.PanelBuff then
        -- 获取状态列表
        local states = data.States or {}

        -- 如果数据中有单个状态信息，也转换为数组格式
        if #states == 0 and (data.StateType or data.TriggerState) then
            local stateData = {
                StateType = data.StateType or data.TriggerState or 0,
                Round = data.Round or data.RemainRound or data.StateRound or 0,
                Desc = XUiHelper.ReplaceTextNewLine(data.StateDesc or ""),
            }
            if stateData.StateType > 0 then
                states = { stateData }
            end
        end

        XTool.UpdateDynamicItem(self._Buffs, states, self.PanelBuff, XUiLuckyTenant2ChessGridBuff, self)
    end
end

function XUiLuckyTenant2GameUiLuckyTenant2ChessDetail:OnBtnDeleteClick(eventData)
    if not self._Data then
        return
    end

    -- 如果来自选棋界面，不执行删除
    if self._Data.IsFromSelectPiece then
        return
    end

    local uid = self._Data.Uid or 0
    self._Control:DeletePiece(uid)
end

---设置背包 UI 引用（用于标识此 Detail 来自背包界面）
---@param bagUI XLuaUi
function XUiLuckyTenant2GameUiLuckyTenant2ChessDetail:SetBagUI(bagUI)
    self._BagUI = bagUI
end

---获取背包 UI（如果此 Detail 来自背包界面）
---@return XLuaUi|nil
function XUiLuckyTenant2GameUiLuckyTenant2ChessDetail:GetBagUI()
    return self._BagUI
end

return XUiLuckyTenant2GameUiLuckyTenant2ChessDetail
