--[[
-- XUiLuckyTenant2GameUiLuckyTenant2Bonds.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2025-12-31 16:39:51
--]]

local XUiLuckyTenant2GameGridBonds = require("XUi/XUiLuckyTenant2/XUiLuckyTenant2Game/XUiLuckyTenant2GameGridBonds")
local XUiLuckyTenant2GameGridBondsIncome = require("XUi/XUiLuckyTenant2/XUiLuckyTenant2Game/XUiLuckyTenant2GameGridBondsIncome")
local XUiLuckyTenant2GameUiLuckyTenant2BondsDetail = require("XUi/XUiLuckyTenant2/XUiLuckyTenant2Game/XUiLuckyTenant2GameUiLuckyTenant2BondsDetail")
local XUiHelper = XUiHelper

-- 标签类型枚举
local TabType = {
    None = 0,
    Bonds = 1,  -- 羁绊面板
    Income = 2, -- 得分记录面板
}

---@class XUiLuckyTenant2GameUiLuckyTenant2Bonds : XUiNode
---@field PanelTab XUiButtonGroup 标签按钮组（包含 BtnTabBonds、BtnTabBondScoreRecord）
local XUiLuckyTenant2GameUiLuckyTenant2Bonds = XClass(XUiNode, "XUiLuckyTenant2GameUiLuckyTenant2Bonds")

function XUiLuckyTenant2GameUiLuckyTenant2Bonds:InitComponents()
    if self.PanelTab and self.BtnTabBonds and self.BtnTabBondScoreRecord then
        self.PanelTab:Init({ self.BtnTabBonds, self.BtnTabBondScoreRecord }, function(index)
            self:SwitchTab(index)
        end)
    else
        if self.BtnTabBonds then
            XUiHelper.RegisterClickEvent(self, self.BtnTabBonds, self.OnBtnTabBondsClick, nil, true)
        end
        if self.BtnTabBondScoreRecord then
            XUiHelper.RegisterClickEvent(self, self.BtnTabBondScoreRecord, self.OnBtnTabBondScoreRecordClick, nil, true)
        end
    end
    if self.GridBondsIncome then
        self.GridBondsIncome.gameObject:SetActiveEx(false)
    end

    -- 初始化羁绊详情面板
    if self.UiLuckyTenant2BondsDetail then
        self.UiLuckyTenant2BondsDetail.gameObject:SetActiveEx(false)
        ---@type XUiLuckyTenant2GameUiLuckyTenant2BondsDetail
        self._BondsDetail = XUiLuckyTenant2GameUiLuckyTenant2BondsDetail.New(self.UiLuckyTenant2BondsDetail, self)
        self._BondsDetail:Close()

        -- 初始化关闭按钮
        if self.BtnClose then
            self.BtnClose.gameObject:SetActiveEx(false)
            XUiHelper.RegisterClickEvent(self, self.BtnClose, self.OnBtnCloseClick, nil, true)
        end
    end
end

function XUiLuckyTenant2GameUiLuckyTenant2Bonds:OnDisable()
    -- 清空，否则会在从其他界面回来后，报错 “子节点 XUiLuckyTenant2GameGridBonds 显示后, activeInHierarchy依旧为false”
    if self._CurrentTabType == TabType.Bonds then
        if self.GridBondsIncome and self._BondsIncomeData then
            XTool.UpdateDynamicItem(self._BondsIncomeGrids, {}, self.GridBondsIncome, XUiLuckyTenant2GameGridBondsIncome, self)
        end
    elseif self._CurrentTabType == TabType.Income then
        if self.GridBonds and self._BondsData then
            XTool.UpdateDynamicItem(self._BondsGrids, {}, self.GridBonds, XUiLuckyTenant2GameGridBonds, self)
        end
    end
end

function XUiLuckyTenant2GameUiLuckyTenant2Bonds:OnStart(...)
    ---@type XUiLuckyTenant2GameGridBonds[]
    self._BondsGrids = {}
    ---@type XUiLuckyTenant2GameGridBondsIncome[]
    self._BondsIncomeGrids = {}

    -- 当前选中的标签类型，默认为 Bonds
    self._CurrentTabType = TabType.None

    -- 当前选中的羁绊BondId（使用BondId来追踪，避免Grid对象引用失效）
    ---@type number|nil
    self._SelectedBondId = nil

    -- 保存的数据
    self._BondsData = {}
    self._ScoreThisRound = 0
    self._BondsIncomeData = {}

    self:InitComponents()
    -- 默认选择 Bonds 面板
    self:SwitchTab(TabType.Bonds)
end

---切换标签
---@param tabType number 标签类型
function XUiLuckyTenant2GameUiLuckyTenant2Bonds:SwitchTab(tabType)
    if self._CurrentTabType == tabType then
        return
    end

    self._CurrentTabType = tabType

    -- 切换标签时清除选中状态
    self:ClearSelection()

    -- 更新面板显示
    if self.ListBonds then
        self.ListBonds.gameObject:SetActiveEx(tabType == TabType.Bonds)
    end
    if self.ListIncome then
        self.ListIncome.gameObject:SetActiveEx(tabType == TabType.Income)
    end

    -- 更新按钮状态（由 PanelTab 统一管理时同步选中索引）
    if self.PanelTab then
        self.PanelTab:SelectIndex(tabType)
    else
        if self.BtnTabBonds then
            self.BtnTabBonds:SetButtonState(tabType == TabType.Bonds and CS.UiButtonState.Select or CS.UiButtonState.Normal)
        end
        if self.BtnTabBondScoreRecord then
            self.BtnTabBondScoreRecord:SetButtonState(tabType == TabType.Income and CS.UiButtonState.Select or CS.UiButtonState.Normal)
        end
    end

    -- 切换标签后，更新当前标签的数据显示
    self:_UpdateCurrentTab()
end

---点击羁绊标签按钮
function XUiLuckyTenant2GameUiLuckyTenant2Bonds:OnBtnTabBondsClick()
    self:SwitchTab(TabType.Bonds)
end

---点击得分记录标签按钮
function XUiLuckyTenant2GameUiLuckyTenant2Bonds:OnBtnTabBondScoreRecordClick()
    self:SwitchTab(TabType.Income)
end

---刷新羁绊面板数据（统一从 Control 拉取 game 数据，选棋/背包/游戏界面均一致）
function XUiLuckyTenant2GameUiLuckyTenant2Bonds:Update()
    self._Control:UpdateBonds()
    self._Control:UpdateBondsIncome()
    local data = self._Control:GetUiData()
    local bondsData = (data and data.Bonds) or {}
    local scoreThisRound = (data and data.AddScore) or 0
    local bondsIncomeData = (data and data.BondsIncome) or {}

    self._BondsData = bondsData
    if scoreThisRound ~= nil then
        self._ScoreThisRound = scoreThisRound
    end
    self._BondsIncomeData = bondsIncomeData

    self:_UpdateCurrentTab()
end

---更新当前标签对应的面板
function XUiLuckyTenant2GameUiLuckyTenant2Bonds:_UpdateCurrentTab()
    if self._CurrentTabType == TabType.Bonds then
        -- 更新羁绊面板
        if self.GridBonds and self._BondsData then
            XTool.UpdateDynamicItem(self._BondsGrids, self._BondsData, self.GridBonds, XUiLuckyTenant2GameGridBonds, self)
            -- 恢复选中状态（根据BondId来恢复）
            if self._SelectedBondId then
                for i, grid in ipairs(self._BondsGrids) do
                    local bondData = self._BondsData[i]
                    if bondData and bondData.BondId == self._SelectedBondId then
                        grid:SetSelected(true)
                        break
                    end
                end
            end
        end
    elseif self._CurrentTabType == TabType.Income then
        -- 更新得分记录面板（只在有值时才更新，避免刷回0）
        if self.TxtScoreThisRound and self._ScoreThisRound ~= nil then
            self.TxtScoreThisRound.text = tostring(self._ScoreThisRound)
        end
        if self.GridBondsIncome and self._BondsIncomeData then
            XTool.UpdateDynamicItem(self._BondsIncomeGrids, self._BondsIncomeData, self.GridBondsIncome, XUiLuckyTenant2GameGridBondsIncome, self)
            -- 恢复选中状态（根据BondId来恢复）
            if self._SelectedBondId then
                for i, grid in ipairs(self._BondsIncomeGrids) do
                    local bondIncomeData = self._BondsIncomeData[i]
                    if bondIncomeData and bondIncomeData.BondId == self._SelectedBondId then
                        grid:SetSelected(true)
                        break
                    end
                end
            end
        end
    end
end

---设置选中的Grid（通过Grid对象，用于Bonds标签）
---@param grid XUiLuckyTenant2GameGridBonds|nil 要选中的Grid，传nil则取消选中
function XUiLuckyTenant2GameUiLuckyTenant2Bonds:SetSelectedGrid(grid)
    -- 先取消所有grid的选中状态（包括Bonds和Income）
    for _, g in ipairs(self._BondsGrids) do
        if g and g:IsValid() then
            g:SetSelected(false)
        end
    end
    for _, g in ipairs(self._BondsIncomeGrids) do
        if g and g:IsValid() then
            g:SetSelected(false)
        end
    end

    -- 设置新的选中grid
    if grid and grid:IsValid() and grid._Data then
        local bondId = grid._Data.BondId
        if bondId then
            self._SelectedBondId = bondId
            grid:SetSelected(true)
        end
    else
        self._SelectedBondId = nil
    end
end

---设置选中的Income Grid（通过Grid对象，用于Income标签）
---@param grid XUiLuckyTenant2GameGridBondsIncome|nil 要选中的Grid，传nil则取消选中
function XUiLuckyTenant2GameUiLuckyTenant2Bonds:SetSelectedIncomeGrid(grid)
    -- 先取消所有grid的选中状态（包括Bonds和Income）
    for _, g in ipairs(self._BondsGrids) do
        if g and g:IsValid() then
            g:SetSelected(false)
        end
    end
    for _, g in ipairs(self._BondsIncomeGrids) do
        if g and g:IsValid() then
            g:SetSelected(false)
        end
    end

    -- 设置新的选中grid
    if grid and grid:IsValid() and grid._Data then
        local bondId = grid._Data.BondId
        if bondId then
            self._SelectedBondId = bondId
            grid:SetSelected(true)
        end
    else
        self._SelectedBondId = nil
    end
end

---设置选中的BondId
---@param bondId number|nil 要选中的BondId，传nil则取消选中
function XUiLuckyTenant2GameUiLuckyTenant2Bonds:SetSelectedBondId(bondId)
    -- 先取消所有grid的选中状态（包括Bonds和Income）
    for _, grid in ipairs(self._BondsGrids) do
        if grid and grid:IsValid() then
            grid:SetSelected(false)
        end
    end
    for _, grid in ipairs(self._BondsIncomeGrids) do
        if grid and grid:IsValid() then
            grid:SetSelected(false)
        end
    end

    -- 设置新的选中BondId
    self._SelectedBondId = bondId

    -- 找到对应的grid并设置选中状态（根据当前标签类型）
    if bondId then
        if self._CurrentTabType == TabType.Bonds then
            -- 在Bonds列表中查找
            for i, grid in ipairs(self._BondsGrids) do
                local bondData = self._BondsData[i]
                if bondData and bondData.BondId == bondId then
                    grid:SetSelected(true)
                    break
                end
            end
        elseif self._CurrentTabType == TabType.Income then
            -- 在Income列表中查找
            for i, grid in ipairs(self._BondsIncomeGrids) do
                local bondIncomeData = self._BondsIncomeData[i]
                if bondIncomeData and bondIncomeData.BondId == bondId then
                    grid:SetSelected(true)
                    break
                end
            end
        end
    end
end

---根据BondId获取羁绊数据（用于Income标签点击时打开详情）
---@param bondId number 羁绊ID
---@return table|nil 羁绊数据
function XUiLuckyTenant2GameUiLuckyTenant2Bonds:GetBondDataByBondId(bondId)
    if not bondId then
        return nil
    end

    -- 从Bonds数据中查找
    for _, bondData in ipairs(self._BondsData) do
        if bondData and bondData.BondId == bondId then
            return bondData
        end
    end

    return nil
end

---取消选中状态
function XUiLuckyTenant2GameUiLuckyTenant2Bonds:ClearSelection()
    self:SetSelectedBondId(nil)
end

---打开羁绊详情面板
---@param data table 羁绊数据
function XUiLuckyTenant2GameUiLuckyTenant2Bonds:OpenBondsDetail(data)
    if not data then
        return
    end

    -- 打开详情面板
    if self._BondsDetail then
        self._BondsDetail:Open()
        self._BondsDetail:Update(data)
        -- 显示关闭按钮
        if self.BtnClose then
            self.BtnClose.gameObject:SetActiveEx(true)
        end
    end
end

---关闭羁绊详情面板
function XUiLuckyTenant2GameUiLuckyTenant2Bonds:CloseBondsDetail()
    if self._BondsDetail then
        self._BondsDetail:Close()
    end
    -- 隐藏关闭按钮
    if self.BtnClose then
        self.BtnClose.gameObject:SetActiveEx(false)
    end
    self:ClearSelection()
end

---关闭按钮点击事件
function XUiLuckyTenant2GameUiLuckyTenant2Bonds:OnBtnCloseClick()
    self:CloseBondsDetail()
end

return XUiLuckyTenant2GameUiLuckyTenant2Bonds
