--[[
-- XUiLuckyTenant2GameGridBondsChessRequire.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2025-12-31 16:39:51
--]]

local XUiHelper = XUiHelper

---@class XUiLuckyTenant2GameGridBondsChessRequire : XUiNode
local XUiLuckyTenant2GameGridBondsChessRequire = XClass(XUiNode, "XUiLuckyTenant2GameGridBondsChessRequire")

function XUiLuckyTenant2GameGridBondsChessRequire:OnStart()
   if self.Button then
        self.Button:AddEventListener(function() self:OnClick() end)
    end
end

---@param data table 棋子数据，包含 Id, Icon, Quality, IsOwned 等字段
function XUiLuckyTenant2GameGridBondsChessRequire:Update(data)
    self._Data = data
    if not data then
        return
    end
    
    -- 设置图标
    if self.RImgIcon then
        if self.RImgIcon.SetRawImage then
            self.RImgIcon:SetRawImage(data.Icon or "")
        elseif self.RImgIcon.SetImage then
            self.RImgIcon:SetImage(data.Icon or "")
        end
    end
    
    -- 设置品质
    if self.ImgQuality then
        if data.QualityValue and self._Control.GetQualityIconCircle then
            local qualityIcon = self._Control:GetQualityIconCircle(data.QualityValue)
            if qualityIcon then
                self.ImgQuality:SetSprite(qualityIcon)
            end
        elseif data.Quality and type(data.Quality) == "string" then
            self.ImgQuality:SetSprite(data.Quality)
        end
    end
    
    -- 设置未拥有标签
    if self.TagNotOwned then
        local isOwned = data.IsOwned or false
        self.TagNotOwned.gameObject:SetActiveEx(not isOwned)
    end
end

function XUiLuckyTenant2GameGridBondsChessRequire:OnClick()
    if not self.Parent or not self._Data then
        return
    end
    if self.Parent.OnChessRequireClick then
        self.Parent:OnChessRequireClick(self._Data)
    end
end

return XUiLuckyTenant2GameGridBondsChessRequire
