--[[
-- XUiLuckyTenant2GameAnimationGetItem.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2025-12-31 16:39:51
--]]

---@class XUiLuckyTenant2GameAnimationGetItem : XUiNode
local XUiLuckyTenant2GameAnimationGetItem = XClass(XUiNode, "XUiLuckyTenant2GameAnimationGetItem")

function XUiLuckyTenant2GameAnimationGetItem:OnAwake()
    self:InitComponents()
end

function XUiLuckyTenant2GameAnimationGetItem:InitComponents()
end

function XUiLuckyTenant2GameAnimationGetItem:OnStart(...)
    self:Update()
end

function XUiLuckyTenant2GameAnimationGetItem:OnEnable()
end

function XUiLuckyTenant2GameAnimationGetItem:OnDisable()
end

function XUiLuckyTenant2GameAnimationGetItem:OnDestroy()
end

function XUiLuckyTenant2GameAnimationGetItem:Update()
    self.IconGetItem:SetImage("")
end

return XUiLuckyTenant2GameAnimationGetItem
