--[[
-- XUiPBRMain.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-01-12 15:24:16
--]]

---@field _Control XPBRGameControl
---@class XUiPBRMain : XLuaUi
local XUiPBRMain = XLuaUiManager.Register(XLuaUi, "UiPBRMain")
local XUiPBRRoleModel = require('XUi/XUiPBRGame/XUiPBRCharacterDetail/XUiPBRRoleModel')
local XUiPanelPBRMainTitle = require("XUi/XUiPBRGame/XUiPBRMain/XUiPanelPBRMainTitle")

function XUiPBRMain:OnAwake()
    self:InitComponents()
end

function XUiPBRMain:InitComponents()
    -- Back Mainui Help
    self:BindExitBtns()
    self:BindHelpBtn(self.BtnHelp, self._Control:GetClientPBRText('CommonHelpKey'))

    -- Button
    self.BtnCollection:AddEventListener(function() self:OnBtnCollectionClick() end)
    self.BtnTask:AddEventListener(function() self:OnBtnTaskClick() end)
    self.BtnCharacter:AddEventListener(function() self:OnBtnCharacterClick() end)
    self.BtnGenius:AddEventListener(function() self:OnBtnGeniusClick() end)
    self.BtnFight:AddEventListener(function() self:OnBtnFightClick() end)
    self.BtnContinueFight:AddEventListener(function() self:OnBtnContinueFightClick() end)
    
    ---@type XUiPBRRoleModel
    self.RoleModel = XUiPBRRoleModel.New(self.GameObject, self)
    
    ---@type XUiPanelPBRMainTitle
    self.PanelTitle = XUiPanelPBRMainTitle.New(self.TittleEasterEgg, self)
    
    
    self._ContinueHandler = function()
        self._Control.InGameControl:ContinueGame()
    end
    
    self._SettleHandler = function()
        XMVCA.XPBRGame.NetworkAgency:DoPbrForceSettleRequest(function(success)
            self:RefreshAll()

            if success then
                XUiManager.TipMsg(self._Control:GetClientPBRText('SettleForceTips'))
            end
        end)
    end
end

function XUiPBRMain:OnStart(...)
    self.IsCheckUpdateScene = false
end

function XUiPBRMain:OnEnable()
    self._Control:AddTimeEventListener(self.OnActivityTimeTimerUpdate, self)
    self:RefreshAll()
end

function XUiPBRMain:OnDisable()
    self._Control:RemoveTimeEventListener(self.OnActivityTimeTimerUpdate, self)
end

function XUiPBRMain:OnDestroy()
end

function XUiPBRMain:RefreshAll()
    self:RefreshFightStatusShow()
    self:RefreshRewardPreview()
    self:RefreshReddot()
    self:RefreshRoleModel()
end

function XUiPBRMain:RefreshFightStatusShow()
    local isCanContinue = self._Control:GetIsHasLastFightProgress()

    self.BtnFight.gameObject:SetActiveEx(not isCanContinue)
    self.BtnContinueFight.gameObject:SetActiveEx(isCanContinue)

    if isCanContinue then
        -- 刷新描述
        local stageId = self._Control.InGameControl:GetCurrentLeaveStageAndCharId()
        local wave = self._Control.InGameControl:GetWaveInSegmentSettleData()
        
        local stageCfg = self._Control:GetStageCfgById(stageId)

        if stageCfg then
            local content = XUiHelper.FormatTextEx(self._Control:GetClientPBRText('UIMainProgress'), stageCfg.StageName, wave)
            
            self.BtnContinueFight:SetNameByGroup(0, content)
        end
    end
end

function XUiPBRMain:RefreshRewardPreview()
    local rewardList = self._Control:GetMainUIRewardPreview()

    if self._GridPreviewRewards == nil then
        self._GridPreviewRewards = {}
    end
    
    XUiHelper.RefreshCustomizedList(self.PanelItem, self.Grid256New, rewardList and #rewardList or 0, function(index, go)
        ---@type XUiGridCommon
        local grid = self._GridPreviewRewards[go]

        if not grid then
            grid = XUiHelper.XUiGridCommon(self, go)
            
            self._GridPreviewRewards[go] = grid
        end
        
        local rewardInfo = rewardList[index]
        
        grid:Refresh(rewardInfo)
        grid:SetReceived(rewardInfo.IsRecieved)
    end)
end

function XUiPBRMain:RefreshReddot()
    self.BtnTask:ShowReddot(XMVCA.XPBRGame:ReddotIsAnyTaskAchieved())
    self.BtnGenius:ShowReddot(XMVCA.XPBRGame:ReddotIsAnyGeniusNodeCanUnlock())
    
    local isAnyStageNewUnlock = XMVCA.XPBRGame:ReddotIsAnyStageNewUnlock()
    self.BtnFight:ShowReddot(isAnyStageNewUnlock)
    self.BtnContinueFight:ShowReddot(isAnyStageNewUnlock)
end

function XUiPBRMain:RefreshRoleModel()
    local cuteModelName = self._Control:GetCuteModelNameShowInMain()

    if not string.IsNilOrEmpty(cuteModelName) then
        self.RoleModel:InitShowCharacter(cuteModelName)
    end
end

--region EventListener

function XUiPBRMain:OnBtnCollectionClick()
    XLuaUiManager.Open('UiPBRCollection')
end

function XUiPBRMain:OnBtnTaskClick()
    XLuaUiManager.Open("UiPBRTask")
end

function XUiPBRMain:OnBtnCharacterClick()
    XLuaUiManager.Open("UiPBRCharacterDetail")
end

function XUiPBRMain:OnBtnGeniusClick()
    XLuaUiManager.Open('UiPBRGenius')
end

function XUiPBRMain:OnBtnFightClick()
    XLuaUiManager.Open("UiPBRChapter")
end

function XUiPBRMain:OnBtnContinueFightClick()
    XLuaUiManager.Open("UiPBRMainFightTips", self._ContinueHandler, self._SettleHandler)
end

function XUiPBRMain:OnActivityTimeTimerUpdate(timeId)
    local now = XTime.GetServerNowTimestamp()
    
    local endTime = XFunctionManager.GetEndTimeByTimeId(timeId)
    
    local leftTime = math.max(0, endTime - now)

    self.TxtTime.text = XUiHelper.GetTime(leftTime, XUiHelper.TimeFormatType.ACTIVITY)

    self:CheckUpdateScene()
end

-- 检查未退出战斗打开UI，等战斗退出了重新刷新UI场景
function XUiPBRMain:CheckUpdateScene()
    if not self.UiSceneInfo then
        return
    end
    
    if not self.IsCheckUpdateScene and XFightUtil.IsFighting() then
        self.IsCheckUpdateScene = true
    elseif self.IsCheckUpdateScene and not XFightUtil.IsFighting() then
        self.UiSceneInfo.GameObject:SetActiveEx(false)
        self.UiSceneInfo.GameObject:SetActiveEx(true)
        self.IsCheckUpdateScene = false
    end
end
--endregion

return XUiPBRMain
