--[[
-- XUiLuckyTenant2Toast.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2025-12-31 16:39:52
--]]

---@class XUiLuckyTenant2Toast : XLuaUi
---@field _Control XLuckyTenant2Control
local XUiLuckyTenant2Toast = XLuaUiManager.Register(XLuaUi, "UiLuckyTenant2Toast")

function XUiLuckyTenant2Toast:OnAwake()
    self._AutoCloseTimer = nil
end

function XUiLuckyTenant2Toast:OnStart(toastData)
    self._ToastData = toastData
    self:Update()

    -- 自动关闭：2秒后自动关闭
    self._AutoCloseTimer = XScheduleManager.ScheduleOnce(function()
        XLuaUiManager.SafeClose(self.Name)
    end, 2000)

    if self.BtnClose then
        self.BtnClose.gameObject:SetActiveEx(false)
    end
end

function XUiLuckyTenant2Toast:OnEnable()
end

function XUiLuckyTenant2Toast:OnDisable()
    -- 取消自动关闭定时器
    -- if self._AutoCloseTimer then
    --     XScheduleManager.UnSchedule(self._AutoCloseTimer)
    --     self._AutoCloseTimer = nil
    --     XLog.Error("XUiLuckyTenant2Toast:OnDisable self._AutoCloseTimer is not nil")
    -- end
end

function XUiLuckyTenant2Toast:OnDestroy()
    -- 取消自动关闭定时器
    if self._AutoCloseTimer then
        XScheduleManager.UnSchedule(self._AutoCloseTimer)
        self._AutoCloseTimer = nil
        XLog.Error("XUiLuckyTenant2Toast:OnDisable self._AutoCloseTimer is not nil")
    end
end

function XUiLuckyTenant2Toast:Update()
    if not self._ToastData then
        return
    end

    local bondName = self._ToastData.BondName or ""
    local oldLevel = self._ToastData.OldLevel or 0
    local newLevel = self._ToastData.NewLevel or 0
    local isUpgrade = newLevel > oldLevel

    -- 控制Panel显隐
    if isUpgrade then
        -- 等级提升：显示PanelUp，隐藏PanelDown
        self.PanelUp.gameObject:SetActiveEx(true)
        self.PanelDown.gameObject:SetActiveEx(false)
        self.TxtInfoUpgrade.text = XUiHelper.GetText("LuckyTenant2BondLevelUp", bondName, oldLevel, newLevel)
    else
        -- 等级降低：显示PanelDown，隐藏PanelUp
        self.PanelUp.gameObject:SetActiveEx(false)
        self.PanelDown.gameObject:SetActiveEx(true)
        self.TxtInfoDowngrade.text = XUiHelper.GetText("LuckyTenant2BondLevelDown", bondName, oldLevel, newLevel)
    end
end

function XUiLuckyTenant2Toast:OnDestroy()
    -- 取消自动关闭定时器
    if self._AutoCloseTimer then
        XScheduleManager.UnSchedule(self._AutoCloseTimer)
        self._AutoCloseTimer = nil
    end

    -- Toast关闭时，通知Control显示队列中的下一个Toast
    if self._Control then
        self._Control:ShowNextToast()
    end
end

return XUiLuckyTenant2Toast
