---
--- 阿尔法 法奥斯生态脚本
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ljb.
--- DateTime: 2026/3/18 12:12
---

local Base = require("Character/BigWorld/XEcologyConstructAI/XEcologyConstructAIBase")
local BaseState = require("Character/BigWorld/XEcologyConstructAI/XEcologyConstructAIBaseState")
local FindPathState = require("Character/BigWorld/XEcologyConstructAI/XEcologyFindCombinePathState")

--region 阿尔法生态2.0期静态参数
---生态状态枚举
local StateEnum = {
    None = 0,
    ---全息状态
    Holographic= 1,
}
---数据黑板key值
local DataBoardKey = {
    None = 0,
    ---全息状态
    Holographic= 1,
}
--endregion


--region 状态-阿尔法-全息
---@class XAlphaHolographicState: XEcologyConstructAIBaseState
local XAlphaHolographicState = XClass(BaseState, "XAlphaHolographicState")

---数据配置
---@overload
function XAlphaHolographicState:InitStateConfig()
    self.StateConfig = {}
    self.StateConfig.StateEnum = StateEnum.Holographic
    self.StateConfig.StateLoopAnim = "Drama_Stand_01"
    self.StateConfig.TriggerId = 1
    self.StateConfig.ShowOptionId = 1
    self.StateConfig.RegisterWorldEventList = {
        EWorldEvent.ActorTrigger,
        EWorldEvent.NpcInteractStart,
        EWorldEvent.NpcInteractComplete,
        EWorldEvent.DramaFinish,
    }
    self.StateConfig.BubbleDict = {
        [EEcologyBubbleType.Around] = {
            Name = "301901",
            TriggerDistance = 6,
            TriggerCD = 2,
            LoopTime = 6,
        },
    }
end
---@overload
---状态进入时
---@param lastStateEnum number 上个状态
function XAlphaHolographicState:OnStateEnter(lastStateEnum)
    self.InteractTriggerCount = 1
    BaseState.OnStateEnter(self, lastStateEnum)
end
function XAlphaHolographicState:UpdateOptionActive()
    local optionId = self.StateConfig.ShowOptionId
    if self.InteractTriggerCount == 2 then
        optionId = 2
    end
    if self.InteractTriggerCount >= 3 then
        optionId = 1
    end
    self._proxy:SetNpcInteractOneOptionActive(self._placeId, optionId)
end
function XAlphaHolographicState:OnNpcInteractStart(eventArgs)
    -- 被交互的不是自己不走逻辑
    if eventArgs.TargetId ~= self._uuid then
        return
    end
    self.InteractTriggerCount = self.InteractTriggerCount + 1
    self:UpdateOptionActive()
    self:PlayPerformLoopAnim()
end
--endregion


--region 阿尔法法奥斯生态AI
---@class XCharAlphaEcology : XEcologyConstructAIBase
---@field _stateMachine XStateMachineController 状态机
local XCharAlphaEcology = XDlcScriptManager.RegCharScript(10610801, "XCharAlphaEcology", Base)

--- 注册状态机状态
function XCharAlphaEcology:RegisterMachineState()
    self._stateMachine:AddState(StateEnum.Holographic, XAlphaHolographicState.New(self._proxy))
end

return XCharAlphaEcology
--endregion
