--[[
-- XUiLuckyTenant2PopupStageDetailGrid.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2025-12-31 16:39:51
--]]

---@class XUiLuckyTenant2PopupStageDetailGrid : XUiNode
---@field Parent XUiLuckyTenant2PopupStageDetail
local XUiLuckyTenant2PopupStageDetailGrid = XClass(XUiNode, "XUiLuckyTenant2PopupStageDetailGrid")


function XUiLuckyTenant2PopupStageDetailGrid:OnStart(...)
    if self.Button then
        XUiHelper.RegisterClickEvent(self, self.Button, self.OnClick, nil, true)
    end
    self:Update()
end

---@param data table 羁绊数据
function XUiLuckyTenant2PopupStageDetailGrid:Update(data)
    if not data then
        return
    end

    self._Data = data

    -- 更新羁绊图标（每次 Update 都设置，避免复用节点时图标丢失）
    if self.RImgIcon then
        self.RImgIcon:SetRawImage(data.Icon or "")
    end
    if data.IsDirty then
        data.IsDirty = false
    end
end

---点击羁绊
function XUiLuckyTenant2PopupStageDetailGrid:OnClick()
    if self._Data and self._Data.BondId then
        self.Parent:OpenBondDetail(self._Data.BondId)
    end
end

return XUiLuckyTenant2PopupStageDetailGrid
