--[[
-- XUiPBRTaskGridTask.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-02-04 12:30:16
--]]

local XDynamicGridTask = require("XUi/XUiTask/XDynamicGridTask")

---@class XUiPBRTaskGridTask : XDynamicGridTask
---@field _Control XPBRGameControl
---@field TxtStarNums UnityEngine.UI.Text
---@field RewardGrid UnityEngine.RectTransform
---@field RewardsContent UnityEngine.RectTransform
---@field BtnReceive XUiButton
---@field BtnReceiveHave UnityEngine.RectTransform
---@field BtnSkip XUiButton
---@field ImgAlreadyReceived UnityEngine.UI.Image
---@field TaskProgress UnityEngine.UI.Image
---@field TxtTaskName UnityEngine.UI.Text
---@field TxtTaskDescribe UnityEngine.UI.Text
---@field ImgCannotReceive UnityEngine.UI.Image
---@field GridCommon XUiPBRTaskGridCommon
local XUiPBRTaskGridTask = XClass(XDynamicGridTask, "XUiPBRTaskGridTask")


return XUiPBRTaskGridTask
