--- 玩法内部的事件Id，单独封装方便管理
local Theatre5EventIds = {
    
    --- 游戏模式（PVP/PVE）发生变更
    EVENT_THEATRE5_GAME_MODE_CHANGED = 'EVENT_THEATRE5_GAME_MODE_CHANGED', 
    
    --region 角色选择
    
    --- 角色涂装变更
    EVENT_THEATRE5_CHARACTER_FASHION_CHANGED = 'EVENT_THEATRE5_CHARACTER_FASHION_CHANGED',
    
    --endregion
    
    --region 商店
    
    --- 将一个物品UI设置到拖拽节点上
    EVENT_THEATRE5_SET_ITEM_TO_DRAGGINGROOT = 'EVENT_THEATRE5_SET_ITEM_TO_DRAGGINGROOT',
    
    --- 刷新背包显示
    EVENT_THEATRE5_REFRESH_BAG_SHOW = 'EVENT_THEATRE5_REFRESH_BAG_SHOW',
    
    --- 刷新商店显示
    EVENT_THEATRE5_REFRESH_STORE_SHOW = 'EVENT_THEATRE5_REFRESH_STORE_SHOW',
    
    --- 刷新技能栏显示
    EVENT_THEATRE5_REFRESH_SKILL_SHOW = 'EVENT_THEATRE5_REFRESH_SKILL_SHOW',
    
    --- 刷新装备栏显示
    EVENT_THEATRE5_REFRESH_EQUIP_SHOW = 'EVENT_THEATRE5_REFRESH_EQUIP_SHOW',
    
    --- 刷新金币显示
    EVENT_THEATRE5_REFRESH_GOLD_SHOW = 'EVENT_THEATRE5_REFRESH_GOLD_SHOW',
    
    --- 设置商店全遮罩（拖拽售出区域）显示状态
    EVENT_THEATRE5_FULLSHOPAREA_SHOW_STATE = 'EVENT_THEATRE5_FULLSHOPAREA_SHOW_STATE',
    
    --- 进入拖拽售出区域
    EVENT_THEATRE5_ENTER_FULLSHOPAREA = 'EVENT_THEATRE5_ENTER_FULLSHOPAREA',
    
    --- 退出拖拽售出区域
    EVENT_THEATRE5_EXIT_FULLSHOPAREA = 'EVENT_THEATRE5_EXIT_FULLSHOPAREA',
    
    --- 请求打开物品详情页
    EVENT_THEATRE5_OPEN_ITEM_DETAIL = 'EVENT_THEATRE5_OPEN_ITEM_DETAIL',
    
    --- 隐藏物品详情页
    EVENT_THEATRE5_HIDE_ITEM_DETAIL = 'EVENT_THEATRE5_HIDE_ITEM_DETAIL',
    
    --- 刷新物品详情页
    EVENT_THEATRE5_REFRESH_ITEM_DETAIL = 'EVENT_THEATRE5_REFRESH_ITEM_DETAIL',
    
    --- 商店状态变换：技能三选一 切换 常规商店
    EVENT_THEATRE5_SHOP_STATE_CHANGED = 'EVENT_THEATRE5_SHOP_STATE_CHANGED',
    
    --- 完成技能三选一
    EVENT_THEATRE5_SKILL_CHOICE_END = 'EVENT_THEATRE5_SKILL_CHOICE_END',

    --- 商店购买
    EVENT_THEATRE5_SHOP_BUY = "EVENT_THEATRE5_SHOP_BUY",

    --- 商店出售
    EVENT_THEATRE5_SHOP_SELL = "EVENT_THEATRE5_SHOP_SELL",
    
    --- 宝珠出售特效
    EVENT_THEATRE5_GEM_SELLOUT_EFFECT_SHOW = 'EVENT_THEATRE5_GEM_SELLOUT_EFFECT_SHOW',
    
    --- 取消容器的聚焦 用于切屏触发应用进入后台时
    EVENT_THEATRE5_CANCEL_CONTAINERS_FOCUS = 'EVENT_THEATRE5_CANCEL_CONTAINERS_FOCUS',
    
    --- 播放技能放置音效
    EVENT_THEATRE5_ITEM_SKILL_PLACED = 'EVENT_THEATRE5_ITEM_SKILL_PLACED',

    --- 播放宝珠放置音效
    EVENT_THEATRE5_ITEM_GEM_PLACED = 'EVENT_THEATRE5_ITEM_GEM_PLACED',
    
    --- 播放冻结/解冻音效，参数1表示是否冻结
    EVENT_THEATRE5_PLAY_GOODS_FREEZE_SFX = 'EVENT_THEATRE5_PLAY_GOODS_FREEZE_SFX',
    
    --- 检查和修复拖拽物品的状态
    EVENT_THEATRE5_CHECK_AND_FIX_DRAGGING_STATE = 'EVENT_THEATRE5_CHECK_AND_FIX_DRAGGING_STATE',
    --endregion

    --region PVE
    --- 事件更新
    EVENT_PVE_UPDATE_EVENT = "EVENT_PVE_UPDATE_EVENT",

    --故事线进度更新
    EVENT_STORY_LINE_PROCESS_UPDATE = "EVENT_STORY_LINE_PROCESS_UPDATE",

    --战斗章节节点推进
    EVENT_CHAPTER_BATTLE_PROMOTE = "EVENT_CHAPTER_BATTLE_PROMOTE",

    --宝箱选择
    EVENT_PVE_ITEM_BOX_SELECT = "EVENT_PVE_ITEM_BOX_SELECT",

    --事件选择
    EVENT_PVE_EVENT_SELECT = "EVENT_PVE_EVENT_SELECT",

    --选择推演问题答案
    EVENT_SELECT_DEDUCE_ANSWER = "EVENT_SELECT_DEDUCE_ANSWER",

    --点击场景物体
    EVENT_CLICK_SCENE_OBJECT = "EVENT_CLICK_SCENE_OBJECT",

    --点击角色头像
    EVENT_CLICK_CHARACTER_HEAD = "EVENT_CLICK_CHARACTER_HEAD",

    --打开或关闭对话
    EVENT_PVE_OPEN_OR_CLOSE_CHAT = "EVENT_PVE_OPEN_OR_CLOSE_CHAT",

    --点击线索板页签
    EVENT_CLICK_CLUE_BOARD_TAG = "EVENT_CLICK_CLUE_BOARD_TAG",

    --线索板显示切换
    EVENT_CLUE_BOARD_SWITCH = "EVENT_CLUE_BOARD_SWITCH",

    --点击简略版线索
    EVENT_CLICK_SIMPLE_CLUE = "EVENT_CLICK_SIMPLE_CLUE",
    --endregion

    --region 战斗
    -- 成功进入战斗
    EVENT_THEATRE5_FIGHT_ENTER_FINISHED = 'EVENT_THEATRE5_FIGHT_ENTER_FINISHED',
    
    --战斗结果退出
    EVENT_BATTLE_RESULT_EXIT = "EVENT_BATTLE_RESULT_EXIT",

    --全部战斗结算退出
    EVENT_WHOLE_BATTLE_EXIT = "EVENT_WHOLE_BATTLE_EXIT",

    --战斗重头再来一次
    EVENT_WHOLE_BATTLE_AGAIN = "EVENT_WHOLE_BATTLE_AGAIN",

    --- 战斗结算
    EVENT_COMMON_BATTLE_SETTLE = "EVENT_COMMON_BATTLE_SETTLE",
    --endregion

    --region 引导
    --返回主界面
    EVENT_GUIDE_THEATRE5_RETURN_MAIN = "EVENT_GUIDE_THEATRE5_RETURN_MAIN",
    --endregion
}

return Theatre5EventIds