--[[
-- XUiPBRPopupEndless.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-01-12 15:29:47
--]]

---@field _Control XPBRGameControl
---@class XUiPBRPopupEndless : XLuaUi
local XUiPBRPopupEndless = XLuaUiManager.Register(XLuaUi, "UiPBRPopupEndless")

function XUiPBRPopupEndless:OnAwake()
    self:InitComponents()
end

function XUiPBRPopupEndless:InitComponents()
    -- Button
    self.BtnEndless:AddEventListener(function() self:OnBtnEndlessClick() end)
    self.BtnSettle:AddEventListener(function() self:OnBtnSettleClick() end)

end

---@param result XFightResult
function XUiPBRPopupEndless:OnStart(result)
    self.Result = result
    self:Update()
end

function XUiPBRPopupEndless:OnEnable()
end

function XUiPBRPopupEndless:OnDisable()
end

function XUiPBRPopupEndless:OnDestroy()
end

function XUiPBRPopupEndless:Update()
    self.BtnEndless:SetButtonState(CS.UiButtonState.Normal)
    self.BtnSettle:SetButtonState(CS.UiButtonState.Normal)
end

function XUiPBRPopupEndless:OnBtnEndlessClick()
    -- 先改为波次结算，然后走正常流程重新进入战斗
    self.Result.Data.IsFightSegmentSettle = true
    self:Close()
    XMVCA.XFuben:SettleFight(self.Result)
end

function XUiPBRPopupEndless:OnBtnSettleClick()
    -- 正常结算
    self:Close()
    XMVCA.XFuben:SettleFight(self.Result)
end

return XUiPBRPopupEndless
