--[[
-- XUiPBRGeniusGridGenuisBig.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-02-03 09:35:52
--]]

--[[
-- XUiPBRGeniusGridGenuisBig.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-02-03 09:35:52
--]]

local XUiPBRGeniusGridBase = require('XUi/XUiPBRGame/XUiPBRGenius/NodeList/XUiPBRGeniusGridBase')

---@class XUiPBRGeniusGridGenuisBig : XUiPBRGeniusGridBase
local XUiPBRGeniusGridGenuisBig = XClass(XUiPBRGeniusGridBase, "XUiPBRGeniusGridGenuisBig")

return XUiPBRGeniusGridGenuisBig
