--[[
-- XUiLineArithmetic3Game.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-02-03 19:58:14
--]]

local XUiLineArithmetic3GameGridTarget = require("XUi/XUiLineArithmetic3/XUiLineArithmetic3Game/XUiLineArithmetic3GameGridTarget")
local XUiLineArithmetic3GameGridDetail = require("XUi/XUiLineArithmetic3/XUiLineArithmetic3Game/XUiLineArithmetic3GameGridDetail")
local XLineArithmetic3Enum = require("XModule/XLineArithmetic3/XLineArithmetic3Enum")
local XUiLineArithmetic3GridItem = require("XUi/XUiLineArithmetic3/XUiLineArithmetic3Game/Grids/XUiLineArithmetic3GridItem")

---@class XUiLineArithmetic3Game : XLuaUi
---@field _Control XLineArithmetic3Control
---@field BtnBack XUiButton
---@field BtnMainUi XUiButton
---@field PanelTarget UnityEngine.RectTransform
---@field PanelPropDetail UnityEngine.RectTransform
---@field GridTarget UnityEngine.RectTransform
---@field BtnHelp UnityEngine.UI.Button
---@field BtnTips UnityEngine.UI.Button 指引按钮，点击后在棋盘上显示通关路线
---@field PanelTips UnityEngine.RectTransform 指引层，用于放置 GridTips
---@field GridTips UnityEngine.GameObject 指引格子预制体（模板，含 X、Y 时放在对应格子位置）
---@field Title UnityEngine.UI.Text
---@field SpecialGrid UnityEngine.RectTransform
---@field XAudioObjectPlayer UnityEngine.RectTransform
---@field GridTarget01 XUiLineArithmetic3GameGridTarget
---@field GridDetail XUiLineArithmetic3GameGridDetail
---@field PanelBoard UnityEngine.RectTransform 格子元素的父节点
---@field PanelEmpty UnityEngine.RectTransform 包含GridLayoutGroup的节点
---@field GridPath UnityEngine.GameObject 路径预制体
---@field GridObstacle UnityEngine.GameObject 障碍预制体
---@field GridStart UnityEngine.GameObject 起点预制体
---@field GridCharacter01 UnityEngine.GameObject 角色预制体1
---@field GridCharacter02 UnityEngine.GameObject 角色预制体2
---@field GridCharacter03 UnityEngine.GameObject 角色预制体3
---@field GridCharacter04 UnityEngine.GameObject 角色预制体4
---@field GridCharacter05 UnityEngine.GameObject 角色预制体5
---@field GridCarriage UnityEngine.GameObject 车厢预制体
---@field PanelTouch XGoInputHandler 输入处理组件
---@field _Game XLineArithmetic3Game 游戏逻辑对象
---@field _GridElements table<string, UnityEngine.GameObject> 格子元素缓存 {key = GameObject}
---@field _CurrentPath table[] 当前绘制的路径
---@field _HeadGrid XUiLineArithmetic3GridItem 车头GameObject
---@field _CarriageGos UnityEngine.GameObject[] 车厢GameObject列表
---@field _DirectionIndicators table<number, UnityEngine.RectTransform> 方向指示器缓存，key 为 Direction 枚举值
local XUiLineArithmetic3Game = XLuaUiManager.Register(XLuaUi, "UiLineArithmetic3Game")

function XUiLineArithmetic3Game:Ctor()
    ---@type XUiLineArithmetic3GameGridTarget[]
    self._StarGrids = {}

    ---@type XUiLineArithmetic3GameGridDetail[]
    self._GridDesc = {}

    ---@type UnityEngine.GameObject[] 当前显示的指引格子列表
    self._TipGrids = {}

    local Emoj = XLineArithmetic3Enum.Emoj

    self._EmojiMap = {
        [Emoj.Initial] = "Initial",
        [Emoj.ReadyToBoard] = "ReadyToBoard",
        [Emoj.AfterBoard] = "AfterBoard",
        [Emoj.ToColor1End] = "ToColor1End",
        [Emoj.ToColor2End] = "ToColor2End",
        [Emoj.ToColor3End] = "ToColor3End",
        [Emoj.ToColor4End] = "ToColor4End",
        [Emoj.ToColor5End] = "ToColor5End",
        [Emoj.ToColor6End] = "ToColor6End",
        [Emoj.ToFinalEnd] = "ToFinalEnd",
    }


    local PathDirection = XLineArithmetic3Enum.PathDirection

    self._PathDirectionType = {
        StraightLine = 1,
        Curve = 2
    }
    -- 方向类型到UI节点名的映射
    self._PathDirection2Type = {
        [PathDirection.LeftToRight] = self._PathDirectionType.StraightLine,
        [PathDirection.RightToLeft] = self._PathDirectionType.StraightLine,
        [PathDirection.UpToDown] = self._PathDirectionType.StraightLine,
        [PathDirection.DownToUp] = self._PathDirectionType.StraightLine,
        [PathDirection.TurnFromUpToLeft] = self._PathDirectionType.Curve,
        [PathDirection.TurnFromUpToRight] = self._PathDirectionType.Curve,
        [PathDirection.TurnFromDownToLeft] = self._PathDirectionType.Curve,
        [PathDirection.TurnFromDownToRight] = self._PathDirectionType.Curve,
        [PathDirection.TurnFromLeftToUp] = self._PathDirectionType.Curve,
        [PathDirection.TurnFromLeftToDown] = self._PathDirectionType.Curve,
        [PathDirection.TurnFromRightToUp] = self._PathDirectionType.Curve,
        [PathDirection.TurnFromRightToDown] = self._PathDirectionType.Curve,
    }
    -- 方向配置表：{ rotation, xScale }
    self._PathDirectionConfig = {
        -- 直线类型
        [PathDirection.LeftToRight] = { 0, 1 },
        [PathDirection.RightToLeft] = { 180, 1 },
        [PathDirection.UpToDown] = { 270, 1 },
        [PathDirection.DownToUp] = { 90, 1 },
        -- 转弯类型
        [PathDirection.TurnFromLeftToUp] = { 0, 1 },
        [PathDirection.TurnFromRightToUp] = { 0, -1 },
        [PathDirection.TurnFromLeftToDown] = { 180, -1 },
        [PathDirection.TurnFromRightToDown] = { 180, 1 },
        [PathDirection.TurnFromUpToLeft] = { 90, -1 },
        [PathDirection.TurnFromDownToLeft] = { 90, 1 },
        [PathDirection.TurnFromUpToRight] = { 270, 1 },
        [PathDirection.TurnFromDownToRight] = { 270, -1 },
    }
end

function XUiLineArithmetic3Game:OnAwake()
    self:InitComponents()
    self:InitGame()
end

function XUiLineArithmetic3Game:InitComponents()
    -- Back Mainui Help
    self:BindExitBtns()
    self:BindHelpBtn(self.BtnHelp, "UiLineArithmetic3GameHelpKey")

    -- BtnTips、PanelTips、GridTips
    if self.BtnTips then
        self.BtnTips.onClick:AddListener(function() self:OnClickBtnTips() end)
    end
    if self.PanelTips then
        self.PanelTips.gameObject:SetActiveEx(false)
    end
    if self.GridTips then
        self.GridTips.gameObject:SetActiveEx(false)
    end

    self.PanelAllGrid.gameObject:SetActiveEx(false)

    -- 注册输入事件监听器
    self.PanelTouch = self.PanelTouch or XUiHelper.TryGetComponent(self.Transform, "SafeAreaContentPane/PanelRight/PanelCheckerboard/PanelTouch", "XGoInputHandler")
    ---@type XGoInputHandler
    local goInputHandler = self.PanelTouch
    goInputHandler:AddPointerDownListener(function(eventData)
        self:OnBeginDrag(eventData)
    end)
    goInputHandler:AddDragListener(function(eventData)
        self:OnDrag(eventData)
    end)
    goInputHandler:AddPointerUpListener(function(eventData)
        self:OnEndDrag(eventData)
    end)

    if self.GridTarget then
        self.GridTarget.gameObject:SetActiveEx(false)
    end
    -- 星1：GridTarget01 固定，直接初始化
    self.GridTarget01 = self.GridTarget01 or XUiHelper.TryGetComponent(self.Transform, "SafeAreaContentPane/PanelLeft/PanelChapterDetail/ListTarget/GridTarget01", "RectTransform")
    if self.GridTarget01 then
        self._StarGrid01 = XUiLineArithmetic3GameGridTarget.New(self.GridTarget01, self)
        self.GridTarget01.gameObject:SetActiveEx(false)
    end
    -- 星2、3：GridTarget02 作为模板，动态实例化
    self.GridTarget02 = self.GridTarget02 or XUiHelper.TryGetComponent(self.Transform, "SafeAreaContentPane/PanelLeft/PanelChapterDetail/ListTarget/GridTarget02", "RectTransform")
    self.GridTarget02.gameObject:SetActiveEx(false)

    if self.SpecialGrid then
        self.SpecialGrid.gameObject:SetActiveEx(false)
    end
end

function XUiLineArithmetic3Game:OnStart(stageId)
    self._StageId = stageId

    -- 初始化游戏逻辑
    self._Control:InitGame(stageId)

    -- 创建命令管理器（需要在 game 初始化之后）
    local XLineArithmetic3CommandManager = require("XModule/XLineArithmetic3/XLineArithmetic3CommandManager")
    ---@type XLineArithmetic3CommandManager
    self._CommandManager = XLineArithmetic3CommandManager.New(self, self._Control:GetGame())

    -- 初始化游戏对象（地图、车头、车厢）
    self:InitializeGameObjects(stageId)

    -- 更新星星目标和事件描述
    self:UpdateStarTarget()
    self:UpdateGridDesc()
    self:UpdateTitle()

    -- 刷新方向指示器
    self:RefreshDirectionIndicators()
end

function XUiLineArithmetic3Game:OnEnable()
    -- 监听游戏更新事件（重新挑战、下一关）
    XEventManager.AddEventListener(XEventId.EVENT_LINE_ARITHMETIC_UPDATE_GAME, self.OnGameUpdate, self)
end

function XUiLineArithmetic3Game:OnDisable()
    -- 移除事件监听
    XEventManager.RemoveEventListener(XEventId.EVENT_LINE_ARITHMETIC_UPDATE_GAME, self.OnGameUpdate, self)
end

--- 游戏更新事件处理（重新挑战、下一关）
function XUiLineArithmetic3Game:OnGameUpdate()
    -- 获取当前关卡ID（从Control获取，因为可能是下一关）
    local stageId = self._Control._StageId
    if not stageId or stageId == 0 then
        XLog.Warning("[XUiLineArithmetic3Game] 游戏更新失败，关卡ID无效")
        return
    end

    -- 重置UI状态
    self:ResetGameUI()

    -- 重新初始化游戏对象
    self._StageId = stageId
    self:InitializeGameObjects(stageId)

    -- 重新创建命令管理器
    local XLineArithmetic3CommandManager = require("XModule/XLineArithmetic3/XLineArithmetic3CommandManager")
    self._CommandManager = XLineArithmetic3CommandManager.New(self, self._Control:GetGame())

    -- 更新星星目标和事件描述
    self:UpdateStarTarget()
    self:UpdateGridDesc()
    self:UpdateTitle()

    -- 刷新已走过路径显示
    self:RefreshTraveledPathDisplay()

    -- 刷新指引为当前（新）关卡的配置
    self:RefreshTipGridsToCurrentStage()

    -- 刷新角色状态和方向指示器
    self:RefreshCharacterStates()
    self:RefreshDirectionIndicators()
end

--- 重置游戏UI状态（清理旧的GameObject）
function XUiLineArithmetic3Game:ResetGameUI()
    -- 停止所有动画
    self:StopAllTweens()

    -- 进入下一关/重新挑战时，关闭并重置提示（避免提示残留到新关卡）
    if self.PanelTips then
        self.PanelTips.gameObject:SetActiveEx(false)
    end
    if self.BtnTips then
        self.BtnTips:SetButtonState(CS.UiButtonState.Normal)
    end
    self:ClearTipGrids()

    -- 销毁旧的命令管理器
    if self._CommandManager then
        self._CommandManager:Destroy()
        self._CommandManager = nil
    end

    -- 清理乘客UID系统
    if self._PassengersByUid then
        for uid, gridItem in pairs(self._PassengersByUid) do
            if gridItem and gridItem.GameObject then
                CS.UnityEngine.GameObject.Destroy(gridItem.GameObject)
            end
        end
    end
    self._PassengersByUid = {}
    self._PassengerUidByPos = {}
    self._PassengerUidByCarriage = {}
    self._PassengerUidCounter = 0

    -- 清理通用GameObject UID系统
    if self._GameObjectsByUid then
        for uid, go in pairs(self._GameObjectsByUid) do
            if go then
                CS.UnityEngine.GameObject.Destroy(go.gameObject)
            end
        end
    end
    self._GameObjectsByUid = {}
    self._GameObjectUidCounter = 0

    -- 清理格子元素缓存
    if self._GridElements then
        for key, gridItem in pairs(self._GridElements) do
            if gridItem and gridItem.GameObject then
                CS.UnityEngine.GameObject.Destroy(gridItem.GameObject)
            end
        end
    end
    self._GridElements = {}

    -- 清理车头
    if self._HeadGrid then
        CS.UnityEngine.GameObject.Destroy(self._HeadGrid.GameObject)
        self._HeadGrid = nil
    end

    -- 清理车厢
    if self._CarriageGos then
        for _, carriageGo in ipairs(self._CarriageGos) do
            if carriageGo then
                CS.UnityEngine.GameObject.Destroy(carriageGo.gameObject)
            end
        end
    end
    self._CarriageGos = {}

    -- 清理路径显示（放回对象池）
    if self._PathGrids then
        for _, pathGrid in ipairs(self._PathGrids) do
            if pathGrid then
                self:ReturnPathGridToPool(pathGrid)
            end
        end
    end
    self._PathGrids = {}

    -- 清理玩家绘制路径显示
    self:ClearSelectedPathDisplay()

    -- 重置活动tween列表
    self._ActiveTweens = {}
end

function XUiLineArithmetic3Game:OnDestroy()
    -- 销毁命令管理器，清理所有 Command 持有的 UI 引用
    if self._CommandManager then
        self._CommandManager:Destroy()
        self._CommandManager = nil
    end

    -- 清理乘客UID系统
    if self._PassengersByUid then
        for uid, gridItem in pairs(self._PassengersByUid) do
            if gridItem and gridItem.GameObject then
                CS.UnityEngine.GameObject.Destroy(gridItem.GameObject)
            end
        end
        self._PassengersByUid = nil
    end
    self._PassengerUidByPos = nil

    -- 清理通用GameObject UID系统
    if self._GameObjectsByUid then
        for uid, go in pairs(self._GameObjectsByUid) do
            if go then
                CS.UnityEngine.GameObject.Destroy(go)
            end
        end
        self._GameObjectsByUid = nil
    end

    -- 销毁路径格子对象池
    self:DestroyPathGridPool()
end

function XUiLineArithmetic3Game:UpdateTitle()
    local stageConfig = self._Control:GetStageConfig(self._StageId)
    self.Title.text = (stageConfig and stageConfig.Name) or ""
end

--- 初始化UI数据
function XUiLineArithmetic3Game:InitGame()
    -- 初始化格子元素缓存
    self._GridElements = {}

    -- 初始化车厢列表
    self._CarriageGos = {}

    -- 初始化路径显示列表（车走过的路）
    self._PathGrids = {}

    -- 路径格子对象池
    ---@type XPool
    self._PathGridPool = XPool.New(function()
        if self.GridPath then
            local pathGo = self:InstantiateGrid(self.GridPath, self.PanelPath)
            if pathGo then
                return XUiLineArithmetic3GridItem.New(pathGo, self)
            end
        end
    end, function(grid)
        grid.GameObject:SetActiveEx(false)
    end, false)

    -- 初始化玩家绘制路径显示列表
    self._SelectedPathGrids = {}

    -- 指引路线格子列表（BtnTips 显示时使用）
    self._TipGrids = {}

    -- 乘客UID管理系统
    self._PassengerUidCounter = 0
    self._PassengersByUid = {}        -- { uid = GameObject }
    self._PassengerUidByCarriage = {} -- { carriageIndex = uid } 车厢索引到乘客UID的映射

    -- 通用GameObject UID管理系统（用于动态创建的临时对象，如颜色节点）
    self._GameObjectUidCounter = 0
    self._GameObjectsByUid = {} -- { uid = GameObject }

    -- 缓存 GridLayoutGroup 的 CellSize
    local gridLayout = self.PanelEmpty:GetComponent(typeof(CS.UnityEngine.UI.GridLayoutGroup))
    if gridLayout then
        self._CellSize = gridLayout.cellSize
    end

    -- 活动的 tween 列表
    self._ActiveTweens = {}

    -- 方向指示器缓存（四个方向节点引用，使用 Direction 枚举）
    self._DirectionIndicators = {
        [XLineArithmetic3Enum.Direction.Up] = nil,
        [XLineArithmetic3Enum.Direction.Left] = nil,
        [XLineArithmetic3Enum.Direction.Down] = nil,
        [XLineArithmetic3Enum.Direction.Right] = nil,
    }
end

--- 注册乘客GameObject，返回唯一UID
---@param grid XUiLineArithmetic3GridItem 乘客GameObject
---@return number 唯一UID
function XUiLineArithmetic3Game:RegisterPassenger(grid)
    self._PassengerUidCounter = self._PassengerUidCounter + 1
    local uid = self._PassengerUidCounter
    self._PassengersByUid[uid] = grid
    return uid
end

--- 通过UID获取乘客GameObject
---@param uid number 乘客UID
---@return UnityEngine.GameObject|nil
function XUiLineArithmetic3Game:GetPassengerByUid(uid)
    return self._PassengersByUid[uid]
end

--- 注销乘客，移除并返回GameObject
---@param uid number 乘客UID
---@return UnityEngine.GameObject|nil
function XUiLineArithmetic3Game:UnregisterPassenger(uid)
    local go = self._PassengersByUid[uid]
    self._PassengersByUid[uid] = nil
    return go
end

--- 设置车厢索引到乘客UID的映射
---@param carriageIndex number 车厢索引
---@param uid number|nil 乘客UID，nil表示清除映射
function XUiLineArithmetic3Game:SetPassengerUidByCarriage(carriageIndex, uid)
    self._PassengerUidByCarriage[carriageIndex] = uid
end

--- 获取车厢索引对应的乘客UID
---@param carriageIndex number 车厢索引
---@return number|nil 乘客UID
function XUiLineArithmetic3Game:GetPassengerUidByCarriage(carriageIndex)
    return self._PassengerUidByCarriage[carriageIndex]
end

--- 获取车厢GameObject
---@param index number 车厢索引
---@return UnityEngine.GameObject|nil
function XUiLineArithmetic3Game:GetCarriageGo(index)
    return self._CarriageGos[index]
end

--- 获取车厢数量
---@return number
function XUiLineArithmetic3Game:GetCarriageCount()
    return #self._CarriageGos
end

--- 获取车头GameObject
---@return UnityEngine.GameObject|nil
function XUiLineArithmetic3Game:GetHeadGo()
    return self._HeadGrid.GameObject
end

--- 获取车头GameObject
---@return UnityEngine.GameObject|nil
function XUiLineArithmetic3Game:GetHeadGrid()
    return self._HeadGrid
end

--- 获取格子元素
---@param key string 格子key
---@return UnityEngine.GameObject|nil
function XUiLineArithmetic3Game:GetGridElement(key)
    return self._GridElements[key]
end

--- 获取颜色预制体
---@param color number 颜色值
---@return UnityEngine.GameObject|nil
function XUiLineArithmetic3Game:GetColorPrefab(color)
    local prefabName = string.format("GridColor%02d", color)
    return self[prefabName]
end

--- 注册GameObject，返回唯一UID
---@param go UnityEngine.GameObject
---@return number 唯一UID
function XUiLineArithmetic3Game:RegisterGameObject(go)
    self._GameObjectUidCounter = self._GameObjectUidCounter + 1
    local uid = self._GameObjectUidCounter
    self._GameObjectsByUid[uid] = go
    return uid
end

--- 通过UID获取GameObject
---@param uid number UID
---@return UnityEngine.GameObject|nil
function XUiLineArithmetic3Game:GetGameObjectByUid(uid)
    return self._GameObjectsByUid[uid]
end

--- 注销并销毁GameObject
---@param uid number UID
function XUiLineArithmetic3Game:DestroyGameObjectByUid(uid)
    local go = self._GameObjectsByUid[uid]
    if go then
        CS.UnityEngine.GameObject.Destroy(go.gameObject)
    end
    self._GameObjectsByUid[uid] = nil
end

--- 通过坐标获取乘客UID
---@param x number 格子X坐标
---@param y number 格子Y坐标
---@return number|nil 乘客UID
function XUiLineArithmetic3Game:GetPassengerUidByPos(x, y)
    if not self._PassengerUidByPos then return nil end
    local posKey = x .. "_" .. y
    return self._PassengerUidByPos[posKey]
end

--- 设置坐标到乘客UID的映射
---@param x number 格子X坐标
---@param y number 格子Y坐标
---@param uid number|nil 乘客UID，nil表示清除映射
function XUiLineArithmetic3Game:SetPassengerUidByPos(x, y, uid)
    self._PassengerUidByPos = self._PassengerUidByPos or {}
    local posKey = x .. "_" .. y
    self._PassengerUidByPos[posKey] = uid
end

--- 统一实例化 Grid 对象，并设置 CellSize
---@param prefab UnityEngine.GameObject 预制体
---@param parent UnityEngine.Transform 父节点
---@return UnityEngine.GameObject
function XUiLineArithmetic3Game:InstantiateGrid(prefab, parent)
    local go = XUiHelper.Instantiate(prefab, parent)
    if go and self._CellSize then
        local rectTransform = go:GetComponent(typeof(CS.UnityEngine.RectTransform))
        if rectTransform then
            rectTransform.sizeDelta = self._CellSize
        end
    end
    return go
end

--- 保存当前 UI 状态快照
function XUiLineArithmetic3Game:SaveUIState()
    local state = {
        HeadPos = self._HeadGrid and self._HeadGrid.Transform.position or nil,
        CarriagePositions = {},
    }
    for i, carriageGo in ipairs(self._CarriageGos) do
        if carriageGo then
            state.CarriagePositions[i] = carriageGo.transform.position
        end
    end
    self._UIStateHistory[#self._UIStateHistory + 1] = state
end

--- 停止所有活动的 tween
function XUiLineArithmetic3Game:StopAllTweens()
    for _, tween in ipairs(self._ActiveTweens) do
        XScheduleManager.UnSchedule(tween)
    end
    self._ActiveTweens = {}
end

--- 创建可追踪的 tween（用于倒放时停止）
---@param duration number 动画时长
---@param onUpdate function 更新回调
---@param onComplete function 完成回调
function XUiLineArithmetic3Game:CreateTween(duration, onUpdate, onComplete)
    local tween
    tween = XUiHelper.Tween(duration, onUpdate, function()
        for index, tweenToRemove in ipairs(self._ActiveTweens) do
            if tweenToRemove == tween then
                table.remove(self._ActiveTweens, index)
                break
            end
        end
        onComplete()
    end)
    if tween then
        self._ActiveTweens[#self._ActiveTweens + 1] = tween
    end
    return tween
end

--- 初始化游戏对象（车头和车厢）
---@param stageId number 关卡ID
function XUiLineArithmetic3Game:InitializeGameObjects(stageId)
    -- 渲染地图格子
    self:RenderMapGrids(stageId)

    -- 获取关卡配置
    local stageConfig = self._Control:GetStageConfig(stageId)
    if not stageConfig then
        XLog.Error("[XUiLineArithmetic3Game] 未找到关卡配置，stageId:", stageId)
        return
    end

    -- 获取车辆配置
    local carConfig = self._Control:GetCarConfig(stageConfig.MapId)
    if not carConfig or not carConfig.Carriages or #carConfig.Carriages == 0 then
        XLog.Error("[XUiLineArithmetic3Game] 未找到车辆配置或车厢为空，mapId:", stageConfig.MapId)
        return
    end

    -- 车头是车厢的第一个参数(cellId)
    local headCharacterId = carConfig.Carriages[1]
    if not headCharacterId then
        XLog.Error("[XUiLineArithmetic3Game] 车厢配置第一个参数为空，mapId:", stageConfig.MapId)
        return
    end

    local headCellConfig = self._Control:GetCellConfigByCharacterId(headCharacterId)
    if not headCellConfig or not headCellConfig.GridName then
        XLog.Error("[XUiLineArithmetic3Game] 未找到车头格子配置，cellId:", headCharacterId)
        return
    end
    local headGridName = headCellConfig.GridName

    -- 获取起点信息
    local startInfo = self._Control:GetStartInfo(stageId)
    if not startInfo then
        XLog.Error("[XUiLineArithmetic3Game] 未找到起点格，stageId:", stageId)
        return
    end

    -- 获取起点的世界坐标
    local startPos = self:GetGridWorldPosition(startInfo.x, startInfo.y)

    -- 创建车厢
    self:CreateCarriages(startPos)

    -- 由于ui排序问题, 需要先创建车厢, 再创建车头, 否则车厢会盖在车头上面
    -- 根据角色id创建车头
    self:CreateHead(headGridName, startPos)

    -- 创建车厢上的初始乘客
    self:CreateCarriagePassengers(startPos)
end

--- 根据GridName创建车头
---@param gridName string 格子名称（如"GridCharacter03"）
---@param position UnityEngine.Vector3 世界坐标
function XUiLineArithmetic3Game:CreateHead(gridName, position)
    -- 根据GridName动态获取预制体
    local prefab = self[gridName]
    if not prefab then
        XLog.Error("[XUiLineArithmetic3Game] 未找到车头预制体:", gridName)
        return
    end

    -- 实例化车头GameObject
    local headGo = self:InstantiateGrid(prefab, self.PanelCharacter)
    headGo.transform:SetPosition(position.x, position.y, position.z)
    self._HeadGrid = XUiLineArithmetic3GridItem.New(headGo, self)
    
    self:InitDirectionIndicators()
end

--- 创建车厢
---@param position UnityEngine.Vector3 起点世界坐标
function XUiLineArithmetic3Game:CreateCarriages(position)
    local game = self._Control:GetGame()
    local carriages = game:GetCarriages()
    if not carriages or #carriages == 0 then return end

    for i = 1, #carriages do
        local carriageGo = self:InstantiateGrid(self.GridCarriage, self.PanelBoard)
        carriageGo.transform.position = position
        self._CarriageGos[i] = carriageGo
    end
end

--- 创建车厢上的初始乘客（从数据层读取 Passenger.Color 与 Passenger.GridName）
---@param position UnityEngine.Vector3 起点世界坐标
function XUiLineArithmetic3Game:CreateCarriagePassengers(position)
    local game = self._Control:GetGame()
    local carriages = game:GetCarriages()
    if not carriages then return end

    for i, carriage in ipairs(carriages) do
        if carriage.Passenger and carriage.Passenger.GridName then
            local carriageGo = self._CarriageGos[i]
            local gridName = carriage.Passenger.GridName
            local characterPrefab = self[gridName]
            if carriageGo and characterPrefab then
                local passengerGo = self:InstantiateGrid(characterPrefab, carriageGo.transform)
                passengerGo.transform:SetLocalPosition(0, 0, 0)

                local passengerGrid = XUiLineArithmetic3GridItem.New(passengerGo, self)
                
                -- 染色乘客（使用数据层颜色）
                if carriage.Passenger.Color then
                    self:UpdatePassengerColor(passengerGrid, carriage.Passenger.Color)
                end

                -- 注册到UID系统，并建立车厢到乘客的映射
                local uid = self:RegisterPassenger(passengerGrid)
                self:SetPassengerUidByCarriage(i, uid)
            end
        end
    end
end

--- 渲染地图格子
---@param stageId number 关卡ID
function XUiLineArithmetic3Game:RenderMapGrids(stageId)
    -- 获取地图配置数据
    local mapData = self._Control:GetMapByStageId(stageId)
    if not mapData or not next(mapData) then
        XLog.Error("[XUiLineArithmetic3Game] 地图数据为空，stageId:", stageId)
        return
    end

    -- 遍历地图的每一行
    for row, rowConfig in pairs(mapData) do
        local y = row
        -- 遍历该行的每一列
        for x, cellId in ipairs(rowConfig.Column) do
            if cellId > 0 then
                -- 获取格子配置
                local cellConfig = self._Control:GetCellConfig(cellId)
                if cellConfig then
                    -- 乘客格配置GridName是空的, 但是依然需要创建角色格
                    -- 如果是乘客格或车站且配置了角色，克隆角色格
                    self:TryCreateCharacterOnGrid(x, y, cellConfig)

                    -- 根据GridName创建格子UI（传递cellConfig用于生成正确的key）
                    if cellConfig.GridName then
                        local gridItem = self:CreateGridElement(x, y, cellConfig.GridName, cellConfig)

                        if not cellConfig.Color or cellConfig.Color == 0 then
                            -- 如果是车站格子，显示车站颜色
                            if gridItem and cellConfig.Type == XLineArithmetic3Enum.GridType.Station then
                                self:UpdateStationColor(x, y, gridItem)
                            end
                        end
                    end
                end
            end
        end
    end
end

--- 尝试在格子上创建角色（仅乘客格和车站支持）
---@param gridGo UnityEngine.GameObject 格子GameObject
---@param cellConfig table 格子配置
function XUiLineArithmetic3Game:TryCreateCharacterOnGrid(x, y, cellConfig)
    if not x or not y or not cellConfig then
        return
    end

    -- 只有乘客格和车站支持 CharacterId
    local GridType = XLineArithmetic3Enum.GridType
    if cellConfig.Type ~= GridType.Passenger and cellConfig.Type ~= GridType.Station then
        return
    end

    -- 检查是否配置了角色
    if not cellConfig.CharacterId or cellConfig.CharacterId <= 0 then
        return
    end

    -- 获取角色配置
    local characterConfig = self._Control:GetCellConfig(cellConfig.CharacterId)
    if not characterConfig or not characterConfig.GridName then
        return
    end

    -- 克隆角色格
    local characterPrefab = self[characterConfig.GridName]
    if characterPrefab then
        local characterGo = self:InstantiateGrid(characterPrefab, self.PanelCharacter)
        local worldPos = self:GetGridWorldPosition(x, y)
        characterGo.transform:SetPosition(worldPos.x, worldPos.y, worldPos.z)

        local characterGrid = XUiLineArithmetic3GridItem.New(characterGo, self)

        -- 更新车站颜色
        self:UpdateStationColor(x, y, characterGrid)

        -- 染色乘客
        self:UpdatePassengerColor(characterGrid, characterConfig.Color)

        
        -- 乘客格使用UID系统管理
        -- if cellConfig.Type == GridType.Passenger then
        local uid = self:RegisterPassenger(characterGrid)
        -- 存储坐标到UID的映射，供BoardCommand初始查找
        local posKey = x .. "_" .. y
        self._PassengerUidByPos = self._PassengerUidByPos or {}
        self._PassengerUidByPos[posKey] = uid

        -- 同时存储到 _GridElements，供上车/下车逻辑使用
        local passengerKey = "Passenger_" .. x .. "_" .. y
        self._GridElements[passengerKey] = characterGrid
        -- end
    end
end

--- 更新车站颜色显示
---@param x number 格子X坐标
---@param y number 格子Y坐标
---@param stationGo XUiLineArithmetic3GridItem 车站GameObject
---@param color number|nil 指定颜色，nil 则从 Game 层读取
function XUiLineArithmetic3Game:UpdateStationColor(x, y, stationGrid, color)
    local stationColor = color
    if stationColor == nil then
        -- 未指定颜色时从 Game 层获取
        local gameMap = self._Control:GetGameMap()
        if not gameMap or not gameMap[y] or not gameMap[y][x] then
            return
        end
        stationColor = gameMap[y][x].StationColor
    end

    -- 先清除旧的颜色节点
    local childCount = stationGrid.Transform.childCount
    for i = childCount - 1, 0, -1 do
        local child = stationGrid.Transform:GetChild(i)
        if child and child.name and string.find(child.name, "GridCharacterColor") then
            CS.UnityEngine.GameObject.Destroy(child.gameObject)
        end
    end

    -- 如果车站有颜色（不是白色），显示颜色节点
    if stationColor and stationColor ~= XLineArithmetic3Enum.Color.White then
        local colorPrefabName = string.format("GridCharacterColor%02d", stationColor)
        local colorPrefab = self[colorPrefabName]

        if colorPrefab then
            local colorRoot = stationGrid.ColorRoot and stationGrid.ColorRoot.transform or stationGrid.Transform
            local colorGo = XUiHelper.Instantiate(colorPrefab, colorRoot)
            colorGo.transform:SetLocalPosition(0, 0, 0)
            colorGo.transform:SetLocalScale(1, 1, 1)
            colorGo.transform:SetAsFirstSibling()
        end
    end
end

--- 批量刷新所有车站的颜色显示
function XUiLineArithmetic3Game:RefreshAllStationColors()
    -- 从Game层获取地图数据
    local gameMap = self._Control:GetGameMap()
    if not gameMap then
        return
    end

    -- 遍历所有格子
    for y, row in pairs(gameMap) do
        for x, gridData in pairs(row) do
            -- 只处理车站类型的格子
            if gridData.Type == XLineArithmetic3Enum.GridType.Station then
                -- 构造车站格子的key
                local key = string.format("%d_%d", x, y)
                local stationGo = self._GridElements[key]

                if stationGo then
                    self:UpdateStationColor(x, y, stationGo)
                end
            end
        end
    end
end

--- 刷新所有乘客颜色显示到 Game 层实际数据（保底刷新）
function XUiLineArithmetic3Game:RefreshAllPassengerColors()
    local gameMap = self._Control:GetGameMap()
    if not gameMap then
        return
    end

    local GridType = XLineArithmetic3Enum.GridType
    for y, row in pairs(gameMap) do
        for x, gridData in pairs(row) do
            if gridData.Passenger and (gridData.Type == GridType.Passenger or gridData.Type == GridType.Station) then
                local passengerUid = self:GetPassengerUidByPos(x, y)
                if passengerUid then
                    local passengerGo = self:GetPassengerByUid(passengerUid)
                    if passengerGo then
                        self:UpdatePassengerColor(passengerGo, gridData.Passenger.Color)
                    end
                end
            end
        end
    end
end

--- 保底刷新所有车站和乘客颜色到 Game 层实际数据
function XUiLineArithmetic3Game:RefreshAllColorsToGameData()
    self:RefreshAllStationColors()
    self:RefreshAllPassengerColors()
end

--- 创建格子UI元素
---@param x number 格子X坐标
---@param y number 格子Y坐标
---@param gridName string 格子名称（如"GridStart"）
---@param cellConfig table 格子配置（可选，用于判断格子类型）
function XUiLineArithmetic3Game:CreateGridElement(x, y, gridName, cellConfig)
    -- 根据格子类型生成不同的缓存key
    local key
    if cellConfig then
        if cellConfig.Type == XLineArithmetic3Enum.GridType.Passenger then
            -- 乘客格使用 "Passenger_x_y" 格式
            key = "PassengerStation_" .. x .. "_" .. y
        elseif cellConfig.Type == XLineArithmetic3Enum.GridType.Character then
            -- 乘客使用 "Passenger_x_y" 格式
            key = "Passenger_" .. x .. "_" .. y
        elseif cellConfig.Type == XLineArithmetic3Enum.GridType.End or
            cellConfig.Type == XLineArithmetic3Enum.GridType.ExtraEnd then
            -- 终点格使用 "End_x_y" 格式
            key = "End_" .. x .. "_" .. y
        else
            -- 其他格子使用默认格式
            key = string.format("%d_%d", x, y)
        end
    else
        -- 如果没有配置，使用默认格式
        key = string.format("%d_%d", x, y)
    end

    -- 如果已经创建过，直接返回
    if self._GridElements[key] then
        return self._GridElements[key]
    end

    -- 根据GridName动态获取预制体
    local prefab = self[gridName]
    if not prefab then
        XLog.Warning("[XUiLineArithmetic3Game] 未找到格子预制体:", gridName)
        return nil
    end

    -- 计算世界坐标
    local position = self:GetGridWorldPosition(x, y)

    -- 创建UI元素
    local gridGo = self:InstantiateGrid(prefab, self.PanelBoard)
    gridGo.transform:SetPosition(position.x, position.y, position.z)
    
    local gridItem = XUiLineArithmetic3GridItem.New(gridGo, self)

    -- 缓存
    self._GridElements[key] = gridItem

    return gridItem
end

--- 将屏幕坐标转换为格子坐标
---@param screenPos UnityEngine.Vector2 屏幕坐标
---@return number|nil, number|nil 格子坐标(x, y)，如果不在有效范围内返回nil
function XUiLineArithmetic3Game:ScreenToGridPosition(screenPos)
    -- 将屏幕坐标转换为PanelEmpty的本地坐标
    local isInRect, v2 = CS.UnityEngine.RectTransformUtility.ScreenPointToLocalPointInRectangle(
        self.PanelEmpty.transform,
        screenPos,
        CS.XUiManager.Instance.UiCamera
    )

    if not isInRect then
        return nil, nil
    end

    -- 获取GridLayoutGroup配置
    local gridLayout = self.PanelEmpty:GetComponent(typeof(CS.UnityEngine.UI.GridLayoutGroup))
    local cellSize = gridLayout.cellSize
    local spacing = gridLayout.spacing

    -- 计算格子坐标（从0开始）
    local gridX = math.floor(v2.x / (cellSize.x + spacing.x))
    local gridY = math.floor(v2.y / (cellSize.y + spacing.y))

    -- 转换为游戏坐标（从1开始）
    local x = gridX + 1
    local y = gridY + 1

    -- 验证坐标是否在地图范围内（9x7）
    if x < 1 or x > 9 or y < 1 or y > 7 then
        return nil, nil
    end

    return x, y
end

--- 刷新已走过路径显示（TraveledPath，使用 GridPath）
function XUiLineArithmetic3Game:RefreshTraveledPathDisplay()
    local game = self._Control:GetGame()
    local traveledPath = game:GetTraveledPath() or {}

    -- 清除多余的路径显示（放回对象池）
    while #self._PathGrids > #traveledPath do
        local pathGrid = table.remove(self._PathGrids)
        if pathGrid then
            self:ReturnPathGridToPool(pathGrid)
        end
    end

    -- 创建/更新路径显示
    for i = 1, #traveledPath do
        local pos = traveledPath[i]
        if self.GridPath and pos then
            -- 如果不存在则从对象池获取
            if not self._PathGrids[i] then
                local pathGrid = self:GetPathGridFromPool()
                if pathGrid then
                    local position = self:GetGridWorldPosition(pos.x, pos.y)
                    pathGrid.GameObject:SetActiveEx(true)
                    pathGrid.Transform:SetPosition(position.x, position.y, position.z)
                    self._PathGrids[i] = pathGrid
                end
            end

            -- 设置路径方向（撤销后重新走时方向可能变化，需要重新设置）
            if self._PathGrids[i] then
                local fromDir, toDir = self:_CalcPathDirections(traveledPath, i)
                if fromDir and toDir then
                    local pathType = self:_CalcPathDirectionType(fromDir, toDir)
                    self:SetPathDirection(self._PathGrids[i], pathType)
                end
            end
        end
    end
end

--- 刷新玩家绘制路径显示（当前 Path，使用 GridPathSelected）
function XUiLineArithmetic3Game:RefreshSelectedPathDisplay()
    local game = self._Control:GetGame()
    local drawingPath = game:GetPath() or {}

    -- 清除多余的路径显示
    while #self._SelectedPathGrids > #drawingPath do
        local pathGo = table.remove(self._SelectedPathGrids)
        if pathGo then
            CS.UnityEngine.GameObject.Destroy(pathGo.gameObject)
        end
    end

    -- 创建缺少的路径显示
    for i = #self._SelectedPathGrids + 1, #drawingPath do
        local pos = drawingPath[i]
        if self.GridPathSelected and pos then
            local pathGo = self:InstantiateGrid(self.GridPathSelected, self.PanelPath)
            local position = self:GetGridWorldPosition(pos.x, pos.y)
            pathGo.transform.position = position
            self._SelectedPathGrids[i] = pathGo
        end
    end
end

--- 清空玩家绘制路径显示
function XUiLineArithmetic3Game:ClearSelectedPathDisplay()
    for _, pathGo in ipairs(self._SelectedPathGrids) do
        if pathGo then
            CS.UnityEngine.GameObject.Destroy(pathGo.gameObject)
        end
    end
    self._SelectedPathGrids = {}
end

--- 取消当前临时路径（松手在 PanelTouch/棋盘外视为无效）
function XUiLineArithmetic3Game:CancelCurrentPath()
    local game = self._Control and self._Control:GetGame() or nil
    if game then
        game:ClearPath()
    end
    self:ClearSelectedPathDisplay()
end

--- 开始画线
---@param eventData PointerEventData 事件数据
function XUiLineArithmetic3Game:OnBeginDrag(eventData)
    -- 动画播放中或回退中禁止操作
    if self._CommandManager:IsPlaying() or self._CommandManager:IsRewinding() then
        return
    end

    local x, y = self:ScreenToGridPosition(eventData.position)
    if not x or not y then
        return
    end

    -- 如果不是undo点，并且不在直线可达范围，直接返回，避免格子选中状态闪烁
    local game = self._Control:GetGame()
    local isUndoTarget = game:IsOnTraveledPath({ x = x, y = y }) and not (game:GetHeadPos() and game:GetHeadPos().x == x and game:GetHeadPos().y == y)
    if not isUndoTarget and not game:CanStraightReach({ x = x, y = y }) then
        return
    end

    game:OnPathAdd({ x = x, y = y })
    self:RefreshSelectedPathDisplay()
end

--- 拖动画线
---@param eventData PointerEventData 事件数据
function XUiLineArithmetic3Game:OnDrag(eventData)
    -- 动画播放中或回退中禁止操作
    if self._CommandManager:IsPlaying() or self._CommandManager:IsRewinding() then
        return
    end

    local x, y = self:ScreenToGridPosition(eventData.position)
    if not x or not y then
        return
    end

    local game = self._Control:GetGame()
    local path = game:GetPath()

    -- 如果不在画线过程中，忽略
    if not path or #path == 0 then
        return
    end

    local lastPos = path[#path]

    -- 如果是同一个格子，忽略
    if lastPos.x == x and lastPos.y == y then
        return
    end

    -- 检查是否回退到上一步
    if #path >= 2 then
        local prevPos = path[#path - 1]
        if prevPos.x == x and prevPos.y == y then
            game:OnPathUndo()
            self:RefreshSelectedPathDisplay()
            return
        end
    end

    -- 尝试添加到路径
    local success = game:OnPathAdd({ x = x, y = y })
    if success then
        self:RefreshSelectedPathDisplay()
    end
end

--- 结束画线
---@param eventData PointerEventData 事件数据
function XUiLineArithmetic3Game:OnEndDrag(eventData)
    -- 动画播放中或回退中禁止操作
    if self._CommandManager:IsPlaying() or self._CommandManager:IsRewinding() then
        return
    end

    local game = self._Control:GetGame()
    -- 松手在 PanelTouch/棋盘外：取消本次临时路径，认为无效
    local endX, endY = self:ScreenToGridPosition(eventData.position)
    if not endX or not endY then
        self:CancelCurrentPath()
        return
    end

    -- 先检查回退：用拖拽终点坐标判断是否命中 TraveledPath 上的历史点
    local traveledPath = game:GetTraveledPath()
    if traveledPath and #traveledPath >= 2 then
        local undoGroupCount = 0
        for i = #traveledPath - 1, 1, -1 do
            if traveledPath[i].x == endX and traveledPath[i].y == endY then
                undoGroupCount = #traveledPath - i
                break
            end
        end
        if undoGroupCount > 0 then
            -- 埋点：记录一次回撤操作（无论撤多少组，都算玩家一次操作）
            if game.OnUndo then
                game:OnUndo(1)
            end
            game:ClearPath()
            self:ClearSelectedPathDisplay()
            -- 隐藏方向指示器（倒放期间）
            self:HideAllDirectionIndicators()
            self._CommandManager:UndoGroups(undoGroupCount, function()
                -- 保底刷新所有车站和乘客颜色到 Game 层实际数据
                self:RefreshAllColorsToGameData()
                -- 刷新星星目标显示（Undo 之后）
                self:UpdateStarTarget()
                -- 刷新方向指示器（倒放完成后显示）
                self:RefreshDirectionIndicators()
            end)
            return
        end
    end

    local path = game:GetPath()
    if not path or #path < 2 then
        self:CancelCurrentPath()
        return
    end

    -- 确认路径并获取指令
    game:ConfirmPath()
    local instructions = game:GetInstructions()

    -- 如果有指令，播放动画
    if instructions and #instructions > 0 then
        self:PlayInstructions(instructions)
    else
        game:ClearPath()
        self:ClearSelectedPathDisplay()
    end
end

--- 播放指令列表
---@param instructions table[] 指令列表
function XUiLineArithmetic3Game:PlayInstructions(instructions)
    if not instructions or #instructions == 0 then
        return
    end

    -- 设置播放状态，禁止玩家操作
    self._CommandManager:SetPlaying(true)

    -- 隐藏方向指示器（动画播放期间）
    self:HideAllDirectionIndicators()

    -- 保存指令队列
    self._InstructionQueue = instructions
    self._CurrentInstructionIndex = 0

    -- 开始播放第一个指令
    self:PlayNextInstruction()
end

--- 播放下一个指令
function XUiLineArithmetic3Game:PlayNextInstruction()
    self._CurrentInstructionIndex = self._CurrentInstructionIndex + 1

    -- 检查是否还有指令
    if self._CurrentInstructionIndex > #self._InstructionQueue then
        -- 所有指令播放完成，结束当前分组
        self._CommandManager:EndGroup()
        -- 关闭播放状态
        self._CommandManager:SetPlaying(false)
        -- 清空路径
        self._Control:GetGame():ClearPath()
        -- 清空玩家绘制路径显示
        self:ClearSelectedPathDisplay()
        -- 刷新已走过路径显示
        self:RefreshTraveledPathDisplay()
        -- 保底刷新所有车站和乘客颜色到 Game 层实际数据
        self:RefreshAllColorsToGameData()
        -- 刷新星星目标显示（所有指令完成后，使用最终状态）
        self:UpdateStarTarget()
        -- 刷新方向指示器（动画播放完成后显示）
        self:RefreshDirectionIndicators()
        -- 检查胜利
        self:CheckVictory()
        return
    end

    -- 播放当前指令
    local instruction = self._InstructionQueue[self._CurrentInstructionIndex]
    local Ins = XLineArithmetic3Enum.Instruction

    -- 遇到 MoveHead 时，结束上一组并开启新一组
    if instruction.Type == Ins.MoveHead then
        if self._CurrentInstructionIndex > 1 then
            self._CommandManager:EndGroup()
        end
        self._CommandManager:BeginGroup()
    end

    local currentIndex = self._CurrentInstructionIndex
    self:PlaySingleInstruction(instruction, function()
        -- 仅在上下车指令执行完成后，按「指令序号」刷新星星目标显示
        if instruction.Type == Ins.Board or instruction.Type == Ins.Disembark then
            self:UpdateStarTarget(currentIndex)
        end
        self:PlayNextInstruction()
    end)
end

--- 检查胜利条件
function XUiLineArithmetic3Game:CheckVictory()
    if self._Control:IsHeadAtEnd() then
        self:OnGameComplete()
    end
end

--- 游戏完成（胜利）
function XUiLineArithmetic3Game:OnGameComplete()
    -- 更新星星目标数据
    self._Control:UpdateStarTarget()

    -- 更新结算描述数据
    self._Control:UpdateSettleDesc()

    -- 弹出结算界面
    self._Control:RequestSettle()
end

--- 播放单个指令（使用 Command 模式）
---@param instruction table 指令数据
---@param onComplete function 完成回调
function XUiLineArithmetic3Game:PlaySingleInstruction(instruction, onComplete)
    local Ins = XLineArithmetic3Enum.Instruction
    local command = self:CreateCommand(instruction)

    if command then
        self._CommandManager:ExecuteCommand(command, onComplete)
    else
        if onComplete then onComplete() end
    end
end

--- 根据指令创建对应的 Command 对象
---@param instruction table 指令数据
---@return XLineArithmetic3Command
function XUiLineArithmetic3Game:CreateCommand(instruction)
    local Ins = XLineArithmetic3Enum.Instruction

    if instruction.Type == Ins.MoveHead then
        local MoveHeadCommand = require("XModule/XLineArithmetic3/XLineArithmetic3MoveHeadCommand")
        return MoveHeadCommand.New(self, instruction.X, instruction.Y, instruction.HeadPosBefore)
    elseif instruction.Type == Ins.Board then
        local BoardCommand = require("XModule/XLineArithmetic3/XLineArithmetic3BoardCommand")
        return BoardCommand.New(self, instruction.GridX, instruction.GridY, instruction.CarriageIndex, instruction.Color, instruction.GridPassengerBefore)
    elseif instruction.Type == Ins.Disembark then
        local DisembarkCommand = require("XModule/XLineArithmetic3/XLineArithmetic3DisembarkCommand")
        return DisembarkCommand.New(self, instruction.GridX, instruction.GridY, instruction.CarriageIndex, instruction.Color, instruction.CarriagePassengerBefore)
    elseif instruction.Type == Ins.ActivateEnd then
        local ActivateEndCommand = require("XModule/XLineArithmetic3/XLineArithmetic3ActivateEndCommand")
        return ActivateEndCommand.New(self, instruction.GridX, instruction.GridY)
    elseif instruction.Type == Ins.DyePassenger then
        local DyePassengerCommand = require("XModule/XLineArithmetic3/XLineArithmetic3DyePassengerCommand")
        return DyePassengerCommand.New(self, instruction.CarriageIndex, instruction.Color, instruction.PassengerColorBefore)
    elseif instruction.Type == Ins.DyeStationPassenger then
        local DyeStationPassengerCommand = require("XModule/XLineArithmetic3/XLineArithmetic3DyeStationPassengerCommand")
        return DyeStationPassengerCommand.New(self, instruction.GridX, instruction.GridY, instruction.Color, instruction.PassengerColorBefore)
    elseif instruction.Type == Ins.StationColorChanged then
        local StationColorChangedCommand = require("XModule/XLineArithmetic3/XLineArithmetic3StationColorChangedCommand")
        return StationColorChangedCommand.New(self, instruction.GridX, instruction.GridY, instruction.Color, instruction.StationColorBefore)
    elseif instruction.Type == Ins.ChangePassengerEmoj then
        local ChangePassengerEmojCommand = require("XModule/XLineArithmetic3/XLineArithmetic3ChangePassengerEmojCommand")
        return ChangePassengerEmojCommand.New(self, instruction.GridX, instruction.GridY, instruction.CarriageIndex, instruction.Emoj, instruction.EmojBefore, instruction.IsHead)
    end

    return nil
end

--- 处理车头移动指令
---@param x number 目标格子X坐标
---@param y number 目标格子Y坐标
---@param onComplete function 完成回调
function XUiLineArithmetic3Game:OnMoveHead(x, y, onComplete)
    if not self._HeadGrid then
        XLog.Warning("[XUiLineArithmetic3Game] 车头未初始化")
        if onComplete then onComplete() end
        return
    end

    -- 保存移动前的 UI 状态
    self:SaveUIState()

    -- 获取目标格子的世界坐标
    local targetPos = self:GetGridWorldPosition(x, y)

    -- 获取车头当前位置（车厢的目标位置）
    local headStartPos = self._HeadGrid.transform.position

    -- 记录每个车厢的起始位置
    local carriageStartPositions = {}
    for i, carriageGo in ipairs(self._CarriageGos) do
        if carriageGo then
            carriageStartPositions[i] = carriageGo.transform.position
        end
    end

    -- 使用可追踪的 tween 同步移动车头和车厢
    local duration = 0.3
    self:CreateTween(duration, function(progress)
        -- 车头移动：从当前位置到目标位置
        local headCurrentPos = CS.UnityEngine.Vector3.Lerp(headStartPos, targetPos, progress)
        self._HeadGrid.Transform:SetPosition(headCurrentPos.x, headCurrentPos.y, headCurrentPos.z)

        -- 车厢移动：从各自位置到车头的起始位置
        for i, carriageGo in ipairs(self._CarriageGos) do
            if carriageGo and carriageStartPositions[i] then
                local carriageCurrentPos = CS.UnityEngine.Vector3.Lerp(carriageStartPositions[i], headStartPos, progress)
                carriageGo.transform.position = carriageCurrentPos
            end
        end
    end, function()
        if onComplete then onComplete() end
    end)
end

--- 车厢跟随车头移动（移动到车头的上一个位置）
---@param prevHeadPos UnityEngine.Vector3 车头移动前的位置
function XUiLineArithmetic3Game:MoveCarriagesToHead(prevHeadPos)
    -- 所有车厢移动到车头的上一个位置（跟在车头后一格）
    for _, carriageGo in ipairs(self._CarriageGos) do
        if carriageGo then
            carriageGo.transform.position = prevHeadPos
        end
    end
end

--- 处理乘客上车指令
---@param gridX number 格子X坐标
---@param gridY number 格子Y坐标
---@param carriageIndex number 车厢索引
---@param color number 乘客颜色
---@param onComplete function 完成回调
function XUiLineArithmetic3Game:OnBoard(gridX, gridY, carriageIndex, color, onComplete)
    -- 获取格子上的乘客GameObject
    local passengerKey = "Passenger_" .. gridX .. "_" .. gridY
    local passengerGo = self._GridElements[passengerKey]

    if not passengerGo then
        XLog.Warning("[XUiLineArithmetic3Game] 格子上没有乘客: (" .. gridX .. ", " .. gridY .. ")")
        if onComplete then onComplete() end
        return
    end

    -- 获取目标车厢
    local carriageGo = self._CarriageGos[carriageIndex]
    if not carriageGo then
        XLog.Warning("[XUiLineArithmetic3Game] 车厢未初始化: " .. carriageIndex)
        if onComplete then onComplete() end
        return
    end

    -- 获取车厢的世界坐标
    local targetPos = carriageGo.transform.position

    -- 获取乘客当前位置
    local startPos = passengerGo.transform.position

    -- 使用缓动动画移动乘客到车厢
    local duration = 0.2
    XUiHelper.Tween(duration, function(progress)
        local currentPos = CS.UnityEngine.Vector3.Lerp(startPos, targetPos, progress)
        passengerGo.transform.position = currentPos
    end, function()
        -- 动画完成后，隐藏乘客GameObject
        passengerGo:SetActive(false)

        -- 调用完成回调
        if onComplete then onComplete() end
    end)
end

--- 处理乘客下车指令
---@param gridX number 格子X坐标
---@param gridY number 格子Y坐标
---@param carriageIndex number 车厢索引
---@param _color number 乘客颜色（未使用，因为重用已存在的GameObject）
---@param onComplete function 完成回调
function XUiLineArithmetic3Game:OnDisembark(gridX, gridY, carriageIndex, _color, onComplete)
    -- 获取车厢
    local carriageGo = self._CarriageGos[carriageIndex]
    if not carriageGo then
        XLog.Warning("[XUiLineArithmetic3Game] 车厢未初始化: " .. carriageIndex)
        if onComplete then onComplete() end
        return
    end

    -- 获取已存在的乘客GameObject（初始化时创建的）
    local passengerKey = "Passenger_" .. gridX .. "_" .. gridY
    local passengerGrid = self._GridElements[passengerKey]

    if not passengerGrid then
        XLog.Warning("[XUiLineArithmetic3Game] 格子上没有乘客GameObject: (" .. gridX .. ", " .. gridY .. ")")
        if onComplete then onComplete() end
        return
    end

    -- 重新激活乘客GameObject（上车时被隐藏了）
    passengerGrid.GameObject:SetActive(true)

    -- 获取目标格子的世界坐标
    local targetPos = self:GetGridWorldPosition(gridX, gridY)

    -- 获取车厢当前位置作为起点
    local startPos = carriageGo.transform.position

    -- 设置初始位置为车厢位置
    passengerGrid.Transform:SetPosition(startPos.x, startPos.y, startPos.z)

    -- 使用缓动动画移动乘客到格子
    local duration = 0.2
    XUiHelper.Tween(duration, function(progress)
        local currentPos = CS.UnityEngine.Vector3.Lerp(startPos, targetPos, progress)
        passengerGrid.transform:SetPosition(currentPos.x, currentPos.y, currentPos.z)
    end, function()
        -- 更新乘客颜色（染色后的颜色）
        self:UpdatePassengerColor(passengerGrid, _color)

        -- 调用完成回调
        if onComplete then onComplete() end
    end)
end

--- 处理激活终点格指令
---@param gridX number 格子X坐标
---@param gridY number 格子Y坐标
---@param onComplete function 完成回调
function XUiLineArithmetic3Game:OnActivateEnd(gridX, gridY, onComplete)
    -- 获取终点格GameObject
    local endKey = "End_" .. gridX .. "_" .. gridY
    local endGo = self._GridElements[endKey]

    if not endGo then
        XLog.Warning("[XUiLineArithmetic3Game] 终点格未找到: (" .. gridX .. ", " .. gridY .. ")")
        if onComplete then onComplete() end
        return
    end

    -- 播放激活动画：缩放效果
    local originalScale = endGo.transform.localScale
    local targetScale = originalScale * 1.2

    local duration = 0.3
    XUiHelper.Tween(duration, function(progress)
        local scale = CS.UnityEngine.Vector3.Lerp(originalScale, targetScale, progress)
        endGo.transform.localScale = scale
    end, function()
        -- 恢复原始大小
        endGo.transform.localScale = originalScale

        -- 调用完成回调
        if onComplete then onComplete() end
    end)
end

--- 更新乘客颜色显示
---@param characterGrid XUiLineArithmetic3GridItem 乘客GameObject
---@param color number 颜色值
function XUiLineArithmetic3Game:UpdatePassengerColor(characterGrid, color)
    if not characterGrid then
        return
    end

    -- 先清除旧的颜色节点
    local childCount = characterGrid.Transform.childCount
    for i = childCount - 1, 0, -1 do
        local child = characterGrid.Transform:GetChild(i)
        if child and child.name and string.find(child.name, "GridCharacterColor") then
            CS.UnityEngine.GameObject.Destroy(child.gameObject)
        end
    end

    -- 如果颜色是白色，不需要添加颜色节点
    if not color or color == XLineArithmetic3Enum.Color.White then
        return
    end

    -- 构建颜色预制体名称（如color=2对应GridCharacterColor02）
    local colorPrefabName = string.format("GridCharacterColor%02d", color)
    local colorPrefab = self[colorPrefabName]

    if not colorPrefab then
        XLog.Warning("[XUiLineArithmetic3Game] 颜色预制体未找到: " .. colorPrefabName)
        return
    end

    -- 克隆颜色节点并挂到乘客上
    local colorRoot = characterGrid.ColorRoot and characterGrid.ColorRoot.transform or characterGrid.Transform
    local colorGo = XUiHelper.Instantiate(colorPrefab, colorRoot)
    colorGo.transform:SetLocalPosition(0, 0, 0)
    colorGo.transform:SetLocalScale(1, 1, 1)
    colorGo.transform:SetAsFirstSibling()

end

--- 更新乘客表情显示
---@param gridItem UnityEngine.GameObject 乘客GameObject
---@param emoj number 表情枚举值 (XLineArithmetic3Enum.Emoj)
function XUiLineArithmetic3Game:UpdatePassengerEmoj(gridItem, emoj)
    if not gridItem then
        return
    end

    -- 遍历所有表情节点，只激活目标表情
    if not XTool.IsTableEmpty(self._EmojiMap) then
        for emojValue, nodeName in pairs(self._EmojiMap) do
            local child = gridItem[nodeName]
            if child then
                child.gameObject:SetActiveEx(emojValue == emoj)
            end
        end
    end
end

--- 根据当前关卡配置刷新指引格子（用于下一关/重新挑战后刷新为新区块 tips）
function XUiLineArithmetic3Game:RefreshTipGridsToCurrentStage()
    if not self.PanelTips or not self.GridTips then
        return
    end

    -- 若存在 BtnTips，则仅在按钮处于选中状态时才刷新/显示指引；
    -- 按钮未选中时，确保隐藏指引
    if self.BtnTips then
        local isOn = self.BtnTips:GetToggleState()
        if not isOn then
            self.PanelTips.gameObject:SetActiveEx(false)
            self:ClearTipGrids()
            return
        end
    end
    self:ClearTipGrids()
    local configs = self._Control:GetHelpConfigsForCurrentStage()
    if not configs or #configs == 0 then
        self.PanelTips.gameObject:SetActiveEx(false)
        return
    end
    local parent = self.PanelTips
    for i = 1, #configs do
        local cfg = configs[i]
        local x = cfg.X
        local y = cfg.Y
        if x and y then
            local tipGo = CS.UnityEngine.GameObject.Instantiate(self.GridTips, parent.transform)
            tipGo.gameObject:SetActiveEx(true)
            -- 设置序号文本（TxtNum）
            local txtNum = XUiHelper.TryGetComponent(tipGo.transform, "TxtNum", "Text")
            if txtNum then
                txtNum.text = tostring(i)
            end
            local worldPos = self:GetGridWorldPosition(x, y)
            tipGo.transform.position = worldPos
            self._TipGrids[#self._TipGrids + 1] = tipGo
        end
    end
    self.PanelTips.gameObject:SetActiveEx(true)
end

--- 点击指引按钮：根据当前关卡 mapId 获取帮助配置，在 PanelTips 层对应 (X,Y) 位置创建 GridTips 指引路线
function XUiLineArithmetic3Game:OnClickBtnTips()
    if not self.PanelTips or not self.GridTips then
        return
    end
    local isOn = self.BtnTips:GetToggleState()
    if isOn then
        self.PanelTips.gameObject:SetActiveEx(true)
        self:RefreshTipGridsToCurrentStage()

        -- 埋点：标记使用过提示
        local game = self._Control:GetGame()
        if game then
            game:MarkUsedTips()
        end
    else
        self.PanelTips.gameObject:SetActiveEx(false)
        self:ClearTipGrids()
    end
end

--- 清除当前所有指引格子
function XUiLineArithmetic3Game:ClearTipGrids()
    for _, go in ipairs(self._TipGrids) do
        if go then
            CS.UnityEngine.GameObject.Destroy(go.gameObject)
        end
    end
    self._TipGrids = {}
end

--- 获取格子的世界坐标
---@param x number 格子X坐标（1-9）
---@param y number 格子Y坐标（1-7）
---@return UnityEngine.Vector3 世界坐标
function XUiLineArithmetic3Game:GetGridWorldPosition(x, y)
    if not self.PanelEmpty then
        XLog.Error("[XUiLineArithmetic3Game] PanelEmpty is nil")
        return CS.UnityEngine.Vector3.zero
    end

    -- 获取 GridLayoutGroup 组件
    local gridLayout = self.PanelEmpty:GetComponent(typeof(CS.UnityEngine.UI.GridLayoutGroup))
    if not gridLayout then
        XLog.Error("[XUiLineArithmetic3Game] GridLayoutGroup not found on PanelEmpty")
        return CS.UnityEngine.Vector3.zero
    end

    -- 读取格子大小和间距
    local cellSize = gridLayout.cellSize
    local spacing = gridLayout.spacing

    -- 计算格子的本地坐标
    -- (1,1) 是左下角，X从左到右(1-9)，Y从下到上(1-7)
    -- 转换为从0开始的索引
    local indexX = x - 1
    local indexY = y - 1

    -- 计算本地位置（左下角为原点）
    local localX = indexX * (cellSize.x + spacing.x) + cellSize.x / 2
    local localY = indexY * (cellSize.y + spacing.y) + cellSize.y / 2

    -- 创建本地坐标向量
    local localPos = CS.UnityEngine.Vector3(localX, localY, 0)

    -- 转换为世界坐标（RectTransform 用 .transform 调用 TransformPoint）
    local worldPos = self.PanelEmpty.transform:TransformPoint(localPos)
    return worldPos
end

--- 更新星星目标显示
--- 星1用固定 GridTarget01，星2、3用 GridTarget02 动态创建（动态长度）
---@param step number|nil 指令步数（用于按动画进度预览星星状态）
function XUiLineArithmetic3Game:UpdateStarTarget(step)
    self._Control:UpdateStarTarget(step)

    local uiData = self._Control:GetUiData()
    local stars = uiData.StarDescData
    -- ui逻辑: 第四颗星作为隐藏星
    local starAmount = math.min(3, #stars)

    -- 星1：固定 GridTarget01
    if starAmount >= 1 and self._StarGrid01 then
        self._StarGrid01:Open()
        self._StarGrid01:Update(stars[1])
    elseif self._StarGrid01 then
        self._StarGrid01:Close()
    end

    -- 星2、3：动态长度，从 GridTarget02 实例化
    for i = 2, starAmount do
        local starDesc = stars[i]
        local uiGrid = self._StarGrids[i]
        if not uiGrid then
            local ui = CS.UnityEngine.GameObject.Instantiate(self.GridTarget02, self.GridTarget02.parent)
            uiGrid = XUiLineArithmetic3GameGridTarget.New(ui, self)
            self._StarGrids[i] = uiGrid
        end
        uiGrid:Open()
        uiGrid:Update(starDesc)
    end
    for i = starAmount + 1, #self._StarGrids do
        local uiGrid = self._StarGrids[i]
        uiGrid:Close()
    end
end

--- 更新事件描述显示
function XUiLineArithmetic3Game:UpdateGridDesc()
    self._Control:UpdateGridDesc()
    local uiData = self._Control:GetUiData()
    local gridDescData = uiData.GridDescData

    for i = 1, #gridDescData do
        local gridDesc = gridDescData[i]
        local uiGrid = self._GridDesc[i]
        if not uiGrid then
            local ui = CS.UnityEngine.GameObject.Instantiate(self.SpecialGrid, self.SpecialGrid.parent)
            uiGrid = XUiLineArithmetic3GameGridDetail.New(ui, self)
            self._GridDesc[i] = uiGrid
        end
        uiGrid:Open()
        uiGrid:Update(gridDesc)
    end
    for i = #gridDescData + 1, #self._GridDesc do
        local uiGrid = self._GridDesc[i]
        uiGrid:Close()
    end
end

--[[
-- GridPath 路，玩家划线经过时，复制一个它，把它放在对应的格子上
-- GridObstacle 障碍，无法通过
-- GridStart 起点
-- GridCharacter01 - GridCharacter05 角色（乘客），也是车头
-- GridCharacterColor01 - GridCharacterColor07 颜色节点，当角色染色，或者车站染色时，把它放在对应的格子上
-- GridEnd01 - GridEnd06 额外终点格
-- GridEnd07 终点格，到达后结束游戏
-- GridStation01 - GridStation07 车站
-- GridCarriage 车厢，开局按照配置复制在角色底下，和角色（车头）重叠，角色移动后，跟随角色移动

-- PanelEmpty 这是一个unity的GridLayoutGroup，读取它的坐标和CellSize，还有StartCorner，StartAxis等参数，可以以此计算棋盘上每个格子的位置，确定格子坐标
    对应棋盘数据9*7
--]]

--============================================================================
-- 方向指示器相关方法
--============================================================================

--- 初始化方向指示器引用（从车头GameObject中获取四个方向的节点）
function XUiLineArithmetic3Game:InitDirectionIndicators()
    if not self._HeadGrid then
        return
    end

    local Direction = XLineArithmetic3Enum.Direction
    
    self._DirectionIndicators[Direction.Up] = self._HeadGrid.up
    self._DirectionIndicators[Direction.Left] = self._HeadGrid.Left
    self._DirectionIndicators[Direction.Down] = self._HeadGrid.down
    self._DirectionIndicators[Direction.Right] = self._HeadGrid.Right

    -- 初始隐藏所有方向指示器
    self:HideAllDirectionIndicators()
end

--- 刷新方向指示器显示（根据可移动方向）
function XUiLineArithmetic3Game:RefreshDirectionIndicators()
    -- 如果正在播放动画或倒放，隐藏所有方向指示器
    if self._CommandManager:IsPlaying() or self._CommandManager:IsRewinding() then
        self:HideAllDirectionIndicators()
        return
    end

    -- 获取可移动方向列表
    local movableDirections = self._Control:GetMovableDirections()

    -- 先隐藏所有方向指示器
    self:HideAllDirectionIndicators()

    -- 显示可移动方向的指示器
    for _, data in ipairs(movableDirections) do
        local direction = data.direction
        local indicator = self._DirectionIndicators[direction]
        if indicator then
            indicator.gameObject:SetActiveEx(true)
        end
    end
end

--- 隐藏所有方向指示器
function XUiLineArithmetic3Game:HideAllDirectionIndicators()
    for _, indicator in pairs(self._DirectionIndicators) do
        if indicator then
            indicator.gameObject:SetActiveEx(false)
        end
    end
end

--============================================================================
-- 角色表情切换相关方法
--============================================================================

--- 刷新所有角色的表情表现
function XUiLineArithmetic3Game:RefreshCharacterStates()
    --todo 初始化状态相关
end

--============================================================================
-- 路径方向显示相关方法
--============================================================================

--- 设置路径格子的方向显示
---@param pathGrid XUiLineArithmetic3GridItem 路径格子GameObject
---@param pathDirection number PathDirection 路径方向类型
function XUiLineArithmetic3Game:SetPathDirection(pathGrid, pathDirection)
    if not pathGrid then
        return
    end

    local PathDirectionType = self._PathDirectionType
    local dirType = self._PathDirection2Type[pathDirection]

    -- 根据类型显示对应指示器
    local isStraight = dirType == PathDirectionType.StraightLine
    if pathGrid.Indicator_VRight then
        pathGrid.Indicator_VRight.gameObject:SetActiveEx(isStraight)
    end
    if pathGrid.Indicator_VUpHalf then
        pathGrid.Indicator_VUpHalf.gameObject:SetActiveEx(not isStraight)
    end
    if pathGrid.Indicator_VRightHalf then
        pathGrid.Indicator_VRightHalf.gameObject:SetActiveEx(not isStraight)
    end

    -- 从配置表获取旋转和缩放
    local config = self._PathDirectionConfig[pathDirection]
    local zRotation = config and config[1] or 0
    local xScale = config and config[2] or 1

    -- 应用旋转和缩放到 IndicatorRoot
    if pathGrid.IndicatorRoot then
        pathGrid.IndicatorRoot:SetEulerRotation(0, 0, zRotation)
        pathGrid.IndicatorRoot:SetLocalScale(xScale, 1, 1)
    end
end

--- 计算路径方向类型（根据来向和去向）
---@param fromDirection number 来向
---@param toDirection number 去向
---@return number PathDirection
function XUiLineArithmetic3Game:_CalcPathDirectionType(fromDirection, toDirection)
    local Direction = XLineArithmetic3Enum.Direction
    local PathDirection = XLineArithmetic3Enum.PathDirection

    -- 直线情况
    if fromDirection == Direction.Left and toDirection == Direction.Right then
        return PathDirection.LeftToRight
    end
    if fromDirection == Direction.Right and toDirection == Direction.Left then
        return PathDirection.RightToLeft
    end
    if fromDirection == Direction.Up and toDirection == Direction.Down then
        return PathDirection.UpToDown
    end
    if fromDirection == Direction.Down and toDirection == Direction.Up then
        return PathDirection.DownToUp
    end

    -- 转弯情况
    if fromDirection == Direction.Up and toDirection == Direction.Left then
        return PathDirection.TurnFromUpToLeft
    end
    if fromDirection == Direction.Up and toDirection == Direction.Right then
        return PathDirection.TurnFromUpToRight
    end
    if fromDirection == Direction.Down and toDirection == Direction.Left then
        return PathDirection.TurnFromDownToLeft
    end
    if fromDirection == Direction.Down and toDirection == Direction.Right then
        return PathDirection.TurnFromDownToRight
    end
    if fromDirection == Direction.Left and toDirection == Direction.Up then
        return PathDirection.TurnFromLeftToUp
    end
    if fromDirection == Direction.Left and toDirection == Direction.Down then
        return PathDirection.TurnFromLeftToDown
    end
    if fromDirection == Direction.Right and toDirection == Direction.Up then
        return PathDirection.TurnFromRightToUp
    end
    if fromDirection == Direction.Right and toDirection == Direction.Down then
        return PathDirection.TurnFromRightToDown
    end

    -- 默认返回
    return PathDirection.LeftToRight
end

--- 计算路径点i的来向和去向
---@param path table 路径点列表
---@param index number 当前点索引
---@return number|nil, number|nil fromDirection, toDirection
function XUiLineArithmetic3Game:_CalcPathDirections(path, index)
    if not path or #path < 2 then
        return nil, nil
    end

    local current = path[index]
    local fromDir, toDir = nil, nil

    -- 计算去向（当前点到下一点的方向）
    if index < #path then
        local nextPos = path[index + 1]
        toDir = self:_GetDirection(current, nextPos)
    end

    -- 计算来向（上一点相对于当前点的位置方向，即来源方向）
    if index > 1 then
        local prevPos = path[index - 1]
        fromDir = self:_GetDirection(current, prevPos)
    end

    -- 如果是起点或终点，只有一个方向时，用同一个方向
    if fromDir and not toDir then
        toDir = fromDir
    elseif toDir and not fromDir then
        fromDir = toDir
    end

    return fromDir, toDir
end

--- 根据两点位置计算方向
---@param from table 起点坐标 {x, y}
---@param to table 终点坐标 {x, y}
---@return number Direction
function XUiLineArithmetic3Game:_GetDirection(from, to)
    local Direction = XLineArithmetic3Enum.Direction
    local dx = to.x - from.x
    local dy = to.y - from.y

    if dy > 0 then
        return Direction.Up
    elseif dy < 0 then
        return Direction.Down
    elseif dx < 0 then
        return Direction.Left
    elseif dx > 0 then
        return Direction.Right
    end

    return Direction.Right -- 默认
end

--============================================================================
-- 路径格子对象池相关方法
--============================================================================

--- 从对象池获取路径格子（池为空则创建新的）
---@return XUiLineArithmetic3GridItem
function XUiLineArithmetic3Game:GetPathGridFromPool()
    return self._PathGridPool:GetItemFromPool()
end

--- 将路径格子放回对象池
---@param pathGrid XUiLineArithmetic3GridItem
function XUiLineArithmetic3Game:ReturnPathGridToPool(pathGrid)
    if not pathGrid or not pathGrid.GameObject then
        return
    end

    -- 隐藏对象
    pathGrid.GameObject:SetActiveEx(false)

    self._PathGridPool:ReturnItemToPool(pathGrid)
end


return XUiLineArithmetic3Game
