--[[
-- XUiPBRPauseListAttribute.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-01-12 15:29:17
--]]

local XUiPBRCommonRolePanelAttribute = require("XUi/XUiPBRGame/CommonUiTemplate/CharacterStatusPanel/XUiPBRCommonRolePanelAttribute")

--- 暂停界面的角色属性来源来自于战斗，需要和默认值比较是增长还是下降
---@class XUiPBRPauseListAttribute : XUiPBRCommonRolePanelAttribute
local XUiPBRPauseListAttribute = XClass(XUiPBRCommonRolePanelAttribute, "XUiPBRPauseListAttribute")

--- 获取角色属性信息，可由子类重写
---@overload
---@return XPBRCharacterStatusParams[]
function XUiPBRPauseListAttribute:GetCharacterStatusInfo(customCharId)
    local infos =  self._Control.CharacterControl:GetCharacterStatusInfo(customCharId, true, true)

    if not XTool.IsTableEmpty(infos) then
        local roleData = CS.XFight.Instance.RoleManager:GetRoleByIndex(0)
        
        --- 根据战斗内实时数据进行调整
        if roleData then
            ---@type XNpc
            local npc = roleData.Npc

            if npc and npc.Attrib then
                for i, v in pairs(infos) do
                    if v.StatusId >= 0 and v.StatusId < npc.Attrib.Length then
                        ---@type XAttrib
                        local attrib = npc.Attrib[v.StatusId]
                        local valInFight = 0
                        
                        local fightValSrc = self._Control.CharacterControl:GetStatusFightValueSrcById(v.StatusId)
                        
                        if fightValSrc == XMVCA.XPBRGame.EnumConst.StatusFightSrcType.CurValue then
                            valInFight = attrib.Value
                        elseif fightValSrc == XMVCA.XPBRGame.EnumConst.StatusFightSrcType.MaxValue then
                            valInFight = attrib.MaxValue
                        end
                        
                        local tempAddition = valInFight - v.BaseValue - (v.StrengthValue or 0)
                        
                        v.TempAddition = tempAddition
                        v.ValueDesc = self._Control.CharacterControl:GetFinalValueDescByStatusInfo(v)
                    end
                end
            end
        end
    end
    
    return infos
end

return XUiPBRPauseListAttribute
