--[[
-- XUiLuckyTenant2MainGridChapter.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2025-12-31 16:39:51
--]]

local XUiLuckyTenant2MainGridStage = require("XUi/XUiLuckyTenant2/XUiLuckyTenant2Main/XUiLuckyTenant2MainGridStage")

---@class XUiLuckyTenant2MainGridChapter : XUiNode
---@field Parent XUiLuckyTenant2Main
---@field BtnClick XUiComponent.XUiButton
---@field TxtName UnityEngine.UI.Text
local XUiLuckyTenant2MainGridChapter = XClass(XUiNode, "XUiLuckyTenant2MainGridChapter")

function XUiLuckyTenant2MainGridChapter:OnStart(...)
    self:InitComponents()
    self:Update()
end

function XUiLuckyTenant2MainGridChapter:InitComponents()
    -- 获取 XUiButton 组件
    if not self.BtnClick then
        self.BtnClick = self.GameObject:GetComponent("XUiButton")
        self.BtnClick:AddEventListener(function() self:OnClick() end)
    end
    
    -- 初始化关卡列表
    self._StageGrids = {}
    if self.GridStage then
        self.GridStage.gameObject:SetActiveEx(false)
    end
end

function XUiLuckyTenant2MainGridChapter:Update(data)
    if not data then
        return
    end
    
    self._Data = data
    
    -- 更新章节名称
    -- self.TxtName.text = data.Name or ""
    self.BtnClick:SetNameByGroup(0, data.Name or "")

    -- 设置按钮选中状态
    if self.BtnClick and self.BtnClick.SetButtonState then
        -- 判断当前章节是否被选中
        local isSelected = false
        if self.Parent then
            local currentChapterData = self.Parent:GetCurrentChapterData()
            if currentChapterData then
                isSelected = currentChapterData.Id == data.Id
            end
        end

        if isSelected then
            self.BtnClick:SetButtonState(CS.UiButtonState.Select)
        else
            self.BtnClick:SetButtonState(CS.UiButtonState.Normal)
        end
    end
    
    -- 更新关卡列表
    local stages = data.Stages or {}
    XTool.UpdateDynamicItem(self._StageGrids, stages, self.GridStage, XUiLuckyTenant2MainGridStage, self)
end

function XUiLuckyTenant2MainGridChapter:OnClick()
    self.Parent:OnClickChapter(self._Data)
end

return XUiLuckyTenant2MainGridChapter
