--自动生成，请勿手动更改
local EGameplayTag = {
    root = 0,
    Missile = 1,
    Missile_Parry = 2,
    Missile_Parry_Trigger = 3,
    Missile_Parry_Counter = 4,
    Missile_Parry_Trigger_Interrupt = 5,
    Missile_Parry_Trigger_Sustain = 6,
    Missile_Parry_Trigger_MultiInteract = 7,
    Missile_Parry_Counter_Heavy = 8,
    Missile_Parry_Counter_Light = 9,
    Missile_Parry_Counter_Medium = 10,
    Missile_BehitType = 11,
    Missile_BehitType_Melee = 12,
    Missile_BehitType_Ranged = 13,
    Magic = 14,
    Magic_RelinkDamage = 15,
    Magic_RelinkDamage_HitType = 16,
    Magic_RelinkDamage_HitType_Break = 17,
    Magic_RelinkDamage_HitType_Ultra = 18,
    Magic_RelinkDamage_HitType_MultiSupQte = 19,
    Magic_RelinkDamage_HitType_MultiEndQte = 20,
}
return EGameplayTag
