--[[
-- XUiLuckyTenant2ChessPanelProp.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2025-12-31 16:39:51
--]]

---@class XUiLuckyTenant2ChessPanelProp : XUiNode
local XUiLuckyTenant2ChessPanelProp = XClass(XUiNode, "XUiLuckyTenant2ChessPanelProp")

function XUiLuckyTenant2ChessPanelProp:OnAwake()
    self:InitComponents()
end

function XUiLuckyTenant2ChessPanelProp:InitComponents()
end

function XUiLuckyTenant2ChessPanelProp:OnStart(...)
    self:Update()
end

function XUiLuckyTenant2ChessPanelProp:OnEnable()
end

function XUiLuckyTenant2ChessPanelProp:OnDisable()
end

function XUiLuckyTenant2ChessPanelProp:OnDestroy()
end

function XUiLuckyTenant2ChessPanelProp:Update()
    self.TxtTitle.text = "羁绊名称"
end

return XUiLuckyTenant2ChessPanelProp
