--[[
-- XUiPBRShopNewListAttribute.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-01-12 15:29:17
--]]

local XUiPBRCommonRolePanelAttribute = require("XUi/XUiPBRGame/CommonUiTemplate/CharacterStatusPanel/XUiPBRCommonRolePanelAttribute")

--- 暂停界面的角色属性来源来自于战斗，需要和默认值比较是增长还是下降
---@class XUiPBRShopNewListAttribute : XUiPBRCommonRolePanelAttribute
local XUiPBRShopNewListAttribute = XClass(XUiPBRCommonRolePanelAttribute, "XUiPBRShopNewListAttribute")

--- 获取角色属性信息，可由子类重写
---@overload
---@return XPBRCharacterStatusParams[]
function XUiPBRShopNewListAttribute:GetCharacterStatusInfo(customCharId)
    local infos =  self._Control.CharacterControl:GetCharacterStatusInfo(customCharId, true, true)

    if not XTool.IsTableEmpty(infos) then
        --- 读取服务端数据
        ---@type XNpc
        local attribDict = self._Control.InGameControl:GetCharacterAttribs()
        local maxAttribDict = self._Control.InGameControl:GetCharacterMaxAttribs()
        
        if not XTool.IsTableEmpty(attribDict) then
            for i, v in pairs(infos) do
                if XTool.IsNumberValidEx(v.StatusId) then
                    local valInGame = 0
                    local valueSrc = self._Control.CharacterControl:GetStatusFightValueSrcById(v.StatusId)

                    if valueSrc == XMVCA.XPBRGame.EnumConst.StatusFightSrcType.CurValue then
                        valInGame = attribDict[v.StatusId] or 0
                    elseif valueSrc == XMVCA.XPBRGame.EnumConst.StatusFightSrcType.MaxValue then
                        valInGame = maxAttribDict[v.StatusId] or 0
                    end
                    
                    -- 有数据才表示有变化
                    if valInGame then
                        local tempAddition = valInGame - v.BaseValue - (v.StrengthValue or 0)

                        v.TempAddition = tempAddition
                    end
                    v.ValueDesc = self._Control.CharacterControl:GetFinalValueDescByStatusInfo(v)
                end
            end
        else
            for i, v in pairs(infos) do
                v.ValueDesc = self._Control.CharacterControl:GetFinalValueDescByStatusInfo(v)
            end
        end
    end
    
    return infos
end

return XUiPBRShopNewListAttribute
