--[[
-- XUiTheatre6GainTips.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-04-14 17:42:13
--]]

---@class XUiTheatre6GainTips : XLuaUi
---@field _Control XTheatre6Control
---@field TxtMedalName UnityEngine.UI.Text
---@field TxtTitle UnityEngine.UI.Text
---@field GridSkill UiObject
---@field GridRelic UiObject
local XUiTheatre6GainTips = XLuaUiManager.Register(XLuaUi, "UiTheatre6GainTips")
local XUiGridTheatre6Skill = require("XUi/XUiTheatre6/Character/Grid/XUiGridTheatre6Skill")
local XUiGridTheatre6Relic = require("XUi/XUiTheatre6/Character/Grid/XUiGridTheatre6Relic")
local ItemType = {
    None = 0,
    Skill = 1,
    AttrPack = 2,
}
function XUiTheatre6GainTips:OnAwake()
    self:InitComponents()
end

function XUiTheatre6GainTips:InitComponents()
end

function XUiTheatre6GainTips:OnStart(gridType, girdId, isUpGrade)
    self.GridSkillUi = XUiGridTheatre6Skill.New(self.GridSkill, self)
    self.GridRelicUi = XUiGridTheatre6Relic.New(self.GridRelic, self)
    self._GridType = gridType
    self._GridId = girdId
    self._IsUpGrade = isUpGrade
    self:Refresh()
end

function XUiTheatre6GainTips:OnEnable()
end

function XUiTheatre6GainTips:OnDisable()
end

function XUiTheatre6GainTips:OnDestroy()
end

function XUiTheatre6GainTips:Refresh()
    if self._GridType == ItemType.Skill then
        self.GridSkillUi:Update(self._GridId)
        self.GridSkillUi:SetClickCb(function() end)
        self.GridSkill.gameObject:SetActiveEx(true)
        self.GridRelic.gameObject:SetActiveEx(false)

        local skillConfig = self._Control:GetSkillCfgById(self._GridId)
        self.TxtMedalName.text = skillConfig.Name
    elseif self._GridType == ItemType.AttrPack then
        self.GridRelicUi:Update(self._GridId)
        self.GridSkill.gameObject:SetActiveEx(false)
        self.GridRelic.gameObject:SetActiveEx(true)
    end
    if self._IsUpGrade then
        self:SkillUpGrade()
    else
        self:GetGrid()
    end
    self:DelayCall(function()
        self:Close()
    end, 2)
end

function XUiTheatre6GainTips:GetGrid()
    if self._GridType == ItemType.Skill then
        self.TxtTitle.text =  XUiHelper.GetText("Theatre6GetSkill")
        local skillConfig = self._Control:GetSkillCfgById(self._GridId)
        self.TxtMedalName.text = skillConfig.Name
    else
        self.TxtTitle.text = XUiHelper.GetText("Theatre6GetAttrPack")
        local attrPackConfig = self._Control:GetAttrPackCfgById(self._GridId)
        self.TxtMedalName.text = attrPackConfig.Name
    end
end

function XUiTheatre6GainTips:SkillUpGrade()
    if self._GridType ~= ItemType.Skill then
        self:Close()
        return
    end
    local skillConfig = self._Control:GetSkillCfgById(self._GridId)
    local curlevel = skillConfig.Level
    self.TxtTitle.text = skillConfig.Name
    self.TxtMedalName.text = XUiHelper.GetText("Theatre6SkillUpGrade")
    self.GridSkillUi:ShowUpgradeEffect(true)
end

return XUiTheatre6GainTips
