--[[
-- XUiLifeTreeGuide.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-03-17 14:49:07
--]]

---@class XUiLifeTreeGuide : XLuaUi
---@field _Control XLifeTreeControl
---@field BtnClose XUiComponent.XUiButton
local XUiLifeTreeGuide = XLuaUiManager.Register(XLuaUi, "UiLifeTreeGuide")
function XUiLifeTreeGuide:OnAwake()
    self:InitComponents()
end

function XUiLifeTreeGuide:InitComponents()
    -- Button
    self.BtnClose:AddEventListener(function() self:OnBtnCloseClick() end)

end

function XUiLifeTreeGuide:OnStart(closeCb)
    self.CloseCb = closeCb
    self:Refresh()

    XMVCA.XLifeTree:RequestLifeTreeFinishProcess(XMVCA.XLifeTree.EnumConst.PROCESS_TYPE.GUIDE)
end

function XUiLifeTreeGuide:OnEnable()
end

function XUiLifeTreeGuide:OnDisable()
end

function XUiLifeTreeGuide:OnDestroy()
end

function XUiLifeTreeGuide:Refresh()
    self.BtnClose:SetButtonState(CS.UiButtonState.Normal)
end

function XUiLifeTreeGuide:OnBtnCloseClick(eventData)
    local cb = self.CloseCb
    self:Close()
    if cb then
        cb()
    end
end

return XUiLifeTreeGuide
