--[[
-- XUiPBRChapter.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-01-12 15:26:58
--]]

local XUiPBRChapterPanelStageList = require("XUi/XUiPBRGame/XUiPBRChapter/XUiPBRChapterPanelStageList")

---@field _Control XPBRGameControl
---@class XUiPBRChapter : XLuaUi
local XUiPBRChapter = XLuaUiManager.Register(XLuaUi, "UiPBRChapter")

function XUiPBRChapter:OnAwake()
    self:InitComponents()
end

function XUiPBRChapter:InitComponents()
    -- Back Mainui Help
    self:BindExitBtns()

    -- Button

    -- PanelAsset
    local showItems = self._Control:GetClientPBRNumberArray('PanelAssetItems')

    if showItems then
        self.PanelAsset = XUiHelper.XUiPanelAsset(self, self.PanelAsset, table.unpack(showItems))
    else
        self.PanelAsset.gameObject:SetActiveEx(false)
        XLog.Error('资源栏Item配置为空，隐藏UI。 key：PanelAssetItems, tab: PBRClientConfig.tab')
    end
end

function XUiPBRChapter:OnStart(jumpStageIndex)
    ---@type XUiPBRChapterPanelStageList
    self.PanelStageList = XUiPBRChapterPanelStageList.New(self.PanelStage, self)
    self.PanelStageList:Open()

    if not jumpStageIndex then
        jumpStageIndex = self._Control:GetJumpStageIndexByBaseRule()
    end
    
    self.PanelStageList:JumpToStageByIndex(jumpStageIndex)
end

function XUiPBRChapter:OnEnable()
end

function XUiPBRChapter:OnDisable()
    
end

function XUiPBRChapter:OnDestroy()
    
end

return XUiPBRChapter
