--[[
-- XUiFashionSuitLobbyPanelRight.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-02-03 10:29:12
--]]

--[[
-- XUiFashionSuitLobbyPanelRight.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-02-03 10:29:12
--]]
local XUiGridCommon = require("XUi/XUiObtain/XUiGridCommon")
---@class XUiFashionSuitLobbyPanelRight : XUiNode
local XUiFashionSuitLobbyPanelRight = XClass(XUiNode, "XUiFashionSuitLobbyPanelRight")
---@field Grid256New XUiFashionSuitLobbyGrid256New
---@field BtnClick XUiButton

function XUiFashionSuitLobbyPanelRight:OnAwake()
end

function XUiFashionSuitLobbyPanelRight:InitComponents()
    -- Button
    self.BtnClick:AddEventListener(function() self:OnBtnClickClick() end)
end

function XUiFashionSuitLobbyPanelRight:OnStart(...)
    self:InitComponents()
end

function XUiFashionSuitLobbyPanelRight:OnEnable()
    self:UpdateReddot()
    self:UpdateReward()
end

function XUiFashionSuitLobbyPanelRight:OnDisable()
end

function XUiFashionSuitLobbyPanelRight:OnDestroy()
end

function XUiFashionSuitLobbyPanelRight:Refresh(cfg)
    self._Cfg = cfg
    self:UpdateReddot()
    self:UpdateReward()
    self.Grid256New.gameObject:SetActiveEx(false)

    self.BtnClick:SetNameByGroup(0, cfg.Name)

    local uiConfig = self._Control:GetFashionSuitUiConfigById(cfg.Id)
    self.BtnClick:SetRawImage(uiConfig.SuitBackground)
    self.UiRImgPicCG:SetRawImage(uiConfig.FirstBg)
    self:HideUiByComplete()
end

function XUiFashionSuitLobbyPanelRight:HideUiByComplete()

    if not self._Cfg then
        return
    end
    -- self.BtnClick:ActiveTextByGroup(1,not self._Cfg.IsComplete)
    if self.PanelTxtDesc then
        self.PanelTxtDesc.gameObject:SetActiveEx(not self._Cfg.IsComplete)
    end
    self.BtnClick:SetNameByGroup(1,  XUiHelper.GetText("FashionSuitProgress3"))
    self.PanelRewardContent.gameObject:SetActiveEx(self._Cfg.IsComplete)
    if self._Cfg.IsComplete then
        return
    end
end

function XUiFashionSuitLobbyPanelRight:SetUiSprite(imgQuality, spriteName)
    imgQuality:SetSprite(spriteName)
end

function XUiFashionSuitLobbyPanelRight:OnBtnClickClick(eventData)
    XLuaUiManager.Open("UiFashionSuitMain", self._Cfg.Id)
end


function XUiFashionSuitLobbyPanelRight:UpdateReddot()
    if not self._Cfg then
        self.BtnClick:ShowReddot(false)
        self.BtnClick:ShowTag(false)
        return
    end
    local hasNew = self._Control:IsSuitHasNew(self._Cfg.Id)
    local canGetReward =self._Cfg.IsComplete and self._Control:IsSuitRewardCanGain(self._Cfg.Id)
    if canGetReward then
        hasNew = false
    end
    self.BtnClick:ShowReddot(canGetReward)
    self.BtnClick:ShowTag(hasNew)
end

function XUiFashionSuitLobbyPanelRight:UpdateReward()
    if not self._Cfg then
        return
    end
    self.RewardPanelList = self.RewardPanelList or {}
    for i = 1, #self.RewardPanelList do
        self.RewardPanelList[i].GameObject:SetActiveEx(false)
    end
    if self._Cfg.IsComplete then
        local rewards = XRewardManager.GetRewardList(self._Cfg.RewardId)
        for i = 1, #rewards do
            local grid = self.RewardPanelList[i]
            if not grid then
                local ui = XUiHelper.Instantiate(self.Grid256New, self.Grid256New.transform.parent)
                grid = XUiGridCommon.New(self, ui)
                table.insert(self.RewardPanelList, grid)
            end
            grid:Refresh(rewards[i])
            local isRewardGain = self._Control:IsSuitRewardGain(self._Cfg.Id)
            grid:SetReceived(isRewardGain)
            grid.GameObject:SetActiveEx(true)
        end
    end
end

return XUiFashionSuitLobbyPanelRight
