--[[
-- XUiPBRPauseListExclusive.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-01-12 15:29:17
--]]

local XUiPBRCommonRolePanelExclusive = require("XUi/XUiPBRGame/CommonUiTemplate/CharacterStatusPanel/XUiPBRCommonRolePanelExclusive")

---@class XUiPBRPauseListExclusive : XUiPBRCommonRolePanelExclusive
local XUiPBRPauseListExclusive = XClass(XUiPBRCommonRolePanelExclusive, "XUiPBRPauseListExclusive")

return XUiPBRPauseListExclusive
