--[[
-- XUiPBRCommonItemDetailGrid.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-01-12 15:30:37
--]]

local XUiPBRCommonItemDetailSkillIcon = require("XUi/XUiPBRGame/CommonUiTemplate/ItemDetailPopupPanel/XUiPBRCommonItemDetailSkillIcon")
local XUiPBRCommonItemDetailTag = require("XUi/XUiPBRGame/CommonUiTemplate/ItemDetailPopupPanel/XUiPBRCommonItemDetailTag")

---@class XUiPBRCommonItemDetailGrid : XUiNode
---@field _Control XPBRGameControl
---@field PanelDesc UnityEngine.UI.ScrollRect
local XUiPBRCommonItemDetailGrid = XClass(XUiNode, "XUiPBRCommonItemDetailGrid")

---@param rootUi XLuaUi
function XUiPBRCommonItemDetailGrid:OnStart(rootUi)
    self.RootUi = rootUi

    self:InitComponents()
end

function XUiPBRCommonItemDetailGrid:OnEnable()
end

function XUiPBRCommonItemDetailGrid:OnDisable()
end

function XUiPBRCommonItemDetailGrid:OnDestroy()
end

function XUiPBRCommonItemDetailGrid:InitComponents()
    -- XUiNode
    ---@type XUiGridCommon
    self.PropGrid = XUiHelper.XUiGridCommon(self.RootUi, self.GridProp)
    ---@type XUiPBRCommonItemDetailSkillIcon
    self.GridSkill = XUiPBRCommonItemDetailSkillIcon.New(self.GridSkill, self)

    if self.TxtDetail:GetType() == typeof(CS.XUiComponent.XUiRichTextCustomRender) then
        self.TxtDetail.requestImage = self._Control:GetRichTextImageRequestHandler()
    end
end

---@param itemId number
function XUiPBRCommonItemDetailGrid:Refresh(itemId, resetScroll)
    if not itemId then
        return
    end

    if resetScroll then
        self.PanelDesc.verticalNormalizedPosition = 1
    end

    self.ItemId = itemId

    self:AOPRefreshBefore()
    
    local itemCfg = self._Control:GetPBRItemCfgById(itemId)
    
    -- 基础信息
    self.TxtName.text = itemCfg.ItemName
    self.TxtDetail.text = XUiHelper.ReplaceTextNewLine(itemCfg.ItemDesc)
    
    -- 判断类型
    if itemCfg.ItemType == XMVCA.XPBRGame.EnumConst.ItemType.Skill then
        self.GridSkill:Open()
        self.GridSkill:Refresh(itemId)

        self.PropGrid.GameObject:SetActiveEx(false)
        
        self:AOPRefreshSkillShowAddition()
    else
        self.PropGrid.GameObject:SetActiveEx(true)
        self.PropGrid:ShowIcon(itemCfg.Icon)
        self.PropGrid:SetBtnNotClick(true)
        
        if itemCfg and XTool.IsNumberValidEx(itemCfg.ItemTier) then
            self.PropGrid:SetQualityShowCustom(itemCfg.ItemTier)
        end
        
        self.GridSkill:Close()
        
        self:AOPRefreshOtherShowAddition()
    end
    
    -- 显示星级
    if itemCfg.ItemType == XMVCA.XPBRGame.EnumConst.ItemType.Skill then
        if self.PanelStarBase then
            self.PanelStarBase.gameObject:SetActiveEx(true)
        end
        self:ShowStartByLevel(itemCfg.ItemTier, itemCfg.OrbColor)
    else
        -- 非技能，详情里不显示额外的星星
        self:ShowStartByLevel(0, 0)
        if self.PanelStarBase then
            self.PanelStarBase.gameObject:SetActiveEx(false)
        end
    end
    
    -- 刷新标签显示
    self:RefreshTagsShow(itemCfg.Tags)
    
    self:AOPRefreshAfter()
end

function XUiPBRCommonItemDetailGrid:ShowStartByLevel(level, orbColor)
    local colorTextList = self._Control:GetClientPBRTextArray('SkillOrbStarColor')
    local colorStr = colorTextList[orbColor + 1] or ''
    
    XUiHelper.RefreshCustomizedList(self.PanelStar, self.ImgStar, level, function(index, go)
        local img = go:GetComponent("Image")

        if img and not string.IsNilOrEmpty(colorStr) then
            img.color = XUiHelper.Hexcolor2Color(string.gsub(colorStr, "#", ""))
        end
    end)
end

function XUiPBRCommonItemDetailGrid:RefreshTagsShow(tags)
    if self._TagGridDict == nil then
        self._TagGridDict = {}
    else
        for i, v in pairs(self._TagGridDict) do
            v:Close()
        end
    end
    
    XUiHelper.RefreshCustomizedList(self.PanelTag.transform, self.Tag, tags and #tags or 0, function(index, go)
        ---@type XUiPBRCommonItemDetailTag
        local tagGrid = self._TagGridDict[go]

        if not tagGrid then
            tagGrid = XUiPBRCommonItemDetailTag.New(go, self)
            self._TagGridDict[go] = tagGrid
        end
        
        tagGrid:Open()
        tagGrid:SetTagShow(tags[index])
    end)
end

--- 子类重写，刷新前执行
function XUiPBRCommonItemDetailGrid:AOPRefreshBefore()
    
end

--- 子类重写，刷新技能显示时额外显示别的内容
function XUiPBRCommonItemDetailGrid:AOPRefreshSkillShowAddition()
    
end

--- 子类重写，刷新普通道具显示时额外显示别的内容
function XUiPBRCommonItemDetailGrid:AOPRefreshOtherShowAddition()

end

--- 子类重写，刷新最后执行
function XUiPBRCommonItemDetailGrid:AOPRefreshAfter()
    
end

return XUiPBRCommonItemDetailGrid
