--[[
-- XUiPBRCollectionGridCollection.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-01-29 16:34:49
--]]

---@class XUiPBRCollectionGridCollection : XUiNode
---@field GridStateCtrl XUiComponent.XUiStateControl
local XUiPBRCollectionGridCollection = XClass(XUiNode, "XUiPBRCollectionGridCollection")


function XUiPBRCollectionGridCollection:InitComponents()
    if self.GridBtn then
        self.GridBtn.enabled = false
    end
end

function XUiPBRCollectionGridCollection:OnStart(...)
    self:InitComponents()
end

function XUiPBRCollectionGridCollection:OnEnable()
end

function XUiPBRCollectionGridCollection:OnDisable()
end

function XUiPBRCollectionGridCollection:OnDestroy()
    
end

---@param params XPBRCollectionItemParam
function XUiPBRCollectionGridCollection:RefreshShow(params)
    if params.IsUnlock then
        self.GridStateCtrl:ChangeState('Normal')
        self.GridBtn:SetRawImage(params.Icon)

        if not string.IsNilOrEmpty(params.IconQuality) then
            for i = 1, 10 do
                local qualityUi = self["ImgQuality" .. i]
                if qualityUi then
                    qualityUi.gameObject:SetActiveEx(true)
                    qualityUi:SetImage(params.IconQuality)
                else
                    break
                end
            end
        else
            for i = 1, 10 do
                local qualityUi = self["ImgQuality" .. i]
                if qualityUi then
                    qualityUi.gameObject:SetActiveEx(false)
                else
                    break
                end
            end
        end
    else
        self.GridStateCtrl:ChangeState('Question')
    end
end

function XUiPBRCollectionGridCollection:SetSelectState(isSelect)
    self.GridBtn:SetButtonState(isSelect and CS.UiButtonState.Select or CS.UiButtonState.Normal)
end

return XUiPBRCollectionGridCollection
