--[[
-- XUiLineArithmetic3ChapterGridStar.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-02-03 19:58:14
--]]

---@class XUiLineArithmetic3ChapterGridStar : XUiNode
---@field _Control XLineArithmetic3Control
---@field ImgStarOff UnityEngine.UI.RawImage
---@field ImgStarOn UnityEngine.UI.RawImage
local XUiLineArithmetic3ChapterGridStar = XClass(XUiNode, "XUiLineArithmetic3ChapterGridStar")

--- 更新星星状态
---@param isActive boolean 是否激活
function XUiLineArithmetic3ChapterGridStar:Update(isActive)
    if isActive then
        self.ImgStarOff.gameObject:SetActiveEx(false)
        self.ImgStarOn.gameObject:SetActiveEx(true)
    else
        self.ImgStarOff.gameObject:SetActiveEx(true)
        self.ImgStarOn.gameObject:SetActiveEx(false)
    end
end

return XUiLineArithmetic3ChapterGridStar
