--[[
-- XUiCommonPopupBuyAsset.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-01-14 15:40:01
--]]

local XUiCommonPopupBuyAssetTargetCard = require("XUi/XUiCommonPopupBuyAsset/XUiCommonPopupBuyAssetTargetCard")

---@class XUiCommonPopupBuyAsset : XLuaUi
local XUiCommonPopupBuyAsset = XLuaUiManager.Register(XLuaUi, "UiCommonPopupBuyAsset")

function XUiCommonPopupBuyAsset:OnAwake()
    self:InitComponents()
end

function XUiCommonPopupBuyAsset:InitComponents()
    -- Button
    self.BtnClose:AddEventListener(handler(self, self.Close))
    self.BtnCancel:AddEventListener(handler(self, self.Close))
    self.BtnPackage:AddEventListener(handler(self, self.OnBtnPackageClicked))
    self.BtnMinusSelect:AddEventListener(handler(self, self.OnBtnMinusSelectClicked))
    self.BtnAddSelect:AddEventListener(handler(self, self.OnBtnAddSelectClicked))
    self.BtnMax:AddEventListener(handler(self, self.OnBtnMaxClicked))
    self.BtnConfirm:AddEventListener(handler(self, self.OnBtnConfirmClicked))
    self.TxtSelect.onValueChanged:AddListener(function()
        self:OnTxtSelectValueChanged()
    end)
    -- InputField 的文本颜色要通过 textComponent 获取
    self.CurNumColor = self.TxtSelect.textComponent.color

end

function XUiCommonPopupBuyAsset:OnStart(useItemId, callBack, challengeCountData, buyAmount)
    self.ItemId = useItemId
    self.CallBack = callBack
    self.ChallengeCountData = challengeCountData
    self.BuyAmount = buyAmount or 1
    self.Cards = {}
    local exchangeConfigs = self._Control:GetItemExchangeConfigsByItemId(self.ItemId)
    for i, config in ipairs(exchangeConfigs) do
        local card = XUiHelper.Instantiate(self.Card1, self.Card1.transform.parent)
        card.gameObject:SetActiveEx(true)
        self.Cards[i] = XUiCommonPopupBuyAssetTargetCard.New(card, self)
        self.Cards[i]:Update(config)
        if not self.CurSelectCard then
            self.Cards[i]:OnSelect()
        else
            self.Cards[i]:OnNormal()
        end
    end
    self:Update()
    self.Card1.gameObject:SetActiveEx(false)
    self.BtnPackage.gameObject:SetActiveEx(XMVCA.XItem:CheckItemHasPackage(self.ItemId))
    self.CardImg:SetImage(XDataCenter.ItemManager.GetItemIcon(self.ItemId))

end

function XUiCommonPopupBuyAsset:OnEnable()
end

function XUiCommonPopupBuyAsset:OnDisable()
end

function XUiCommonPopupBuyAsset:OnDestroy()
end

function XUiCommonPopupBuyAsset:Update()

    if not self.CurSelectCard then
        return
    end
    local itemCount = XDataCenter.ItemManager.GetCount(self.CurSelectCard.ItemId)
    local itemType = XDataCenter.ItemManager.GetItemType(self.CurSelectCard.ItemId)
    local MAX_COUNT = CS.XGame.Config:GetInt("ShopBuyGoodsCountLimit")
    if itemType == XItemConfigs.ItemType.FurnitureItem then
        MAX_COUNT = XFurnitureConfigs.MaxDrawBuyCount
    end
    local buyLimit = XItemConfigs.GetBuyAssetBuyLimit(self.CurSelectCard.ItemId)
    if buyLimit ~= 0 then
        MAX_COUNT = buyLimit
    end
    self.MaxExchangeCount = math.min(MAX_COUNT, math.floor(itemCount / self.CurSelectCard.Config.UseItemCount) or 1)
    self.MinExchangeCount = self.CurSelectCard.Config.MinCount or 1
    if self.MaxExchangeCount < self.MinExchangeCount then
        self.MinExchangeCount = 0
    end
    local curCount = self.BuyAmount
    if self.BuyAmount >self.MaxExchangeCount then
        curCount = self.MaxExchangeCount
    end
    if curCount < self.MinExchangeCount then
        curCount = self.MinExchangeCount
    end
    self.CurExchangeCount = curCount
    self:NotifyItemCountChange()
    self.TxtPossess.text =XUiHelper.GetText("UiBuyAssetHasCount", XDataCenter.ItemManager.GetCount(self.ItemId))
    self.CurSelectCard:RefreshCostNum()
end

function XUiCommonPopupBuyAsset:OnBtnPackageClicked()
    XLuaUiManager.Open("UiCommonPopupUsePackage", self.ItemId, self.CallBack, self.ChallengeCountData, self.BuyAmount)
    self:Close()
end

-- 减少兑换数量
function XUiCommonPopupBuyAsset:OnBtnMinusSelectClicked()
    if self.CurExchangeCount <= self.MinExchangeCount then
        return
    end
    self.CurExchangeCount = self.CurExchangeCount - 1
    self:NotifyItemCountChange()
end

-- 增加兑换数量
function XUiCommonPopupBuyAsset:OnBtnAddSelectClicked()
    if self.CurExchangeCount + 1 > self.MaxExchangeCount then
        return
    end
    self.CurExchangeCount = self.CurExchangeCount + 1
    self:NotifyItemCountChange()
end

-- 最大兑换数量
function XUiCommonPopupBuyAsset:OnBtnMaxClicked()
    self.CurExchangeCount = self.MaxExchangeCount
    self:NotifyItemCountChange()
end

function XUiCommonPopupBuyAsset:OnTxtSelectValueChanged()
    if self._IsUpdatingSelectText then
        return
    end

    local count = tonumber(self.TxtSelect.text)
    if not count then
        count = self.MinExchangeCount
    end
    if count < self.MinExchangeCount then
        count = self.MinExchangeCount
    end
    if count > self.MaxExchangeCount then
        count = self.MaxExchangeCount
    end
    self.CurExchangeCount = count
    self:NotifyItemCountChange()
end

function XUiCommonPopupBuyAsset:NotifyItemCountChange()
    local curNum = self.CurExchangeCount
    if curNum < 1 then
        curNum = 1
    end
    local selectText = tostring(curNum)

    self._IsUpdatingSelectText = true
    self.TxtSelect.text = selectText
    -- InputField 的文本颜色要通过 textComponent 设置
    self.TxtSelect.textComponent.color = self.CurExchangeCount < 1 and CS.UnityEngine.Color.red or self.CurNumColor
    self._IsUpdatingSelectText = false

    for _, card in ipairs(self.Cards) do
        card:OnChangeNum(self.CurExchangeCount)
    end
end

function XUiCommonPopupBuyAsset:OnBtnConfirmClicked()
    if not self.CurSelectCard or self.CurExchangeCount <= 0 then
        return
    end
    XMVCA.XItem:RequestExchange(self.ItemId, self.CurExchangeCount, self.CurSelectCard.ItemId, function(rewardGoodsList)
        XUiManager.OpenUiObtain(rewardGoodsList)
        self:Update()
        if self.CallBack then
            self.CallBack()
        end
    end)
end

return XUiCommonPopupBuyAsset
