---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangzhuolin.
--- DateTime: 2025/4/16 14:38
---
local QuestBase = require("Common/XQuestBase")
---@class XQuestScript6001
local Quest_6001 = XDlcScriptManager.RegQuestScript(6001, "XQuestScript6001", QuestBase)

function Quest_6001:Init()
end

function Quest_6001:Terminate()
end

--================================================
--DLC-任务目标类型：https://kurogame.feishu.cn/docx/TR7AdBehwoWUrrxpV0cc0Wp1nxf

---@class Quest6001Objective
local Quest6001Objective = XClass(nil, "Quest6001Objective")

---@param quest XQuestScript6001
function Quest6001Objective:Ctor(quest)
    self.quest = quest
end

local emptyVector3 = { x = 0, y = 0, z = 0 }

local ObjectiveDefines = {}
--不用数字key，是为了能在IDEA的structure视图中识别这里的table结构，方便快速跳转

--1.前往时序广场寻找NPC库探探
---@class QuestObjective60010101 : Quest6001Objective
ObjectiveDefines.Obj60010101 = {
    Id = 60010101,
    Type = EQuestObjectiveType.ReachTargetPosition,
    Args = {
        LevelId = 4001,
        TargetPosition = { x = 575.009, y = 145.223, z = 1368.089 },                   -- 后续替换为摆放点坐标
        ReachDistance = 3,                             -- 到达锚点3米范围内
    },
    ---@param obj QuestObjective60010101
    ---@param proxy StatusSyncFight.XFightScriptProxy
    EnterFunc = function(obj, proxy)
        proxy:SetNpcInteractComponentEnable(proxy:GetNpcUUID(100002), false)    --关闭NPC的交互
        proxy:FinishQuestObjectiveScriptEnter()
    end,
    ---@param obj QuestObjective60010101
    ---@param proxy StatusSyncFight.XFightScriptProxy
    ExitFunc = function(obj, proxy)
        proxy:FinishQuestObjectiveScriptExit()
    end,
}

--2.播放Drama
---@class QuestObjective60010102 : Quest6001Objective
ObjectiveDefines.Obj60010102 = {
    Id = 60010102,
    Type = EQuestObjectiveType.DramaPlayFinish,
    Args = {
        LevelId = 4001,
        DramaName = "DramaNPC9000212",
    },
    ---@param obj QuestObjective60010102
    ---@param proxy StatusSyncFight.XFightScriptProxy
    EnterFunc = function(obj, proxy)
        proxy:SetNpcInteractComponentEnable(proxy:GetNpcUUID(100002), false)
        proxy:FinishQuestObjectiveScriptEnter()
        proxy:LoadSceneObject(100006)
    end,
    ---@param obj QuestObjective60010102
    ---@param proxy StatusSyncFight.XFightScriptProxy
    ExitFunc = function(obj, proxy)
        proxy:SetSceneObjectActive(100006, false)
        proxy:FinishQuestObjectiveScriptExit()
    end,
}

--3.等待宝箱打开
---@class QuestObjective60010103 : Quest6001Objective
ObjectiveDefines.Obj60010103 = {
    Id = 60010103,
    Type = EQuestObjectiveType.InteractComplete,
    Args = {
        LevelId = 4001,
        TargetArgs = {
            --交互对象是一个SceneObject
            [ETargetActorType.SceneObject] = {
                [100006] = 0,--宝箱
            },
        },
    },
    ---@param obj QuestObjective60010103
    ---@param proxy StatusSyncFight.XFightScriptProxy
    InitFunc = function(obj, proxy)
        obj.TriggerID1 = 800014
    end,
    ---@param obj QuestObjective60010103
    ---@param proxy StatusSyncFight.XFightScriptProxy
    EnterFunc = function(obj, proxy)
        proxy:LoadSceneObject(obj.TriggerID1)
        proxy:NpcNavigateTo(proxy:GetNpcUUID(100002), { x =575.01, y = 145.082, z = 1350.83 }, ENpcMoveType.Walk) --NPC寻路到寶箱
        proxy:AddTimerTask(6, function()    --  监听时间
            proxy:DoSceneObjectAction(100006, 6001)
            proxy:AddTimerTask(1,function()
                proxy:SetSceneObjectActive(100006, true)
            end)
            proxy:FinishQuestObjectiveScriptEnter()
        end)
    end,
    ---@param obj QuestObjective60010103
    ---@param proxy StatusSyncFight.XFightScriptProxy
    ExitFunc = function(obj, proxy)
        proxy:SetNpcInteractComponentEnable(proxy:GetNpcUUID(100002), true)
        proxy:FinishQuestObjectiveScriptExit()
    end,
}

local StepDefines = {} --本任务包含的所有任务步骤的参数配置（不要删除！）

--Step的参数配置，至少要有一个，可按需增加
StepDefines.Step = {
    Id = 600101,
    ExecMode = EQuestStepExecMode.Serial,
}
QuestBase.InitSteps(StepDefines) --固定的任务步骤数据初始化调用（不要删除！）
QuestBase.InitQuestObjectives(Quest6001Objective, ObjectiveDefines) --固定的任务目标数据初始化调用（不要删除！）

return Quest_6001