--[[
-- XUiLuckyTenant2PopupStageDetail.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2025-12-31 16:39:51
--]]

local XUiLuckyTenant2PopupStageDetailGrid = require("XUi/XUiLuckyTenant2/XUiLuckyTenant2PopupStageDetail/XUiLuckyTenant2PopupStageDetailGrid")
local XUiLuckyTenant2GameUiLuckyTenant2BondsDetail = require("XUi/XUiLuckyTenant2/XUiLuckyTenant2Game/XUiLuckyTenant2GameUiLuckyTenant2BondsDetail")

---@class XUiLuckyTenant2PopupStageDetail : XLuaUi
---@field _Control XLuckyTenant2Control
local XUiLuckyTenant2PopupStageDetail = XLuaUiManager.Register(XLuaUi, "UiLuckyTenant2PopupStageDetail")

function XUiLuckyTenant2PopupStageDetail:OnAwake()
    self:InitComponents()
end

function XUiLuckyTenant2PopupStageDetail:InitComponents()
    -- Button
    if self.BtnTanchuangCloseBig then
        self.BtnTanchuangCloseBig:AddEventListener(function() self:OnBtnTanchuangCloseClick() end)
    end
    if self.BtnTanchuangClose then
        self.BtnTanchuangClose:AddEventListener(function() self:OnBtnTanchuangCloseClick() end)
    end
    if self.BtnTongBlue02 then
        self.BtnTongBlue02:AddEventListener(function() self:OnBtnTongBlue02Click() end)
        -- 将按钮在父节点的 SiblingIndex 提到最高
        self.BtnTongBlue02.transform:SetAsLastSibling()
    end
    -- if self.BtnCloseDetail then
    --     XUiHelper.RegisterClickEvent(self, self.BtnCloseDetail, self.OnBtnCloseDetailClick)
    -- end

    -- DynamicTable
    self.DynamicTableNormal = XUiHelper.DynamicTableNormal(self, self.PanelList, XUiLuckyTenant2PopupStageDetailGrid)
    if self.GridPiece then
        self.GridPiece.gameObject:SetActiveEx(false)
    end

    -- 初始化羁绊详情面板
    if self.UiLuckyTenant2BondsDetail then
        self.UiLuckyTenant2BondsDetail.gameObject:SetActiveEx(false)
        ---@type XUiLuckyTenant2GameUiLuckyTenant2BondsDetail
        self._BondsDetail = XUiLuckyTenant2GameUiLuckyTenant2BondsDetail.New(self.UiLuckyTenant2BondsDetail, self)
        self._BondsDetail:Close()
    end
end

function XUiLuckyTenant2PopupStageDetail:OnStart(stageId, ...)
    self._StageId = stageId
    if self._Control and stageId then
        self._Control:UpdateStageDetail(stageId)
    end
end

function XUiLuckyTenant2PopupStageDetail:OnEnable()
    self:Update()
end

function XUiLuckyTenant2PopupStageDetail:OnDisable()
end

function XUiLuckyTenant2PopupStageDetail:OnDestroy()
end

function XUiLuckyTenant2PopupStageDetail:Update()
    if not self._Control then
        return
    end

    local data = self._Control:GetUiData().StageDetail
    if not data then
        return
    end

    -- 更新关卡名称：章节名·关卡名（stage 表 Name）
    local displayName = (data.ChapterName and data.ChapterName ~= "" and (data.ChapterName) or "") .. (data.Name or "")
    if self.RImgStageName then
        self.RImgStageName.text = displayName
    end

    -- 更新最佳回合数
    if self.TxtSchedule then
        self.TxtSchedule.text = tostring(data.BestRound or 0)
    end

    -- 更新最佳分数
    if self.TxtScore then
        self.TxtScore.text = tostring(data.BestScore or 0)
    end

    -- 更新MAX标记
    if self.Max then
        self.Max.gameObject:SetActiveEx(data.IsMax or false)
    end

    -- 更新任务数量
    if self.TxtRewardNum then
        self.TxtRewardNum.text = tostring(data.QuestAmount or 0)
    end

    -- 更新关卡描述：普通描述 / 完美通关描述（配置表 Desc、PerfectDesc）；为空时隐藏该文本和其父节点
    local descNormal = data.Desc and tostring(data.Desc):gsub("^%s*(.-)%s*$", "%1") or ""
    if self.TxtTargetNormal then
        self.TxtTargetNormal.text = descNormal
        local parent = self.TxtTargetNormal.transform and self.TxtTargetNormal.transform.parent
        if parent and parent.gameObject then
            parent.gameObject:SetActiveEx(descNormal ~= "")
        end
    end
    local descPerfect = data.PerfectDesc and tostring(data.PerfectDesc):gsub("^%s*(.-)%s*$", "%1") or ""
    if self.TxtTargetPerfect then
        self.TxtTargetPerfect.text = descPerfect
        local parent = self.TxtTargetPerfect.transform and self.TxtTargetPerfect.transform.parent
        if parent and parent.gameObject then
            parent.gameObject:SetActiveEx(descPerfect ~= "")
        end
    end

    -- 关1只显示 UiStage1，关2只显示 UiStage2，关3只显示 UiStage3（当前是第几关就只亮第几个）
    local stageIndexInChapter = data.StageIndexInChapter or 0
    local uiStages = { self.UiStage1, self.UiStage2, self.UiStage3 }
    for i = 1, 3 do
        if uiStages[i] then
            uiStages[i].gameObject:SetActiveEx(i == stageIndexInChapter)
        end
    end

    -- 更新羁绊列表
    self.DynamicTableNormal:SetDataSource(data.Bonds or {})
    self.DynamicTableNormal:ReloadDataSync(1)

    -- 更新开始按钮状态
    if data.IsPlaying then
        if self.BtnTongBlue then
            self.BtnTongBlue.gameObject:SetActiveEx(true)
        end
        if self.BtnTongBlue02 then
            self.BtnTongBlue02.gameObject:SetActiveEx(false)
        end
    else
        if self.BtnTongBlue then
            self.BtnTongBlue.gameObject:SetActiveEx(false)
        end
        if self.BtnTongBlue02 then
            self.BtnTongBlue02.gameObject:SetActiveEx(true)
        end
    end

    -- 更新空状态提示
    if self.TextEmpty then
        local bonds = data.Bonds or {}
        self.TextEmpty.gameObject:SetActiveEx(#bonds == 0)
    end
end

function XUiLuckyTenant2PopupStageDetail:OnBtnTanchuangCloseClick(eventData)
    if self._BondsDetail:IsNodeShow() then
        self._BondsDetail:Close()
        return
    end
    self:Close()
end

function XUiLuckyTenant2PopupStageDetail:OnBtnCloseDetailClick(eventData)
    self._BondsDetail:Close()
end

---开始游戏
function XUiLuckyTenant2PopupStageDetail:OnBtnTongBlue02Click(eventData)
    if not self._StageId then
        return
    end

    -- 请求服务器开始游戏
    XMVCA.XLuckyTenant2:RequestStart(self._StageId, function(playingStage)
        self:Close()
        -- 服务器返回成功后打开游戏界面
        -- playingStage 包含恢复游戏所需的 record 数据
        local seed = XTime.GetServerNowTimestamp()
        local isFirstTimeEntering = true
        XLuaUiManager.Open("UiLuckyTenant2Game", self._StageId, seed, isFirstTimeEntering, playingStage)
    end)
end

function XUiLuckyTenant2PopupStageDetail:OnDynamicTableEvent(event, index, grid)
    if event == DYNAMIC_DELEGATE_EVENT.DYNAMIC_GRID_ATINDEX then
        ---@type XUiLuckyTenant2PopupStageDetailGrid
        local data = self.DynamicTableNormal:GetData(index)
        grid:Update(data)
    elseif event == DYNAMIC_DELEGATE_EVENT.DYNAMIC_GRID_TOUCHED then
        local data = self.DynamicTableNormal:GetData(index)
        if data and data.BondId then
            self:OpenBondDetail(data.BondId)
        end
    end
end

---打开羁绊详情
---@param bondId number 羁绊ID
function XUiLuckyTenant2PopupStageDetail:OpenBondDetail(bondId)
    if not self._BondsDetail or not self._Control then
        return
    end

    -- 从Control获取羁绊详情数据
    local bondData = self._Control:GetBondDetailDataForStagePopup(bondId)
    if not bondData then
        return
    end

    -- 打开羁绊详情面板
    self._BondsDetail:Open()
    self._BondsDetail:Update(bondData)
end

return XUiLuckyTenant2PopupStageDetail
