--[[
-- XUiLuckyTenant2Settlement.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2025-12-31 16:39:51
--]]

---@class XUiLuckyTenant2Settlement : XLuaUi
---@field _Control XLuckyTenant2Control
local XUiLuckyTenant2Settlement = XLuaUiManager.Register(XLuaUi, "UiLuckyTenant2Settlement")

function XUiLuckyTenant2Settlement:OnAwake()
    self:InitComponents()
end

function XUiLuckyTenant2Settlement:InitComponents()
    -- Button
    self.BtnAgain:AddEventListener(function() self:OnBtnAgainClick() end)
    self.BtnQuit:AddEventListener(function() self:OnBtnQuitClick() end)
    self.BtnTanchuangCloseBig:AddEventListener(function() self:OnBtnTanchuangCloseBigClick() end)

    self.Perfect = self.Perfect or XUiHelper.TryGetComponent(self.Transform, "SafeAreaContentPane/Perfect", "RectTransform")
    self.Complete = self.Complete or XUiHelper.TryGetComponent(self.Transform, "SafeAreaContentPane/Complete", "RectTransform")
    self.Fail = self.Fail or XUiHelper.TryGetComponent(self.Transform, "SafeAreaContentPane/Fail", "RectTransform")
end

function XUiLuckyTenant2Settlement:OnStart(...)
    self:Update()
end

function XUiLuckyTenant2Settlement:OnEnable()
end

function XUiLuckyTenant2Settlement:OnDisable()
end

function XUiLuckyTenant2Settlement:OnDestroy()
end

function XUiLuckyTenant2Settlement:Update()
    if not self._Control then
        return
    end

    -- 更新结算数据
    self._Control:UpdateSettlement()
    local settlementData = self._Control:GetUiData().Settlement

    -- 显示分数
    if self.TxtScore then
        self.TxtScore.text = tostring(settlementData.Score or 0)
    end

    -- 显示回合数
    if self.TxtRound then
        self.TxtRound.text = tostring(settlementData.Round or 0)
    end

    -- 显示任务进度
    if self.TxtTask then
        self.TxtTask.text = tostring(settlementData.QuestCompletedAmount or 0) .. "/" .. tostring(settlementData.QuestTotalAmount or 0)
    end

    -- 显示标题和描述，以及对应的UI节点
    if settlementData.IsPerfectClear then
        -- 完美通关
        if self.TxtTitle then
            self.TxtTitle.text = XUiHelper.GetText("LuckyTenantPerfectClear")
        end
        if self.TxtDoc then
            self.TxtDoc.text = XUiHelper.GetText("LuckyTenantPerfectClearDesc")
        end
        -- 显示Perfect节点，隐藏其他节点
        if self.Perfect then
            self.Perfect.gameObject:SetActiveEx(true)
        end
        if self.Complete then
            self.Complete.gameObject:SetActiveEx(false)
        end
        if self.Fail then
            self.Fail.gameObject:SetActiveEx(false)
        end
    elseif settlementData.IsNormalClear then
        -- 普通通关
        if self.TxtTitle then
            self.TxtTitle.text = XUiHelper.GetText("LuckyTenantNormalClear")
        end
        if self.TxtDoc then
            self.TxtDoc.text = XUiHelper.GetText("LuckyTenantNormalClearDesc")
        end
        -- 显示Complete节点，隐藏其他节点
        if self.Perfect then
            self.Perfect.gameObject:SetActiveEx(false)
        end
        if self.Complete then
            self.Complete.gameObject:SetActiveEx(true)
        end
        if self.Fail then
            self.Fail.gameObject:SetActiveEx(false)
        end
    elseif settlementData.IsFail then
        -- 失败
        if self.TxtTitle then
            self.TxtTitle.text = XUiHelper.GetText("LuckyTenantFail")
        end
        if self.TxtDoc then
            self.TxtDoc.text = XUiHelper.GetText("LuckyTenantFailDesc")
        end
        -- 显示Fail节点，隐藏其他节点
        if self.Perfect then
            self.Perfect.gameObject:SetActiveEx(false)
        end
        if self.Complete then
            self.Complete.gameObject:SetActiveEx(false)
        end
        if self.Fail then
            self.Fail.gameObject:SetActiveEx(true)
        end
    else
        -- 默认显示普通通关
        if self.TxtTitle then
            self.TxtTitle.text = XUiHelper.GetText("LuckyTenantNormalClear")
        end
        if self.TxtDoc then
            self.TxtDoc.text = XUiHelper.GetText("LuckyTenantNormalClearDesc")
        end
        -- 显示Complete节点，隐藏其他节点
        if self.Perfect then
            self.Perfect.gameObject:SetActiveEx(false)
        end
        if self.Complete then
            self.Complete.gameObject:SetActiveEx(true)
        end
        if self.Fail then
            self.Fail.gameObject:SetActiveEx(false)
        end
    end

    -- 显示新记录标记
    if self.TagNew then
        self.TagNew.gameObject:SetActiveEx(settlementData.IsNewRecord == true)
    end

    -- 设置按钮状态
    if self.BtnAgain then
        self.BtnAgain:SetButtonState(CS.UiButtonState.Normal)
    end
    if self.BtnQuit then
        self.BtnQuit:SetButtonState(CS.UiButtonState.Normal)
    end
    if self.BtnTanchuangCloseBig then
        self.BtnTanchuangCloseBig:SetButtonState(CS.UiButtonState.Normal)
    end
end

function XUiLuckyTenant2Settlement:OnBtnAgainClick(eventData)
    -- 再次游戏：关闭结算界面和游戏界面，然后重新打开游戏界面
    local stageId = self._Control:GetStageIdForSettlement()
    if not stageId or stageId <= 0 then
        return
    end

    -- 请求服务器开始游戏
    XMVCA.XLuckyTenant2:RequestStart(stageId, function(playingStage)
        self:Remove()
        XLuaUiManager.Remove("UiLuckyTenant2Game")
        -- 服务器返回成功后打开游戏界面
        XScheduleManager.ScheduleNextFrame(function()
            -- playingStage 包含恢复游戏所需的 record 数据
            local seed = XTime.GetServerNowTimestamp()
            local isFirstTimeEntering = true
            XLuaUiManager.Open("UiLuckyTenant2Game", stageId, seed, isFirstTimeEntering, playingStage)
        end)
    end)
end

function XUiLuckyTenant2Settlement:OnBtnQuitClick(eventData)
    -- 退出：关闭结算界面和游戏界面，主界面在UI栈中会自动恢复显示并在OnEnable中刷新
    self:Close()
    XLuaUiManager.SafeClose("UiLuckyTenant2Game")
end

function XUiLuckyTenant2Settlement:OnBtnTanchuangCloseBigClick(eventData)
    -- 关闭按钮：与退出相同
    self:OnBtnQuitClick(eventData)
end

return XUiLuckyTenant2Settlement
