--[[
-- XUiLifeTreePopupTeach.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-02-25 11:16:04
--]]

---@class XUiLifeTreePopupTeach : XLuaUi
---@field _Control XLifeTreeControl
---@field TxtDesc UnityEngine.UI.Text
---@field Video XVideoPlayerUGUI
---@field TxtName UnityEngine.UI.Text
---@field BtnMask UnityEngine.UI.Image
---@field PanelDetail UiObject
---@field BtnClose XUiComponent.XUiButtonExt
---@field BtnCloseBg XUiComponent.XUiButton
---@field BtnGo XUiComponent.XUiButton
local XUiLifeTreePopupTeach = XLuaUiManager.Register(XLuaUi, "UiLifeTreePopupTeach")
function XUiLifeTreePopupTeach:OnAwake()
    self:InitComponents()
end

function XUiLifeTreePopupTeach:InitComponents()
    -- Button
    self.BtnClose:AddEventListener(function() self:OnBtnCloseClick() end)
    self.BtnCloseBg:AddEventListener(function() self:OnBtnCloseBgClick() end)
    self.BtnGo:AddEventListener(function() self:OnBtnGoClick() end)
end

function XUiLifeTreePopupTeach:OnStart(...)
    self:Refresh()
end

function XUiLifeTreePopupTeach:OnEnable()
end

function XUiLifeTreePopupTeach:OnDisable()
end

function XUiLifeTreePopupTeach:OnDestroy()
    self.Video:Stop()
end

function XUiLifeTreePopupTeach:Refresh()
    local clientConfig = self._Control:GetLifeTreeClientConfigConfigById("HelpCourseVideoConfigId")
    self.VideoId = clientConfig.Values[3]
    self.TxtName.text = XUiHelper.ConvertLineBreakSymbol(clientConfig.Values[1])
    self.TxtDesc.text = XUiHelper.ConvertLineBreakSymbol(clientConfig.Values[2])
    self.Video:SetInfoByVideoId(self.VideoId)
    self.Video:Play()
end

function XUiLifeTreePopupTeach:OnBtnCloseClick()
    self:Close()
end

function XUiLifeTreePopupTeach:OnBtnCloseBgClick()
    self:Close()
end

function XUiLifeTreePopupTeach:OnBtnGoClick()
    self.Video:Stop()
    XLuaVideoManager.PlayUiVideo(self.VideoId, function()
        self.Video:Play()
    end)
end

return XUiLifeTreePopupTeach
