--[[
-- XUiLineArithmetic3MainGridChapter.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-02-03 19:58:14
--]]

---@class XUiLineArithmetic3MainGridChapter : XUiNode
---@field _Control XLineArithmetic3Control
---@field TxtStar UnityEngine.UI.Text
---@field PanelLock UnityEngine.UI.RawImage
---@field Button XUiButton
---@field Text1 UnityEngine.UI.Text
---@field GridRoot UnityEngine.RectTransform
---@field FxUiLineArithmeticGridChapter UnityEngine.UI.Image
local XUiLineArithmetic3MainGridChapter = XClass(XUiNode, "XUiLineArithmetic3MainGridChapter")

function XUiLineArithmetic3MainGridChapter:OnStart()
    ---@type XLineArithmetic3ControlChapterData
    self._Data = false
    self:InitComponents()
end

function XUiLineArithmetic3MainGridChapter:InitComponents()
    -- 绑定按钮点击事件
    XUiHelper.RegisterClickEvent(self, self.Button, self.OnClick)
end

--- 更新章节数据
---@param data XLineArithmetic3ControlChapterData
function XUiLineArithmetic3MainGridChapter:Update(data)
    self._Data = data

    -- 设置星数和名称
    self.Button:SetNameByGroup(0, data.TxtStar)
    self.Button:SetNameByGroup(1, data.Name)

    -- 显示红点（新章节）
    self.Button:ShowReddot(data.IsNew)

    -- 设置按钮状态
    if data.IsOpen then
        self.Button:SetButtonState(CS.UiButtonState.Normal)
    else
        self.Button:SetButtonState(CS.UiButtonState.Disable)
    end

    -- 设置锁定文本
    local uiText = self.Text1
    if uiText and uiText.text then
        uiText.text = data.TxtLock
    end
end

--- 点击章节按钮
function XUiLineArithmetic3MainGridChapter:OnClick()
    self._Control:OnClickChapter(self._Data)
end

function XUiLineArithmetic3MainGridChapter:OnEnable()
end

function XUiLineArithmetic3MainGridChapter:OnDisable()
end

function XUiLineArithmetic3MainGridChapter:OnDestroy()
end

return XUiLineArithmetic3MainGridChapter
