--[[
-- XUiPBRShopNewPanelItem.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-01-12 15:30:37
--]]

local XUiPBRShopNewGridItem = require("XUi/XUiPBRGame/XUiPBRShopNew/GoodsPanel/XUiPBRShopNewGridItem")

---@class XUiPBRShopNewPanelItem : XUiNode
local XUiPBRShopNewPanelItem = XClass(XUiNode, "XUiPBRShopNewPanelItem")

--- 固定商品格子数：没有商品表现为空
local ConstSlotCount = 3

function XUiPBRShopNewPanelItem:OnStart(...)
    self:InitComponents()
end

function XUiPBRShopNewPanelItem:OnEnable()
end

function XUiPBRShopNewPanelItem:OnDisable()
end

function XUiPBRShopNewPanelItem:OnDestroy()
end

function XUiPBRShopNewPanelItem:InitComponents()
    ---@type XUiPBRShopNewGridItem[]
    self.GoodsPanelList = {}
    
    local prefabName = self.PanelItem.gameObject.name
    
    for i = 1, ConstSlotCount do
        local go = nil
        
        if i == 1 then
            self.PanelItem.gameObject:SetActiveEx(true)

            go = self.PanelItem
        else
            go = XUiHelper.Instantiate(self.PanelItem.gameObject, self.PanelItem.transform.parent)
        end
        
        -- 有序命名，用于引导聚焦
        go.gameObject.name = prefabName .. i
        
        local panel = XUiPBRShopNewGridItem.New(go, self, self.Parent)

        self.GoodsPanelList[i] = panel
    end
end

---@param itemIds number[]
function XUiPBRShopNewPanelItem:RefreshGoodsShow(itemIds)
    for i = 1, ConstSlotCount do
        local panel = self.GoodsPanelList[i]

        if panel then
            panel:Refresh(itemIds[i], true)
        end
    end
end


return XUiPBRShopNewPanelItem
