--[[
-- XUiLuckyTenant2PopupNormal.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2025-12-31 16:39:51
--]]

---@class XUiLuckyTenant2PopupNormal : XLuaUi
---@field _Control XLuckyTenant2Control
local XUiLuckyTenant2PopupNormal = XLuaUiManager.Register(XLuaUi, "UiLuckyTenant2PopupNormal")

function XUiLuckyTenant2PopupNormal:OnAwake()
    self:InitComponents()
end

function XUiLuckyTenant2PopupNormal:InitComponents()
    -- Button
    if self.BtnSave then
        self.BtnSave:AddEventListener(function() self:OnBtnSaveClick() end)
    end
    if self.BtnRestart then
        self.BtnRestart:AddEventListener(function() self:OnBtnRestartClick() end)
    end
    if self.BtnTanchuangCloseBig then
        self.BtnTanchuangCloseBig:AddEventListener(function() self:OnBtnTanchuangCloseBigClick() end)
    end
    if self.BtnOver then
        self.BtnOver:AddEventListener(function() self:OnBtnOverClick() end)
    end
end

function XUiLuckyTenant2PopupNormal:OnStart(...)
end

function XUiLuckyTenant2PopupNormal:OnEnable()
end

function XUiLuckyTenant2PopupNormal:OnDisable()
end

function XUiLuckyTenant2PopupNormal:OnDestroy()
end

-- 取消按钮 - 关闭弹窗
function XUiLuckyTenant2PopupNormal:OnBtnSaveClick(eventData)
    XLuaUiManager.Remove("UiLuckyTenant2Game")
    self:Close()
end

-- 重新开始按钮 - 重新开始当前关卡
function XUiLuckyTenant2PopupNormal:OnBtnRestartClick(eventData)
    -- 获取当前游戏对象
    local game = self._Control._Game
    if not game then
        XUiManager.TipText("LuckyTenant2NoPlayingStage")
        self:Close()
        return
    end
    
    local stageId = game:GetStageId()
    if not stageId or stageId <= 0 then
        XUiManager.TipText("LuckyTenant2NoPlayingStage")
        self:Close()
        return
    end

    -- 调用重开接口（会发送重开协议并收集结算数据）
    XMVCA.XLuckyTenant2:RequestRestart(game, function()
        -- 关闭当前弹窗和游戏界面
        self:Close()
        XLuaUiManager.Remove("UiLuckyTenant2Game")

        -- 请求服务器开始新游戏
        XMVCA.XLuckyTenant2:RequestStart(stageId, function(playingStage)
            -- 服务器返回成功后打开游戏界面
            -- playingStage 包含恢复游戏所需的 record 数据
            local seed = XTime.GetServerNowTimestamp()
            local isFirstTimeEntering = true
            XLuaUiManager.Open("UiLuckyTenant2Game", stageId, seed, isFirstTimeEntering, playingStage)
        end)
    end)
end

-- 关闭按钮 - 关闭弹窗
function XUiLuckyTenant2PopupNormal:OnBtnTanchuangCloseBigClick(eventData)
    self:Close()
end

-- 结束游戏按钮 - 退出到关卡选择界面
function XUiLuckyTenant2PopupNormal:OnBtnOverClick(eventData)
    local isNormalClear = self._Control:IsCurrentGameNormalClear() or false

    self._Control:RequestEndGame(function(success)
        if success and isNormalClear and self._Control:EnterNormalClearState() then
            self:Close()
            return
        end

        XLuaUiManager.Remove("UiLuckyTenant2Game")
        self:Close()
    end)
end

return XUiLuckyTenant2PopupNormal