--[[
-- XUiLifeTreeChapterUnlock.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-03-12 15:45:23
--]]

---@class XUiLifeTreeChapterUnlock : XLuaUi
---@field _Control XLifeTreeControl
---@field BtnClose XUiComponent.XUiButtonExt
---@field BtnGo XUiComponent.XUiButton
---@field RawImgIcon UnityEngine.UI.RawImage
---@field TxtTips UnityEngine.UI.Text
---@field TxtTitle UnityEngine.UI.Text
local XUiLifeTreeChapterUnlock = XLuaUiManager.Register(XLuaUi, "UiLifeTreeChapterUnlock")
function XUiLifeTreeChapterUnlock:OnAwake()
    self:InitComponents()
end

function XUiLifeTreeChapterUnlock:InitComponents()
    -- Button
    self.BtnClose:AddEventListener(function() self:OnBtnCloseClick() end)
    self.BtnGo:AddEventListener(function() self:OnBtnGoClick() end)

end

function XUiLifeTreeChapterUnlock:OnStart(chapterId, isInChapter)
    self.ChapterId = chapterId -- 章节Id
    self.IsInChapter = isInChapter -- 是否在章节里面
    self:Refresh()
end

function XUiLifeTreeChapterUnlock:OnEnable()
end

function XUiLifeTreeChapterUnlock:OnDisable()
end

function XUiLifeTreeChapterUnlock:OnDestroy()
end

function XUiLifeTreeChapterUnlock:Refresh()
    -- 贴图
    local chapterConfig = self._Control:GetLifeTreeChapterConfigById(self.ChapterId)
    self.RawImgIcon:SetRawImage(chapterConfig.Icon)
    -- 章节名称
    local exhibitionConfig = XMVCA.XMainLine2:GetConfigExhibitionChapter(self.ChapterId)
    self.TxtTitle.text = exhibitionConfig.TitleName
    -- 解锁提示
    self.TxtTips.text = chapterConfig.UnlockTips
    -- 在章节内的弹窗不需要显示跳转按钮
    self.BtnGo.gameObject:SetActiveEx(not self.IsInChapter)
    
    -- 记录弹窗
    XMVCA.XLifeTree:RequestLifeTreeFinishProcess(XMVCA.XLifeTree.EnumConst.PROCESS_TYPE.CHAPTER, self.ChapterId)
end

function XUiLifeTreeChapterUnlock:OnBtnCloseClick(eventData)
    self:Close()
end

function XUiLifeTreeChapterUnlock:OnBtnGoClick(eventData)
    XMVCA.XMainLine2:OpenExhibitionChapter(self.ChapterId)
    self:Close()
end

return XUiLifeTreeChapterUnlock
