--[[
-- XUiPBRCommonRolePanelExclusive.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-01-12 15:28:08
--]]

local XUiPBRCommonRoleGridExclusive = require("XUi/XUiPBRGame/CommonUiTemplate/CharacterStatusPanel/XUiPBRCommonRoleGridExclusive")

--- 通用的角色专属信息面板，其角色属性格子需是通用结构，自身需是非动态列表的滑动窗
---@class XUiPBRCommonRolePanelExclusive : XUiNode
---@field _Control XPBRGameControl
---@field ListExclusive UnityEngine.UI.ScrollRect
local XUiPBRCommonRolePanelExclusive = XClass(XUiNode, "XUiPBRCommonRolePanelExclusive")

function XUiPBRCommonRolePanelExclusive:OnStart(...)
    self:InitComponents()
end

function XUiPBRCommonRolePanelExclusive:OnEnable()
end

function XUiPBRCommonRolePanelExclusive:OnDisable()
end

function XUiPBRCommonRolePanelExclusive:OnDestroy()
end

function XUiPBRCommonRolePanelExclusive:InitComponents()
    self.GridExclusiveList = {}

    for i = 1, 10 do
        local go = self['GridExclusive' .. i]

        if go then
            local grid = XUiPBRCommonRoleGridExclusive.New(go, self)

            table.insert(self.GridExclusiveList, grid)
        else
            break
        end
    end
end

--- 获取角色专属描述信息通用数据结构，子类可重写以便调整数据来源
function XUiPBRCommonRolePanelExclusive:GetCharacterExclusiveDescInfo(customCharId)
    return self._Control.CharacterControl:GetCharacterExclusiveDescInfo(customCharId)
end

function XUiPBRCommonRolePanelExclusive:RefreshCharacterExclusiveDesc(customCharId, resetScroll)
    local infos = self:GetCharacterExclusiveDescInfo(customCharId)

    for i = 1, #self.GridExclusiveList do
        local info = infos[i]

        if info then
            self.GridExclusiveList[i]:Open()
            self.GridExclusiveList[i]:Refresh(info)
        else
            self.GridExclusiveList[i]:Close()
        end
    end

    if resetScroll then
        self.ListExclusive.verticalNormalizedPosition = 1
    end
end

return XUiPBRCommonRolePanelExclusive
