--[[
-- XUiPBRShopNewPanelRound.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-01-12 15:30:37
--]]

---@class XUiPBRShopNewPanelRound : XUiNode
---@field _Control XPBRGameControl
local XUiPBRShopNewPanelRound = XClass(XUiNode, "XUiPBRShopNewPanelRound")
local XUiPBRNormalWaveGrid = require('XUi/XUiPBRGame/XUiPBRShopNew/RoundPanel/XUiPBRNormalWaveGrid')
local XUiPBRBossWaveGrid = require('XUi/XUiPBRGame/XUiPBRShopNew/RoundPanel/XUiPBRBossWaveGrid')
local XUiPBRStageListScrollView = require('XUi/XUiPBRGame/XUiPBRChapter/XUiPBRStageListScrollView')

local GridType = {
    Normal = 1,
    Boss = 2,
}

function XUiPBRShopNewPanelRound:OnStart(stageId, curWave)
    self.StageId = stageId
    self.CurWave = curWave
    self:InitComponents()
end

function XUiPBRShopNewPanelRound:OnEnable()
end

function XUiPBRShopNewPanelRound:OnDisable()
end

function XUiPBRShopNewPanelRound:OnDestroy()
end


function XUiPBRShopNewPanelRound:InitComponents()
    self.GridNormal.gameObject:SetActiveEx(false)
    self.GridBoss.gameObject:SetActiveEx(false)
    
    -- 目前没有刷新需求，但还是按照可刷新来做
    ---@type XPool
    self._NormalWaveGridPool = XPool.New(function() 
        local go = XUiHelper.Instantiate(self.GridNormal, self.Content)
        
        local grid = XUiPBRNormalWaveGrid.New(go, self, GridType.Normal)
        
        return grid
    end, function(grid)
        grid:Close()
    end)

    ---@type XPool
    self._BossWaveGridPool = XPool.New(function()
        local go = XUiHelper.Instantiate(self.GridBoss, self.Content, GridType.Boss)

        local grid = XUiPBRBossWaveGrid.New(go, self)

        return grid
    end, function(grid)
        grid:Close()
    end)
    
    ---@type XUiPBRStageListScrollView
    self.ScrollViewMoveComponent = XUiPBRStageListScrollView.New(self.GameObject, self.Parent, self.ListRound)
    self.ScrollViewMoveComponent:Init()
end

function XUiPBRShopNewPanelRound:RecycleAllGrids()
    if not XTool.IsTableEmpty(self._WaveGridList) then
        for i = #self._WaveGridList, 1, -1 do
            ---@type XUiPBRBaseWaveGrid
            local grid = self._WaveGridList[i]
            
            self._WaveGridList[i] = nil

            if grid.GridType == GridType.Normal then
                self._NormalWaveGridPool:ReturnItemToPool(grid)
            elseif grid.GridType == GridType.Boss then
                self._BossWaveGridPool:ReturnItemToPool(grid)
            else
                XLog.Error('存在无类型的波次UI节点')
            end
        end
    end
end

function XUiPBRShopNewPanelRound:RefreshWavesShow()
    self:RecycleAllGrids()
    self.TxtWave.gameObject:SetActiveEx(false)

    if self._WaveGridList == nil then
        self._WaveGridList = {}
    end
    
    local stageCfg = self._Control:GetStageCfgById(self.StageId)

    if stageCfg and not XTool.IsTableEmpty(stageCfg.MonsterWaves) then
        if stageCfg.StageType == XMVCA.XPBRGame.EnumConst.StageCustomType.Challenge and stageCfg.FinishWaves < self.CurWave then
            -- 显示文本
            self.TxtWave.gameObject:SetActiveEx(true)
            self.TxtWave.text = XUiHelper.FormatTextEx(self._Control:GetClientPBRText('UIShopWavesProgress'), self.CurWave)
        else
            -- 配置表该字段是数组，按索引即可
            local count = math.min(#stageCfg.MonsterWaves, stageCfg.FinishWaves)

            for i = 1, count do
                local monsterWaveId = stageCfg.MonsterWaves[i]
                local waveCfg = self._Control.InGameControl:GetTablePBRMonsterWaveCfgById(monsterWaveId)

                if waveCfg then
                    ---@type XUiPBRBaseWaveGrid
                    local grid = nil

                    if waveCfg.IconType == XMVCA.XPBRGame.EnumConst.WaveShowType.Boss then
                        grid = self._BossWaveGridPool:GetItemFromPool()
                        grid:Open()
                        grid:RefreshShow(monsterWaveId, i, self.CurWave)
                    else
                        grid = self._NormalWaveGridPool:GetItemFromPool()
                        grid:Open()
                        grid:RefreshShow(monsterWaveId, i, self.CurWave)
                    end

                    if grid then
                        table.insert(self._WaveGridList, grid)
                    end
                end
            end

            CS.UnityEngine.UI.LayoutRebuilder.ForceRebuildLayoutImmediate(self.ListRound.content)
            self:FocusCurWaveUI(self.CurWave, false)
        end
    end
end

--region 窗口滑动聚焦

---@param onlyViewFull @只要完全显示出来就可以了不需要聚焦到屏幕中心
function XUiPBRShopNewPanelRound:FocusCurWaveUI(index, onlyViewFull, cb)
    local grid = self._WaveGridList[index]

    if grid then
        local tarPosX = nil

        if onlyViewFull then
            local halfGridWidth = grid.Transform.sizeDelta.x
            local boundsOffset = self._Control:GetClientPBRNumber('UiStageBoundsLeftOffset')
            -- 找出一个关卡UI完全显示出来的范围
            local leftPos = - self.ScrollViewMoveComponent.HalfViewPortWidth - grid.Transform.localPosition.x + boundsOffset + halfGridWidth
            local rightPos = self.ScrollViewMoveComponent.HalfViewPortWidth - grid.Transform.localPosition.x - boundsOffset - halfGridWidth

            -- 限制坐标在它们之间
            tarPosX = XMath.Clamp(self.ListRound.content.localPosition.x, leftPos, rightPos)
        else
            -- 聚焦到中间
            -- Conetnt锚点在最左侧， 希望聚焦关卡UI在屏幕中心（不强制）
            local contentToCenter = 0

            tarPosX = contentToCenter - grid.Transform.localPosition.x
        end

        -- 越界检查，Content锚点在左侧时，即坐标为0时为起始，不可大于0，也不可小于自身长度的负数 - 屏幕宽度
        tarPosX = XMath.Clamp(tarPosX, - self.ListRound.content.transform.sizeDelta.x + self.ScrollViewMoveComponent.HalfViewPortWidth , - self.ScrollViewMoveComponent.HalfViewPortWidth)

        self.ScrollViewMoveComponent:PlayScrollViewMove(tarPosX, nil, true, cb)
    end
end

--endregion

return XUiPBRShopNewPanelRound
