--[[
-- XUiActivityBossSingleSettlementGridCharacter.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-05-21 18:26:58
--]]

---@class XUiActivityBossSingleSettlementGridCharacter : XUiNode
---@field RImgHead UnityEngine.UI.RawImage
local XUiActivityBossSingleSettlementGridCharacter = XClass(XUiNode, "XUiActivityBossSingleSettlementGridCharacter")
function XUiActivityBossSingleSettlementGridCharacter:InitComponents()
end

function XUiActivityBossSingleSettlementGridCharacter:OnStart(...)
    self:InitComponents()
    self:Refresh()
end

function XUiActivityBossSingleSettlementGridCharacter:OnEnable()
end

function XUiActivityBossSingleSettlementGridCharacter:OnDisable()
end

function XUiActivityBossSingleSettlementGridCharacter:OnDestroy()
end

function XUiActivityBossSingleSettlementGridCharacter:Refresh()
    self.RImgHead:SetImage("")
end

return XUiActivityBossSingleSettlementGridCharacter
