--[[
-- XUiPBRCharacterDetailGridCharacter.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-01-12 15:28:08
--]]

---@class XUiPBRCharacterDetailGridCharacter : XUiNode
---@field _Control XPBRGameControl
local XUiPBRCharacterDetailGridCharacter = XClass(XUiNode, "XUiPBRCharacterDetailGridCharacter")

function XUiPBRCharacterDetailGridCharacter:OnStart(...)
    self:InitComponents()
end

function XUiPBRCharacterDetailGridCharacter:OnEnable()
end

function XUiPBRCharacterDetailGridCharacter:OnDisable()
end

function XUiPBRCharacterDetailGridCharacter:OnDestroy()
end

function XUiPBRCharacterDetailGridCharacter:InitComponents()
    self:SetRecommendShow(false)
end

---@param cfg XTablePBRCharacter
function XUiPBRCharacterDetailGridCharacter:Refresh(cfg)
    self.CustomCharId = cfg.CharacterId
    
    self.GridBtn:SetRawImage(cfg.CharacterIcon)
    self.GridBtn:SetNameByGroup(0, cfg.CharacterName)
    self.PanelLock.gameObject:SetActiveEx(not self._Control.CharacterControl:GetIsCharacterUnlock(cfg.CharacterId))
end

function XUiPBRCharacterDetailGridCharacter:SetRecommendShow(isShow)
    if self.PanelRecommend then
        self.PanelRecommend.gameObject:SetActiveEx(isShow)
    end
end

return XUiPBRCharacterDetailGridCharacter
