--[[
-- XUiPBRCharacterDetailPanelPick.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-01-12 15:28:08
--]]

local XUiPBRCharacterDetailGridCharacter = require("XUi/XUiPBRGame/XUiPBRCharacterDetail/XUiPBRCharacterDetailGridCharacter")

---@class XUiPBRCharacterDetailPanelPick : XUiNode
---@field _Control XPBRGameControl
---@field GridBtnGroup XUiButtonGroup
local XUiPBRCharacterDetailPanelPick = XClass(XUiNode, "XUiPBRCharacterDetailPanelPick")

function XUiPBRCharacterDetailPanelPick:OnStart(selectCharCb)
    self._SelectCharCb = selectCharCb

    self:InitComponents()
end

function XUiPBRCharacterDetailPanelPick:OnEnable()
end

function XUiPBRCharacterDetailPanelPick:OnDisable()
end

function XUiPBRCharacterDetailPanelPick:OnDestroy()
    
end

function XUiPBRCharacterDetailPanelPick:InitComponents()
    local characterCfgs = self._Control.CharacterControl:GetCharacterCfgs()

    ---@type XUiPBRCharacterDetailGridCharacter[]
    self.CharacterGrids = {}
    self.CharacterCfgList = characterCfgs

    local buttonList = {}

    XUiHelper.RefreshCustomizedList(self.ListCharacter, self.GridCharacter, characterCfgs and #characterCfgs or 0, function(index, go)
        local grid = XUiPBRCharacterDetailGridCharacter.New(go, self)
        grid:Open()
        grid:Refresh(characterCfgs[index])

        table.insert(self.CharacterGrids, grid)

        local xuiButton = grid.GameObject:GetComponent(typeof(CS.XUiComponent.XUiButton))

        if xuiButton then
            table.insert(buttonList, xuiButton)
        end
    end)

    self.GridBtnGroup:Init(buttonList, handler(self, self.OnBtnGroupSelect), 1)
end

function XUiPBRCharacterDetailPanelPick:OnBtnGroupSelect(index, force)
    if self._CurSelectIndex == index and not force then
        return
    end
    
    self._CurSelectIndex = index
    
    local cfg = self.CharacterCfgList[index]

    if self._SelectCharCb then
        self._SelectCharCb(cfg)
    end
end

function XUiPBRCharacterDetailPanelPick:ShowAndSelectRecommendChar(customCharId)
    if XTool.IsTableEmpty(self.CharacterGrids) then
        return
    end

    -- 设置推荐标签显示
    for i, v in pairs(self.CharacterGrids) do
        v:SetRecommendShow(v.CustomCharId == customCharId)
    end
    
    -- 选中推荐角色
    self:SelectByCustomCharId(customCharId)
end

function XUiPBRCharacterDetailPanelPick:SelectByCustomCharId(customCharId)
    local index = nil

    if not XTool.IsTableEmpty(self.CharacterCfgList) then
        for i, v in pairs(self.CharacterCfgList) do
            if v.CharacterId == customCharId then
                index = i
                break
            end
        end
    end

    if XTool.IsNumberValidEx(index) then
        self.GridBtnGroup:SelectIndex(index, true)
    end
end

function XUiPBRCharacterDetailPanelPick:SelectByIndex(index)
    if XTool.IsNumberValidEx(index) then
        self.GridBtnGroup:SelectIndex(index, true)
    end
end

return XUiPBRCharacterDetailPanelPick
