--[[
-- XUiPBRCharacterDetailPanelExclusive.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-01-12 15:28:08
--]]

local XUiPBRCommonRolePanelExclusive = require("XUi/XUiPBRGame/CommonUiTemplate/CharacterStatusPanel/XUiPBRCommonRolePanelExclusive")

---@class XUiPBRCharacterDetailPanelExclusive : XUiPBRCommonRolePanelExclusive
---@field _Control XPBRGameControl
---@field ListExclusive UnityEngine.UI.ScrollRect
local XUiPBRCharacterDetailPanelExclusive = XClass(XUiPBRCommonRolePanelExclusive, "XUiPBRCharacterDetailPanelExclusive")

return XUiPBRCharacterDetailPanelExclusive
