--[[
-- XUiFashionSuitPopupNew.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-02-03 16:59:31
--]]

--[[
-- XUiFashionSuitPopupNew.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-02-03 16:59:31
--]]


---@field _Control XFashionSuitControl
local XUiFashionSuitPopupNewPanelInfo = require(
"XUi/XUiFashionSuit/XUiFashionSuitPopupNew/XUiFashionSuitPopupNewPanelInfo")
---@class XUiFashionSuitPopupNew : XLuaUi
local XUiFashionSuitPopupNew = XLuaUiManager.Register(XLuaUi, "UiFashionSuitPopupNew")
---@field BtnClose XUiButton
---@field BtnPic XUiButton
---@field BtnNext XUiButton
---@field BtnLast XUiButton
---@field PanelDot UnityEngine.RectTransform
---@field ImgDotNormal UnityEngine.RectTransform
---@field BtnDot XUiButton
---@field PanelInfo UiObject

function XUiFashionSuitPopupNew:OnAwake()
    self:InitComponents()
end

function XUiFashionSuitPopupNew:InitComponents()
    -- Button
    self.BtnClose:AddEventListener(function() self:Close() end)
    self.BtnPic:AddEventListener(function() self:OnBtnPicClick() end)
    self.BtnNext:AddEventListener(function() self:OnBtnNextClick() end)
    self.BtnLast:AddEventListener(function() self:OnBtnLastClick() end)
    self.PanelInfo = XUiFashionSuitPopupNewPanelInfo.New(self.PanelInfo, self)
end

function XUiFashionSuitPopupNew:OnStart(noticeIds)
    self._CurIndex = 1
    self._ShowFashionIds = self._Control:GetShowFashionSuitNotice(noticeIds)
    self.BtnNext.gameObject:SetActiveEx(self._ShowFashionIds and #self._ShowFashionIds > 1)
    self.BtnLast.gameObject:SetActiveEx(self._ShowFashionIds and #self._ShowFashionIds > 1)
    self._ShowFashionId = self._ShowFashionIds[self._CurIndex]
    self._BtnDots = {}
    for i = 1, #self._ShowFashionIds do
        local dot = XUiHelper.Instantiate(self.BtnDot, self.BtnDot.transform.parent)
        table.insert(self._BtnDots, dot)
        dot:AddEventListener(function() self:OnBtnDotClick(i) end)
    end
    self.BtnDot.gameObject:SetActiveEx(false)
    self:Refresh()
end

function XUiFashionSuitPopupNew:OnEnable()
end

function XUiFashionSuitPopupNew:OnDisable()
end

function XUiFashionSuitPopupNew:OnDestroy()
end

function XUiFashionSuitPopupNew:Refresh(lastIndex)
    local cfg = XFashionConfigs.GetFashionTemplate(self._ShowFashionId)
    self.BtnPic:SetRawImage(cfg.FashionSuitResourcePicPath)
    self._BtnDots[self._CurIndex]:SetButtonState(CS.UiButtonState.Select)
    if XTool.IsNumberValid(lastIndex) and lastIndex > -1 then
        self._BtnDots[lastIndex]:SetButtonState(CS.UiButtonState.Normal)
    end
    self.PanelInfo:Refresh(self._ShowFashionId)
    local noticeId = self._Control:GetNoticeIdByFashionId(self._ShowFashionId)
    if XTool.IsNumberValid(noticeId) then
        self._Control:MarkNoticeFashionSuitIdIsRead(noticeId) -- 设置已读
    end
end

function XUiFashionSuitPopupNew:OnBtnPicClick(eventData)
    XMVCA.XShop:OpenFashionDetailUi(self._ShowFashionId, nil)
end

function XUiFashionSuitPopupNew:OnBtnNextClick(eventData)
    local lastIndex = self._CurIndex
    self._CurIndex = self._CurIndex + 1
    if self._CurIndex > #self._ShowFashionIds then
        self._CurIndex = 1
    end
    self._ShowFashionId = self._ShowFashionIds[self._CurIndex]
    self:Refresh(lastIndex)
end

function XUiFashionSuitPopupNew:OnBtnLastClick(eventData)
    local lastIndex = self._CurIndex
    self._CurIndex = self._CurIndex - 1
    if self._CurIndex < 1 then
        self._CurIndex = #self._ShowFashionIds
    end
    self._ShowFashionId = self._ShowFashionIds[self._CurIndex]
    self:Refresh(lastIndex)
end

function XUiFashionSuitPopupNew:OnBtnDotClick(index)
    local lastIndex = self._CurIndex
    self._CurIndex = index
    self._ShowFashionId = self._ShowFashionIds[self._CurIndex]
    self:Refresh(lastIndex)
end

return XUiFashionSuitPopupNew
