--[[
-- XUiLuckyTenant2PopupSuccess.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2025-12-31 16:39:51
--]]

local XUiLuckyTenant2ChessProp = require("XUi/XUiLuckyTenant2/XUiLuckyTenant2Chess/XUiLuckyTenant2ChessProp")

---@class XUiLuckyTenant2PopupSuccess : XLuaUi
---@field _Control XLuckyTenant2Control
local XUiLuckyTenant2PopupSuccess = XLuaUiManager.Register(XLuaUi, "UiLuckyTenant2PopupSuccess")

function XUiLuckyTenant2PopupSuccess:OnAwake()
    self:InitComponents()
end

function XUiLuckyTenant2PopupSuccess:InitComponents()
    -- Button
    self.BtnTanchuangCloseBig:AddEventListener(function() self:OnBtnTanchuangCloseBigClick() end)

    -- 奖励道具列表（与 XUiLuckyTenant2Chess 道具刷新逻辑一致：Prop1 为模板用于克隆）
    self._PropGrids = {}
    if self.Prop1 then
        self.Prop1.gameObject:SetActiveEx(false)
    end

    self.PanelReward = self.PanelReward or XUiHelper.TryGetComponent(self.Transform, "SafeAreaContentPane/PanelDetail/PanelReward", "RectTransform")
    self.RewardList = self.RewardList or XUiHelper.TryGetComponent(self.Transform, "SafeAreaContentPane/PanelDetail/PanelReward/RewardList", "RectTransform")
end

function XUiLuckyTenant2PopupSuccess:OnStart(questData)
    self._QuestData = questData
    self:Update()
end

function XUiLuckyTenant2PopupSuccess:OnEnable()
end

function XUiLuckyTenant2PopupSuccess:OnDisable()
end

function XUiLuckyTenant2PopupSuccess:OnDestroy()
end

function XUiLuckyTenant2PopupSuccess:Update()
    if not self._QuestData then
        return
    end

    local questData = self._QuestData
    local currentScore = questData.CurrentScore or 0
    local targetScore = questData.TargetScore or 0

    -- 更新目标文本
    self.TxtTarget.text = string.format("%d/%d", currentScore, targetScore)

    -- 更新进度条
    if targetScore > 0 then
        self.ImgBar.fillAmount = math.min(1, currentScore / targetScore)
    else
        self.ImgBar.fillAmount = 0
    end

    -- 已完成quest数量/quest数量
    local questCompletedAmount = self._Control:GetQuestCompletedAmount()
    local questTotalAmount = self._Control:GetQuestTotalAmount()
    self.TxtTotalProgress.text = XUiHelper.GetText("LuckyTenant2PopupSuccessRound", questCompletedAmount, questTotalAmount)

    -- 更新奖励道具列表（数据来自 PrepareQuestSuccessData，即 LuckyTenant2StageTask 的 RewardPieces / RewardPiecesAmount）
    local rewards = questData.Rewards or {}
    if self.Prop1 and self._PropGrids then
        XTool.UpdateDynamicItem(self._PropGrids, rewards, self.Prop1, XUiLuckyTenant2ChessProp, self)
    end
    -- 无奖励时隐藏奖励区域
    if self.PanelReward then
        self.PanelReward.gameObject:SetActiveEx(#rewards > 0)
    end
end

function XUiLuckyTenant2PopupSuccess:OnBtnTanchuangCloseBigClick(eventData)
    -- 关闭弹窗并发送事件
    self:Close()
    -- 发送弹窗关闭事件，让Control处理后续逻辑
    XEventManager.DispatchEvent(XEventId.EVENT_LUCKY_TENANT2_QUEST_SUCCESS_POPUP_CLOSE)
end

return XUiLuckyTenant2PopupSuccess
