--[[
-- XUiFashionSuitLobbyGridTab.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-02-02 18:06:45
--]]

--[=====[AUTO GENERATED START: HEADER]=====]
--[[
-- XUiFashionSuitLobbyGridTab.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-02-02 18:06:45
--]]
--[=====[AUTO GENERATED END: HEADER]=====]

--[=====[AUTO GENERATED START: CLASS]=====]
---@class XUiFashionSuitLobbyGridTab : XUiNode
---@field BtnTab XUiButton
---@field TagNew UnityEngine.RectTransform
---@field TagAllGet UnityEngine.RectTransform
local XUiFashionSuitLobbyGridTab = XClass(XUiNode, "XUiFashionSuitLobbyGridTab")

--[=====[AUTO GENERATED END: CLASS]=====]

--[=====[AUTO GENERATED START: LIFECYCLE]=====]
function XUiFashionSuitLobbyGridTab:OnAwake()
end

function XUiFashionSuitLobbyGridTab:InitComponents()
    -- Button
    -- self.BtnTab:AddEventListener(function() self:OnBtnTabClick() end)
end

function XUiFashionSuitLobbyGridTab:OnStart(...)
    self:InitComponents()
end

function XUiFashionSuitLobbyGridTab:OnEnable()
    self:UpdateProgress()
end

function XUiFashionSuitLobbyGridTab:OnDisable()
end

function XUiFashionSuitLobbyGridTab:OnDestroy()
end

--[=====[AUTO GENERATED END: LIFECYCLE]=====]

--[=====[AUTO GENERATED START: INIT_COMPONENTS]=====]
function XUiFashionSuitLobbyGridTab:Update(cfg)
    self._Cfg = cfg
    self.Type = cfg.Type
    self.IsLock = cfg.Type == self._Control.FashionSuitType.Lock
    self.BtnTab:SetDisable(self.IsLock)
    if not self.IsLock then
        self.BtnTab:SetNameByGroup(0, cfg.Name)
        self.BtnTab:SetRawImage(cfg.SuitLogo)
    end

  
    self:UpdateProgress()
end

--[=====[AUTO GENERATED END: INIT_COMPONENTS]=====]

function XUiFashionSuitLobbyGridTab:UpdateProgress()
    if not self._Cfg then
        return
    end
    if self.IsLock then
        return
    end
    local own = self._Control:GetCollectCount(self._Cfg.Id)
    self._IsAllFashionGain = #self._Cfg.FashionIds == own
    local text = own .. "/" .. #self._Cfg.FashionIds
    if not self._Cfg.IsComplete then
        text = own
    end
    self.BtnTab:SetNameByGroup(1, XUiHelper.GetText("FashionSuitProgress1", text))
    for _, fashionId in pairs(self._Cfg.FashionIds) do
        if not self._Control:IsFashionViewed(fashionId) then
            self.TagNew.gameObject:SetActiveEx(true)
            break
        end
    end
    self.TagAllGet.gameObject:SetActiveEx(self._IsAllFashionGain)
    local isRewardGain = self._Control:IsSuitRewardGain(self._Cfg.Id)
    self.BtnTab:ShowReddot( not isRewardGain)
end

function XUiFashionSuitLobbyGridTab:OnBtnTabClick()
    if self.Type == self._Control.FashionSuitType.Lock then
        XUiManager.TipMsg(XUiHelper.GetText("FashionSuitProgress2"))
        return
    end
    self.Parent:OnGridTabClick(self._Cfg)
end

return XUiFashionSuitLobbyGridTab
