--[[
-- XUiFashionSuitLobbyPanelRight.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-02-03 10:29:12
--]]

--[[
-- XUiFashionSuitLobbyPanelRight.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-02-03 10:29:12
--]]
local XUiGridCommon = require("XUi/XUiObtain/XUiGridCommon")
---@class XUiFashionSuitLobbyPanelRight : XUiNode
local XUiFashionSuitLobbyPanelRight = XClass(XUiNode, "XUiFashionSuitLobbyPanelRight")
---@field Grid256New XUiFashionSuitLobbyGrid256New
---@field BtnClick XUiButton

function XUiFashionSuitLobbyPanelRight:OnAwake()
end

function XUiFashionSuitLobbyPanelRight:InitComponents()
    -- Button
    self.BtnClick:AddEventListener(function() self:OnBtnClickClick() end)
end

function XUiFashionSuitLobbyPanelRight:OnStart(...)
    self:InitComponents()
end

function XUiFashionSuitLobbyPanelRight:OnEnable()
    self:UpdateReddot()
    self:UpdateReward()
end

function XUiFashionSuitLobbyPanelRight:OnDisable()
end

function XUiFashionSuitLobbyPanelRight:OnDestroy()
end

function XUiFashionSuitLobbyPanelRight:Refresh(cfg)
    self._Cfg = cfg
    self:UpdateReddot()
    self:UpdateReward()
    self.Grid256New.gameObject:SetActiveEx(false)
    

    self.BtnClick:SetNameByGroup(0, cfg.Name)
    local txtDesc = ""
    if not cfg.IsComplete then
        txtDesc = XUiHelper.GetText("FashionSuitProgress3")
    end
    self.BtnClick:SetNameByGroup(1, txtDesc)
    self.BtnClick:SetRawImage(cfg.SuitBackground)
end

function XUiFashionSuitLobbyPanelRight:SetUiSprite(imgQuality, spriteName)
    imgQuality:SetSprite(spriteName)
end

function XUiFashionSuitLobbyPanelRight:OnBtnClickClick(eventData)
    XLuaUiManager.Open("UiFashionSuitMain", self._Cfg.Id)
end

function XUiFashionSuitLobbyPanelRight:UpdateReddot()
    if not self._Cfg then
        return
    end
    local isRed = false
    for _, fashionId in pairs(self._Cfg.FashionIds) do
        if not XMVCA.XFashionSuit:IsFashionViewed(fashionId) then
            isRed = true
            break
        end
    end
    self.BtnClick:ShowReddot(isRed)
end

function XUiFashionSuitLobbyPanelRight:UpdateReward()
    if not self._Cfg then
        return
    end
self.RewardPanelList = self.RewardPanelList or {}
    for i = 1, #self.RewardPanelList do
        self.RewardPanelList[i].GameObject:SetActiveEx(false)
    end
    local temp = {
        ShowReceived = self._Control:IsSuitRewardGain(self._Cfg.Id)
    }
    local rewardsList = XRewardManager.GetRewardList(self._Cfg.RewardId)
    for i = 1, #rewardsList do
        if not self.RewardPanelList[i] then
            local grid = XUiHelper.Instantiate(self.Grid256New, self.Grid256New.transform.parent)
            local item = XUiGridCommon.New(self, grid)
            table.insert(self.RewardPanelList, item)
        end
        local gridUi = self.RewardPanelList[i]
        gridUi.GameObject:SetActiveEx(true)
        gridUi:Refresh(rewardsList[i],temp)
    end
end
return XUiFashionSuitLobbyPanelRight
