---
--- 空花2.0生态构造体系统管控的AI基础脚本
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ljb.
--- DateTime: 2026/3/10 20:47
---

local EEcologyEvent = {
    SetStateId = 1001,
    LogBoard = 1002,
    LogPath = 1003,
}

local Base = require("Common/XBigWorldCharBase")
local XStateMachineController = require("Common/StateMachine/XStateMachineController")
local XEcologyState2FindPathTransition = require("Character/BigWorld/XEcologyConstructAI/XEcologyState2FindPathTransition")
local XFindPath2EcologyStateTransition = require("Character/BigWorld/XEcologyConstructAI/XFindPath2EcologyStateTransition")

---生态AI基类
---@class XEcologyConstructAIBase : XBigWorldCharBase
---@field _uuid number npcUUID
---@field _isInit boolean 已初始化
---@field _stateMachine XStateMachineController 状态机
---@field _proxy XDlcCSharpFuncs
---@field FindPathStateEnum number 寻路状态枚举
local XEcologyConstructAIBase = XClass(Base, "XEcologyConstructAIBase")

---@param proxy XDlcCSharpFuncs
function XEcologyConstructAIBase:Ctor(proxy)
    self._proxy = proxy
end

---@param dt number @ delta time
function XEcologyConstructAIBase:Update(dt)
    -- 隐藏则不做逻辑更新
    if not self._proxy:GetNpcActive(self._uuid) then
        return
    end
    if not self._isInit then
        self:TryInitAIEnterState()
    end
    self._stateMachine:Update(dt)
end

---@param eventType number
---@param eventArgs userdata
function XEcologyConstructAIBase:HandleEvent(eventType, eventArgs)
    self._stateMachine:HandleEvent(eventType, eventArgs)
end

function XEcologyConstructAIBase:HandleLuaEvent(eventType, eventArgs)
    if eventArgs.ScriptId ~= self._proxy.Id then
        return
    end

    if eventType == EEcologyEvent.SetStateId then
        XScriptTool.EcologyError(self, "生态AI Debug状态切换 StateId = "..eventArgs.StateId)
        self._stateMachine:SwitchState(eventArgs.StateId)
    elseif eventType == EEcologyEvent.LogBoard then
        XScriptTool.EcologyError(self, "生态AI 打印黑板值: ", self._stateMachine._dataBoard)
    elseif eventType == EEcologyEvent.LogPath then
        if self._stateMachine.CurStateEnum == self.FindPathStateEnum then
            ---@type XEcologyFindCombinePathState
            local pathState = self._stateMachine:GetState(self._stateMachine.CurStateEnum)
            if pathState then
                pathState:OnLogPath()
            end
        else
            XScriptTool.EcologyError(self, "生态AI 打印路线失败: 当前不是寻路状态")
        end
    end
end

function XEcologyConstructAIBase:Terminate()
    self:TerminateStateMachine()
end

--region 状态转移方程
---注册跳转到寻路状态的状态转移方程
---@param startState number 从什么状态进入寻路状态
---@param getTargetStateFunc number 获取寻路的目标状态方法
---@param stayTime number 呆多久后进入寻路状态
---@param stopTimerTriggerId number 停止计时的触发器Id
---@param checkDistance number 寻路状态目标点检查精度, 不配默认为0.1
function XEcologyConstructAIBase:RegisterInFindPathStateTransition(startState, getTargetStateFunc, stayTime, stopTimerTriggerId, additionCheckFunc, checkDistance)
    self._stateMachine:AddStateTransition(startState, self.FindPathStateEnum, 
            XEcologyState2FindPathTransition.New(self._proxy), stayTime, stopTimerTriggerId, additionCheckFunc, startState, getTargetStateFunc, checkDistance)
end

---注册寻路状态跳出去的状态转移方程
---@param targetState number
---@param checkDistance number 检查精度, 不配默认为0.1
function XEcologyConstructAIBase:RegisterOutFindPathStateTransition(targetState, checkDistance)
    self._stateMachine:AddStateTransition(self.FindPathStateEnum, targetState,
            XFindPath2EcologyStateTransition.New(self._proxy), self._proxy:GetEcologyConstructStateInitPos(self._uuid, targetState), checkDistance)
end
--endregion

--region 基础生命周期函数
---@private
function XEcologyConstructAIBase:CommonInit()
    self._isInit = false
    self._uuid = self._proxy:GetSelfNpcId()
    self:InitStateMachine()
    for _, eventId in pairs(EEcologyEvent) do
        self._proxy:RegisterLuaEvent(eventId)
    end
end
--endregion

--region 状态机
---@private
function XEcologyConstructAIBase:InitStateMachine()
    -- 初始化状态机
    self._stateMachine = XStateMachineController.New(self._proxy)
    self._stateMachine:Init()

    self:RegisterMachineState()
    self:RegisterMachineStateTransition()
end

--- 注册状态机状态
function XEcologyConstructAIBase:RegisterMachineState()
end

--- 注册状态转移方程
function XEcologyConstructAIBase:RegisterMachineStateTransition()
end

---@private
---初始化AI的状态
function XEcologyConstructAIBase:TryInitAIEnterState()
    -- 读取当前生态状态
    -- 默认存在状态, 在组件postInit周期已经默认初始状态为stateId = 1
    -- 因此直接读取即可
    local haveSave, curStateEnum = self._proxy:TryGetBBInt(XVarDomain.Npc, self._uuid, EEcologySaveKey.CurStateEnum)
    self._stateMachine:SwitchState(curStateEnum)
    self._isInit = true
end

---@private
function XEcologyConstructAIBase:TerminateStateMachine()
    self._stateMachine:Terminate()
    self._stateMachine = nil
end
--endregion

return XEcologyConstructAIBase
