---
--- 空花2.0 状态转移方程：寻路状态->生态状态
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ljb.
--- DateTime: 2026/3/10 20:47
---

local XLevelNpcStateTransition = require("Common/StateMachine/Transition/XLevelNpcStateTransition")

---v空花2期 寻路到其他状态-状态转移方程
---@class XFindPath2EcologyStateTransition: XLevelNpcStateTransition 寻路到其他状态
---@field _fromState XEcologyFindCombinePathState
---@field _toState XEcologyFindCombinePathState
---@field _targetPos Vector3 目标点
---@field _checkDistance number 到达距离判断
---@field _placeId number
---@field _uuid number
local XFindPath2EcologyStateTransition = XClass(XLevelNpcStateTransition, "XFindPath2EcologyStateTransition")

---@overload
function XFindPath2EcologyStateTransition:InitOther(targetPos, checkDistance)
    self._targetPos = targetPos
    if checkDistance ~= nil and checkDistance > 0 then
        self._checkDistance = checkDistance
    else
        self._checkDistance = 0.1
    end
end

---@overload
---@return boolean
function XFindPath2EcologyStateTransition:Condition(dt)
    if not self._proxy:GetNpcActive(self._uuid)
            or self._proxy:CheckNpcIsInInteract(self._placeId)
            or (self._fromState.TargetState ~= self._toState.StateConfig.StateEnum)
    then
        return false
    end
    if self._proxy:CheckNpcDistanceWithPos(self._uuid, self._targetPos.x, self._targetPos.y, self._targetPos.z, self._checkDistance) then
        return true
    end
    return false
end

return XFindPath2EcologyStateTransition