--[[
-- XUiLifeTreeUnlockType.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-02-25 11:16:04
--]]

local CSInstantiate = CS.UnityEngine.Object.Instantiate
local XUiLifeTreeUnlockTypeGridUnlockCondition = require("XUi/XUiLifeTree/XUiLifeTreeUnlockType/XUiLifeTreeUnlockTypeGridUnlockCondition")

---@class XUiLifeTreeUnlockType : XLuaUi
---@field _Control XLifeTreeControl
---@field BtnClose XUiComponent.XUiButton
---@field BtnBg UnityEngine.UI.Button
---@field PanelUnlockConditions UnityEngine.RectTransform
---@field GridUnlockCondition UnityEngine.RectTransform
---@field GridConditionDic table<number, XUiLifeTreeUnlockTypeGridUnlockCondition>
local XUiLifeTreeUnlockType = XLuaUiManager.Register(XLuaUi, "UiLifeTreeUnlockType")
function XUiLifeTreeUnlockType:OnAwake()
    self:InitComponents()
end

function XUiLifeTreeUnlockType:InitComponents()
    -- Button
    self.BtnClose:AddEventListener(function() self:OnBtnCloseClick() end)
    self.BtnBg:AddEventListener(function() self:OnBtnBgClick() end)
end

function XUiLifeTreeUnlockType:OnStart(catalogId)
    self.CatalogId = catalogId
    self.UnlockCount = self._Control:GetCharacterUnlockCountByCatalogId(catalogId)
    self.IsUnlockFinish = self._Control:IsCharacterUnlockFinish(catalogId)
    self.GridConditionDic = {}
    self:InitGridUnlockConditions()
end

function XUiLifeTreeUnlockType:OnEnable()
    self:Refresh()
end

function XUiLifeTreeUnlockType:OnDisable()
end

function XUiLifeTreeUnlockType:OnDestroy()
end

function XUiLifeTreeUnlockType:Refresh()
    self.PanelUnlockTitle.gameObject:SetActiveEx(not self.IsUnlockFinish)
    self.PanelPlayTitle.gameObject:SetActiveEx(self.IsUnlockFinish)
end

function XUiLifeTreeUnlockType:OnBtnCloseClick()
    self:Close()
end

function XUiLifeTreeUnlockType:OnBtnBgClick()
    self:Close()
end

function XUiLifeTreeUnlockType:InitGridUnlockConditions()
    self.GridUnlockCondition.gameObject:SetActiveEx(false)
    local catalogConfig = self._Control:GetLifeTreeCharacterCatalogConfigById(self.CatalogId)
    local skipIds
    local skipDescs
    local skipIcons
    if self.IsUnlockFinish then
        skipIds = catalogConfig.UnlockSkipIds
        skipDescs = catalogConfig.UnlockSkipDescs
        skipIcons = catalogConfig.UnlockSkipIcons
    else
        local nextUnlockIndex = self.UnlockCount + 1
        skipIds = catalogConfig["SkipIds" .. nextUnlockIndex]
        skipDescs = catalogConfig["SkipDescs" .. nextUnlockIndex]
        skipIcons = catalogConfig["SkipIcons" .. nextUnlockIndex]
    end
    
    for i, skipId in ipairs(skipIds) do
        local desc = skipDescs[i]
        local icon = skipIcons[i]
        local go = CSInstantiate(self.GridUnlockCondition, self.PanelUnlockConditions)
        ---@type XUiLifeTreeUnlockTypeGridUnlockCondition
        local grid = XUiLifeTreeUnlockTypeGridUnlockCondition.New(go, self, desc, skipId, icon)
        grid:Open()
        self.GridConditionDic[skipId] = grid
    end
end

return XUiLifeTreeUnlockType
