--[[
-- XUiTheatre6PopupSellSkill.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-03-12 10:46:31
--]]

---@class XUiTheatre6PopupSellSkill : XLuaUi
---@field _Control XTheatre6Control
---@field UiTxtDesc XUiRichTextCustomRender
---@field BtnCanel XUiComponent.XUiButton
---@field BtnSure XUiComponent.XUiButton
---@field BtnClose XUiComponent.XUiButton
---@field PanelAsset UnityEngine.RectTransform
local XUiTheatre6PopupSellSkill = XLuaUiManager.Register(XLuaUi, "UiTheatre6PopupSellSkill")
function XUiTheatre6PopupSellSkill:OnAwake()
    self:InitComponents()
end

function XUiTheatre6PopupSellSkill:InitComponents()
    -- Button
    self.BtnCanel:AddEventListener(function() self:OnBtnCanelClick() end)
    self.BtnSure:AddEventListener(function() self:OnBtnSureClick() end)
    self.BtnClose:AddEventListener(function() self:OnBtnCloseClick() end)

    -- PanelAsset
    self.PanelAsset = XUiHelper.XUiPanelAsset(self, self.PanelAsset, XDataCenter.ItemManager.ItemId.FreeGem)

end

function XUiTheatre6PopupSellSkill:OnStart(overQueue)
    if XTool.IsTableEmpty(overQueue) then
        self:Close()
        return
    end

    local skillNames = ""
    local goldAmount = 0
    for key, skillId in ipairs(overQueue) do
        local skillCfg = self._Control:GetSkillCfgById(skillId)
        skillNames = skillNames..skillCfg.Name.. "、"
        goldAmount = goldAmount + skillCfg.SellPrice
    end
    skillNames = skillNames:sub(1, -4) -- 去掉最后一个顿号
    self.UiTxtDesc.text = string.format(XUiHelper.GetText("Theatre6SkillBagFull"), skillNames, goldAmount)
    self:Refresh()
end

function XUiTheatre6PopupSellSkill:OnEnable()
end

function XUiTheatre6PopupSellSkill:OnDisable()
end

function XUiTheatre6PopupSellSkill:OnDestroy()
end

function XUiTheatre6PopupSellSkill:Refresh()

end

function XUiTheatre6PopupSellSkill:OnBtnCanelClick(eventData)
    self:Close()
end

function XUiTheatre6PopupSellSkill:OnBtnSureClick(eventData)
    self._Control:OverQueueSellRequest(function()
        self:Close()
    end)
end

function XUiTheatre6PopupSellSkill:OnBtnCloseClick(eventData)
    self:Close()
end

return XUiTheatre6PopupSellSkill
