---
--- 神威 法奥斯生态脚本
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ljb.
--- DateTime: 2026/3/18 12:12
---

local Base = require("Character/BigWorld/XEcologyConstructAI/XEcologyConstructAIBase")
local BaseState = require("Character/BigWorld/XEcologyConstructAI/XEcologyConstructAIBaseState")
local FindPathState = require("Character/BigWorld/XEcologyConstructAI/XEcologyFindCombinePathState")

--region 神威生态2.0期静态参数
---生态状态枚举
local StateEnum = {
    None = 0,
    ---教学楼入口处等待指挥官
    TeachingBuilding = 1,
    ---训练室
    TrainingRoom = 2,
    ---墓碑区
    Tombstone = 3,
    ---教室内：观察学生
    InClass = 4,
    ---小吃摊
    Stall = 5,
    ---寻路过程
    FindPath = 6,
}
---数据黑板key值
local DataBoardKey = {
    None = 0,
    ---教学楼入口处等待指挥官
    TeachingBuilding = 1,
    ---训练室
    TrainingRoom = 2,
    ---墓碑区
    Tombstone = 3,
    ---教室内：观察学生
    InClass = 4,
    ---小吃摊
    Stall = 5,
    ---寻路过程
    FindPath = 6,
}
--endregion


--region 状态-神威-教学楼
---@class XKamuiTeachingBuildingState: XEcologyConstructAIBaseState
local XKamuiTeachingBuildingState = XClass(BaseState, "XKamuiTeachingBuildingState")

---数据配置
---@overload
function XKamuiTeachingBuildingState:InitStateConfig()
    self.StateConfig = {}
    self.StateConfig.StateEnum = StateEnum.TeachingBuilding
    self.StateConfig.StateAnim = "Drama_Stand_05"
    self.StateConfig.TriggerId = 1
    self.StateConfig.ShowOptionId = 1
    self.StateConfig.RegisterWorldEventList = {
        EWorldEvent.ActorTrigger,
        EWorldEvent.NpcInteractStart,
        EWorldEvent.NpcInteractComplete,
        EWorldEvent.DramaFinish,
    }
end

function XKamuiTeachingBuildingState:OnStateEnter(lastStateEnum)
    BaseState.OnStateEnter(self, lastStateEnum)
    self.StateMachine:SetDataBoard(DataBoardKey.TeachingBuilding, 0)
end

function XKamuiTeachingBuildingState:HandleEvent(eventType, eventArgs)
    BaseState.HandleEvent(self, eventType, eventArgs)
    if eventType == EWorldEvent.DramaFinish and eventArgs.DramaName == "Drama_3016_004" then
        if not eventArgs.HistoryDecisionDict[6] then
            return
        end
        if table.contains(eventArgs.HistoryDecisionDict[6], 1) then
            self.StateMachine:SetDataBoard(DataBoardKey.TeachingBuilding, 1) ----去往教室
        elseif table.contains(eventArgs.HistoryDecisionDict[6], 2) then
            self.StateMachine:SetDataBoard(DataBoardKey.TeachingBuilding, 2) ---去往训练室
        end
    end
end

--endregion


--region 状态-神威-训练室
---@class XKamuiTrainingRoomState: XEcologyConstructAIBaseState
local XKamuiTrainingRoomState = XClass(BaseState, "XKamuiTrainingRoomState")

---数据配置
---@overload
function XKamuiTrainingRoomState:InitStateConfig()
    self.StateConfig = {}
    self.StateConfig.StateEnum = StateEnum.TrainingRoom
    self.StateConfig.StateAnim = "Drama_FightPlay"
    self.StateConfig.TriggerId = 1
    self.StateConfig.ShowOptionId = 2
    self.StateConfig.RegisterWorldEventList = {
        EWorldEvent.ActorTrigger,
        EWorldEvent.NpcInteractStart,
        EWorldEvent.NpcInteractComplete,
    }
    self.StateConfig.BubbleDict = {
        [EEcologyBubbleType.Near] = {
            Name = "301604",
            TriggerDistance = 6,
            TriggerCD = 30,
            LoopTime = 3,
        }
    }
end

function XKamuiTrainingRoomState:OnStateEnter(lastStateEnum)
    BaseState.OnStateEnter(self, lastStateEnum)
    self.StateMachine:SetDataBoard(DataBoardKey.TrainingRoom, 0)
end
--endregion


--region 状态-神威-墓碑
---@class XKamuiTombstoneState: XEcologyConstructAIBaseState
local XKamuiTombstoneState = XClass(BaseState, "XKamuiTombstoneState")

---数据配置
---@overload
function XKamuiTombstoneState:InitStateConfig()
    self.StateConfig = {}
    self.StateConfig.StateEnum = StateEnum.Tombstone
    self.StateConfig.StateAnim = "Drama_KnightKneel"
    self.StateConfig.TriggerId = 1
    self.StateConfig.ShowOptionId = 3
    self.StateConfig.RegisterWorldEventList = {
        EWorldEvent.ActorTrigger,
        EWorldEvent.NpcInteractStart,
        EWorldEvent.NpcInteractComplete,
    }
    self.StateConfig.BubbleDict = {
        [EEcologyBubbleType.Near] = {
            Name = "301603",
            TriggerDistance = 6,
            TriggerCD = 30,
            LoopTime = 3,
        }
    }
end

function XKamuiTombstoneState:OnStateEnter(lastStateEnum)
    BaseState.OnStateEnter(self, lastStateEnum)
    self.StateMachine:SetDataBoard(DataBoardKey.Tombstone, 0)
end

function XKamuiTombstoneState:OnActorTrigger(eventArgs)
    BaseState.OnActorTrigger(self, eventArgs)
    if eventArgs.TriggerState == ETriggerState.Enter and eventArgs.TriggerHolderUUID == self._uuid then
        self._proxy:PlayDramaBubble(ETargetActorType.Npc, self._uuid, "301603")
        self.StateMachine:SetDataBoard(DataBoardKey.Tombstone, 1)
    end
end

--endregion


--region 状态-神威-教室
---@class XKamuiInClassState: XEcologyConstructAIBaseState
local XKamuiInClassState = XClass(BaseState, "XKamuiInClassState")

---数据配置
---@overload
function XKamuiInClassState:InitStateConfig()
    self.StateConfig = {}
    self.StateConfig.StateEnum = StateEnum.InClass
    self.StateConfig.StateAnim = "Drama_Stand_01"
    self.StateConfig.TriggerId = 1
    self.StateConfig.ShowOptionId = 7
    self.StateConfig.RegisterWorldEventList = {
        EWorldEvent.ActorTrigger,
        EWorldEvent.NpcInteractStart,
        EWorldEvent.NpcInteractComplete,
    }
end

function XKamuiInClassState:OnStateEnter(lastStateEnum)
    BaseState.OnStateEnter(self, lastStateEnum)
    self.StateMachine:SetDataBoard(DataBoardKey.InClass, 0)
end
--endregion

function XKamuiInClassState:OnActorTrigger(eventArgs)
    BaseState.OnActorTrigger(self, eventArgs)
    if eventArgs.TriggerState == ETriggerState.Enter and eventArgs.TriggerHolderUUID == self._uuid then
        self.StateMachine:SetDataBoard(DataBoardKey.InClass, 1)
    end
end

function XKamuiInClassState:UpdateOptionActive()
    local optionId = self.StateConfig.ShowOptionId
    if self._proxy:IsQuestObjectiveFinished(20160102) then
        optionId = 4
    end
    self._proxy:SetNpcInteractOneOptionActive(self._placeId, optionId)
end


--region 状态-神威-小吃摊
---@class XKamuiStallState: XEcologyConstructAIBaseState
local XKamuiStallState = XClass(BaseState, "XKamuiStallState")

---数据配置
---@overload
function XKamuiStallState:InitStateConfig()
    self.StateConfig = {}
    self.StateConfig.StateEnum = StateEnum.Stall
    self.StateConfig.StateAnim = "Drama_LookAround"
    self.StateConfig.TriggerId = 1
    self.StateConfig.ShowOptionId = 5
    self.StateConfig.RegisterWorldEventList = {
        EWorldEvent.ActorTrigger,
        EWorldEvent.NpcInteractStart,
        EWorldEvent.NpcInteractComplete,
    }
    self.StateConfig.BubbleDict = {
        [EEcologyBubbleType.Near] = {
            Name = "301605",
            TriggerDistance = 6,
            TriggerCD = 30,
            LoopTime = 3,
        }
    }
end

function XKamuiStallState:OnStateEnter(lastStateEnum)
    BaseState.OnStateEnter(self, lastStateEnum)
    self.StateMachine:SetDataBoard(DataBoardKey.Stall, self._proxy:Random(0,1))
end
--endregion

function XKamuiStallState:OnActorTrigger(eventArgs)
    BaseState.OnActorTrigger(self, eventArgs)
    if eventArgs.TriggerState == ETriggerState.Enter and eventArgs.TriggerHolderUUID == self._uuid then
        self._proxy:PlayNpcCustomPerformAnim(self._uuid, "Drama_Stand_01", 0.5, 0.5, false)
    end
end


--region 状态-神威-寻路
---@class XKamuiFindPathState: XEcologyFindCombinePathState
local XKamuiFindPathState = XClass(FindPathState, "XKamuiFindPathState")

---数据配置
---@overload
function XKamuiFindPathState:InitStateConfig()
    self.StateConfig = {}
    self.StateConfig.StateEnum = StateEnum.FindPath
    self.StateConfig.TriggerId = 1
    self.StateConfig.ShowOptionId = 6
    self.StateConfig.RegisterWorldEventList = {
        EWorldEvent.ActorTrigger,
        EWorldEvent.NpcInteractStart,
        EWorldEvent.NpcInteractComplete,
    }

    self.StateConfig.FindPathConfig = {}
    self.StateConfig.FindPathConfig.MeetCommanderBubbleName = "301601"
end
--endregion


--region 神威法奥斯生态AI
---@class XCharKamuiEcology : XEcologyConstructAIBase
---@field _stateMachine XStateMachineController 状态机
local XCharKamuiEcology = XDlcScriptManager.RegCharScript(10610501, "XCharKamuiEcology", Base)

--- 注册状态机状态
function XCharKamuiEcology:RegisterMachineState()
    self._stateMachine:AddState(StateEnum.TeachingBuilding, XKamuiTeachingBuildingState.New(self._proxy))
    self._stateMachine:AddState(StateEnum.TrainingRoom, XKamuiTrainingRoomState.New(self._proxy))
    self._stateMachine:AddState(StateEnum.Tombstone, XKamuiTombstoneState.New(self._proxy))
    self._stateMachine:AddState(StateEnum.InClass, XKamuiInClassState.New(self._proxy))
    self._stateMachine:AddState(StateEnum.Stall, XKamuiStallState.New(self._proxy))
    self._stateMachine:AddState(StateEnum.FindPath, XKamuiFindPathState.New(self._proxy))
end

--- 注册状态转移方程
function XCharKamuiEcology:RegisterMachineStateTransition()
    -- 设置寻路状态枚举值
    self.FindPathStateEnum = StateEnum.FindPath
    self.NextStateList = {
        StateEnum.TeachingBuilding, StateEnum.Tombstone, StateEnum.Stall, StateEnum.TrainingRoom, StateEnum.InClass
    }
    self.NextStateRotDict ={
        [StateEnum.TeachingBuilding] = {x=0, y=-114.512, z=0},
        [StateEnum.Tombstone] = {x=0, y=-106.342, z=0},
        [StateEnum.Stall] = {x=0, y=144.786, z=0},
        [StateEnum.TrainingRoom] = {x=0, y=-104.532, z=0},
        [StateEnum.InClass] = {x=0, y=-72.046, z=0},
    }
    -- 其他状态到寻路状态
    self:RegisterInFindPathStateTransition(StateEnum.TeachingBuilding, function()
        if self._stateMachine:CheckDataBoard(DataBoardKey.TeachingBuilding, 1) then
            return StateEnum.InClass
        elseif self._stateMachine:CheckDataBoard(DataBoardKey.TeachingBuilding, 2) then
            return StateEnum.TrainingRoom
        else
            return StateEnum.Tombstone
        end
    end, 30, 1)
    self:RegisterInFindPathStateTransition(StateEnum.TrainingRoom, function()
        return self._stateMachine:CheckDataBoard(DataBoardKey.TrainingRoom, 1) and StateEnum.Stall or StateEnum.Stall
    end, 30, 1)
    self:RegisterInFindPathStateTransition(StateEnum.Tombstone, function()
        return self._stateMachine:CheckDataBoard(DataBoardKey.Tombstone, 1) and StateEnum.Stall or StateEnum.Stall
    end, 20, 1)
    self:RegisterInFindPathStateTransition(StateEnum.Stall, function()
        return self._stateMachine:CheckDataBoard(DataBoardKey.Stall, 1) and StateEnum.TeachingBuilding or StateEnum.Tombstone
    end, 20, 1)
    self:RegisterInFindPathStateTransition(StateEnum.InClass, function()
        return self._stateMachine:CheckDataBoard(DataBoardKey.InClass, 1) and StateEnum.Stall or StateEnum.Stall
    end, 20, 1)


    -- 寻路状态到其他状态
    self:RegisterOutFindPathStateTransition(StateEnum.TeachingBuilding)
    self:RegisterOutFindPathStateTransition(StateEnum.TrainingRoom)
    self:RegisterOutFindPathStateTransition(StateEnum.Tombstone)
    self:RegisterOutFindPathStateTransition(StateEnum.InClass)
    self:RegisterOutFindPathStateTransition(StateEnum.Stall)
end

return XCharKamuiEcology
--endregion
