---
--- 凡妮莎 法奥斯生态脚本
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ljb.
--- DateTime: 2026/3/18 12:12
---

local Base = require("Character/BigWorld/XEcologyConstructAI/XEcologyConstructAIBase")
local BaseState = require("Character/BigWorld/XEcologyConstructAI/XEcologyConstructAIBaseState")
local FindPathState = require("Character/BigWorld/XEcologyConstructAI/XEcologyFindCombinePathState")

--region 凡妮莎生态2.0期静态参数
---生态状态枚举
local StateEnum = {
    None = 0,
    ---教室里观察学生
    InClass = 1,
    ---训练室
    TrainingRoom = 2,
    ---对景
    FacingView = 3,
    ---演讲台
    Podium = 4,
    ---寻路过程
    FindPath = 5,
}
---数据黑板key值
local DataBoardKey = {
    None = 0,
    ---教室里观察学生
    InClass = 1,
    ---训练室
    TrainingRoom = 2,
    ---对景
    FacingView = 3,
    ---演讲台
    Podium = 4,
    ---寻路过程
    FindPath = 5,
}
--endregion


--region 状态-凡妮莎-教室里观察学生
---@class XVanessaInClassState: XEcologyConstructAIBaseState
local XVanessaInClassState = XClass(BaseState, "XVanessaInClassState")

---数据配置
---@overload
function XVanessaInClassState:InitStateConfig()
    self.StateConfig = {}
    self.StateConfig.StateEnum = StateEnum.InClass
    self.StateConfig.StateAnim = "Drama_Stand_15"
    self.StateConfig.TriggerId = 1
    self.StateConfig.ShowOptionId = 1
    self.StateConfig.RegisterWorldEventList = {
        EWorldEvent.ActorTrigger,
        EWorldEvent.NpcInteractStart,
        EWorldEvent.NpcInteractComplete,
        EWorldEvent.DramaFinish,
    }
    self.StateConfig.BubbleDict = {
        [EEcologyBubbleType.Around] = {
            Name = "300604",
            TriggerDistance = 6,
            TriggerCD = 2,
            LoopTime = 3,
        },
    }
end

function XVanessaInClassState:OnStateEnter(lastStateEnum)
    BaseState.OnStateEnter(self, lastStateEnum)
    self.StateMachine:SetDataBoard(DataBoardKey.InClass, 0)
end

function XVanessaInClassState:HandleEvent(eventType, eventArgs)
    BaseState.HandleEvent(self, eventType, eventArgs)
    if eventType == EWorldEvent.DramaFinish and eventArgs.DramaName == "TargetDrama" then
        if not eventArgs.HistoryDecisionDict[clipId] then
            return
        end
        if table.contains(eventArgs.HistoryDecisionDict[clipId], decisionId) then
            self.StateMachine:SetDataBoard(DataBoardKey.InClass, 1)
        end
    end
end
--endregion


--region 状态-凡妮莎-训练室
---@class XVanessaTrainingRoomState: XEcologyConstructAIBaseState
local XVanessaTrainingRoomState = XClass(BaseState, "XVanessaTrainingRoomState")

---数据配置
---@overload
function XVanessaTrainingRoomState:InitStateConfig()
    self.StateConfig = {}
    self.StateConfig.StateEnum = StateEnum.TrainingRoom
    self.StateConfig.StateAnim = "Drama_Stand_06"
    self.StateConfig.TriggerId = 1
    self.StateConfig.ShowOptionId = 2
    self.StateConfig.RegisterWorldEventList = {
        EWorldEvent.ActorTrigger,
        EWorldEvent.NpcInteractStart,
        EWorldEvent.NpcInteractComplete,
    }
    self.StateConfig.BubbleDict = {
        [EEcologyBubbleType.Around] = {
            Name = "300605",
            TriggerDistance = 6,
            TriggerCD = 2,
            LoopTime = 3,
        },
        [EEcologyBubbleType.Near] = {
            Name = "300601",
            TriggerDistance = 2.5,
            TriggerCD = 2,
            LoopTime = 3,
        }
    }
end

function XVanessaTrainingRoomState:OnStateEnter(lastStateEnum)
    BaseState.OnStateEnter(self, lastStateEnum)
    self.StateMachine:SetDataBoard(DataBoardKey.TrainingRoom, 0)
end
--endregion


--region 状态-凡妮莎-对景
---@class XVanessaFacingViewState: XEcologyConstructAIBaseState
local XVanessaFacingViewState = XClass(BaseState, "XVanessaFacingViewState")

---数据配置
---@overload
function XVanessaFacingViewState:InitStateConfig()
    self.StateConfig = {}
    self.StateConfig.StateEnum = StateEnum.FacingView
    self.StateConfig.StateAnim = "Drama_Stand_07"
    self.StateConfig.TriggerId = 1
    self.StateConfig.ShowOptionId = 3
    self.StateConfig.RegisterWorldEventList = {
        EWorldEvent.ActorTrigger,
        EWorldEvent.NpcInteractStart,
        EWorldEvent.NpcInteractComplete,
    }
    self.StateConfig.BubbleDict = {
        [EEcologyBubbleType.Around] = {
            Name = "300606",
            TriggerDistance = 6,
            TriggerCD = 2,
            LoopTime = 3,
        },
        [EEcologyBubbleType.Near] = {
            Name = "300602",
            TriggerDistance = 2.5,
            TriggerCD = 2,
            LoopTime = 3,
        }
    }
end

function XVanessaFacingViewState:OnStateEnter(lastStateEnum)
    BaseState.OnStateEnter(self, lastStateEnum)
    self.StateMachine:SetDataBoard(DataBoardKey.FacingView, 0)
end
--endregion


--region 状态-凡妮莎-演讲台
---@class XVanessaPodiumState: XEcologyConstructAIBaseState
local XVanessaPodiumState = XClass(BaseState, "XVanessaPodiumState")

---数据配置
---@overload
function XVanessaPodiumState:InitStateConfig()
    self.StateConfig = {}
    self.StateConfig.StateEnum = StateEnum.Podium
    self.StateConfig.StateAnim = "Drama_Stand_07"
    self.StateConfig.TriggerId = 1
    self.StateConfig.ShowOptionId = 4
    self.StateConfig.RegisterWorldEventList = {
        EWorldEvent.ActorTrigger,
        EWorldEvent.NpcInteractStart,
        EWorldEvent.NpcInteractComplete,
    }
    self.StateConfig.BubbleDict = {
        [EEcologyBubbleType.Around] = {
            Name = "300606",
            TriggerDistance = 6,
            TriggerCD = 2,
            LoopTime = 3,
        },
        [EEcologyBubbleType.Near] = {
            Name = "300602",
            TriggerDistance = 2.5,
            TriggerCD = 2,
            LoopTime = 3,
        }
    }
end

function XVanessaPodiumState:OnStateEnter(lastStateEnum)
    BaseState.OnStateEnter(self, lastStateEnum)
    self.StateMachine:SetDataBoard(DataBoardKey.Podium, 0)
end
--endregion


--region 状态-凡妮莎-寻路
---@class XVanessaFindPathState: XEcologyFindCombinePathState
local XVanessaFindPathState = XClass(FindPathState, "XVanessaFindPathState")

---数据配置
---@overload
function XVanessaFindPathState:InitStateConfig()
    self.StateConfig = {}
    self.StateConfig.StateEnum = StateEnum.FindPath
    self.StateConfig.TriggerId = 1
    self.StateConfig.ShowOptionId = 5
    self.StateConfig.RegisterWorldEventList = {
        EWorldEvent.ActorTrigger,
        EWorldEvent.NpcInteractStart,
        EWorldEvent.NpcInteractComplete,
    }

    self.StateConfig.FindPathConfig = {}
    self.StateConfig.FindPathConfig.MeetCommanderBubbleName = "300603"
end
--endregion


--region 凡妮莎法奥斯生态AI
---@class XCharVanessaEcology : XEcologyConstructAIBase
---@field _stateMachine XStateMachineController 状态机
local XCharVanessaEcology = XDlcScriptManager.RegCharScript(10610401, "XCharVanessaEcology", Base)

--- 注册状态机状态
function XCharVanessaEcology:RegisterMachineState()
    self._stateMachine:AddState(StateEnum.InClass, XVanessaInClassState.New(self._proxy))
    self._stateMachine:AddState(StateEnum.TrainingRoom, XVanessaTrainingRoomState.New(self._proxy))
    self._stateMachine:AddState(StateEnum.FacingView, XVanessaFacingViewState.New(self._proxy))
    self._stateMachine:AddState(StateEnum.Podium, XVanessaPodiumState.New(self._proxy))
    self._stateMachine:AddState(StateEnum.FindPath, XVanessaFindPathState.New(self._proxy))
end

--- 注册状态转移方程
function XCharVanessaEcology:RegisterMachineStateTransition()
    -- 设置寻路状态枚举值
    self.FindPathStateEnum = StateEnum.FindPath
    -- 其他状态到寻路状态
    self:RegisterInFindPathStateTransition(StateEnum.InClass, function()
        return self._stateMachine:CheckDataBoard(DataBoardKey.InClass, 1) and StateEnum.FacingView or StateEnum.TrainingRoom
    end, 5, 1)
    self:RegisterInFindPathStateTransition(StateEnum.TrainingRoom, function()
        return self._stateMachine:CheckDataBoard(DataBoardKey.TrainingRoom, 1) and StateEnum.FacingView or StateEnum.Podium
    end, 5, 1)
    self:RegisterInFindPathStateTransition(StateEnum.Podium, function()
        return self._stateMachine:CheckDataBoard(DataBoardKey.Podium, 1) and StateEnum.InClass or StateEnum.FacingView
    end, 5, 1)
    self:RegisterInFindPathStateTransition(StateEnum.FacingView, function()
        return self._stateMachine:CheckDataBoard(DataBoardKey.FacingView, 1) and StateEnum.Podium or StateEnum.InClass
    end, 5, 1)
    
    -- 寻路状态到其他状态
    self:RegisterOutFindPathStateTransition(StateEnum.InClass)
    self:RegisterOutFindPathStateTransition(StateEnum.TrainingRoom)
    self:RegisterOutFindPathStateTransition(StateEnum.FacingView)
    self:RegisterOutFindPathStateTransition(StateEnum.Podium)
end

return XCharVanessaEcology
--endregion
