--[[
-- XUiPBRSettlementPanelSkill.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-01-12 15:30:10
--]]

local XUiPBRCommonSkillListPanel = require('XUi/XUiPBRGame/CommonUiTemplate/ItemShowListPanel/XUiPBRCommonSkillListPanel')

---@class XUiPBRSettlementPanelSkill : XUiPBRCommonSkillListPanel
---@field _Control XPBRGameControl
local XUiPBRSettlementPanelSkill = XClass(XUiPBRCommonSkillListPanel, "XUiPBRSettlementPanelSkill")


return XUiPBRSettlementPanelSkill
