--[[
-- XUiPBRSettlementPanelProp.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-01-12 15:30:10
--]]

local XUiPBRCommonPropListPanel = require('XUi/XUiPBRGame/CommonUiTemplate/ItemShowListPanel/XUiPBRCommonPropListPanel')

---@class XUiPBRSettlementPanelProp : XUiPBRCommonPropListPanel
local XUiPBRSettlementPanelProp = XClass(XUiPBRCommonPropListPanel, "XUiPBRSettlementPanelProp")

return XUiPBRSettlementPanelProp
