--[[
-- XUiPBRShopNewPanelProp.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-01-12 15:30:37
--]]

local XUiPBRCommonPropListPanel = require('XUi/XUiPBRGame/CommonUiTemplate/ItemShowListPanel/XUiPBRCommonPropListPanel')
--- 继承自结算面板道具显示
---@class XUiPBRShopNewPanelProp : XUiPBRCommonPropListPanel
local XUiPBRShopNewPanelProp = XClass(XUiPBRCommonPropListPanel, "XUiPBRShopNewPanelProp")


return XUiPBRShopNewPanelProp
