--[[
-- XUiPBRShopNewUiPBRPanelAttribute.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-01-12 15:30:37
--]]

local XUiPBRCommonRolePanelStatus = require('XUi/XUiPBRGame/CommonUiTemplate/CharacterStatusPanel/XUiPBRCommonRolePanelStatus')

---@class XUiPBRShopNewUiPBRPanelAttribute : XUiPBRCommonRolePanelStatus
local XUiPBRShopNewUiPBRPanelAttribute = XClass(XUiPBRCommonRolePanelStatus, "XUiPBRShopNewUiPBRPanelAttribute")

---@overload
function XUiPBRShopNewUiPBRPanelAttribute:GetPanelAttributeCls()
    return require('XUi/XUiPBRGame/XUiPBRShopNew/CharacterInfo/XUiPBRShopNewListAttribute')
end

return XUiPBRShopNewUiPBRPanelAttribute
