--[[
-- XUiPBRCharacterDetailPanelAttribute.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-01-12 15:28:08
--]]

local XUiPBRCommonRolePanelAttribute = require("XUi/XUiPBRGame/CommonUiTemplate/CharacterStatusPanel/XUiPBRCommonRolePanelAttribute")

---@class XUiPBRCharacterDetailPanelAttribute : XUiPBRCommonRolePanelAttribute
---@field _Control XPBRGameControl
---@field ListAttribute UnityEngine.UI.ScrollRect
local XUiPBRCharacterDetailPanelAttribute = XClass(XUiPBRCommonRolePanelAttribute, "XUiPBRCharacterDetailPanelAttribute")


return XUiPBRCharacterDetailPanelAttribute
