--[[
-- XUiLifeTreeMain.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-02-25 11:16:04
--]]

local CSInstantiate = CS.UnityEngine.Object.Instantiate
local CSDirctorPlayType = CS.XUiPlayTimelineAnimation.DirctorPlayType
local Lerp = CS.UnityEngine.Mathf.Lerp
local stringSub = string.sub
local CAMERA_DRAG_SPEED_X = 0.1 -- 拖拽X方向速度
local CAMERA_DRAG_SPEED_Y = 0.06 -- 拖拽Y方向速度
local CAMERA_FADE_TIME = 0.6 -- 拖拽缓缓衰弱的时间

local CAMERA_Y_VALUE_LIFE_TREE = 0 -- 生命树状态的摄像机值
local CAMERA_Y_VALUE_SEA = 1 -- 意识海状态的摄像机值
local CAMERA_Y_VALUE_SWITCH = 0.7 -- 摄像机切换意识海的值
local CHANGE_CAMERA_VALUE_TIME = 0.4 -- 修改摄像机X和Y值的时间

local CAMERA_ZOOM_IN_TIME = 1 -- 镜头推进动画时间

local STATE = {
    LIFE_TREE = 1,  -- 生命树
    SEA = 2,        -- 意识海
}

-- Exponential Ease Out
local EaseExpoOut = function(t)
    if t >= 1 then return 1 end
    return 1 - math.pow(2, -10 * t)
end

-- Quadratic Ease Out
local EaseQuadOut = function(t)
    if t >= 1 then return 1 end
    return t * (2 - t)  -- 等价于 1 - (1-t)²
end

local XUiLifeTreeMainGridRegularCard = require("XUi/XUiLifeTree/XUiLifeTreeMain/XUiLifeTreeMainGridRegularCard")
local XUiLifeTreeMainGridDivineCard = require("XUi/XUiLifeTree/XUiLifeTreeMain/XUiLifeTreeMainGridDivineCard")
---@class XUiLifeTreeMain : XLuaUi
---@field _Control XLifeTreeControl
---@field BtnBack XUiComponent.XUiButton
---@field BtnMainUi XUiComponent.XUiButton
---@field BtnHelp XUiComponent.XUiButton
---@field BtnAchievement XUiComponent.XUiButton
---@field PanelItem UnityEngine.RectTransform
---@field Grid256New UnityEngine.RectTransform
---@field PanelLifeTree UnityEngine.RectTransform
---@field PanelSea UnityEngine.RectTransform
---@field BtnPositioningLifeTree XUiComponent.XUiButton
---@field BtnPositioningSea XUiComponent.XUiButton
---@field TopControlWhite UiObject
---@field ImgLingqu UnityEngine.UI.Image
---@field PanelDragBg XGoInputHandler
---@field GridDivineCard UiObject
---@field GridRegularCard UiObject
---@field GridDivineCard UiObject
---@field PanelCard UnityEngine.RectTransform
---@field BtnTask XUiComponent.XUiButton
---@field TxtTaskProgress UnityEngine.UI.Text
---@field SceneConstellationGoDic table<number, UnityEngine.GameObject>
---@field SceneAnimationGoDic table<string, UnityEngine.Playables.PlayableDirector>
local XUiLifeTreeMain = XLuaUiManager.Register(XLuaUi, "UiLifeTreeMain")
function XUiLifeTreeMain:OnAwake()
    self.PanelLifeTree.gameObject:SetActiveEx(true)
    self.PanelSea.gameObject:SetActiveEx(false)
    self:InitCameraParameters()
    self:InitScene()
    self:InitComponents()
    self:InitCards()
end

function XUiLifeTreeMain:InitCameraParameters()
    local configDragSpeed = self._Control:GetLifeTreeClientConfigConfigById("CameraDragSpeed")
    if configDragSpeed then
        if configDragSpeed.Values[1] then
            CAMERA_DRAG_SPEED_X = tonumber(configDragSpeed.Values[1])
        end
        if configDragSpeed.Values[2] then
            CAMERA_DRAG_SPEED_Y = tonumber(configDragSpeed.Values[2])
        end
    end

    local configSwitchTime = self._Control:GetLifeTreeClientConfigConfigById("CameraSwitchTime")
    if configSwitchTime then
        if configSwitchTime.Values[1] then
            CHANGE_CAMERA_VALUE_TIME = tonumber(configSwitchTime.Values[1])
        end
    end
end

function XUiLifeTreeMain:InitScene()
    -- 摄像机
    local cameraRoot = self.UiModelGo.transform
    ---@type CS.Cinemachine.CinemachineFreeLook
    self.CamFarMain = cameraRoot:Find("UiFarRoot/CamFarMain"):GetComponent(typeof(CS.Cinemachine.CinemachineFreeLook))
    ---@type CS.Cinemachine.CinemachineFreeLook
    self.CamNearMain = cameraRoot:Find("UiNearRoot/CamNearMain"):GetComponent(typeof(CS.Cinemachine.CinemachineFreeLook))
    ---@type CS.UnityEngine.Camera
    self.UiNearCamera = cameraRoot:Find("UiNearRoot/UiNearCamera"):GetComponent("Camera")
    ---@type CS.UnityEngine.Camera
    self.UiFarCamera = cameraRoot:Find("UiFarRoot/UiFarCamera"):GetComponent("Camera")
    ---@type CS.UnityEngine.Transform
    self.LookAtPoint = cameraRoot:Find("LookAtPoint")
    ---@type CS.UnityEngine.Transform
    self.ZoomInPoint = cameraRoot:Find("ZoomInPoint")
    
    -- 场景
    local sceneRoot = self.UiSceneInfo.Transform
    local constellationList = sceneRoot:Find("GroupBase/ConstellationList")
    if constellationList then
        self.SceneConstellationGoDic = {}
        local CONSTELLATION_PREFIX = "Constellation"
        local prefixCount = #CONSTELLATION_PREFIX
        local constellationConfigs = self._Control:GetLifeTreeConstellationConfigs()
        
        local childCount = constellationList.childCount
        for i = 0, childCount - 1 do
            local child = constellationList:GetChild(i)
            if child then
                local name = child.gameObject.name
                if stringSub(name, 1, prefixCount) == CONSTELLATION_PREFIX then
                    -- 去掉前缀，提取数字部分
                    local numStr = stringSub(name, prefixCount + 1)
                    local id = tonumber(numStr)
                    local isExit = constellationConfigs[id] ~= nil
                    child.gameObject:SetActive(isExit)
                    if isExit then
                        self.SceneConstellationGoDic[id] = child
                    end
                end
            end
        end
    end
end

function XUiLifeTreeMain:InitComponents()
    -- Back Mainui Help
    self:BindExitBtns()

    -- Button
    self.BtnHelp:AddEventListener(function() self:OnBtnHelpClick() end)
    self.BtnTask:AddEventListener(function() self:OnBtnTaskClick() end)
    self.BtnPositioningLifeTree:AddEventListener(function() self:OnBtnPositioningLifeTreeClick() end)
    self.BtnPositioningSea:AddEventListener(function() self:OnBtnPositioningSeaClick() end)

    -- InputHandler
    self.PanelDragBg:AddBeginDragListener(function(eventData) self:OnPanelDragBgBeginDrag(eventData) end)
    self.PanelDragBg:AddDragListener(function(eventData) self:OnPanelDragBgDrag(eventData) end)
    self.PanelDragBg:AddEndDragListener(function(eventData) self:OnPanelDragBgEndDrag(eventData) end)

    self._Grid256NewArray = {}
    if self.Grid256New then
        self.Grid256New.gameObject:SetActiveEx(false)
    end
end

---@param isSea boolean 是否切换意识海
function XUiLifeTreeMain:OnStart(isSea)
    if isSea then
        self:OnSwitchSea()
    else
        self:OnSwitchLifeTree()
        self:PlayStartAnimation()
    end
end

function XUiLifeTreeMain:OnEnable()
    self:Refresh()
    self:StartTimer()
    self:PlayCameraResetAnimation()
end

function XUiLifeTreeMain:OnDisable()
    self:RemoveTimer()
    self:RemoveSetCameraValueTimer()
end

function XUiLifeTreeMain:OnDestroy()
end

function XUiLifeTreeMain:Refresh()
    self:RefreshBtnTask()
    self:RefreshBtnPositioningSea()
    self:RefreshSceneConstellations()
end

function XUiLifeTreeMain:RefreshBtnTask()
    local config = self._Control:GetLifeTreeClientConfigConfigById("TaskPreviewRewardId")
    local rewardId = tonumber(config.Values[1])
    local rewardItems = XRewardManager.GetRewardList(rewardId)
    XTool.UpdateDynamicGridCommon(self._Grid256NewArray, rewardItems, self.Grid256New, self)

    local taskIds = self._Control:GetTaskIds()
    local finishCnt = 0
    local allCnt = #taskIds
    for _, taskId in ipairs(taskIds) do
        local isFinish = XDataCenter.TaskManager.IsTaskFinished(taskId)
        if isFinish then
            finishCnt = finishCnt + 1
        end
    end
    local isAllFinish = finishCnt >= allCnt
    self.ImgLingqu.gameObject:SetActiveEx(isAllFinish)
    self.TxtTaskProgress.text = string.format("<color=#7db5ff>%s</color>/%s", finishCnt, allCnt)
    
    -- 蓝点
    local isRed = XMVCA.XLifeTree:IsRedTask()
    self.BtnTask:ShowReddot(isRed)
end

function XUiLifeTreeMain:OnBtnHelpClick()
    XLuaUiManager.Open("UiLifeTreePopupTeach")
end

function XUiLifeTreeMain:OnBtnTaskClick()
    XLuaUiManager.Open("UiLifeTreeTask")
end

function XUiLifeTreeMain:OnBtnPositioningLifeTreeClick()
    -- 运营埋点
    local dict = {}
    dict["type"] = 2
    CS.XRecord.Record(dict, "1000042", "LifeTreeOperation")

    self.BtnPositioningLifeTree.gameObject:SetActiveEx(false)
    self:SetCameraValueWithAnim(0, CAMERA_Y_VALUE_LIFE_TREE)
    self:PlayLifeTreeAnimations()
end

function XUiLifeTreeMain:OnBtnPositioningSeaClick()
    -- 运营埋点
    local dict = {}
    dict["type"] = 1
    CS.XRecord.Record(dict, "1000042", "LifeTreeOperation")

    self.BtnPositioningSea.gameObject:SetActiveEx(false)
    self:SetCameraValueWithAnim(0, CAMERA_Y_VALUE_SEA)
    self:PlaySeaAnimations()
end

function XUiLifeTreeMain:RefreshBtnPositioningSea()
    local isRed = XMVCA.XLifeTree:IsRed()
    self.BtnPositioningSea:ShowReddot(isRed)
end

---@param eventData UnityEngine.EventSystems.PointerEventData
function XUiLifeTreeMain:OnPanelDragBgBeginDrag(eventData)
    
end

---@param eventData UnityEngine.EventSystems.PointerEventData
function XUiLifeTreeMain:OnPanelDragBgDrag(eventData)
    if self.IsPlayCameraAnim then return end -- 播生命树、意识海的摄像机切换动画时，不允许拖动
    
    -- 修改X轴方向的值
    -- eventData.delta 是本次拖拽的像素增量
    local xInput = -eventData.delta.x * CAMERA_DRAG_SPEED_X
    self:SetCameraXInput(xInput)
    self.LastDragXInput = xInput
    
    --[[
    -- 修改Y轴方向的值
    local yInput = -eventData.delta.y * CAMERA_DRAG_SPEED_Y
    self:SetCameraYInput(yInput)
    self.LastDragYInput = yInput
    ]]
    
    self.LastDragTime = CS.UnityEngine.Time.realtimeSinceStartup
    self.IsCameraPosValueChange = true
end

---@param eventData UnityEngine.EventSystems.PointerEventData
function XUiLifeTreeMain:OnPanelDragBgEndDrag(eventData)
    
end

-- 开始定时器
function XUiLifeTreeMain:StartTimer()
    self:RemoveTimer()
    self.Timer = XScheduleManager.ScheduleForever(function()
        self:CheckCameraMoveFade()
        if self.IsCameraPosValueChange then
            self:OnCameraPosValueChange()
            self.IsCameraPosValueChange = false
        end
    end, 0)
end

-- 移除定时器
function XUiLifeTreeMain:RemoveTimer()
    if self.Timer then
        XScheduleManager.UnSchedule(self.Timer)
        self.Timer = nil
    end
end

-- 切换到意识海
function XUiLifeTreeMain:OnSwitchSea()
    self.State = STATE.SEA
    self.PanelLifeTree.gameObject:SetActiveEx(false)
    self.PanelSea.gameObject:SetActiveEx(true)
    self.BtnPositioningSea.gameObject:SetActiveEx(true)
end

-- 切换到生命树
function XUiLifeTreeMain:OnSwitchLifeTree()
    self.State = STATE.LIFE_TREE
    self.PanelLifeTree.gameObject:SetActiveEx(true)
    self.PanelSea.gameObject:SetActiveEx(false)
    self.BtnPositioningLifeTree.gameObject:SetActiveEx(true)
end

-- 播放开始动画
function XUiLifeTreeMain:PlayStartAnimation()
    -- 场景动画
    self:StopSceneAnimation("AnimEnable02")
    self:StopSceneAnimation("AnimEnable03")
    self:PlaySceneAnimation("AnimEnable01")

    -- 摄像机动画
    self:PlayCameraAnimation("UiLifeTreeCamAnimEnable01")

    -- UI动画
    self:ShowUi(false)
    self:PlayAnimationWithMask("Start", function()
        self:ShowUi(true)
    end)
end

-- 显示或隐藏UI
function XUiLifeTreeMain:ShowUi(isShow)
    self.PanelTask.gameObject:SetActiveEx(isShow)
    self.PanelCard.gameObject:SetActiveEx(isShow)
    self.PanelLifeTree.gameObject:SetActiveEx(isShow and self.State == STATE.LIFE_TREE)
    self.PanelSea.gameObject:SetActiveEx(isShow and self.State == STATE.SEA)
    
    for _, card in pairs(self.GridCards) do
        if isShow then
            card:Open()
        else
            card:Close()
        end
    end
end

--region 场景动画

function XUiLifeTreeMain:GetSceneAnimationGo(animName)
    self.SceneAnimationGoDic = self.SceneAnimationGoDic or {}
    local animGo = self.SceneAnimationGoDic[animName]
    if animGo then
        return animGo
    end

    local sceneRoot = self.UiSceneInfo.Transform
    animGo = sceneRoot:Find("Animations/" .. tostring(animName))
    if not animGo then
        XLog.Error("未找到场景动画节点UiMain3dLifeTree(Clone)/Animations/" .. tostring(animName))
        return
    end
    self.SceneAnimationGoDic[animName] = animGo
    return animGo
end

-- 播放场景动画
function XUiLifeTreeMain:PlaySceneAnimation(animName, cb, isBack)
    local animGo = self:GetSceneAnimationGo(animName)
    if animGo then
        animGo.gameObject:SetActiveEx(true)
        local playType = isBack and CSDirctorPlayType.Back or CSDirctorPlayType.Forward
        local playTypeInt = CS.System.Convert.ToInt32(playType)
        local speed = 1
        animGo.gameObject:PlayTimelineAnimation(playTypeInt, speed, cb)
        return
    end
end

-- 停止场景动画
function XUiLifeTreeMain:StopSceneAnimation(animName)
    local animGo = self:GetSceneAnimationGo(animName)
    if animGo then
        animGo.gameObject:StopTimelineAnimation()
        animGo.gameObject:SetActiveEx(false)
    end
end

-- 播放生命树动画
function XUiLifeTreeMain:PlayLifeTreeAnimations()
    self:StopSceneAnimation("AnimEnable01")
    self:StopSceneAnimation("AnimEnable02")
    
    XLuaUiManager.SetMask(true)
    self:PlaySceneAnimation("AnimEnable03", function()
        XLuaUiManager.SetMask(false)
    end)
end

-- 播放意识海动画
function XUiLifeTreeMain:PlaySeaAnimations()
    self:StopSceneAnimation("AnimEnable01")
    self:StopSceneAnimation("AnimEnable03")

    XLuaUiManager.SetMask(true)
    self:PlaySceneAnimation("AnimEnable02", function()
        XLuaUiManager.SetMask(false)
    end)
end
--endregion

--region 摄像机
-- 设置摄像机X方向的输入
function XUiLifeTreeMain:SetCameraXInput(xInput)
    self.CamFarMain:SetXInput(xInput)
    --self.CamNearMain:SetXInput(xInput)
    self.CurXInput = xInput
end

-- 设置摄像机Y方向的输入
function XUiLifeTreeMain:SetCameraYInput(yInput)
    self.CamFarMain:SetYInput(yInput)
    self.CamNearMain:SetYInput(yInput)
    self.CurYInput = yInput
end

-- 设置摄像机X方向的值
function XUiLifeTreeMain:SetCameraXValue(value)
    self.CamFarMain:SetXValue(value)
    --self.CamNearMain:SetXValue(value)
end

-- 设置摄像机Y方向的值
function XUiLifeTreeMain:SetCameraYValue(value)
    self.CamFarMain:SetYValue(value)
    self.CamNearMain:SetYValue(value)
end

-- 检测处理镜头移动衰减
function XUiLifeTreeMain:CheckCameraMoveFade()
    if self.IsPlayCameraAnim then return end  -- 播生命树、意识海的摄像机切换动画时，不需要进行镜头移动衰减
    if not self.LastDragTime then return end
    if self.CurXInput == 0 and self.CurYInput == 0 then return end

    local curTime = CS.UnityEngine.Time.realtimeSinceStartup
    local fadeProgress = (curTime - self.LastDragTime) / CAMERA_FADE_TIME
    fadeProgress = EaseExpoOut(fadeProgress)
    if self.CurXInput ~= 0 then
        local xInput = Lerp(self.LastDragXInput, 0, fadeProgress)
        self:SetCameraXInput(xInput)
    end

    if self.CurYInput ~= 0 then
        local yInput = Lerp(self.LastDragYInput, 0, fadeProgress)
        self:SetCameraYInput(yInput)
    end
    self.IsCameraPosValueChange = true
end

-- 设置摄像机的X轴和Y轴的值，并通过动画逐渐切换到目标值
function XUiLifeTreeMain:SetCameraValueWithAnim(aimXValue, aimYValue)
    local curXValue = self.CamFarMain:GetXValue()
    local curYValue = self.CamFarMain:GetYValue()
    local startTime = CS.UnityEngine.Time.realtimeSinceStartup
    self:RemoveSetCameraValueTimer()
    self.IsPlayCameraAnim = true
    self.SetCameraValueTimer = XScheduleManager.ScheduleForever(function()
        local progress = (CS.UnityEngine.Time.realtimeSinceStartup - startTime) / CHANGE_CAMERA_VALUE_TIME
        progress = EaseQuadOut(progress)
        local xValue = Lerp(curXValue, aimXValue, progress)
        local yValue = Lerp(curYValue, aimYValue, progress)
        self:SetCameraXValue(xValue)
        self:SetCameraYValue(yValue)
        self.IsCameraPosValueChange = true
        if progress >= 1 then
            self:RemoveSetCameraValueTimer()
        end
    end, 0)
end

function XUiLifeTreeMain:RemoveSetCameraValueTimer()
    if self.SetCameraValueTimer then
        XScheduleManager.UnSchedule(self.SetCameraValueTimer)
        self.SetCameraValueTimer = nil
    end
    self.IsPlayCameraAnim = false
end

-- 摄像机位置值发生变化
function XUiLifeTreeMain:OnCameraPosValueChange()
    self:CheckSwitchState()
    self:CheckUpdateUiPointPos()
end

-- 检测切换状态
function XUiLifeTreeMain:CheckSwitchState()
    local yValue = self.CamFarMain:GetYValue()
    local isSea = yValue > CAMERA_Y_VALUE_SWITCH
    local isLifeTree = not isSea
    if self.State ~= STATE.SEA and isSea then
        self:OnSwitchSea()
    elseif self.State ~= STATE.LIFE_TREE and isLifeTree then
        self:OnSwitchLifeTree()
    end
end

-- 检测更新Ui点位位置
function XUiLifeTreeMain:CheckUpdateUiPointPos()
    for _, gridCard in pairs(self.GridCards) do
        gridCard:UpdatePosition()
    end
end

-- 播放场景动画
function XUiLifeTreeMain:PlayCameraAnimation(animName)
    local animGo = self.UiModelGo.transform:Find("Animation/" .. tostring(animName))
    if not animGo then
        XLog.Error("未找到镜头动画节点UiMain3dLifeTree(Clone)/Animation/" .. tostring(animName))
        return
    end
    animGo.gameObject:SetActiveEx(true)
    animGo.gameObject:PlayTimelineAnimation(function()
        animGo.gameObject:SetActiveEx(false)
    end)
end

-- 播放镜头推进动画
function XUiLifeTreeMain:PlayCameraZoomInAnimation(cb)
    if self.IsCameraZoomIn then return end

    self:ShowUi(false)
    self.CamFarMain.gameObject:SetActiveEx(false)
    self.LastFarCameraPosition = self.UiFarCamera.transform.position

    -- 隐藏摄像机
    self.UiNearCamera.gameObject:SetActiveEx(false)

    -- 界面压黑动画
    self:PlayAnimation("DarkDisable")

    -- 镜头推进动画
    local targetPosition = self.ZoomInPoint.transform.position -- 镜头推进目标位置
    self:StopCameraZoomInAnimation()
    self.UiFarCameraTweener = self.UiFarCamera.transform:DOMove(targetPosition, CAMERA_ZOOM_IN_TIME)
    :SetEase(CS.DG.Tweening.Ease.InCubic)
    :OnComplete(function()
        self.UiFarCameraTweener = nil
        self.IsCameraZoomIn = true
        if cb then cb() end
    end)
end

-- 播放镜头恢复动画动画
function XUiLifeTreeMain:PlayCameraResetAnimation(cb)
    if not self.IsCameraZoomIn then return end

    -- 界面黑色消退动画
    self:PlayAnimation("DarkEnable")

    -- 镜头推进动画
    self:StopCameraZoomInAnimation()
    self.UiFarCameraTweener = self.UiFarCamera.transform:DOMove(self.LastFarCameraPosition, CAMERA_ZOOM_IN_TIME)
    :SetEase(CS.DG.Tweening.Ease.OutCubic)
    :OnComplete(function()
        self.UiFarCameraTweener = nil
        self.IsCameraZoomIn = false
        self:ShowUi(true)
        self:CheckUpdateUiPointPos()
        self.CamFarMain.gameObject:SetActiveEx(true)

        -- 显示摄像机
        self.UiNearCamera.gameObject:SetActiveEx(true)
        if cb then cb() end
    end)
end

function XUiLifeTreeMain:StopCameraZoomInAnimation()
    if self.UiFarCameraTweener then
        self.UiFarCameraTweener:Kill()
        self.UiFarCameraTweener = nil
    end
end

--endregion

--region PanelCard
-- 初始化卡牌节点
function XUiLifeTreeMain:InitCards()
    self.GridDivineCard.gameObject:SetActiveEx(false)
    self.GridRegularCard.gameObject:SetActiveEx(false)

    -- 卡牌跟随的3D点位
    ---@type (XUiLifeTreeMainGridDivineCard|XUiLifeTreeMainGridRegularCard)[]
    self.GridCards = {}
    local sceneRoot = self.UiSceneInfo.Transform
    local sceneUi = sceneRoot:Find("GroupBase/Ui")
    local constellationConfigs = self._Control:GetLifeTreeConstellationConfigs()
    for constellationId, constellationConfig in pairs(constellationConfigs) do
        local catalogIds = constellationConfig.CharacterCatalogIds
        for _, catalogId in ipairs(catalogIds) do
            local catalogConfig = self._Control:GetLifeTreeCharacterCatalogConfigById(catalogId)
            local follow3DGo = sceneUi:Find(catalogConfig.SceneFollowPoint)
            if not follow3DGo then
                XLog.Error(string.format("UiMain3dLifeTree场景缺少节点GroupBase/Ui/%s", catalogConfig.SceneFollowPoint))
                goto CONTINUE
            end
            if catalogConfig.CardType == XMVCA.XLifeTree.EnumConst.CARD_TYPE.DIVINE then
                local go = CSInstantiate(self.GridDivineCard, self.PanelCard)
                self.GridCards[catalogId] = XUiLifeTreeMainGridDivineCard.New(go, self, constellationId, catalogId, follow3DGo)
            else
                local go = CSInstantiate(self.GridRegularCard, self.PanelCard)
                go.transform:SetAsFirstSibling()
                self.GridCards[catalogId] = XUiLifeTreeMainGridRegularCard.New(go, self, constellationId, catalogId, follow3DGo)
            end
            self.GridCards[catalogId]:Open()
            :: CONTINUE ::
        end
    end
end

-- 刷新场景星座列表状态
function XUiLifeTreeMain:RefreshSceneConstellations()
    for constellationId, go in pairs(self.SceneConstellationGoDic) do
        --local catalogId = self._Control:GetConstellationDivineCharacterCatalogId(constellationId) -- 神卡CatalogId
        --local isUnlock = self._Control:IsCharacterUnlock(catalogId)
        local isRed = XMVCA.XLifeTree:IsRedConstellation(constellationId)
        --go:Find("Lock").gameObject:SetActiveEx(not isUnlock)
        go:Find("Unlock").gameObject:SetActiveEx(not isRed)
        go:Find("EffectRed").gameObject:SetActiveEx(isRed)
    end
end

--endregion

return XUiLifeTreeMain
