--[[
-- XUiLifeTreeMainGridDivineCard.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-03-02 20:13:11
--]]

local XUiLifeTreeMainGridCard = require("XUi/XUiLifeTree/XUiLifeTreeMain/XUiLifeTreeMainGridCard")
---@class XUiLifeTreeMainGridDivineCard : XUiLifeTreeMainGridCard
---@field _Control XLifeTreeControl
---@field RImgHeadIcon UnityEngine.UI.RawImage
---@field Parent XUiLifeTreeMain
---@field Button XUiComponent.XUiButton
local XUiLifeTreeMainGridDivineCard = XClass(XUiLifeTreeMainGridCard, "XUiLifeTreeMainGridDivineCard")

function XUiLifeTreeMainGridDivineCard:OnStart(constellationId, catalogId, follow3DGo)
    self.ConstellationId = constellationId
    self.CatalogId = catalogId
    self.Follow3DGo = follow3DGo
    
    self:InitComponents()
end

function XUiLifeTreeMainGridDivineCard:OnEnable()
    self:Refresh()
end

function XUiLifeTreeMainGridDivineCard:OnDisable()
end

function XUiLifeTreeMainGridDivineCard:OnDestroy()
end

function XUiLifeTreeMainGridDivineCard:InitComponents()
    self.Button:AddEventListener(function() self:OnBtnButtonClick() end)
end

function XUiLifeTreeMainGridDivineCard:Refresh()
    self.ImgOffline.gameObject:SetActiveEx(false)
    self.ImgLocked.gameObject:SetActiveEx(false)
    self.ImgUnlockedPositive.gameObject:SetActiveEx(false)
    self.ImgUnlockedReverse.gameObject:SetActiveEx(false)
    self.UnlockEffect.gameObject:SetActiveEx(false)
    
    -- 角色状态
    local unlockCount, state = XMVCA.XLifeTree:GetCharacterStateByCatalogId(self.CatalogId) -- 解锁次数和状态
    local divineType = self._Control:GetCharacterDivineState(self.CatalogId) -- 当前神卡类型
    local isOffline = state == XMVCA.XLifeTree.EnumConst.CHARACTER_STATE.OFFLINE -- 是否未上线
    local isUnlockable = state == XMVCA.XLifeTree.EnumConst.CHARACTER_STATE.NEXT_UNLOCKABLE -- 是否可解锁下一状态

    -- 刷新UI
    local catalogConfig = self._Control:GetLifeTreeCharacterCatalogConfigById(self.CatalogId)
    if isOffline then
        self.ImgOffline.gameObject:SetActiveEx(true)
    elseif divineType == XMVCA.XLifeTree.EnumConst.DIVINE_TYPE.POSITIVE then
        self.ImgUnlockedPositive.gameObject:SetActiveEx(true)
        local icon = XMVCA.XCharacter:GetCharSmallHeadIcon(catalogConfig.CharacterId)
        self.ImgUnlockedPositive:GetObject("RImgHeadIcon"):SetRawImage(icon)
    elseif divineType == XMVCA.XLifeTree.EnumConst.DIVINE_TYPE.REVERSE then
        self.ImgUnlockedReverse.gameObject:SetActiveEx(true)
        local icon = XMVCA.XCharacter:GetCharSmallHeadIcon(catalogConfig.CharacterId)
        self.ImgUnlockedReverse:GetObject("RImgHeadIcon"):SetRawImage(icon)
    else
        self.ImgLocked.gameObject:SetActiveEx(true)
        local icon = XMVCA.XCharacter:GetCharSmallHeadIcon(catalogConfig.CharacterId)
        self.ImgLocked:GetObject("RImgHeadIcon"):SetRawImage(icon)
    end
    
    -- 可解锁特效
    self.UnlockEffect.gameObject:SetActiveEx(isUnlockable)

    -- 更新位置
    self:UpdatePosition()
end

function XUiLifeTreeMainGridDivineCard:OnBtnButtonClick()
    local catalogConfig = self._Control:GetLifeTreeCharacterCatalogConfigById(self.CatalogId)
    local characterId = catalogConfig.CharacterId

    -- 运营埋点
    local dict = {}
    dict["type"] = 3
    dict["character_id"] = characterId
    CS.XRecord.Record(dict, "1000042", "LifeTreeOperation")

    self.Parent:PlayCameraZoomInAnimation(function() 
        XLuaUiManager.Open("UiLifeTreeCard", self.ConstellationId)
    end)
end

return XUiLifeTreeMainGridDivineCard
