--[[
-- XUiLineArithmetic3Chapter.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-02-03 19:58:14
--]]

local XUiLineArithmetic3ChapterGridChapter = require("XUi/XUiLineArithmetic3/XUiLineArithmetic3Chapter/XUiLineArithmetic3ChapterGridChapter")

---@class XUiLineArithmetic3Chapter : XLuaUi
---@field _Control XLineArithmetic3Control
---@field BtnBack XUiButton
---@field BtnMainUi XUiButton
---@field Chapter1 UnityEngine.RectTransform
---@field Chapter2 UnityEngine.RectTransform
---@field Chapter3 UnityEngine.RectTransform
---@field Chapter4 UnityEngine.RectTransform
---@field Chapter5 UnityEngine.RectTransform
---@field Chapter6 UnityEngine.RectTransform
---@field Chapter7 UnityEngine.RectTransform
---@field GridChapter UnityEngine.RectTransform
---@field TxtStar UnityEngine.UI.Text
---@field BtnHelp UnityEngine.UI.Button
---@field ListBarrier UnityEngine.UI.ScrollRect
---@field TxtTitle UnityEngine.UI.Text
---@field Img01 UnityEngine.RectTransform
---@field Img02 UnityEngine.RectTransform
---@field Img03 UnityEngine.RectTransform
---@field Img04 UnityEngine.RectTransform
local XUiLineArithmetic3Chapter = XLuaUiManager.Register(XLuaUi, "UiLineArithmetic3Chapter")

function XUiLineArithmetic3Chapter:Ctor()
    ---@type XUiLineArithmetic3ChapterGridChapter[]
    self._GridChapters = {}
end

function XUiLineArithmetic3Chapter:OnAwake()
    self:BindExitBtns()
    self.GridChapter.gameObject:SetActiveEx(false)
    self:BindHelpBtn(self.BtnHelp, "LineArithmeticHelp")

    -- 隐藏默认背景
    local bgName = "Img01"
    local bg = XUiHelper.TryGetComponent(self.Transform, "FullScreenBackground/" .. bgName, "RectTransform")
    if bg then
        bg.gameObject:SetActiveEx(false)
    end
end

function XUiLineArithmetic3Chapter:OnStart(...)
end

function XUiLineArithmetic3Chapter:OnEnable()
    XEventManager.AddEventListener(XEventId.EVENT_LINE_ARITHMETIC_UPDATE_STAGE, self.Update, self)
    self:Update()
    self:UpdateTitle()

    local uiData = self._Control:GetUiData()
    if uiData.IsDefaultSelectDirty then
        self._Control:SetDefaultSelectDirty(false)
        local index = uiData.DefaultSelectStageIndex
        self:ScrollToCurrentGame(index)
    end

    self:PlayStageAnimation()
end

function XUiLineArithmetic3Chapter:OnDisable()
    XEventManager.RemoveEventListener(XEventId.EVENT_LINE_ARITHMETIC_UPDATE_STAGE, self.Update, self)
end

function XUiLineArithmetic3Chapter:OnDestroy()
end

--- 更新关卡列表
function XUiLineArithmetic3Chapter:Update()
    self._Control:UpdateStage()
    local uiData = self._Control:GetUiData()
    local stages = uiData.Stage
    for i = 1, #stages do
        ---@type XUiLineArithmetic3ChapterGridChapter
        local grid = self._GridChapters[i]
        if not grid then
            local parent = self["Chapter" .. i]
            if not parent then
                XLog.Error("[XUiLineArithmetic3Chapter] 章节节点不够了，加多个吧:", i)
                break
            end
            local ui = CS.UnityEngine.Object.Instantiate(self.GridChapter, parent.transform)
            ui.localPosition = Vector3.zero
            grid = XUiLineArithmetic3ChapterGridChapter.New(ui, self)
            self._GridChapters[i] = grid
        end
        grid:Open()
        grid:Update(stages[i])
    end
    for i = #stages + 1, #self._GridChapters do
        local grid = self._GridChapters[i]
        grid:Close()
    end

    -- 根据当前章节序号显示/隐藏装饰节点
    self:_UpdateDecorationNodes(uiData.CurrentChapterIndex or 1)

    local bgName = uiData.ChapterBg
    local bg = XUiHelper.TryGetComponent(self.Transform, "FullScreenBackground/" .. bgName, "RectTransform")
    if bg then
        bg.gameObject:SetActiveEx(true)
    end

    -- 根据关卡数量控制content长度
    ---@type UnityEngine.Rect
    local rect = self.ListBarrier.content.transform
    if #stages < 7 then
        rect:SetSizeWithCurrentAnchors(CS.UnityEngine.RectTransform.Axis.Horizontal, 2900)
    end
end

--- 根据当前章节序号显示/隐藏装饰节点（PanelChapter0X 和 GridChapter0X）
---@param chapterIndex number 当前章节在所有章节中的序号
function XUiLineArithmetic3Chapter:_UpdateDecorationNodes(chapterIndex)
    local i = 1
    while true do
        local indexStr = string.format("%02d", i)
        local panel = self["PanelChapter" .. indexStr]
        local gridDecor = self["GridChapter" .. indexStr]
        if not panel and not gridDecor then
            break
        end
        local show = i == chapterIndex
        if panel then
            panel.gameObject:SetActiveEx(show)
        end
        if gridDecor then
            gridDecor.gameObject:SetActiveEx(show)
        end
        i = i + 1
    end
end

--- 滚动到当前关卡
---@param index number 关卡索引
function XUiLineArithmetic3Chapter:ScrollToCurrentGame(index)
    if not index then
        return
    end
    local grid = self._GridChapters[index]
    if grid then
        ---@type UnityEngine.UI.ScrollRect
        local listChapter = self.ListBarrier
        local worldPosition = grid.Transform:TransformPoint(Vector3.zero)
        local localPosition = listChapter.content.transform:InverseTransformPoint(worldPosition)
        local contentWidth = listChapter.content.transform.rect.width - listChapter.transform.rect.width
        local value = (localPosition.x - listChapter.transform.rect.width / 2) / contentWidth
        value = CS.UnityEngine.Mathf.Clamp(value, 0, 1)
        listChapter.horizontalNormalizedPosition = value
    end
end

--- 更新章节标题
function XUiLineArithmetic3Chapter:UpdateTitle()
    self._Control:UpdateChapterTitle()
    local uiData = self._Control:GetUiData()
    self.TxtTitle.text = uiData.CurrentChapterName
    self.TxtStar.text = uiData.CurrentChapterStar
end

--- 播放关卡动画
function XUiLineArithmetic3Chapter:PlayStageAnimation()
    local grids = self._GridChapters
    for i = 1, #grids do
        local grid = grids[i]
        if grid:IsNodeShow() then
            grid:Close()
            local timer
            timer = XScheduleManager.ScheduleOnce(function()
                grid:Open()
                grid:PlayAnimation("GridChapterEnable")
                self:_RemoveTimerIdAndDoCallback(timer)
            end, 100 * (i - 1))
            self:_AddTimerId(timer)
        end
    end
end

return XUiLineArithmetic3Chapter
