--[[
-- XUiFashionSuitPopupNewPanelInfo.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-02-04 10:24:51
--]]

--[[
-- XUiFashionSuitPopupNewPanelInfo.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-02-04 10:24:51
--]]

local XUiGridCommon = require("XUi/XUiObtain/XUiGridCommon")
---@class XUiFashionSuitPopupNewPanelInfo : XUiNode
local XUiFashionSuitPopupNewPanelInfo = XClass(XUiNode, "XUiFashionSuitPopupNewPanelInfo")
---@field UiRImgIcon UnityEngine.UI.RawImage
---@field UiTxtSeriesName UnityEngine.UI.Text
---@field UiTxtSkinName UnityEngine.UI.Text
---@field UiTxtCharacterName UnityEngine.UI.Text
---@field Grid256New UiObject
---@field TxtTips UnityEngine.UI.Text

function XUiFashionSuitPopupNewPanelInfo:OnAwake()
end

function XUiFashionSuitPopupNewPanelInfo:InitComponents()
end

function XUiFashionSuitPopupNewPanelInfo:OnStart(...)
    self:InitComponents()
    self.Grid256New.gameObject:SetActiveEx(false)
end

function XUiFashionSuitPopupNewPanelInfo:OnEnable()
end

function XUiFashionSuitPopupNewPanelInfo:OnDisable()
end

function XUiFashionSuitPopupNewPanelInfo:OnDestroy()
end

function XUiFashionSuitPopupNewPanelInfo:Refresh(fashionId)
    local fashionConfig = XFashionConfigs.GetFashionTemplate(fashionId)
    
    self._FashionSuitId = XMVCA.XFashionSuit:GetFashionSuitId(fashionId)
    local suitConfig = self._Control:GetFashionSuitById(self._FashionSuitId)
    local characterName = XMVCA.XCharacter:GetCharacterTemplate(fashionConfig.CharacterId).Name
    self.UiRImgIcon:SetRawImage(suitConfig.SuitLogo)
    self.UiTxtSeriesName.text = suitConfig.Name
    self.UiTxtSkinName.text = fashionConfig.Name
    self.UiTxtCharacterName.text = characterName
    self.PanelReward.gameObject:SetActiveEx(suitConfig.IsComplete)
    if suitConfig.IsComplete then
        self:UpdateReward()
    end
end

function XUiFashionSuitPopupNewPanelInfo:UpdateReward()
    self.RewardPanelList = self.RewardPanelList or {}
    for i = 1, #self.RewardPanelList do
        self.RewardPanelList[i].GameObject:SetActiveEx(false)
    end
    local temp = {
        ShowReceived = self._Control:IsSuitRewardGain(self._FashionSuitId)
    }
    local suitConfig = self._Control:GetFashionSuitById(self._FashionSuitId)
    local rewardsList = XRewardManager.GetRewardList(suitConfig.RewardId)
    for i = 1, #rewardsList do
        if not self.RewardPanelList[i] then
            local grid = XUiHelper.Instantiate(self.Grid256New, self.Grid256New.transform.parent)
            local item = XUiGridCommon.New(self, grid)
            table.insert(self.RewardPanelList, item)
        end
        local gridUi = self.RewardPanelList[i]
        gridUi.GameObject:SetActiveEx(true)
        gridUi:Refresh(rewardsList[i], temp)
    end
end
function XUiFashionSuitPopupNewPanelInfo:SetUiSprite(imgQuality, spriteName)
    imgQuality:SetSprite(spriteName)
end
return XUiFashionSuitPopupNewPanelInfo
