--[[
-- XUiLuckyTenant2TaskGridTask.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2025-12-31 16:39:52
--]]

---@class XUiLuckyTenant2TaskGridTask : XUiNode
local XUiLuckyTenant2TaskGridTask = XClass(XUiNode, "XUiLuckyTenant2TaskGridTask")

function XUiLuckyTenant2TaskGridTask:OnAwake()
    self:InitComponents()
end

function XUiLuckyTenant2TaskGridTask:InitComponents()
end

function XUiLuckyTenant2TaskGridTask:OnStart(...)
    self:Update()
end

function XUiLuckyTenant2TaskGridTask:OnEnable()
end

function XUiLuckyTenant2TaskGridTask:OnDisable()
end

function XUiLuckyTenant2TaskGridTask:OnDestroy()
end

function XUiLuckyTenant2TaskGridTask:Update()
end

return XUiLuckyTenant2TaskGridTask
