--[[
-- XUiPBRGenius.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-02-03 09:35:52
--]]


local XUiPBRGeniusPanelGeniusList = require("XUi/XUiPBRGame/XUiPBRGenius/NodeList/XUiPBRGeniusPanelGeniusList")
local XUiPBRGeniusPanelGeniusDetail = require("XUi/XUiPBRGame/XUiPBRGenius/DetailPanel/XUiPBRGeniusPanelGeniusDetail")
local XUiPBRGeniusItemPopupPanelDetail = require('XUi/XUiPBRGame/XUiPBRGenius/DetailPanel/XUiPBRGeniusItemPopupPanelDetail')

---@class XUiPBRGenius : XLuaUi
---@field _Control XPBRGameControl
---@field BtnBack XUiButton
---@field BtnMainUi XUiButton
---@field PanelSpecialTool UnityEngine.RectTransform
---@field PanelGeniusList UnityEngine.RectTransform
---@field PanelGeniusDetail UnityEngine.RectTransform
---@field UiPBRPanelDetail UnityEngine.RectTransform
local XUiPBRGenius = XLuaUiManager.Register(XLuaUi, "UiPBRGenius")

function XUiPBRGenius:OnAwake()
    self:InitComponents()
end

function XUiPBRGenius:InitComponents()
    -- Back Mainui Help
    self:BindExitBtns()

    ---@type XUiPBRGeniusPanelGeniusDetail
    self.PanelGeniusDetail = XUiPBRGeniusPanelGeniusDetail.New(self.PanelGeniusDetail, self)
    ---@type XUiPBRGeniusPanelGeniusList
    self.PanelGeniusList = XUiPBRGeniusPanelGeniusList.New(self.PanelGeniusList, self)

    self.AssetActivityPanel = XUiHelper.NewPanelActivityAssetSafe(self._Control:GetClientPBRNumberArray('PanelAssetItems'), self.PanelSpecialTool, self)

    self.UiPBRPanelDetail.gameObject:SetActiveEx(false)
    ---@type XUiPBRGeniusItemPopupPanelDetail
    self.ItemDetailPanel = XUiPBRGeniusItemPopupPanelDetail.New(self.UiPBRPanelDetail, self)
end

function XUiPBRGenius:OnStart(...)
    self:Refresh()
    self._StartRun = true
end

function XUiPBRGenius:OnEnable()
    self._Control:AddEventListener(XMVCA.XPBRGame.EventId.EVENT_PBR_INNER_OPEN_GENIUS_DETAIL, self.OnDetailShow, self)
    self._Control:AddEventListener(XMVCA.XPBRGame.EventId.EVENT_PBR_INNER_OPEN_ITEM_DETAIL, self.OnItemDetailOpenEvent, self)

    if self._StartRun then
        -- 默认选中
        local nodeId = self._Control.GeniusControl:GetDefaultSelectNodeId()

        self.PanelGeniusList:SelectByNodeId(nodeId)

        self._StartRun = false
    end
end

function XUiPBRGenius:OnDisable()
    self._Control:RemoveEventListener(XMVCA.XPBRGame.EventId.EVENT_PBR_INNER_OPEN_GENIUS_DETAIL, self.OnDetailShow, self)
    self._Control:RemoveEventListener(XMVCA.XPBRGame.EventId.EVENT_PBR_INNER_OPEN_ITEM_DETAIL, self.OnItemDetailOpenEvent, self)
end

function XUiPBRGenius:OnDestroy()
end

function XUiPBRGenius:Refresh()
    self.PanelGeniusList:Refresh()
end

function XUiPBRGenius:OnDetailShow(nodeId)
    self.PanelGeniusDetail:Refresh(nodeId)
end

function XUiPBRGenius:OnItemDetailOpenEvent(posUi, itemId)
    self.ItemDetailPanel:Open()
    self.ItemDetailPanel:RefreshItemShow(posUi, itemId)
end

return XUiPBRGenius
