--[[
-- XUiLuckyTenant2Game.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2025-12-31 16:39:51
--]]

local XUiLuckyTenant2GamePanelTipsnew = require(
    "XUi/XUiLuckyTenant2/XUiLuckyTenant2Game/XUiLuckyTenant2GamePanelTipsnew")
local XUiLuckyTenant2GameGridChess = require("XUi/XUiLuckyTenant2/XUiLuckyTenant2Game/XUiLuckyTenant2GameGridChess")
local XUiLuckyTenant2GameGridRound = require("XUi/XUiLuckyTenant2/XUiLuckyTenant2Game/XUiLuckyTenant2GameGridRound")
local XUiLuckyTenant2GamePanelChess = require("XUi/XUiLuckyTenant2/XUiLuckyTenant2Game/XUiLuckyTenant2GamePanelChess")
local XUiLuckyTenant2GameAnimationGetScore = require(
    "XUi/XUiLuckyTenant2/XUiLuckyTenant2Game/XUiLuckyTenant2GameAnimationGetScore")
local XUiLuckyTenant2GameAnimationGetItem = require(
    "XUi/XUiLuckyTenant2/XUiLuckyTenant2Game/XUiLuckyTenant2GameAnimationGetItem")
local XUiLuckyTenant2GameUiLuckyTenant2Bonds = require(
    "XUi/XUiLuckyTenant2/XUiLuckyTenant2Game/XUiLuckyTenant2GameUiLuckyTenant2Bonds")
local XUiLuckyTenant2GameUiLuckyTenant2ChessDetail = require(
    "XUi/XUiLuckyTenant2/XUiLuckyTenant2Game/XUiLuckyTenant2GameUiLuckyTenant2ChessDetail")
local XUiLuckyTenant2PropDisplay = require("XUi/XUiLuckyTenant2/XUiLuckyTenant2PropDisplay")
local XLuckyTenant2Enum = require("XModule/XLuckyTenant2/Game/XLuckyTenant2Enum")
local GameState = XLuckyTenant2Enum.GameState
local XTool = XTool

---@class XUiLuckyTenant2Game : XLuaUi
---@field _Control XLuckyTenant2Control
local XUiLuckyTenant2Game = XLuaUiManager.Register(XLuaUi, "UiLuckyTenant2Game")

function XUiLuckyTenant2Game:Ctor()
    self._Timer = false
    ---@type XUiLuckyTenant2GameGridChess[]
    self._Grids = {}
    ---@type XUiLuckyTenant2GameGridRound[]
    self._GridRounds = {}
    ---@type XUiLuckyTenant2GameAnimationGetScore[]
    self._AnimationGetScore = {}
    ---@type XUiLuckyTenant2GameAnimationGetItem[]
    self._AnimationGetItem = {}

    self._State = 0
    self._TimerNextState = false
    self._TimerAddScore = false
    ---@type table 当前道具列表（刷新/删除道具，由 XUiLuckyTenant2PropDisplay 填充）
    self._QuestReward = {}
    self._StageId = 0
    if self.PropReward then
        self.PropReward.gameObject:SetActiveEx(false)
    end
    self._Seed = 0
    self._IsFirstTimeEntering = false

    self._IsPause = false
    self._IsCancelNextState = false

    self._IsSpeedUp = false
    self._TimeScaleSpeedUp = 5
    self._TimerRoll = false
    self._IsCheckGuide = false

    -- 分数动画相关
    self._PieceScoreAnimations = {}            -- 待播放的棋子分数动画列表 {x, y, value}
    self._PieceScoreAnimationIndex = 0         -- 当前播放的动画索引
    self._IsPlayingPieceScoreAnimation = false -- 是否正在播放分数动画
    self._AccumulatedScoreForAnimation = 0     -- 动画过程中的累计分数
    self._BaseScoreForAnimation = 0            -- 动画开始前的基准分数
    self._AnimationLevelLastTriggered = 0      -- 飘字动画已触发的最高等级（1/2/3），仅等级2/3时播放TxtTargetScoreEnable
    self._FxLoop02Timer = nil                  -- 等级3特效 FxUiLuckyTenant202Loop02 的隐藏定时器
    -- 动画等级系数缓存（LuckyTenant2AnimationLevel1/2/3），惰性读取 ClientConfig 后复用
    self._CachedAnimLevel1 = nil
    self._CachedAnimLevel2 = nil
    self._CachedAnimLevel3 = nil
end

function XUiLuckyTenant2Game:OnAwake()
    XMVCA.XLuckyTenant2:SetPlaying(true)

    self.BtnBack:AddEventListener(function() self:OnBtnBackClick() end)
    self:BindHelpBtn(nil, self._Control:GetUiData().HelpKey)

    XUiHelper.RegisterClickEvent(self, self.BtnArrange, self.OnClickNextRound, nil, true)
    if self.BtnBag then
        XUiHelper.RegisterClickEvent(self, self.BtnBag, self.OnClickBag, nil, true)
    end
    XUiHelper.RegisterClickEvent(self, self.BtnTanchuangCloseBig, self.ClosePanelTips, nil, true)

    if self.AnimationGetScore then
        self.AnimationGetScore.gameObject:SetActiveEx(false)
        if self.AnimationGetItem then
            self.AnimationGetItem.gameObject:SetActiveEx(false)
        end
    end
    if self.TxtAddScore then
        self.TxtAddScore.gameObject:SetActiveEx(false)
    end

    if self.BtnSpeedUp then
        XUiHelper.RegisterClickEvent(self, self.BtnSpeedUp, self.OnClickSpeedUp, nil, true)
        local isOn = XSaveTool.GetData("LuckyTenant2SpeedUp")
        if isOn then
            self.BtnSpeedUp:SetButtonState(CS.UiButtonState.Select)
        else
            self.BtnSpeedUp:SetButtonState(CS.UiButtonState.Normal)
        end
        self._IsSpeedUp = isOn
    end

    if self.UiLuckyTenant2ChessDetail then
        self.UiLuckyTenant2ChessDetail.gameObject:SetActiveEx(false)
        ---@type XUiLuckyTenant2GameUiLuckyTenant2ChessDetail
        self._Detail = XUiLuckyTenant2GameUiLuckyTenant2ChessDetail.New(self.UiLuckyTenant2ChessDetail, self)
        self._Detail:Close()
    end

    if self.UiLuckyTenant2Bonds then
        ---@type XUiLuckyTenant2GameUiLuckyTenant2Bonds
        self._Bonds = XUiLuckyTenant2GameUiLuckyTenant2Bonds.New(self.UiLuckyTenant2Bonds, self)
    end

    self:ClosePanelTips()

    --[[
        特效和动画逻辑
        动画等级 = 本回合得分 >= 本阶段得分/本阶段（quest）回合数量 * 系数
        等级1=90%，等级2=110%，等级3=130%
        当飘字后得分达到等级时：等级1播放Shake1，等级2播放Shake2，等级3播放Shake3；等级2和3另播放TxtTargetScoreEnable；等级3另显示 FxUiLuckyTenant202Loop02
        FxUiLuckyTenant202Loop03：本回合分数进度条超出上限（当前分数>=阶段目标）时显示
        有棋子出生在GridChess时播放ChessBorn
    --]]
    self.FxUiLuckyTenant202Loop02 = self.FxUiLuckyTenant202Loop02 or self.ImgBarScore.transform:Find("FxUiLuckyTenant202Loop02")
    self.FxUiLuckyTenant202Loop03 = self.FxUiLuckyTenant202Loop03 or self.ImgBarScore.transform:Find("FxUiLuckyTenant202Loop03")
    if self.FxUiLuckyTenant202Loop02 then
        self.FxUiLuckyTenant202Loop02.gameObject:SetActiveEx(false)
    end
    if self.FxUiLuckyTenant202Loop03 then
        self.FxUiLuckyTenant202Loop03.gameObject:SetActiveEx(false)
    end
end

function XUiLuckyTenant2Game:OnStart(stageId, seed, isFirstTimeEntering, record)
    self._StageId = stageId or 101
    self._Seed = seed or XTime.GetServerNowTimestamp()
    if isFirstTimeEntering == nil then
        isFirstTimeEntering = true
    end
    self._IsFirstTimeEntering = isFirstTimeEntering
    self:StartGame(record)
end

function XUiLuckyTenant2Game:OnEnable()
    if not self._IsCheckGuide then
        local isGuide = XDataCenter.GuideManager.CheckGuideOpen()
        self:CheckGuide(isGuide)
        self._IsCheckGuide = true
    end

    if self._IsPause then
        --指引暂停时， 也得先刷新一次界面
        self:UpdateUi()
    else
        self:Update()
    end

    -- 刷新羁绊等级（重新计算所有羁绊的等级，从选棋界面返回时需要刷新）
    self._Control:RefreshBondLevels()

    -- 刷新羁绊列表（从选棋界面返回时，羁绊等级可能已改变）
    self._Control:UpdateBonds()
    self:UpdateBonds()

    self._Timer = XScheduleManager.ScheduleForever(function()
        self:Update()
    end, 0)

    -- 监听任务成功弹窗关闭事件
    XEventManager.AddEventListener(XEventId.EVENT_LUCKY_TENANT2_QUEST_SUCCESS_POPUP_CLOSE, self.OnQuestSuccessPopupClose, self)

    -- 显示下一个Toast
    self._Control:ShowNextToast()
end

function XUiLuckyTenant2Game:CheckGuide(isGuide)
    -- 指引中, 暂停游戏
    if isGuide or XDataCenter.GuideManager.CheckIsInGuide() then
        self:_OnGuideEvent(0)
    end
end

function XUiLuckyTenant2Game:OnDisable()
    XScheduleManager.UnSchedule(self._Timer)
    self._Timer = false

    -- 回收等级3特效定时器并隐藏
    if self._FxLoop02Timer then
        XScheduleManager.UnSchedule(self._FxLoop02Timer)
        self._FxLoop02Timer = nil
    end
    if self.FxUiLuckyTenant202Loop02 and self.FxUiLuckyTenant202Loop02.gameObject then
        self.FxUiLuckyTenant202Loop02.gameObject:SetActiveEx(false)
    end

    -- 注销任务成功弹窗关闭事件
    XEventManager.RemoveEventListener(XEventId.EVENT_LUCKY_TENANT2_QUEST_SUCCESS_POPUP_CLOSE, self.OnQuestSuccessPopupClose, self)
end

---任务成功弹窗关闭事件处理
function XUiLuckyTenant2Game:OnQuestSuccessPopupClose()
    if self._Control then
        self._Control:NextGameState()
        -- 强制刷新UI信息，确保分数进度条和目标分数显示为下一个quest的数值
        self._Control:SetUiDataDirty(true)
        self:UpdateInfo()
    end
end

function XUiLuckyTenant2Game:OnDestroy()
    XMVCA.XLuckyTenant2:SetPlaying(false)

    CS.UnityEngine.Time.timeScale = 1
    if self._Control then
        self._Control:ClearGame()
    end
    XMVCA.XLuckyTenant2:ClearAfterLeavingTheGame()
    if XLuaUiManager.IsMaskShow("LuckyTenant2") then
        XLuaUiManager.SetMask(false, "LuckyTenant2")
    end
end

function XUiLuckyTenant2Game:SetUiDirtyAndUpdate()
    if self._Control then
        self._Control:SetUiDataDirty(true)
        self:UpdateUi()
    end
end

function XUiLuckyTenant2Game:UpdateUi()
    if not self._Control then
        return
    end

    local uiData = self._Control:GetUiData()
    if uiData.IsDirty then
        -- 先调用 Control 层的 UpdateInfo 来更新数据（包括 TotalRound）
        self._Control:UpdateInfo()
        self:UpdateInfo()
        uiData.IsDirty = false
        -- 仅在数据脏时更新棋盘，避免每帧都刷新
        self:UpdateChessboard()
    else
        -- 即使 IsDirty 为 false，也需要更新羁绊列表（因为从选棋界面返回时，羁绊等级可能已改变）
        self._Control:UpdateBonds()
        self:UpdateBonds()
    end
end

function XUiLuckyTenant2Game:Update()
    if self._IsPause then
        self:UpdateAnimation()
        return
    end
    -- 请求中，不进行下一步
    if XMVCA.XLuckyTenant2:IsRequesting() then
        self:UpdateAnimation()
        return
    end

    if not self._Control then
        return
    end

    local uiData = self._Control:GetUiData()
    self:UpdateUi()

    local gameState = uiData.GameState
    if self._State ~= gameState then
        self._State = gameState
        self:HandleStateAction()
    end
    self:UpdateAnimation()
end

function XUiLuckyTenant2Game:UpdateAnimation()
    if self._State == GameState.Animation then
        if not self._Control then
            return
        end

        local uiData = self._Control:GetUiData()
        local animationGroups = uiData.AnimationGroups
        -- 动画态但没有动画组时，仍需要先刷新倒计时并刷新棋盘
        if uiData.ChessboardSnapshot and not uiData.IsRoundCountdownApplied then
            self._Control:ApplyRoundCountdownForAnimation()
            self._Control:UpdateChessboard()
            self:UpdateChessboard()
        end
        if animationGroups and #animationGroups > 0 then
            -- 单回合内同一格子同类型特效只播一次：仅在回合开始时（动画组从无到有）清空记录
            local groupCount = #animationGroups
            if groupCount > 0 and (not self._LastAnimationGroupCount or self._LastAnimationGroupCount == 0) then
                self._GridEffectPlayedInGroup = {}
            end
            self._LastAnimationGroupCount = groupCount

            -- 动画开始时，先对倒计时做一次-1刷新（只会生效一次）
            if self._Control then
                self._Control:ApplyRoundCountdownForAnimation()
            end
            local animationGroup = animationGroups[1]
            if animationGroup then
                -- 检查是否是第一个动画组的第一次更新（需要立即刷新棋盘）
                local wasWaiting = animationGroup._State == "waiting"

                -- 使用 Time.deltaTime 更新动画（转换为秒）
                local deltaTime = CS.UnityEngine.Time.deltaTime
                local isFinish = animationGroup:Update(deltaTime)

                -- 如果从 waiting 状态转为 playing 状态，标记需要刷新棋盘并播放动画
                if wasWaiting and animationGroup._State == "playing" then
                    -- 播放该动画组的动画（单回合内同格同类型特效不重复，由 _GridEffectPlayedInGroup 在回合开始时清空保证）
                    animationGroup:PlayAnimations(self)
                    -- 立即刷新一次棋盘
                    if self._Control then
                        self._Control:ApplyRoundCountdownForAnimation()
                        self._Control:UpdateChessboard()
                        self:UpdateChessboard()
                    end
                    self._ChessboardDirty = true
                end

                if isFinish then
                    -- 动画组完成，移除它
                    table.remove(animationGroups, 1)

                    -- 如果还有下一个动画组，标记需要刷新棋盘（为下一个技能做准备）
                    if #animationGroups > 0 then
                        self._ChessboardDirty = true
                    end
                end
            end
        end

        -- 统一刷新棋盘（如果标记为脏）
        if self._ChessboardDirty then
            self._Control:UpdateChessboard()
            self:UpdateChessboard()
            self._ChessboardDirty = false
        end

        -- 检查是否所有动画组都已完成
        local animationGroupsCount = animationGroups and #animationGroups or 0
        if animationGroupsCount == 0 then
            self._LastAnimationGroupCount = 0 -- 回合结束，下次有动画组时再清空 _GridEffectPlayedInGroup
            -- 如果还没有开始播放分数动画，先同步棋盘到最终状态，再播分数飞字（避免先飞分再刷棋盘的错误顺序）
            if not self._IsPlayingPieceScoreAnimation then
                -- 清除快照，让棋盘使用真实数据（新棋子出现、旧棋子移除），再刷新 UI
                self._Control._UiData.ChessboardSnapshot = nil
                self._Control:UpdateUiData(true)
                self:UpdateChessboard()
                self:StartPieceScoreAnimation()
                -- else
                -- 如果正在播放分数动画，检查是否完成（在 PlayNextPieceScoreAnimation 的回调中处理）
            end
        end
    end
end

function XUiLuckyTenant2Game:HandleStateAction()
    if not self._Control then
        return
    end

    if self._State == GameState.ShowQuestGoalsOnFirstRound then
        if not XLuaUiManager.IsMaskShow("LuckyTenant2") then
            XLuaUiManager.SetMask(true, "LuckyTenant2")
        end
        self._TimerNextState = XScheduleManager.ScheduleForever(function()
            if self._IsPause then
                return
            end
            XScheduleManager.UnSchedule(self._TimerNextState)
            self._TimerNextState = false
            self._Control:NextGameState()
        end, 1000)
        return
    end

    if self._State == GameState.SelectPiece then
        if self.PanelTaskFinish then
            self.PanelTaskFinish.gameObject:SetActiveEx(false)
        end
        if XLuaUiManager.IsMaskShow("LuckyTenant2") then
            XLuaUiManager.SetMask(false, "LuckyTenant2")
        end
        self._Control:StartSelectPiece()
        return
    end

    if self._State == GameState.CheckQuestCompletionStatus then
        self._TimerNextState = XScheduleManager.ScheduleForever(function()
            if self._IsPause then
                return
            end
            XScheduleManager.UnSchedule(self._TimerNextState)
            self._TimerNextState = false
            self._Control:NextGameState()
        end, 1000)
        return
    end

    if self._State == GameState.ShowNextQuestGoals then
        -- 打开目标达成弹窗
        -- 关闭mask，让弹窗可以点击
        if XLuaUiManager.IsMaskShow("LuckyTenant2") then
            XLuaUiManager.SetMask(false, "LuckyTenant2")
        end

        local game = self._Control._Game
        if game then
            local currentScore = game:GetTotalScore()
            -- 获取刚完成的任务（当前任务），而不是下一个任务
            local currentQuest = game:GetCurrentQuest()
            if currentQuest then
                -- 准备 quest 数据（包括奖励）
                local questData = self._Control:PrepareQuestSuccessData(currentQuest, currentScore)
                XLuaUiManager.Open("UiLuckyTenant2PopupSuccess", questData)
            else
                -- 如果没有当前任务，直接推进状态
                self._Control:NextGameState()
            end
        end
        return
    end

    if self._State == GameState.GameOver then
        if XLuaUiManager.IsMaskShow("LuckyTenant2") then
            XLuaUiManager.SetMask(false, "LuckyTenant2")
        end
        self._Control:OnStagePassed()
        XLuaUiManager.Open("UiLuckyTenant2Settlement")
        return
    end

    if self._State == GameState.NormalClear then
        if XLuaUiManager.IsMaskShow("LuckyTenant2") then
            XLuaUiManager.SetMask(false, "LuckyTenant2")
        end
        self._Control:OnStagePassed()
        XLuaUiManager.Open("UiLuckyTenant2Settlement")
        return
    end

    if self._State == GameState.PerfectClear then
        if XLuaUiManager.IsMaskShow("LuckyTenant2") then
            XLuaUiManager.SetMask(false, "LuckyTenant2")
        end
        self._Control:OnStagePassed()
        XLuaUiManager.Open("UiLuckyTenant2Settlement")
        return
    end

    if self._State == GameState.Animation then
        if not XLuaUiManager.IsMaskShow("LuckyTenant2") then
            XLuaUiManager.SetMask(true, "LuckyTenant2")
        end
        self:PlayAnimation("BtnArrangePress")
        if self._IsSpeedUp then
            local timeScale = self._TimeScaleSpeedUp
            CS.UnityEngine.Time.timeScale = timeScale
        end
        return
    end
end

function XUiLuckyTenant2Game:SetScore(value)
    if self.TxtNumScore then
        self.TxtNumScore.text = tostring(value)
    end
    self._LastScoreForTxtTargetScoreEnable = value
end

---动画等级：本回合得分 >= 本阶段得分/本阶段（quest）回合数 * 系数
---等级1=90%，等级2=110%，等级3=130%；仅等级2和3时播放 TxtTargetScoreEnable
---@param scoreThisRound number 本回合累计得分
---@return number 0/1/2/3，0 表示未达等级1
function XUiLuckyTenant2Game:GetAnimationLevel(scoreThisRound)
    if not self._Control then
        return 0
    end
    local game = self._Control:GetGame()
    if not game then
        return 0
    end
    local quest = game:GetCurrentQuest()
    if not quest or not quest.Round or quest.Round <= 0 then
        return 0
    end
    local targetScore = quest.Score or 0
    local questRounds = quest.Round
    -- 直接缓存 3 个配置值，首次读取后复用
    if self._CachedAnimLevel1 == nil then
        self._CachedAnimLevel1 = CS.XGame.ClientConfig:GetInt("LuckyTenant2AnimationLevel1") or 90
        self._CachedAnimLevel2 = CS.XGame.ClientConfig:GetInt("LuckyTenant2AnimationLevel2") or 110
        self._CachedAnimLevel3 = CS.XGame.ClientConfig:GetInt("LuckyTenant2AnimationLevel3") or 130
    end
    local threshold1 = targetScore / questRounds * self._CachedAnimLevel1 / 100
    local threshold2 = targetScore / questRounds * self._CachedAnimLevel2 / 100
    local threshold3 = targetScore / questRounds * self._CachedAnimLevel3 / 100
    if scoreThisRound >= threshold3 then
        return 3
    end
    if scoreThisRound >= threshold2 then
        return 2
    end
    if scoreThisRound >= threshold1 then
        return 1
    end
    return 0
end

---TxtTargetScoreEnable 动画：先 stop 再播放一次（在飘字达到动画等级2或3时调用）
function XUiLuckyTenant2Game:PlayTxtTargetScoreEnableAnimation()
    self:StopAnimation("TxtTargetScoreEnable")
    self:PlayAnimation("TxtTargetScoreEnable")
end

function XUiLuckyTenant2Game:SetAddScore(value)
    if not self.TxtAddScore then
        return
    end

    if value > 0 then
        self.TxtAddScore.text = value
        self.TxtAddScore.gameObject:SetActiveEx(true)
        if self._TimerAddScore then
            XScheduleManager.UnSchedule(self._TimerAddScore)
        end
        self._TimerAddScore = XScheduleManager.ScheduleOnce(function()
            self.TxtAddScore.gameObject:SetActiveEx(false)
            self._TimerAddScore = false
        end, 3000)
    end
end

function XUiLuckyTenant2Game:SetDeleteCoin(value)
    if self.TxtNumDeleteCoin then
        self.TxtNumDeleteCoin.text = tostring(value or 0)
    end
end

function XUiLuckyTenant2Game:SetRefreshCoin(value)
    if self.TxtNumRefreshCoin then
        self.TxtNumRefreshCoin.text = tostring(value or 0)
    end
end

function XUiLuckyTenant2Game:GetUiData()
    if not self._Control then
        return nil
    end
    local data = self._Control:GetUiData()
    return data
end

function XUiLuckyTenant2Game:UpdateInfo()
    if not self._Control then
        return
    end

    local data = self:GetUiData()
    if not data then
        return
    end

    self:SetScore(data.Score)
    self:SetAddScore(data.AddScore)
    self:SetDeleteCoin(data.DeleteCoin)
    self:SetRefreshCoin(data.RefreshCoin)

    if self.TxtTaskOrder then
        self.TxtTaskOrder.text = data.QuestCompletedAmount .. "/" .. data.QuestTotalAmount
    end
    if self.TxtNumRound then
        self.TxtNumRound.text = tostring(data.Round)
    end
    if self.TxtTask then
        self.TxtTask.text = XUiHelper.ReplaceTextNewLine(data.QuestDesc)
    end
    -- 统一计算总回合数和当前回合数（用于多个UI元素）
    local currentRound = data.Round or 0
    local totalRound = data.TotalRound or 0
    -- 显示的总回合数最小为 1（TotalRound 在 Control 层已经处理过 quest 上限限制）
    local displayTotalRound = math.max(1, totalRound)
    local lastTargetQuest = self._Control:GetLastTargetQuest()
    local lastTargetQuestRound = lastTargetQuest and lastTargetQuest.Round or 0

    -- 更新当前回合数显示
    if self.TxtTotalTimes then
        currentRound = math.max(1, currentRound)
        self.TxtTotalTimes.text = XUiHelper.GetText("LuckyTenant2TotalTimes", tostring(currentRound))
    end

    -- 更新目标分数显示（当前分数/当前阶段需要的分数），普通状态用 #f1d58f
    if self.TxtTargetScore then
        local currentScore = data.Score or 0
        local targetQuestScore = 0
        targetQuestScore = self._Control:GetTargetQuestScore()
        self.TxtTargetScore.text = tostring(currentScore) .. "/" .. tostring(targetQuestScore)
        self.TxtTargetScore.color = XUiHelper.Hexcolor2Color("f1d58f")
    end

    -- 更新剩余回合数：currentRound 为 0-based，用 1-based 显示回合参与计算，得到 5 4 3 2 1
    if self.TxtTimesRemain then
        local nextQuestRound = 0
        nextQuestRound = self._Control:GetNextQuestRound()
        local remainRound = math.max(1, nextQuestRound - currentRound + 1)
        local upperLimit = nextQuestRound - lastTargetQuestRound
        remainRound = math.min(remainRound, upperLimit)
        remainRound = math.max(1, remainRound)
        self.TxtTimesRemain.text = XUiHelper.GetText("LuckyTenant2TimesRemain", tostring(remainRound))
    end

    -- 更新分数进度条（使用当前分数/当前阶段目标分数），普通状态用 #f1d58f
    if self.ImgBarScore then
        local currentScore = data.Score or 0
        local targetQuestScore = 0
        targetQuestScore = self._Control:GetTargetQuestScore()
        local fillAmount = targetQuestScore > 0 and (currentScore / targetQuestScore) or 0
        fillAmount = math.max(0, math.min(1, fillAmount)) -- 限制在 0-1 之间
        self.ImgBarScore.fillAmount = fillAmount
        self.ImgBarScore.color = XUiHelper.Hexcolor2Color("f1d58f")
        -- 本回合超出上限（当前分数>=阶段目标）时显示 FxUiLuckyTenant202Loop03
        if self.FxUiLuckyTenant202Loop03 then
            self.FxUiLuckyTenant202Loop03.gameObject:SetActiveEx(fillAmount >= 1 and targetQuestScore > 0)
        end
    end

    self:UpdateBagAmount()
    self:UpdateProp()
    self:UpdateQuestList()
    self:UpdateBonds()
end

function XUiLuckyTenant2Game:ForceUpdateBagAmount()
    if not self._Control then
        return
    end

    -- 先更新棋子数量（即使IsBagDirty为false也要更新）
    self._Control:UpdateBagAmount()
    self._Control:UpdateBag()
    local data = self._Control:GetUiData()
    if self.BtnBag then
        local maxPieces = self._Control:GetChessBoardMaxPieces()
        self.BtnBag:SetNameByGroup(0, tostring(data.PiecesAmount) .. " / " .. tostring(maxPieces))
    end
end

function XUiLuckyTenant2Game:UpdateBagAmount()
    if not self._Control then
        return
    end

    self._Control:UpdateBag()
    if self._State ~= GameState.Animation and self._State ~= GameState.Roll then
        local data = self._Control:GetUiData()
        if self.BtnBag then
            local maxPieces = self._Control:GetChessBoardMaxPieces()
            self.BtnBag:SetNameByGroup(0, tostring(data.PiecesAmount) .. " / " .. tostring(maxPieces))
        end
    end
end

function XUiLuckyTenant2Game:UpdateChessboard()
    if not self._Control then
        return
    end

    local data = self._Control:GetUiData()
    if not data or not data.Chessboard then
        return
    end

    if self.GridChess then
        XTool.UpdateDynamicItem(self._Grids, data.Chessboard, self.GridChess, XUiLuckyTenant2GameGridChess, self)
    end
end

---更新当前道具显示（刷新/删除道具在背包中的数量，调用公共 XUiLuckyTenant2PropDisplay）
function XUiLuckyTenant2Game:UpdateProp()
    if self.Prop1 and self._QuestReward then
        XUiLuckyTenant2PropDisplay.UpdatePropDisplay(self._Control, self._QuestReward, self.Prop1, self)
    end
end

function XUiLuckyTenant2Game:UpdateQuestList()
    if not self._Control then
        return
    end

    local data = self:GetUiData()
    if not data or not data.Quests then
        return
    end

    local currentRound = data.Round or 0

    if self.GridRound then
        -- 使用 Control 提供的显示顺序（当前、前一个、后一个、完美/普通通关、最后一个）
        local questsToShow = data.Quests or {}
        XTool.UpdateDynamicItem(self._GridRounds, questsToShow, self.GridRound, XUiLuckyTenant2GameGridRound, self)

        for i = 1, #self._GridRounds do
            local gridRound = self._GridRounds[i]
            local questData = questsToShow[i]
            if gridRound and questData then
                gridRound:Update(questData, currentRound, questsToShow, questData.OriginalIndex or i)
            end
        end
    end
end

---更新羁绊显示（由 Bonds 内部统一从 Control 拉取数据）
function XUiLuckyTenant2Game:UpdateBonds()
    if not self._Bonds then
        return
    end
    self._Bonds:Update()
end

function XUiLuckyTenant2Game:StartGame(record)
    if self._Control then
        self._Control:StartGame(self._StageId, self._Seed, self._IsFirstTimeEntering, record)
        -- 游戏开始后，立即更新一次 UI，确保棋盘数据被显示
        self:UpdateUi()
    end
end

function XUiLuckyTenant2Game:OnClickNextRound()
    if XMVCA.XLuckyTenant2:IsRequesting() then
        return
    end

    if self._State == GameState.CheckQuestCompletionStatus then
        --快进 直接开始选棋
        return
    end

    if XLuaUiManager.IsUiLoad("UiLuckyTenant2OverDetail") then
        return
    end

    if self._State == GameState.Roll then
        if self._Control then
            self._Control:Roll()
        end
        if self.BtnBag then
            self.BtnBag:SetNameByGroup(0, XUiHelper.GetText("LuckyTenantBagPlaying"))
        end
        return
    end
end

function XUiLuckyTenant2Game:OnClickBag()
    if XMVCA.XLuckyTenant2:IsRequesting() then
        return
    end
    if self._State == GameState.Roll then
        XLuaUiManager.Open("UiLuckyTenant2ChessBag")
    end
end

function XUiLuckyTenant2Game:ClosePanelTips()
    if self.PanelTips then
        self.PanelTips.gameObject:SetActiveEx(false)
    end
    if self._Detail then
        self._Detail:Close()
    end
    if self._Bonds and self._Bonds.CloseBondsDetail then
        self._Bonds:CloseBondsDetail()
    end
end

function XUiLuckyTenant2Game:OnClickSpeedUp(event, isOn)
    if not self.BtnSpeedUp then
        return
    end

    local isOn = self.BtnSpeedUp.ButtonState == CS.UiButtonState.Select
    self._IsSpeedUp = isOn
    XSaveTool.SaveData("LuckyTenant2SpeedUp", isOn)
end

function XUiLuckyTenant2Game:_OnGuideEvent(value)
    value = tonumber(value)
    if XLuaUiManager.IsMaskShow("LuckyTenant2") then
        XLuaUiManager.SetMask(false, "LuckyTenant2")
    end
    if value == 0 then
        self._IsPause = true
        return
    end
    if value == 1 then
        self._IsPause = false
    end
end

-- PlayAnimation/StopAnimation 使用基类 XLuaUi 实现（Timeline/UiProxy），无需在此覆盖

---点击棋盘上的棋子
---@param data table 棋子数据
function XUiLuckyTenant2Game:OnClickPieceOnChessboard(data)
    if not data or not data.IsValid then
        return
    end

    if self.PanelTips then
        self.PanelTips.gameObject:SetActiveEx(true)
    end
    if self.PanelRewardTips then
        self.PanelRewardTips.gameObject:SetActiveEx(false)
    end
    if self._Detail then
        self._Detail:Open()
        self._Detail:Update(data)
    end
end

---根据位置索引获取对应的 grid
---@param position number 位置索引（1-based）
---@return XUiLuckyTenant2GameGridChess|nil
function XUiLuckyTenant2Game:GetGridByPosition(position)
    if not position or position < 1 or position > #self._Grids then
        return nil
    end
    return self._Grids[position]
end

---根据坐标获取对应的 grid
---@param x number X坐标
---@param y number Y坐标
---@return XUiLuckyTenant2GameGridChess|nil
function XUiLuckyTenant2Game:GetGridByXY(x, y)
    if not self._Control then
        return nil
    end

    -- 数据和动画分离：直接通过坐标计算position，不依赖数据
    -- position = (y - 1) * Column + x
    local column = self._Control:GetChessBoardColumn()
    if not column or column <= 0 then
        return nil
    end

    local position = (y - 1) * column + x
    return self:GetGridByPosition(position)
end

---播放分数动画
---@param x number X坐标
---@param y number Y坐标
---@param value number 分数值
---@param duration number 动画持续时间（秒）
---@param callback function 完成回调
function XUiLuckyTenant2Game:PlayAnimationGetScore(x, y, value, duration, callback)
    if not self.AnimationGetScore or value <= 0 then
        if callback then
            callback()
        end
        return
    end

    -- 获取对应的 grid
    local grid = self:GetGridByXY(x, y)
    if not grid then
        if callback then
            callback()
        end
        return
    end

    -- 计算目标位置（分数进度条的位置）
    local targetRectTransform = self.ImgBarScore and self.ImgBarScore.transform
    if not targetRectTransform then
        if callback then
            callback()
        end
        return
    end

    local endPosition = targetRectTransform.position
    -- 起始位置使用格子内 TxtCost（分数文字）的位置，飞字才贴合
    local startPosition = (grid.TxtCost and grid.TxtCost.transform) and grid.TxtCost.transform.position or grid.Transform.position

    -- 查找可复用的节点（已隐藏的节点）
    local getScoreGrid = nil
    for key, grid in pairs(self._AnimationGetScore) do
        if grid and grid:IsValid() and not grid:IsNodeShow() then
            -- 找到已隐藏的节点，复用
            getScoreGrid = grid
            break
        end
    end

    -- 如果没有可复用的节点，创建一个新的
    if not getScoreGrid then
        local ui = CS.UnityEngine.Object.Instantiate(self.AnimationGetScore, self.AnimationGetScore.transform.parent)
        ui.gameObject:SetActiveEx(false) -- 先设置为 false，由 Open() 来激活
        getScoreGrid = XUiLuckyTenant2GameAnimationGetScore.New(ui, self)
        -- 使用时间戳作为 key 确保唯一性
        local key = string.format("score_%d",
            math.floor(CS.UnityEngine.Time.frameCount * 1000 + (CS.UnityEngine.Time.time * 1000) % 1000))
        self._AnimationGetScore[key] = getScoreGrid
    end

    -- 设置起始位置
    if getScoreGrid.Transform then
        getScoreGrid.Transform.position = startPosition
    end
    -- 使用 Open() 方法显示节点（会触发 OnStart -> Update，所以要在 Open 之后设置文本）
    if getScoreGrid then
        getScoreGrid:Open()
    end
    -- 在 Open() 之后设置文本（避免被 Update() 覆盖）
    if getScoreGrid and getScoreGrid.TextGetScore then
        getScoreGrid.TextGetScore.text = "+" .. tostring(value)
    end

    -- 播放移动动画
    if getScoreGrid.Transform then
        XUiHelper.DoWorldMove(getScoreGrid.Transform, endPosition, duration, XUiHelper.EaseType.Linear, function()
            -- 动画完成后，隐藏节点以便复用
            if getScoreGrid then
                getScoreGrid:Close()
            end

            -- 如果正在播放棋子分数动画，不在这里更新分数（由 PlayNextPieceScoreAnimation 处理）
            -- 否则，正常更新分数显示
            if not self._IsPlayingPieceScoreAnimation then
                if self._Control then
                    local uiData = self._Control:GetUiData()
                    if uiData then
                        self:SetScore(uiData.Score or 0)
                        self:SetAddScore(uiData.AddScore or 0)
                    end
                end
            end

            if callback then
                callback()
            end
        end)
    else
        -- 如果没有 Transform，直接完成
        if callback then
            callback()
        end
    end
end

---开始播放所有棋子的分数动画
function XUiLuckyTenant2Game:StartPieceScoreAnimation()
    if not self._Control then
        return
    end

    -- 收集所有棋子的分数数据
    local data = self._Control:GetUiData()
    if not data or not data.Chessboard then
        self:FinishPieceScoreAnimation()
        return
    end

    -- 收集所有有效棋子的分数数据
    self._PieceScoreAnimations = {}
    for _, chessData in ipairs(data.Chessboard) do
        if chessData.IsValid and chessData.X and chessData.Y then
            local value = chessData.Score or chessData.Value or 0
            if value > 0 then
                self._PieceScoreAnimations[#self._PieceScoreAnimations + 1] = {
                    x = chessData.X,
                    y = chessData.Y,
                    value = value
                }
            end
        end
    end

    -- 如果没有需要播放的动画，直接完成
    if #self._PieceScoreAnimations == 0 then
        self:FinishPieceScoreAnimation()
        return
    end

    -- 初始化动画状态
    self._IsPlayingPieceScoreAnimation = true
    self._PieceScoreAnimationIndex = 0
    self._AnimationLevelLastTriggered = 0

    -- 获取动画开始前的基准分数（当前总分 - 本回合分数）
    if self._Control then
        local game = self._Control:GetGame()
        if game then
            local totalScore = game:GetTotalScore() or 0
            local scoreThisRound = game:GetScoreThisRound() or 0
            self._BaseScoreForAnimation = totalScore - scoreThisRound
            self._AccumulatedScoreForAnimation = self._BaseScoreForAnimation
        end
    end

    -- 开始播放第一个动画
    self:PlayNextPieceScoreAnimation()
end

---播放下一个棋子分数动画
function XUiLuckyTenant2Game:PlayNextPieceScoreAnimation()
    if not self._IsPlayingPieceScoreAnimation then
        return
    end

    self._PieceScoreAnimationIndex = self._PieceScoreAnimationIndex + 1

    if self._PieceScoreAnimationIndex > #self._PieceScoreAnimations then
        -- 所有动画播放完成
        self:FinishPieceScoreAnimation()
        return
    end

    local animData = self._PieceScoreAnimations[self._PieceScoreAnimationIndex]
    if not animData then
        self:FinishPieceScoreAnimation()
        return
    end

    -- 播放单个分数动画，动画完成后更新累计分数并播放下一个
    local duration = 0.5 -- 每个动画持续时间
    self:PlayAnimationGetScore(animData.x, animData.y, animData.value, duration, function()
        -- 动画完成，更新累计分数
        self._AccumulatedScoreForAnimation = self._AccumulatedScoreForAnimation + animData.value

        -- 更新分数显示
        if self.TxtNumScore then
            self.TxtNumScore.text = tostring(math.floor(self._AccumulatedScoreForAnimation))
        end

        -- 动画等级：本回合得分 >= 本阶段得分/本阶段回合数 * (90%/110%/130%)；等级1播Shake1，等级2播Shake2，等级3播Shake3；等级2和3播TxtTargetScoreEnable；等级3另显示 FxUiLuckyTenant202Loop02
        local scoreThisRoundSoFar = self._AccumulatedScoreForAnimation - self._BaseScoreForAnimation
        local currentLevel = self:GetAnimationLevel(scoreThisRoundSoFar)
        if currentLevel >= 1 and currentLevel > self._AnimationLevelLastTriggered then
            if currentLevel >= 3 then
                self:PlayAnimation("Shake3")
                if self.FxUiLuckyTenant202Loop02 then
                    if self._FxLoop02Timer then
                        XScheduleManager.UnSchedule(self._FxLoop02Timer)
                        self._FxLoop02Timer = nil
                    end
                    self.FxUiLuckyTenant202Loop02.gameObject:SetActiveEx(true)
                    local node = self.FxUiLuckyTenant202Loop02
                    self._FxLoop02Timer = XScheduleManager.ScheduleOnce(function()
                        self._FxLoop02Timer = nil
                        if node and node.gameObject then
                            node.gameObject:SetActiveEx(false)
                        end
                    end, 2000)
                end
            elseif currentLevel >= 2 then
                self:PlayAnimation("Shake2")
            else
                self:PlayAnimation("Shake1")
            end
            if currentLevel >= 2 then
                self:PlayTxtTargetScoreEnableAnimation()
            end
            self._AnimationLevelLastTriggered = currentLevel
        end

        -- 播放下一个动画（延迟一小段时间）
        XScheduleManager.ScheduleOnce(function()
            self:PlayNextPieceScoreAnimation()
        end, 50) -- 50ms 延迟
    end)
end

---完成所有棋子分数动画
function XUiLuckyTenant2Game:FinishPieceScoreAnimation()
    self._IsPlayingPieceScoreAnimation = false
    self._PieceScoreAnimations = {}
    self._PieceScoreAnimationIndex = 0

    -- 更新到最终分数（从 Control 层获取）；重置动画等级触发标记
    self._AnimationLevelLastTriggered = 0
    if self._Control then
        local uiData = self._Control:GetUiData()
        if uiData then
            local finalScore = uiData.Score or 0
            self._LastScoreForTxtTargetScoreEnable = finalScore
            self:SetScore(finalScore)
        end
    end

    -- 调用 FinishAnimation 继续游戏流程
    if self._Control then
        self._Control:FinishAnimation()
        if CS.UnityEngine.Time.timeScale ~= 1 then
            CS.UnityEngine.Time.timeScale = 1
        end
    end
end

---播放获得道具动画
---@param x number X坐标
---@param y number Y坐标
---@param itemId number 道具ID
---@param duration number 动画持续时间（秒）
---@param callback function 完成回调
function XUiLuckyTenant2Game:PlayAnimationGetItem(x, y, itemId, duration, callback)
    if not self.AnimationGetItem or not itemId or itemId <= 0 then
        if callback then
            callback()
        end
        return
    end

    -- 获取对应的 grid
    local grid = self:GetGridByXY(x, y)
    if not grid then
        if callback then
            callback()
        end
        return
    end

    -- 计算目标位置（背包按钮的位置）
    local targetRectTransform = self.BtnBag and self.BtnBag.transform
    if not targetRectTransform then
        if callback then
            callback()
        end
        return
    end

    local endPosition = targetRectTransform.position
    local startPosition = grid.Transform.position

    -- 查找可复用的节点（已隐藏的节点）
    local getItemGrid = nil
    for key, gridItem in pairs(self._AnimationGetItem) do
        if gridItem and gridItem:IsValid() and not gridItem:IsNodeShow() then
            -- 找到已隐藏的节点，复用
            getItemGrid = gridItem
            break
        end
    end

    -- 如果没有可复用的节点，创建一个新的
    if not getItemGrid then
        local ui = CS.UnityEngine.Object.Instantiate(self.AnimationGetItem, self.AnimationGetItem.transform.parent)
        ui.gameObject:SetActiveEx(false) -- 先设置为 false，由 Open() 来激活
        getItemGrid = XUiLuckyTenant2GameAnimationGetItem.New(ui, self)
        -- 使用时间戳作为 key 确保唯一性
        local key = string.format("item_%d",
            math.floor(CS.UnityEngine.Time.frameCount * 1000 + (CS.UnityEngine.Time.time * 1000) % 1000))
        self._AnimationGetItem[key] = getItemGrid
    end

    -- 更新动画数据（设置图标等）
    if getItemGrid and getItemGrid.IconGetItem then
        -- 这里可以根据 itemId 设置对应的图标
        -- 暂时留空，后续可以根据需求实现
    end

    -- 设置起始位置
    if getItemGrid.Transform then
        getItemGrid.Transform.position = startPosition
    end
    -- 使用 Open() 方法显示节点
    if getItemGrid then
        getItemGrid:Open()
    end

    -- 播放移动动画
    if getItemGrid.Transform then
        XUiHelper.DoWorldMove(getItemGrid.Transform, endPosition, duration, XUiHelper.EaseType.Linear, function()
            -- 动画完成后，隐藏节点以便复用
            if getItemGrid then
                getItemGrid:Close()
            end

            if callback then
                callback()
            end
        end)
    else
        -- 如果没有 Transform，直接完成
        if callback then
            callback()
        end
    end
end

---播放添加棋子动画（生成棋子）
---动画阶段棋盘用快照显示，快照不包含新加的棋子，所以先从当前游戏状态取该格数据并刷新格子，再播特效
---@param pieceId number 棋子ID
---@param x number|nil X坐标（可选）
---@param y number|nil Y坐标（可选）
function XUiLuckyTenant2Game:PlayAnimationAddPiece(pieceId, x, y)
    if not x or not y then
        return
    end
    local grid = self:GetGridByXY(x, y)
    if not grid then
        return
    end
    -- 动画阶段棋盘是快照，新棋子不在快照里；先用当前游戏状态刷新该格，让新棋子显示出来
    if self._Control and self._Control.GetCellDisplayDataFromGame then
        local data = self._Control:GetCellDisplayDataFromGame(x, y)
        if data then
            grid:Update(data)
        end
    end
    -- 再播放该格子的生成/出现特效；有棋子出生在 GridChess 时播放 ChessBorn
    if grid.PlayAnimation then
        grid:PlayAnimation("ChessBorn")
    end
    if grid.ShowEffect then
        grid:ShowEffect()
    elseif grid.Effect and grid.Effect.gameObject then
        grid.Effect.gameObject:SetActiveEx(true)
        XScheduleManager.ScheduleOnce(function()
            if grid and grid.Effect and grid.Effect.gameObject then
                grid.Effect.gameObject:SetActiveEx(false)
            end
        end, 800)
    end
end

---播放更新棋子动画（属性变化：值、等级、状态等）
---动画阶段棋盘是快照，格子显示的是旧数据；先用当前游戏状态刷新该格再播特效，否则看不到数值/等级等变化
---@param pieceUid number 棋子UID
---@param skillId number|nil 来源技能ID（动画组传入，用于日志）
function XUiLuckyTenant2Game:PlayAnimationUpdatePiece(pieceUid, skillId)
    if not pieceUid or pieceUid <= 0 then
        return
    end

    if not self._Control then
        return
    end

    local uiData = self._Control:GetUiData()
    if not uiData or not uiData.Chessboard then
        return
    end

    -- 从棋盘数据中查找对应的棋子（快照中仍有该棋子，位置未变）
    local pieceData = nil
    for _, chessData in ipairs(uiData.Chessboard) do
        if chessData.Uid == pieceUid then
            pieceData = chessData
            break
        end
    end

    if not pieceData then
        return
    end

    local grid = self:GetGridByPosition(pieceData.Position)
    if not grid then
        return
    end

    -- 动画阶段格子显示的是快照旧数据，先用当前游戏状态刷新该格，再播特效
    local x, y = pieceData.X, pieceData.Y
    if x and y and self._Control.GetCellDisplayDataFromGame then
        local data = self._Control:GetCellDisplayDataFromGame(x, y)
        if data then
            grid:Update(data)
        end
    end

    -- 倒计时减少时播放沙漏特效（状态/回合数变化）；单回合内同一格子只播一次
    local gridKey = (x and y) and (tostring(x) .. "," .. tostring(y)) or ("uid_" .. tostring(pieceUid))
    if not self:_WasGridEffectPlayedInGroup("Countdown", gridKey) and grid.PlayEffectCountdownDecrease then
        self:_MarkGridEffectPlayedInGroup("Countdown", gridKey)
        grid:PlayEffectCountdownDecrease(skillId)
    end
    -- 注：Update(data) 内部已调用 UpdateEffectVisibility，无需再调 ShowEffect，避免重复刷新特效
end

---根据 pieceUid 或 (x,y) 获取对应格子，用于播放格子动画
---@param pieceUid number 棋子UID（可选，有则从棋盘数据查位置）
---@param x number X坐标（可选）
---@param y number Y坐标（可选）
---@return XUiLuckyTenant2GameGridChess|nil
function XUiLuckyTenant2Game:GetGridByPieceUidOrXY(pieceUid, x, y)
    if x and y and x > 0 and y > 0 then
        return self:GetGridByXY(x, y)
    end
    if not pieceUid or pieceUid <= 0 or not self._Control then
        return nil
    end
    local uiData = self._Control:GetUiData()
    if not uiData or not uiData.Chessboard then
        return nil
    end
    for _, chessData in ipairs(uiData.Chessboard) do
        if chessData.Uid == pieceUid then
            return self:GetGridByPosition(chessData.Position)
        end
    end
    return nil
end

---单回合内该格子该类型特效是否已播过（用于同格同类型只播一次）
---@param effectType string "Countdown"|"Delete"|"WeaponSkill"|"Infection"|"RoleEliminate"
---@param gridKey string 格子键，如 "x,y" 或 "uid_xxx"
---@return boolean
function XUiLuckyTenant2Game:_WasGridEffectPlayedInGroup(effectType, gridKey)
    if not self._GridEffectPlayedInGroup or not effectType or not gridKey then
        return false
    end
    local set = self._GridEffectPlayedInGroup[effectType]
    return set and set[gridKey] == true
end

---标记单回合内该格子该类型特效已播
---@param effectType string
---@param gridKey string
function XUiLuckyTenant2Game:_MarkGridEffectPlayedInGroup(effectType, gridKey)
    if not effectType or not gridKey then
        return
    end
    if not self._GridEffectPlayedInGroup then
        self._GridEffectPlayedInGroup = {}
    end
    if not self._GridEffectPlayedInGroup[effectType] then
        self._GridEffectPlayedInGroup[effectType] = {}
    end
    self._GridEffectPlayedInGroup[effectType][gridKey] = true
end

---播放主动发动技能动画（发动技能的棋子）
---@param pieceUid number 棋子UID
---@param x number X坐标
---@param y number Y坐标
---@param skillId number 技能ID（可选，用于武器类技能播放 FxUiLuckyTenant213）
function XUiLuckyTenant2Game:PlayAnimationActivateSkillEnable(pieceUid, x, y, skillId)
    local grid = self:GetGridByPieceUidOrXY(pieceUid, x, y)
    if not grid then return end
    local gridKey = (x and y and x > 0 and y > 0) and (tostring(x) .. "," .. tostring(y)) or (grid._Data and grid._Data.X and grid._Data.Y and (tostring(grid._Data.X) .. "," .. tostring(grid._Data.Y))) or ("uid_" .. tostring(pieceUid))
    -- 武器类技能（Type401-407）发动时播放特效；单回合内同一格子只播一次
    if skillId and skillId >= 401 and skillId <= 407 and grid.PlayEffectWeaponSkill and not self:_WasGridEffectPlayedInGroup("WeaponSkill", gridKey) then
        self:_MarkGridEffectPlayedInGroup("WeaponSkill", gridKey)
        grid:PlayEffectWeaponSkill(skillId)
    end
    if grid.PlayAnimation then
        grid:PlayAnimation("ActivateSkillEnable")
    end
end

---播放受技能影响动画（被技能影响的棋子）
---@param pieceUid number 棋子UID（可选，无则用 x,y 定位）
---@param x number X坐标
---@param y number Y坐标
---@param skillId number 技能ID（可选，用于传染/角色消除播放对应特效）
function XUiLuckyTenant2Game:PlayAnimationAffectedBySkillEnable(pieceUid, x, y, skillId)
    local grid = self:GetGridByPieceUidOrXY(pieceUid, x, y)
    if not grid then return end
    local gridKey = (x and y and x > 0 and y > 0) and (tostring(x) .. "," .. tostring(y)) or (grid._Data and grid._Data.X and grid._Data.Y and (tostring(grid._Data.X) .. "," .. tostring(grid._Data.Y))) or ("uid_" .. tostring(pieceUid))
    -- 子虫/红潮传染（Type207/208/601）播放传染特效；角色消除（Type304/305/306）播放被角色消除特效；单回合内同一格子同类型只播一次
    if skillId then
        if (skillId == 207 or skillId == 208 or skillId == 601) and grid.PlayEffectInfectionSkill and not self:_WasGridEffectPlayedInGroup("Infection", gridKey) then
            self:_MarkGridEffectPlayedInGroup("Infection", gridKey)
            grid:PlayEffectInfectionSkill(skillId)
        elseif (skillId == 304 or skillId == 305 or skillId == 306) and grid.PlayEffectRoleEliminate and not self:_WasGridEffectPlayedInGroup("RoleEliminate", gridKey) then
            self:_MarkGridEffectPlayedInGroup("RoleEliminate", gridKey)
            grid:PlayEffectRoleEliminate(skillId)
        end
    end
    if grid.PlayAnimation then
        grid:PlayAnimation("AffectedBySkillEnable")
    end
end

---播放删除棋子动画（包含完整的消除过程：晃动源棋子 -> 高亮目标棋子 -> 删除动画）
---@param pieceUid number 被删除的棋子UID
---@param x number X坐标
---@param y number Y坐标
---@param fromPieceUid number 发出消除动作的棋子UID（可选）
---@param pieceId number 被删棋子ID（可选，用于宝盒/非宝盒消除特效 208/209）
---@param skillId number|nil 来源技能ID（动画组传入，用于日志）
function XUiLuckyTenant2Game:PlayAnimationDeletePiece(pieceUid, x, y, fromPieceUid, pieceId, skillId)
    -- 在被消除的格子上播放消除特效（宝盒 209，其它 208）；单回合内同一格子只播一次
    local grid = self:GetGridByXY(x, y)
    local gridKey = (x and y) and (tostring(x) .. "," .. tostring(y)) or ("uid_" .. tostring(pieceUid))
    if grid and not self:_WasGridEffectPlayedInGroup("Delete", gridKey) then
        self:_MarkGridEffectPlayedInGroup("Delete", gridKey)
        if pieceId and self._Control and self._Control._Model then
            local pieceType = self._Control._Model:GetLuckyTenant2ChessTypeById(pieceId)
            local XLuckyTenant2Enum = require("XModule/XLuckyTenant2/Game/XLuckyTenant2Enum")
            if pieceType == XLuckyTenant2Enum.PieceType.Box and grid.PlayEffectEliminatedBox then
                grid:PlayEffectEliminatedBox(skillId)
            elseif grid.PlayEffectEliminatedNormal then
                grid:PlayEffectEliminatedNormal(skillId)
            end
        elseif grid.PlayEffectEliminatedNormal then
            grid:PlayEffectEliminatedNormal(skillId)
        end
    end
    -- 步骤1: 如果有fromPieceUid，先晃动发出消除动作的棋子
    if fromPieceUid and fromPieceUid > 0 then
        self:_PlayShakeAnimationForPiece(fromPieceUid, function()
            -- 步骤2: 高亮被消除的棋子
            self:_PlayHighlightAnimationForPiece(pieceUid, x, y, function()
                -- 步骤3: 播放删除动画
                self:_PlayDeleteAnimationForPiece(pieceUid, x, y)
            end)
        end)
    else
        -- 如果没有fromPieceUid，直接高亮然后删除
        self:_PlayHighlightAnimationForPiece(pieceUid, x, y, function()
            self:_PlayDeleteAnimationForPiece(pieceUid, x, y)
        end)
    end
end

---播放晃动动画（用于发出消除动作的棋子）
---@param pieceUid number 棋子UID
---@param callback function 完成回调
function XUiLuckyTenant2Game:_PlayShakeAnimationForPiece(pieceUid, callback)
    if not pieceUid or pieceUid <= 0 then
        if callback then callback() end
        return
    end

    -- 从棋盘数据中查找对应的棋子位置
    if not self._Control then
        if callback then callback() end
        return
    end

    local uiData = self._Control:GetUiData()
    if not uiData or not uiData.Chessboard then
        if callback then callback() end
        return
    end

    -- 查找对应的棋子数据
    local pieceData = nil
    for _, chessData in ipairs(uiData.Chessboard) do
        if chessData.Uid == pieceUid then
            pieceData = chessData
            break
        end
    end

    if not pieceData then
        if callback then callback() end
        return
    end

    local grid = self:GetGridByPosition(pieceData.Position)
    if not grid then
        if callback then callback() end
        return
    end

    local targetTransform = nil
    if grid.PanelChess and grid.PanelChess.gameObject then
        targetTransform = grid.PanelChess.transform
    elseif grid.Root and grid.Root.gameObject then
        targetTransform = grid.Root.transform
    end

    if not targetTransform then
        if callback then callback() end
        return
    end

    -- 使用简单的缩放动画模拟晃动效果（可以后续优化为真正的晃动动画）
    local originalScale = targetTransform.localScale
    local shakeScale = CS.UnityEngine.Vector3(originalScale.x * 1.1, originalScale.y * 1.1, originalScale.z)
    local duration = 0.15 -- 晃动时间

    -- 快速放大然后恢复
    XUiHelper.DoScale(targetTransform, originalScale, shakeScale, duration / 2, XUiHelper.EaseType.Sin, function()
        XUiHelper.DoScale(targetTransform, shakeScale, originalScale, duration / 2, XUiHelper.EaseType.Sin, function()
            if callback then callback() end
        end)
    end)
end

---播放高亮动画（用于被消除的棋子）
---@param pieceUid number 棋子UID
---@param x number X坐标
---@param y number Y坐标
---@param callback function 完成回调
function XUiLuckyTenant2Game:_PlayHighlightAnimationForPiece(pieceUid, x, y, callback)
    local grid = self:GetGridByXY(x, y)
    if not grid then
        if callback then callback() end
        return
    end

    local targetTransform = nil
    if grid.PanelChess and grid.PanelChess.gameObject then
        targetTransform = grid.PanelChess.transform
    elseif grid.Root and grid.Root.gameObject then
        targetTransform = grid.Root.transform
    end

    if not targetTransform then
        if callback then callback() end
        return
    end

    -- 使用简单的缩放动画模拟高亮效果（可以后续优化为颜色或发光效果）
    local originalScale = targetTransform.localScale
    local highlightScale = CS.UnityEngine.Vector3(originalScale.x * 1.15, originalScale.y * 1.15, originalScale.z)
    local duration = 0.2 -- 高亮时间

    -- 放大然后恢复
    XUiHelper.DoScale(targetTransform, originalScale, highlightScale, duration / 2, XUiHelper.EaseType.Sin, function()
        XUiHelper.DoScale(targetTransform, highlightScale, originalScale, duration / 2, XUiHelper.EaseType.Sin,
            function()
                if callback then callback() end
            end)
    end)
end

---播放删除动画（棋子消失）
---@param pieceUid number 棋子UID
---@param x number X坐标
---@param y number Y坐标
function XUiLuckyTenant2Game:_PlayDeleteAnimationForPiece(pieceUid, x, y)
    local grid = self:GetGridByXY(x, y)
    if not grid then
        return
    end

    -- 使用 PanelChess 或 Root 播放缩放消失动画
    local targetTransform = nil
    local targetGameObject = nil
    local originalScale = nil

    if grid.PanelChess and grid.PanelChess.gameObject then
        targetTransform = grid.PanelChess.transform
        targetGameObject = grid.PanelChess.gameObject
        originalScale = targetTransform.localScale
    elseif grid.Root and grid.Root.gameObject then
        targetTransform = grid.Root.transform
        targetGameObject = grid.Root.gameObject
        originalScale = targetTransform.localScale
    end

    if not targetTransform or not targetGameObject then
        return
    end

    -- 使用 XUiHelper.DoScale 播放缩放消失动画
    local zeroScale = CS.UnityEngine.Vector3.zero
    local duration = 0.3

    XUiHelper.DoScale(targetTransform, originalScale, zeroScale, duration, XUiHelper.EaseType.Sin, function()
        -- 动画完成后，确保对象被隐藏并恢复原始缩放
        if targetGameObject and targetTransform then
            targetGameObject:SetActiveEx(false)
            targetTransform.localScale = originalScale
        end
    end)
end

function XUiLuckyTenant2Game:OnBtnBackClick()
    XLuaUiManager.Open("UiLuckyTenant2PopupNormal")
end

return XUiLuckyTenant2Game
