--[[
-- XUiLuckyTenant2GameUiLuckyTenant2BondsDetail.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2025-12-31 16:39:51
--]]

local XUiLuckyTenant2GameGridBondsBuff = require("XUi/XUiLuckyTenant2/XUiLuckyTenant2Game/XUiLuckyTenant2GameGridBondsBuff")
local XUiLuckyTenant2GameGridBondsChessRequire = require("XUi/XUiLuckyTenant2/XUiLuckyTenant2Game/XUiLuckyTenant2GameGridBondsChessRequire")
local XUiLuckyTenant2GameUiLuckyTenant2ChessDetail = require("XUi/XUiLuckyTenant2/XUiLuckyTenant2Game/XUiLuckyTenant2GameUiLuckyTenant2ChessDetail")
local XTool = XTool

---@class XUiLuckyTenant2GameUiLuckyTenant2BondsDetail : XUiNode
---@field _Root XLuaUi
local XUiLuckyTenant2GameUiLuckyTenant2BondsDetail = XClass(XUiNode, "XUiLuckyTenant2GameUiLuckyTenant2BondsDetail")

function XUiLuckyTenant2GameUiLuckyTenant2BondsDetail:OnStart(...)
    ---@type XUiLuckyTenant2GameGridBondsBuff[]
    self._BuffGrids = {}
    ---@type XUiLuckyTenant2GameGridBondsChessRequire[]
    self._ChessRequireGrids = {}
    ---@type UnityEngine.UI.Text[] 被动技能描述文本组件数组
    self._PassiveSkillDescTexts = {}
    
    if self.UiLuckyTenant2ChessDetail then
        ---@type XUiLuckyTenant2GameUiLuckyTenant2ChessDetail
        self._ChessDetail = XUiLuckyTenant2GameUiLuckyTenant2ChessDetail.New(self.UiLuckyTenant2ChessDetail, self)
        self._ChessDetail:Close()
    end
end

function XUiLuckyTenant2GameUiLuckyTenant2BondsDetail:BuildChessDetailData(chessData)
    if not chessData then
        return nil
    end
    local chessId = chessData.Id or 0
    return self._Control:BuildChessDetailDataByChessId(chessId)
end

function XUiLuckyTenant2GameUiLuckyTenant2BondsDetail:OnChessRequireClick(chessData)
    local detailData = self:BuildChessDetailData(chessData)
    if not detailData then
        return
    end
    self._ChessDetail:Update(detailData)
    self._ChessDetail:Open()
end

---@param data table 羁绊数据
function XUiLuckyTenant2GameUiLuckyTenant2BondsDetail:Update(data, hideChessRequire)
    if not data then
        return
    end
    
    self._Data = data
    
    -- 设置羁绊名称（兼容 Name / BondName，游戏内列表用 Name，关卡详情弹窗用 BondName）
    local nameText = data.Name or data.BondName or ""
    if self.TxtName then
        self.TxtName.text = nameText
    end
    
    -- 设置羁绊图标（兼容 Icon / BondIcon：游戏内列表用 Icon，关卡详情弹窗用 BondIcon）
    local icon = data.Icon or data.BondIcon or ""
    if self.BondsIcon then
        local image = self.BondsIcon:GetComponent(typeof(CS.UnityEngine.UI.RawImage))
        if image then
            image:SetImage(icon)
        end
    end
    
    -- 设置提示文本（显示 UpgradeRequireDesc）
    if self.TxtTips then
        local tipsText = ""
        if data.BondId then
            tipsText = self._Control:GetBondUpgradeRequireDesc(data.BondId) or ""
        end
        self.TxtTips.text = tipsText
    end
    
    -- 设置被动技能描述（支持多个被动技能）
    if self.TxtPassiveSkillDesc then
        local passiveSkillDescs = {}
        
        if data.BondId then
            local bondLevel = data.Level
            passiveSkillDescs = self._Control:GetBondPassiveSkillDesc(data.BondId, bondLevel) or {}
        end
        
        -- 确保有足够的文本组件
        local needCount = #passiveSkillDescs
        if needCount == 0 then
            needCount = 1  -- 至少显示一个（即使是空的）
        end
        
        -- 初始化第一个组件（使用原有的组件）
        if not self._PassiveSkillDescTexts[1] then
            self._PassiveSkillDescTexts[1] = self.TxtPassiveSkillDesc
        end
        
        -- 隐藏多余的组件
        for i = #self._PassiveSkillDescTexts, needCount + 1, -1 do
            if self._PassiveSkillDescTexts[i] then
                self._PassiveSkillDescTexts[i].gameObject:SetActiveEx(false)
            end
        end
        
        -- 显示并更新需要的组件
        for i = 1, needCount do
            local txtComp = nil
            
            if not self._PassiveSkillDescTexts[i] then
                if i == 1 then
                    -- 第一个使用原有的组件
                    txtComp = self.TxtPassiveSkillDesc
                else
                    -- 后续的需要克隆
                    local cloneObj = CS.UnityEngine.Object.Instantiate(self.TxtPassiveSkillDesc.gameObject, self.TxtPassiveSkillDesc.transform.parent)
                    txtComp = cloneObj:GetComponent("UnityEngine.UI.Text")
                    if not txtComp then
                        txtComp = cloneObj:GetComponent("TMPro.TextMeshProUGUI")
                    end
                    
                    -- 设置排序（在原组件的后面）
                    local originalSiblingIndex = self.TxtPassiveSkillDesc.transform:GetSiblingIndex()
                    cloneObj.transform:SetSiblingIndex(originalSiblingIndex + i - 1)
                end
                self._PassiveSkillDescTexts[i] = txtComp
            else
                txtComp = self._PassiveSkillDescTexts[i]
            end
            
            -- 设置文本内容
            if txtComp then
                txtComp.gameObject:SetActiveEx(true)
                local desc = passiveSkillDescs[i] or ""
                txtComp.text = desc
            end
        end
    end
    
    -- 更新 Buff 列表
    if self.ListBuff and self.GridBuff then
        local buffs = data.Buffs or {}
        XTool.UpdateDynamicItem(self._BuffGrids, buffs, self.GridBuff, XUiLuckyTenant2GameGridBondsBuff, self)
    end
    
    if not hideChessRequire then
        -- 更新关联棋子列表
        if self.GridChessRequire then
            local chessRequires = data.ChessRequires or {}
            XTool.UpdateDynamicItem(self._ChessRequireGrids, chessRequires, self.GridChessRequire, XUiLuckyTenant2GameGridBondsChessRequire, self)
        end
    end

    -- 切换其他羁绊后，要关闭棋子详情弹窗
    self._ChessDetail:Close()
end

return XUiLuckyTenant2GameUiLuckyTenant2BondsDetail
