--[[
-- XUiLuckyTenant2GameGridBondsBuff.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2025-12-31 16:39:51
--]]

---@class XUiLuckyTenant2GameGridBondsBuff : XUiNode
local XUiLuckyTenant2GameGridBondsBuff = XClass(XUiNode, "XUiLuckyTenant2GameGridBondsBuff")

function XUiLuckyTenant2GameGridBondsBuff:OnAwake()
    self:InitComponents()
end

function XUiLuckyTenant2GameGridBondsBuff:InitComponents()
end

function XUiLuckyTenant2GameGridBondsBuff:OnStart(...)
    -- 记录原色值
    self._OriginalIndexColor = nil
    self._OriginalDescColor = nil
end

function XUiLuckyTenant2GameGridBondsBuff:OnEnable()
end

function XUiLuckyTenant2GameGridBondsBuff:OnDisable()
end

function XUiLuckyTenant2GameGridBondsBuff:OnDestroy()
end

---@param data table Buff数据，包含 Index、Desc、IsOwned 和 ImageBg 字段
function XUiLuckyTenant2GameGridBondsBuff:Update(data)
    if not data then
        return
    end
    
    -- 设置品质背景（根据羁绊等级，由 Control 传入 ImageBg）
    if self.ImageBg and data.ImageBg then
        if self.ImageBg.SetRawImage then
            self.ImageBg:SetRawImage(data.ImageBg)
        elseif self.ImageBg.SetImage then
            self.ImageBg:SetImage(data.ImageBg)
        end
    end
    
    -- 等级对应字色（由 Control 传入 LevelColor：已拥有=该等级色 0~4，未拥有=0 级 #8893a4）
    local textColor = data.LevelColor and XUiHelper.Hexcolor2Color(data.LevelColor)
    -- 显示需求数量（棋子数量/类型数量），优先使用 Require，否则回落到 Index
    if self.TxtIndex then
        local requireNum = data.Require
        local textValue = requireNum or data.Index or 0
        self.TxtIndex.text = tostring(textValue)
        self.TxtIndex.color = textColor
    end
    
    -- 设置描述
    if self.TxtDesc then
        self.TxtDesc.text = XUiHelper.ReplaceTextNewLine(data.Desc or "")
    end
end

return XUiLuckyTenant2GameGridBondsBuff
