--[[
-- XUiLuckyTenant2GameGridBonds.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2025-12-31 16:39:51
--]]

---@class XUiLuckyTenant2GameGridBonds : XUiNode
local XUiLuckyTenant2GameGridBonds = XClass(XUiNode, "XUiLuckyTenant2GameGridBonds")

function XUiLuckyTenant2GameGridBonds:OnStart(...)
    ---@type XUiComponent.XUiButton
    self._Button = XUiHelper.TryGetComponent(self.Transform, "", "XUiButton")
    if self._Button then
        self._Button.CallBack = function()
            self:OnClick()
        end
    end

    -- 羁绊等级增加时播放的特效，播一段时间后隐藏
    self.FxUiLuckyTenant21Jiban01 = self.Transform:Find("FxUiLuckyTenant21Jiban01")
    if self.FxUiLuckyTenant21Jiban01 then
        self.FxUiLuckyTenant21Jiban01.gameObject:SetActiveEx(false)
    end
    self._LevelUpTimer = nil -- 等级增加特效的隐藏定时器，用于回收
    self._LastLevel = nil    -- 上一帧等级，用于检测等级增加

    -- 初始化选中状态为 false
    self._IsSelected = false
end

function XUiLuckyTenant2GameGridBonds:OnEnable()
end

function XUiLuckyTenant2GameGridBonds:OnDisable()
    self:_CancelLevelUpTimer()
end

function XUiLuckyTenant2GameGridBonds:OnDestroy()
    self:_CancelLevelUpTimer()
end

---取消等级增加特效的隐藏定时器
function XUiLuckyTenant2GameGridBonds:_CancelLevelUpTimer()
    if self._LevelUpTimer then
        XScheduleManager.UnSchedule(self._LevelUpTimer)
        self._LevelUpTimer = nil
    end
end

---@param data table 羁绊数据
function XUiLuckyTenant2GameGridBonds:Update(data)
    if not data then
        return
    end

    -- 羁绊等级增加时显示 FxUiLuckyTenant21Jiban01，一段时间后隐藏（定时器回收、不重播同一等级）
    local newLevel = type(data.Level) == "number" and data.Level or nil
    if newLevel ~= nil and (self._LastLevel == nil or newLevel > self._LastLevel) then
        self:_CancelLevelUpTimer()
        if self.FxUiLuckyTenant21Jiban01 then
            self.FxUiLuckyTenant21Jiban01.gameObject:SetActiveEx(true)
            local node = self.FxUiLuckyTenant21Jiban01
            local delayMs = 1500
            self._LevelUpTimer = XScheduleManager.ScheduleOnce(function()
                self._LevelUpTimer = nil
                if node and node.gameObject then
                    node.gameObject:SetActiveEx(false)
                end
            end, delayMs)
        end
    end
    self._LastLevel = newLevel

    self._Data = data

    -- 设置羁绊品质背景（根据羁绊等级从 Control 传入的 ImageBg）
    if self.ImageBg and data.ImageBg then
        if self.ImageBg.SetRawImage then
            self.ImageBg:SetRawImage(data.ImageBg)
        elseif self.ImageBg.SetImage then
            self.ImageBg:SetImage(data.ImageBg)
        end
    end

    -- 设置羁绊图标
    if self.BondIcon and data.Icon then
        if self.BondIcon.SetRawImage then
            self.BondIcon:SetRawImage(data.Icon)
        elseif self.BondIcon.SetImage then
            self.BondIcon:SetImage(data.Icon)
        end
    end
    -- 羁绊等级对应 icon 颜色（0~4）
    if self.BondIcon and data.LevelColor then
        self.BondIcon.color = XUiHelper.Hexcolor2Color(data.LevelColor)
    end

    -- 设置羁绊名称
    if self.TxtName then
        self.TxtName.text = data.Name or ""
    end
    -- 羁绊等级对应字色
    -- if self.TxtName and data.LevelColor then
    --     self.TxtName.color = XUiHelper.Hexcolor2Color(data.LevelColor)
    -- end

    -- 设置等级文本（如：2/4/5/6/7）
    if self.TxtLvNum then
        self.TxtLvNum.text = data.LevelText or ""
    end

    -- 设置当前羁绊棋子数量（或棋子类型数量）
    if self.TxtLv then
        local pieceCount = data.PieceCount or 0
        self.TxtLv.text = tostring(pieceCount)
    end
end

function XUiLuckyTenant2GameGridBonds:OnClick()
    if not self._Data then
        return
    end

    -- 先设置选中状态（确保在打开详情界面之前选中状态已更新）
    if self.Parent and self.Parent.SetSelectedGrid then
        self.Parent:SetSelectedGrid(self)
    end

    -- 然后打开详情界面（直接通过Parent调用，Parent是XUiLuckyTenant2GameUiLuckyTenant2Bonds）
    if self.Parent and self.Parent.OpenBondsDetail then
        self.Parent:OpenBondsDetail(self._Data)
    end
end

---设置选中状态
---@param isSelected boolean 是否选中
function XUiLuckyTenant2GameGridBonds:SetSelected(isSelected)
    self._IsSelected = isSelected

    -- 更新按钮状态
    if self._Button then
        if isSelected then
            self._Button:SetButtonState(CS.UiButtonState.Select)
        else
            self._Button:SetButtonState(CS.UiButtonState.Normal)
        end
    end

    -- 如果有选中状态的UI元素（如高亮图片），也可以在这里更新
    -- if self.ImgSelect then
    --     self.ImgSelect.gameObject:SetActiveEx(isSelected)
    -- end
end

---获取是否选中
---@return boolean
function XUiLuckyTenant2GameGridBonds:IsSelected()
    return self._IsSelected or false
end

return XUiLuckyTenant2GameGridBonds
