--[[
-- XUiActivityBossSingleSettlement.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-05-21 21:15:09
--]]

-- local XUiActivityBossSingleSettlementGridCharacter = require("XUi/XUiActivityBossSingleSettlement/XUiActivityBossSingleSettlement/XUiActivityBossSingleSettlementGridCharacter")

---@class XUiActivityBossSingleSettlement : XLuaUi
---@field GridCharacter1 UnityEngine.RectTransform
---@field ListCharacter UnityEngine.RectTransform
---@field ListInfo UnityEngine.RectTransform
---@field txtStageName UnityEngine.UI.Text
---@field goDefensePart UnityEngine.RectTransform
---@field goSpecialSkillPart UnityEngine.RectTransform
---@field goDefenseBreakPart UnityEngine.RectTransform
---@field txtDefenseBreakScore UnityEngine.UI.Text
---@field txtSpecialSkillScore UnityEngine.UI.Text
---@field txtDefenseScore UnityEngine.UI.Text
---@field txtTotleScore UnityEngine.UI.Text
---@field goNewRecodeHint UnityEngine.RectTransform
---@field txtHighScore UnityEngine.UI.Text
---@field BtnReFight XUiComponent.XUiButton
---@field BtnExitFight XUiComponent.XUiButton
---@field txtDifficultyScore UnityEngine.UI.Text
---@field txtDifficultyRate UnityEngine.UI.Text
---@field txtPassTime UnityEngine.UI.Text
---@field txtPassTimeRate UnityEngine.UI.Text
local XUiActivityBossSingleSettlement = XLuaUiManager.Register(XLuaUi, "UiActivityBossSingleSettlement")
function XUiActivityBossSingleSettlement:OnAwake()
    self:InitComponents()
end

function XUiActivityBossSingleSettlement:InitComponents()
    -- Button
    self.BtnReFight:AddEventListener(function() self:OnBtnReFightClick() end)
    self.BtnExitFight:AddEventListener(function() self:OnBtnExitFightClick() end)

    -- XUiNode
    -- ---@type XUiFubenBossSingleSettlementGridCharacter
    -- self.GridCharacter1 = XUiFubenBossSingleSettlementGridCharacter.New(self.GridCharacter1, self)
end

function XUiActivityBossSingleSettlement:OnStart(windata)
    self._winData = windata
    self:_RefreshCharacterList()
    self:Refresh(windata)
end

function XUiActivityBossSingleSettlement:OnEnable()
end

function XUiActivityBossSingleSettlement:OnDisable()
end

function XUiActivityBossSingleSettlement:OnDestroy()
end
 
function XUiActivityBossSingleSettlement:Refresh(windata)
    local settleData = windata.SettleData
    local result = windata.SettleData.BossActivityDifficultyScaleResult


    local stageId   = settleData.StageId
    local detailTitle = XFubenActivityBossSingleConfigs.GetBossChallengeDetailTitle(stageId)
    local activityId = XDataCenter.FubenActivityBossSingleManager.GetCurActivityId() 
    local bossActivityCfg = XFubenActivityBossSingleConfigs.GetActivityConfig(activityId)
    local bossActivityName = bossActivityCfg.Name
    self.txtStageName.text =  detailTitle .. bossActivityName 

    if result == nil then
        local fallBackStr = "--"
        self.txtDefenseBreakScore.text =fallBackStr
        self.txtSpecialSkillScore.text = fallBackStr
        self.txtDefenseScore.text =  fallBackStr
        self.txtTotleScore.text =  fallBackStr

        self.txtPassTimeRate.text = fallBackStr
        self.txtPassTime.text = fallBackStr
        self.txtDifficultyRate.text = fallBackStr
        self.txtDifficultyScore.text = fallBackStr
        self.txtUseTime.text = fallBackStr
        return 
    end


    local totleScore = result and result.Score or 0

    local defenseScore = result and result.DefenseScore or 0
    local SpecialSkillScore = result and result.SpecialSkillScore or 0
    local DefenseBreakScore = result and result.DefenseBreakScore or 0
    local IsNewRecord = result and result.IsNewRecord or false
    local useTime = result and result.FightTime or 0
    local rawTotleScore = defenseScore + SpecialSkillScore + DefenseBreakScore

    local lastDifficultScoreRecord = result and result.OldScore or 0
    
    self.txtDefenseBreakScore.text = DefenseBreakScore
    self.txtSpecialSkillScore.text = SpecialSkillScore
    self.txtDefenseScore.text =  defenseScore
 
    self.txtTotleScore.text =  totleScore 
    self.txtUseTime.text = XUiHelper.GetTime(useTime)

    local timeScaleCO =  XFubenActivityBossSingleConfigs.GetBossTimeScoreCOByTime(useTime)
    local timeRate = timeScaleCO.ScoreRatio/1000
    self.txtPassTimeRate.text = "X" .. timeRate 
    self.txtPassTime.text = math.ceil( (timeRate-1) * (rawTotleScore))

    local levelCO = XFubenActivityBossSingleConfigs.GetBossLevelScoreCOByScore(lastDifficultScoreRecord)
    local levelRate = levelCO.ScoreRatio/1000
    self.txtDifficultyRate.text = "X" .. levelRate
    self.txtDifficultyScore.text = math.ceil( (levelRate -1)* (rawTotleScore))

    self.BtnReFight:SetButtonState(CS.UiButtonState.Normal)
    self.BtnExitFight:SetButtonState(CS.UiButtonState.Normal)

    self.goNewRecodeHint.gameObject:SetActiveEx(IsNewRecord)

    XDataCenter.FubenActivityBossSingleManager.SetCurDifficultScoreRecord(stageId,totleScore)
    XDataCenter.FubenActivityBossSingleManager.GetLastDifficultScoreRecord(stageId,lastDifficultScoreRecord)
end

function XUiActivityBossSingleSettlement:OnBtnReFightClick(eventData)
    CS.XFight.ExitForClient(false)
    self:Close()

    local windata = self._winData
    local settleData = windata.SettleData
    local stageId = settleData.StageId
    XDataCenter.FubenActivityBossSingleManager.JumpToRoleRoom(stageId)
end
 

function XUiActivityBossSingleSettlement:OnBtnExitFightClick()
    CS.XFight.ExitForClient(false)
    self:Close()
end

--- 刷新角色列表显示
function XUiActivityBossSingleSettlement:_RefreshCharacterList()
    if not self.ListCharacter or not self.GridCharacter1 then
        return
    end

    local characterList = nil

    if self._winData then
        if self._winData.SettleData and self._winData.SettleData.NpcHpInfo then
            characterList = self._winData.SettleData.NpcHpInfo
        elseif self._winData.CharExp then
            characterList = self._winData.CharExp
        end
    end

    if not characterList or XTool.IsTableEmpty(characterList) then
        return
    end

    for _, v in ipairs(characterList) do
        -- 支持两种数据结构：NpcHpInfo 使用 CharacterId，CharExp 使用 Id
        local characterId = v.CharacterId or v.Id
        if characterId and characterId > 0 then
            local gridObj = XUiHelper.Instantiate(self.GridCharacter1, self.ListCharacter)
            local imgHead = gridObj.transform:Find("RImgHead")
            if imgHead then
                local rawImage = imgHead:GetComponent(typeof(CS.UnityEngine.UI.RawImage))
                if rawImage then
                    rawImage:SetRawImage(XMVCA.XCharacter:GetCharBigHeadIcon(characterId))
                end
            end
        end
    end

    if self.GridCharacter1 and not XTool.UObjIsNil(self.GridCharacter1.gameObject) then
        self.GridCharacter1.gameObject:SetActiveEx(false)
    end
end

return XUiActivityBossSingleSettlement

