---
--- 阿尔法 法奥斯生态脚本
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ljb.
--- DateTime: 2026/3/18 12:12
---

local Base = require("Character/BigWorld/XEcologyConstructAI/XEcologyConstructAIBase")
local BaseState = require("Character/BigWorld/XEcologyConstructAI/XEcologyConstructAIBaseState")
local FindPathState = require("Character/BigWorld/XEcologyConstructAI/XEcologyFindCombinePathState")

--region 阿尔法生态2.0期静态参数
---生态状态枚举
local StateEnum = {
    None = 0,
    ---教学楼入口处等待指挥官
    TeachingBuilding = 1,
    ---长椅等待指挥官坐下
    Bench = 2,
    ---参观礼堂
    Auditorium = 3,
    ---教室内：趴桌上
    InClass = 4,
    ---寻路过程
    FindPath = 5,
}
---数据黑板key值
local DataBoardKey = {
    None = 0,
    ---教学楼入口处等待指挥官
    TeachingBuilding = 1,
    ---长椅等待指挥官坐下
    Bench = 2,
    ---参观礼堂
    Auditorium = 3,
    ---教室内：趴桌上
    InClass = 4,
    ---寻路过程
    FindPath = 5,
}
--endregion


--region 状态-阿尔法-教学楼
---@class XAlphaTeachingBuildingState: XEcologyConstructAIBaseState
local XAlphaTeachingBuildingState = XClass(BaseState, "XAlphaTeachingBuildingState")

---数据配置
---@overload
function XAlphaTeachingBuildingState:InitStateConfig()
    self.StateConfig = {}
    self.StateConfig.StateEnum = StateEnum.TeachingBuilding
    self.StateConfig.StateAnim = "Drama_Stand_15"
    self.StateConfig.TriggerId = 1
    self.StateConfig.ShowOptionId = 1
    self.StateConfig.RegisterWorldEventList = {
        EWorldEvent.ActorTrigger,
        EWorldEvent.NpcInteractStart,
        EWorldEvent.NpcInteractComplete,
        EWorldEvent.DramaFinish,
    }
    self.StateConfig.BubbleDict = {
        [EEcologyBubbleType.Around] = {
            Name = "300604",
            TriggerDistance = 6,
            TriggerCD = 2,
            LoopTime = 3,
        },
    }
end

function XAlphaTeachingBuildingState:OnStateEnter(lastStateEnum)
    BaseState.OnStateEnter(self, lastStateEnum)
    self.StateMachine:SetDataBoard(DataBoardKey.TeachingBuilding, 0)
end

function XAlphaTeachingBuildingState:HandleEvent(eventType, eventArgs)
    BaseState.HandleEvent(self, eventType, eventArgs)
    if eventType == EWorldEvent.DramaFinish and eventArgs.DramaName == "TargetDrama" then
        if not eventArgs.HistoryDecisionDict[clipId] then
            return
        end
        if table.contains(eventArgs.HistoryDecisionDict[clipId], decisionId) then
            self.StateMachine:SetDataBoard(DataBoardKey.TeachingBuilding, 1)
        end
    end
end
--endregion


--region 状态-阿尔法-长椅
---@class XAlphaBenchState: XEcologyConstructAIBaseState
local XAlphaBenchState = XClass(BaseState, "XAlphaBenchState")

---数据配置
---@overload
function XAlphaBenchState:InitStateConfig()
    self.StateConfig = {}
    self.StateConfig.StateEnum = StateEnum.Bench
    self.StateConfig.StateAnim = "Drama_Stand_06"
    self.StateConfig.TriggerId = 1
    self.StateConfig.ShowOptionId = 2
    self.StateConfig.RegisterWorldEventList = {
        EWorldEvent.ActorTrigger,
        EWorldEvent.NpcInteractStart,
        EWorldEvent.NpcInteractComplete,
    }
    self.StateConfig.BubbleDict = {
        [EEcologyBubbleType.Around] = {
            Name = "300605",
            TriggerDistance = 6,
            TriggerCD = 2,
            LoopTime = 3,
        },
        [EEcologyBubbleType.Near] = {
            Name = "300601",
            TriggerDistance = 2.5,
            TriggerCD = 2,
            LoopTime = 3,
        }
    }
end

function XAlphaBenchState:OnStateEnter(lastStateEnum)
    BaseState.OnStateEnter(self, lastStateEnum)
    self.StateMachine:SetDataBoard(DataBoardKey.Bench, 0)
end
--endregion


--region 状态-阿尔法-礼堂
---@class XAlphaAuditoriumState: XEcologyConstructAIBaseState
local XAlphaAuditoriumState = XClass(BaseState, "XAlphaAuditoriumState")

---数据配置
---@overload
function XAlphaAuditoriumState:InitStateConfig()
    self.StateConfig = {}
    self.StateConfig.StateEnum = StateEnum.Auditorium
    self.StateConfig.StateAnim = "Drama_Stand_07"
    self.StateConfig.TriggerId = 1
    self.StateConfig.ShowOptionId = 3
    self.StateConfig.RegisterWorldEventList = {
        EWorldEvent.ActorTrigger,
        EWorldEvent.NpcInteractStart,
        EWorldEvent.NpcInteractComplete,
    }
    self.StateConfig.BubbleDict = {
        [EEcologyBubbleType.Around] = {
            Name = "300606",
            TriggerDistance = 6,
            TriggerCD = 2,
            LoopTime = 3,
        },
        [EEcologyBubbleType.Near] = {
            Name = "300602",
            TriggerDistance = 2.5,
            TriggerCD = 2,
            LoopTime = 3,
        }
    }
end

function XAlphaAuditoriumState:OnStateEnter(lastStateEnum)
    BaseState.OnStateEnter(self, lastStateEnum)
    self.StateMachine:SetDataBoard(DataBoardKey.Auditorium, 0)
end
--endregion


--region 状态-阿尔法-教室
---@class XAlphaInClassState: XEcologyConstructAIBaseState
local XAlphaInClassState = XClass(BaseState, "XAlphaInClassState")

---数据配置
---@overload
function XAlphaInClassState:InitStateConfig()
    self.StateConfig = {}
    self.StateConfig.StateEnum = StateEnum.InClass
    self.StateConfig.StateAnim = "Drama_Stand_07"
    self.StateConfig.TriggerId = 1
    self.StateConfig.ShowOptionId = 4
    self.StateConfig.RegisterWorldEventList = {
        EWorldEvent.ActorTrigger,
        EWorldEvent.NpcInteractStart,
        EWorldEvent.NpcInteractComplete,
    }
    self.StateConfig.BubbleDict = {
        [EEcologyBubbleType.Around] = {
            Name = "300606",
            TriggerDistance = 6,
            TriggerCD = 2,
            LoopTime = 3,
        },
        [EEcologyBubbleType.Near] = {
            Name = "300602",
            TriggerDistance = 2.5,
            TriggerCD = 2,
            LoopTime = 3,
        }
    }
end

function XAlphaInClassState:OnStateEnter(lastStateEnum)
    BaseState.OnStateEnter(self, lastStateEnum)
    self.StateMachine:SetDataBoard(DataBoardKey.InClass, 0)
end
--endregion


--region 状态-阿尔法-寻路
---@class XAlphaFindPathState: XEcologyFindCombinePathState
local XAlphaFindPathState = XClass(FindPathState, "XAlphaFindPathState")

---数据配置
---@overload
function XAlphaFindPathState:InitStateConfig()
    self.StateConfig = {}
    self.StateConfig.StateEnum = StateEnum.FindPath
    self.StateConfig.TriggerId = 1
    self.StateConfig.ShowOptionId = 5
    self.StateConfig.RegisterWorldEventList = {
        EWorldEvent.ActorTrigger,
        EWorldEvent.NpcInteractStart,
        EWorldEvent.NpcInteractComplete,
    }

    self.StateConfig.FindPathConfig = {}
    self.StateConfig.FindPathConfig.MeetCommanderBubbleName = "300603"
end
--endregion


--region 阿尔法法奥斯生态AI
---@class XCharAlphaEcology : XEcologyConstructAIBase
---@field _stateMachine XStateMachineController 状态机
local XCharAlphaEcology = XDlcScriptManager.RegCharScript(10610801, "XCharAlphaEcology", Base)

--- 注册状态机状态
function XCharAlphaEcology:RegisterMachineState()
    self._stateMachine:AddState(StateEnum.TeachingBuilding, XAlphaTeachingBuildingState.New(self._proxy))
    self._stateMachine:AddState(StateEnum.Bench, XAlphaBenchState.New(self._proxy))
    self._stateMachine:AddState(StateEnum.Auditorium, XAlphaAuditoriumState.New(self._proxy))
    self._stateMachine:AddState(StateEnum.InClass, XAlphaInClassState.New(self._proxy))
    self._stateMachine:AddState(StateEnum.FindPath, XAlphaFindPathState.New(self._proxy))
end

--- 注册状态转移方程
function XCharAlphaEcology:RegisterMachineStateTransition()
    -- 设置寻路状态枚举值
    self.FindPathStateEnum = StateEnum.FindPath
    -- 其他状态到寻路状态
    self:RegisterInFindPathStateTransition(StateEnum.TeachingBuilding, function()
        return self._stateMachine:CheckDataBoard(DataBoardKey.TeachingBuilding, 1) and StateEnum.Auditorium or StateEnum.Bench
    end, 5, 1)
    self:RegisterInFindPathStateTransition(StateEnum.Bench, function()
        return self._stateMachine:CheckDataBoard(DataBoardKey.Bench, 1) and StateEnum.Auditorium or StateEnum.InClass
    end, 5, 1)
    self:RegisterInFindPathStateTransition(StateEnum.InClass, function()
        return self._stateMachine:CheckDataBoard(DataBoardKey.InClass, 1) and StateEnum.TeachingBuilding or StateEnum.Auditorium
    end, 5, 1)
    self:RegisterInFindPathStateTransition(StateEnum.Auditorium, function()
        return self._stateMachine:CheckDataBoard(DataBoardKey.Auditorium, 1) and StateEnum.InClass or StateEnum.TeachingBuilding
    end, 5, 1)
    
    -- 寻路状态到其他状态
    self:RegisterOutFindPathStateTransition(StateEnum.TeachingBuilding)
    self:RegisterOutFindPathStateTransition(StateEnum.Bench)
    self:RegisterOutFindPathStateTransition(StateEnum.Auditorium)
    self:RegisterOutFindPathStateTransition(StateEnum.InClass)
end

return XCharAlphaEcology
--endregion
