---
--- 库洛姆 法奥斯生态脚本
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ljb.
--- DateTime: 2026/3/18 12:12
---

local Base = require("Character/BigWorld/XEcologyConstructAI/XEcologyConstructAIBase")
local BaseState = require("Character/BigWorld/XEcologyConstructAI/XEcologyConstructAIBaseState")
local FindPathState = require("Character/BigWorld/XEcologyConstructAI/XEcologyFindCombinePathState")

--region 库洛姆生态2.0期静态参数
---生态状态枚举
local StateEnum = {
    None = 0,
    ---礼堂
    Auditorium = 1,
    ---生活区
    LifeArea = 2,
    ---纪念碑
    Monument = 3,
    ---纪念碑广场
    MonumentSquare = 4,
    ---教学楼
    TeachingBuilding = 5,
    ---无人机社团
    DroneClub = 6,
    ---寻路过程
    FindPath = 7,
}
---数据黑板key值
local DataBoardKey = {
    None = 0,
    ---礼堂
    Auditorium = 1,
    ---生活区
    LifeArea = 2,
    ---纪念碑
    Monument = 3,
    ---纪念碑广场
    MonumentSquare = 4,
    ---教学楼
    TeachingBuilding = 5,
    ---无人机社团
    DroneClub = 6,
    ---寻路过程
    FindPath = 7,
}
--endregion


--region 状态-库洛姆-礼堂
---@class XChromeAuditoriumState: XEcologyConstructAIBaseState
local XChromeAuditoriumState = XClass(BaseState, "XChromeAuditoriumState")

---数据配置
---@overload
function XChromeAuditoriumState:InitStateConfig()
    self.StateConfig = {}
    self.StateConfig.StateEnum = StateEnum.Auditorium
    self.StateConfig.StateAnim = "Drama_Stand_07"
    self.StateConfig.TriggerId = 1
    self.StateConfig.ShowOptionId = 3
    self.StateConfig.RegisterWorldEventList = {
        EWorldEvent.ActorTrigger,
        EWorldEvent.NpcInteractStart,
        EWorldEvent.NpcInteractComplete,
    }
    self.StateConfig.BubbleDict = {
        [EEcologyBubbleType.Around] = {
            Name = "300606",
            TriggerDistance = 6,
            TriggerCD = 2,
            LoopTime = 3,
        },
        [EEcologyBubbleType.Near] = {
            Name = "300602",
            TriggerDistance = 2.5,
            TriggerCD = 2,
            LoopTime = 3,
        }
    }
end

function XChromeAuditoriumState:OnStateEnter(lastStateEnum)
    BaseState.OnStateEnter(self, lastStateEnum)
    self.StateMachine:SetDataBoard(DataBoardKey.Auditorium, 0)
end
--endregion


--region 状态-库洛姆-生活区
---@class XChromeLifeAreaState: XEcologyConstructAIBaseState
local XChromeLifeAreaState = XClass(BaseState, "XChromeLifeAreaState")

---数据配置
---@overload
function XChromeLifeAreaState:InitStateConfig()
    self.StateConfig = {}
    self.StateConfig.StateEnum = StateEnum.Monument
    self.StateConfig.StateAnim = "Drama_Stand_06"
    self.StateConfig.TriggerId = 1
    self.StateConfig.ShowOptionId = 2
    self.StateConfig.RegisterWorldEventList = {
        EWorldEvent.ActorTrigger,
        EWorldEvent.NpcInteractStart,
        EWorldEvent.NpcInteractComplete,
    }
    self.StateConfig.BubbleDict = {
        [EEcologyBubbleType.Around] = {
            Name = "300605",
            TriggerDistance = 6,
            TriggerCD = 2,
            LoopTime = 3,
        },
        [EEcologyBubbleType.Near] = {
            Name = "300601",
            TriggerDistance = 2.5,
            TriggerCD = 2,
            LoopTime = 3,
        }
    }
end

function XChromeLifeAreaState:OnStateEnter(lastStateEnum)
    BaseState.OnStateEnter(self, lastStateEnum)
    self.StateMachine:SetDataBoard(DataBoardKey.Monument, 0)
end
--endregion


--region 状态-库洛姆-纪念碑
---@class XChromeMonumentState: XEcologyConstructAIBaseState
local XChromeMonumentState = XClass(BaseState, "XChromeMonumentState")

---数据配置
---@overload
function XChromeMonumentState:InitStateConfig()
    self.StateConfig = {}
    self.StateConfig.StateEnum = StateEnum.Monument
    self.StateConfig.StateAnim = "Drama_Stand_07"
    self.StateConfig.TriggerId = 1
    self.StateConfig.ShowOptionId = 4
    self.StateConfig.RegisterWorldEventList = {
        EWorldEvent.ActorTrigger,
        EWorldEvent.NpcInteractStart,
        EWorldEvent.NpcInteractComplete,
    }
    self.StateConfig.BubbleDict = {
        [EEcologyBubbleType.Around] = {
            Name = "300606",
            TriggerDistance = 6,
            TriggerCD = 2,
            LoopTime = 3,
        },
        [EEcologyBubbleType.Near] = {
            Name = "300602",
            TriggerDistance = 2.5,
            TriggerCD = 2,
            LoopTime = 3,
        }
    }
end

function XChromeMonumentState:OnStateEnter(lastStateEnum)
    BaseState.OnStateEnter(self, lastStateEnum)
    self.StateMachine:SetDataBoard(DataBoardKey.Monument, 0)
end
--endregion


--region 状态-库洛姆-纪念碑广场
---@class XChromeMonumentSquareState: XEcologyConstructAIBaseState
local XChromeMonumentSquareState = XClass(BaseState, "XChromeMonumentSquareState")

---数据配置
---@overload
function XChromeMonumentSquareState:InitStateConfig()
    self.StateConfig = {}
    self.StateConfig.StateEnum = StateEnum.MonumentSquare
    self.StateConfig.StateAnim = "Drama_Stand_07"
    self.StateConfig.TriggerId = 1
    self.StateConfig.ShowOptionId = 4
    self.StateConfig.RegisterWorldEventList = {
        EWorldEvent.ActorTrigger,
        EWorldEvent.NpcInteractStart,
        EWorldEvent.NpcInteractComplete,
    }
    self.StateConfig.BubbleDict = {
        [EEcologyBubbleType.Around] = {
            Name = "300606",
            TriggerDistance = 6,
            TriggerCD = 2,
            LoopTime = 3,
        },
        [EEcologyBubbleType.Near] = {
            Name = "300602",
            TriggerDistance = 2.5,
            TriggerCD = 2,
            LoopTime = 3,
        }
    }
end

function XChromeMonumentSquareState:OnStateEnter(lastStateEnum)
    BaseState.OnStateEnter(self, lastStateEnum)
    self.StateMachine:SetDataBoard(DataBoardKey.MonumentSquare, 0)
end
--endregion


--region 状态-库洛姆-教学楼
---@class XChromeTeachingBuildingState: XEcologyConstructAIBaseState
local XChromeTeachingBuildingState = XClass(BaseState, "XChromeTeachingBuildingState")

---数据配置
---@overload
function XChromeTeachingBuildingState:InitStateConfig()
    self.StateConfig = {}
    self.StateConfig.StateEnum = StateEnum.TeachingBuilding
    self.StateConfig.StateAnim = "Drama_Stand_15"
    self.StateConfig.TriggerId = 1
    self.StateConfig.ShowOptionId = 1
    self.StateConfig.RegisterWorldEventList = {
        EWorldEvent.ActorTrigger,
        EWorldEvent.NpcInteractStart,
        EWorldEvent.NpcInteractComplete,
    }
    self.StateConfig.BubbleDict = {
        [EEcologyBubbleType.Around] = {
            Name = "300604",
            TriggerDistance = 6,
            TriggerCD = 2,
            LoopTime = 3,
        },
    }
end

function XChromeTeachingBuildingState:OnStateEnter(lastStateEnum)
    BaseState.OnStateEnter(self, lastStateEnum)
    self.StateMachine:SetDataBoard(DataBoardKey.TeachingBuilding, 0)
end
--endregion


--region 状态-库洛姆-无人机社团
---@class XChromeDroneClubState: XEcologyConstructAIBaseState
local XChromeDroneClubState = XClass(BaseState, "XChromeDroneClubState")

---数据配置
---@overload
function XChromeDroneClubState:InitStateConfig()
    self.StateConfig = {}
    self.StateConfig.StateEnum = StateEnum.DroneClub
    self.StateConfig.StateAnim = "Drama_Stand_07"
    self.StateConfig.TriggerId = 1
    self.StateConfig.ShowOptionId = 4
    self.StateConfig.RegisterWorldEventList = {
        EWorldEvent.ActorTrigger,
        EWorldEvent.NpcInteractStart,
        EWorldEvent.NpcInteractComplete,
    }
    self.StateConfig.BubbleDict = {
        [EEcologyBubbleType.Around] = {
            Name = "300606",
            TriggerDistance = 6,
            TriggerCD = 2,
            LoopTime = 3,
        },
        [EEcologyBubbleType.Near] = {
            Name = "300602",
            TriggerDistance = 2.5,
            TriggerCD = 2,
            LoopTime = 3,
        }
    }
end

function XChromeDroneClubState:OnStateEnter(lastStateEnum)
    BaseState.OnStateEnter(self, lastStateEnum)
    self.StateMachine:SetDataBoard(DataBoardKey.DroneClub, 0)
end
--endregion


--region 状态-库洛姆-寻路
---@class XChromeFindPathState: XEcologyFindCombinePathState @库洛姆寻路状态
local XChromeFindPathState = XClass(FindPathState, "XChromeFindPathState")

---数据配置
---@overload
function XChromeFindPathState:InitStateConfig()
    self.StateConfig = {}
    self.StateConfig.StateEnum = StateEnum.FindPath
    self.StateConfig.TriggerId = 1
    self.StateConfig.ShowOptionId = 5
    self.StateConfig.RegisterWorldEventList = {
        EWorldEvent.ActorTrigger,
        EWorldEvent.NpcInteractStart,
        EWorldEvent.NpcInteractComplete,
    }

    self.StateConfig.FindPathConfig = {}
    self.StateConfig.FindPathConfig.MeetCommanderBubbleName = "300603"
end
--endregion


--region 库洛姆法奥斯生态AI
---@class XCharChromeEcology : XEcologyConstructAIBase
---@field _stateMachine XStateMachineController 状态机
local XCharChromeEcology = XDlcScriptManager.RegCharScript(10611601, "XCharChromeEcology", Base)

--- 注册状态机状态
function XCharChromeEcology:RegisterMachineState()
    self._stateMachine:AddState(StateEnum.Auditorium, XChromeAuditoriumState.New(self._proxy))
    self._stateMachine:AddState(StateEnum.LifeArea, XChromeLifeAreaState.New(self._proxy))
    self._stateMachine:AddState(StateEnum.Monument, XChromeMonumentState.New(self._proxy))
    self._stateMachine:AddState(StateEnum.MonumentSquare, XChromeMonumentState.New(self._proxy))
    self._stateMachine:AddState(StateEnum.TeachingBuilding, XChromeTeachingBuildingState.New(self._proxy))
    self._stateMachine:AddState(StateEnum.DroneClub, XChromeDroneClubState.New(self._proxy))
    self._stateMachine:AddState(StateEnum.FindPath, XChromeFindPathState.New(self._proxy))
end

--- 注册状态转移方程
function XCharChromeEcology:RegisterMachineStateTransition()
    -- 设置寻路状态枚举值
    self.FindPathStateEnum = StateEnum.FindPath
    -- 其他状态到寻路状态
    self:RegisterInFindPathStateTransition(StateEnum.Auditorium, function()
        return self._stateMachine:CheckDataBoard(DataBoardKey.Auditorium, 1) and StateEnum.DroneClub or StateEnum.TeachingBuilding
    end, 5, 1)
    self:RegisterInFindPathStateTransition(StateEnum.LifeArea, function()
        return self._stateMachine:CheckDataBoard(DataBoardKey.LifeArea, 1) and StateEnum.Auditorium or StateEnum.Monument
    end, 5, 1)
    self:RegisterInFindPathStateTransition(StateEnum.Monument, function()
        return self._stateMachine:CheckDataBoard(DataBoardKey.Monument, 1) and StateEnum.Auditorium or StateEnum.DroneClub
    end, 5, 1)
    self:RegisterInFindPathStateTransition(StateEnum.MonumentSquare, function()
        return self._stateMachine:CheckDataBoard(DataBoardKey.MonumentSquare, 1) and StateEnum.Auditorium or StateEnum.DroneClub
    end, 5, 1)
    self:RegisterInFindPathStateTransition(StateEnum.TeachingBuilding, function()
        return self._stateMachine:CheckDataBoard(DataBoardKey.TeachingBuilding, 1) and StateEnum.Auditorium or StateEnum.Monument
    end, 5, 1)
    self:RegisterInFindPathStateTransition(StateEnum.DroneClub, function()
        return self._stateMachine:CheckDataBoard(DataBoardKey.DroneClub, 1) and StateEnum.TeachingBuilding or StateEnum.Auditorium
    end, 5, 1)
    
    -- 寻路状态到其他状态
    self:RegisterOutFindPathStateTransition(StateEnum.TeachingBuilding)
    self:RegisterOutFindPathStateTransition(StateEnum.LifeArea)
    self:RegisterOutFindPathStateTransition(StateEnum.Monument)
    self:RegisterOutFindPathStateTransition(StateEnum.Auditorium)
    self:RegisterOutFindPathStateTransition(StateEnum.DroneClub)
end

return XCharChromeEcology
--endregion
