--[[
-- XUiCommonPopupBuyAssetTargetCard.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-01-14 15:40:01
--]]

local XUiCommonPopupBuyAssetTargetCard = XClass(nil, "XUiCommonPopupBuyAssetTargetCard")

function XUiCommonPopupBuyAssetTargetCard:Ctor(ui, rootUi)
    self.GameObject = ui.gameObject
    self.Transform = ui.transform
    self.RootUi = rootUi
    XTool.InitUiObject(self)
    self.CurNumColor = self.CostNum.color
end

function XUiCommonPopupBuyAssetTargetCard:Update(config)
    self.Config = config
    self.ItemId = config.UseItemId
    self.CardImg:SetImage(XDataCenter.ItemManager.GetItemIcon(config.UseItemId))
    self.Select.gameObject:SetActiveEx(false)
    self.BtnBuy:AddEventListener(handler(self, self.OnSelect))
    self:RefreshCostNum()
end

function XUiCommonPopupBuyAssetTargetCard:OnNormal()
    self.Select.gameObject:SetActiveEx(false)
    self.BtnBuy.gameObject:SetActiveEx(true)
end

function XUiCommonPopupBuyAssetTargetCard:OnSelect()
    self.Select.gameObject:SetActiveEx(true)
    self.BtnBuy.gameObject:SetActiveEx(false)
    if self.RootUi.CurSelectCard then
        self.RootUi.CurSelectCard:OnNormal()
    end
    self.RootUi.CurSelectCard = self
    self.RootUi:Update()
end

function XUiCommonPopupBuyAssetTargetCard:OnChangeNum(num)
    local displayNum = num < 1 and 1 or num
    local costCount = displayNum * self.Config.UseItemCount
    local itemCount = XDataCenter.ItemManager.GetCount(self.ItemId)
    if itemCount < costCount then
        self.CostNum.color = CS.UnityEngine.Color.red
    else
        self.CostNum.color = self.CurNumColor
    end
    self.CostNum.text = tostring(costCount)
end

function XUiCommonPopupBuyAssetTargetCard:RefreshCostNum()
    self.CurNum.text = XDataCenter.ItemManager.GetCount(self.ItemId)
end

return XUiCommonPopupBuyAssetTargetCard
