---
--- 空花2.0 状态转移方程：生态状态->寻路状态
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ljb.
--- DateTime: 2026/3/10 20:47
---

local XLevelNpcStateTransition = require("Common/StateMachine/Transition/XLevelNpcStateTransition")

---v空花2期 其他状态到寻路状态-状态转移方程
---@class XEcologyState2FindPathTransition: XLevelNpcStateTransition 其他状态到寻路状态
---@field _stayTime number 持续时长
---@field _conditionAddCheckFunc function 额外检查方法
---@field _findPathEnterStateId number 寻路状态的目标状态
---@field _findPathGetTargetStateIdFunc function 获取寻路状态的目标状态方法
---@field _findPathCheckDistance number 寻路参数：到达距离判断
---@field _toState XEcologyFindCombinePathState
---@field _stopTimerTriggerId number 触发停止计时的Trigger
---@field _placeId number
---@field _uuid number
---@field _isTimer bool
local XEcologyState2FindPathTransition = XClass(XLevelNpcStateTransition, "XEcologyState2FindPathTransition")

---@overload
function XEcologyState2FindPathTransition:InitOther(stayTime, stopTimerTriggerId, conditionCheckFunc, findPathEnterStateId, findPathGetTargetStateIdFunc, findPathCheckDistance)
    self._stayTime = stayTime
    self._curTime = self._stayTime
    self._conditionAddCheckFunc = conditionCheckFunc
    self._findPathEnterStateId = findPathEnterStateId
    self._findPathGetTargetStateIdFunc = findPathGetTargetStateIdFunc
    self._findPathCheckDistance = findPathCheckDistance
    self._stopTimerTriggerId = stopTimerTriggerId
    self._isTimer = true
    if self._stopTimerTriggerId then
        self._proxy:RegisterEvent(EWorldEvent.ActorTrigger)
    end
end

---@overload
---@return boolean
function XEcologyState2FindPathTransition:Condition(dt)
    if not self._proxy:GetNpcActive(self._uuid) then
        return false
    end
    if self._placeId == 0 or self._proxy:CheckNpcIsInInteract(self._placeId) then
        return false
    end

    if not self._isTimer then
        return false
    end

    -- 持续时间小于0则视为无限时长
    if self._stayTime < 0 then
        -- 无限时长的需要有额外条件判断
        if self._conditionAddCheckFunc then
            return self._conditionAddCheckFunc()
        end
        return false
    end
    
    -- 有额外条件判断的需要先满足条件
    if self._conditionAddCheckFunc and not self._conditionAddCheckFunc() then
        return false
    end
    
    self._curTime = self._curTime - dt
    if self._curTime <= 0 then
        return true
    end
    return false
end

---@overload
function XEcologyState2FindPathTransition:OnTransitionBefore()
    self._curTime = self._stayTime
end

---@overload
function XEcologyState2FindPathTransition:OnTransitionAfter()
    local findPathTargetState = self._findPathGetTargetStateIdFunc()
    if self._toState and findPathTargetState then
        self._toState:InitPath(self._findPathEnterStateId, findPathTargetState, self._findPathCheckDistance)
    end
end

---@param eventType number
---@param eventArgs userdata
function XEcologyState2FindPathTransition:HandleEvent(eventType, eventArgs)
    if eventType == EWorldEvent.ActorTrigger then
        self:OnActorTrigger(eventType, eventArgs)
    end
end

function XEcologyState2FindPathTransition:OnActorTrigger(eventType, eventArgs)
    if eventArgs.TriggerId ~= self._stopTimerTriggerId
            or self._uuid ~= eventArgs.TriggerHolderUUID
            or not self._proxy:IsPlayerNpc(eventArgs.EnteredActorUUID)
    then
        return
    end
    if eventArgs.TriggerState == ETriggerState.Enter then
        self._isTimer = false
        XLog.Debug("[脚本: "..self._proxy.Id.."]状态转移方程 停止计时 从状态:"..self._fromState.StateEnum.." 到状态:"..self._toState.StateEnum)
    elseif eventArgs.TriggerState == ETriggerState.Exit then
        self._isTimer = true
        XLog.Debug("[脚本: "..self._proxy.Id.."]状态转移方程 开始计时 从状态:"..self._fromState.StateEnum.." 到状态:"..self._toState.StateEnum)
    end
end

return XEcologyState2FindPathTransition