---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/3/27 17:47
---
local tableInsert = table.insert

local CsXTextManager = CS.XTextManager

local XUiBattleRoleRoomDefaultProxy = require("XUi/XUiNewRoomSingle/XUiBattleRoleRoomDefaultProxy")
local XUiBfrtBattleRoleRoomProxy = XClass(XUiBattleRoleRoomDefaultProxy, "XUiBfrtBattleRoleRoomProxy")

---@param team XTeam
function XUiBfrtBattleRoleRoomProxy:Ctor(team, stageId)
    self.Team = team
    self.StageId = stageId
end

---@param baseBattleRoleRoom XUiBattleRoleRoom
function XUiBfrtBattleRoleRoomProxy:AOPOnStartAfter(baseBattleRoleRoom)
    self._TempGroupTeam = XDataCenter.BfrtManager.GetViewGroupFightTeams()
end

function XUiBfrtBattleRoleRoomProxy:AOPOnDestroyAfter(baseBattleRoleRoom)
    self._UpdateData(baseBattleRoleRoom)
end

function XUiBfrtBattleRoleRoomProxy:AOPOnClickBtnBack(baseBattleRoleRoom)
    self._UpdateData(baseBattleRoleRoom)
    baseBattleRoleRoom:Close()

    return true
end

function XUiBfrtBattleRoleRoomProxy:AOPOnClickFight(baseBattleRoleRoom)
    self._UpdateData(baseBattleRoleRoom)
    baseBattleRoleRoom:Close()

    return true
end

function XUiBfrtBattleRoleRoomProxy:GetBtnEnterName()
    return CsXTextManager.GetText("UIBattleRoleRoomBtnConfirm")
end

function XUiBfrtBattleRoleRoomProxy:AOPOnCharacterClickBefore(baseBattleRoleRoom, index)
    self._UpdateData(baseBattleRoleRoom)
    XEventManager.DispatchEvent(XEventId.EVENT_BFRT_TEAM_UPDATE)
    XEventManager.DispatchEvent(XEventId.EVENT_BFRT_OPEN_BATTLE_ROOM_DETAIL, baseBattleRoleRoom.StageId, index)

    return true
end

function XUiBfrtBattleRoleRoomProxy._UpdateData(baseBattleRoleRoom)
    local stageId = baseBattleRoleRoom.StageId
    ---@type XTeam
    local team = baseBattleRoleRoom.Team

    XDataCenter.BfrtManager.SetTeamFirstFightPos(stageId, team:GetFirstFightPos())
    XDataCenter.BfrtManager.SetTeamCaptainPos(stageId, team:GetCaptainPos())

    local groupId = XDataCenter.BfrtManager.GetViewGroupId()
    local curTeamIdx = XDataCenter.BfrtManager.GetCurSelectTeamIdx()
    XDataCenter.BfrtManager.SetTeamGeneralSkillId(groupId, curTeamIdx, team:GetCurGeneralSkill())
    XDataCenter.BfrtManager.UpdateViewGroupGeneralSkills()

    XDataCenter.BfrtManager.SetTeamCgIndex(groupId, curTeamIdx, team:GetEnterCgIndex(), team:GetSettleCgIndex())
    XDataCenter.BfrtManager.UpdateViewCgIndexGroup()

    local entityIds = team:GetEntityIds()
    for pos, entityId in ipairs(entityIds) do
        XDataCenter.BfrtManager.SetViewGroupFightTeamData(curTeamIdx, pos, entityId)
    end
end

--function XUiBfrtBattleRoleRoomProxy:_UpdateReplaceTeamData()
--    for _, replaceData in ipairs(self._ReplaceTeamData) do
--        XDataCenter.BfrtManager.SetViewGroupFightTeamData(replaceData.TeamIdx, replaceData.TeamPos, 0) -- 直接顶掉不进行替换
--    end
--    self._ReplaceTeamData = {}
--end

-- 回调式重复角色检测（不依赖协程）
function XUiBfrtBattleRoleRoomProxy:FilterPresetTeamEntitiyIdsCallback(teamInfoData, finishCb)
    local teamData = teamInfoData.TeamData
    if not teamData then
        if finishCb then finishCb() end
        return
    end

    local indexList = {}
    for charPos, charId in pairs(teamData) do
        if XTool.IsNumberValid(charId) then
            local otherTeamIdx, otherTeamPos = self:_CheckCharacterSameToOtherTeam(charId)
            if otherTeamIdx > 0 then
                table.insert(indexList, {Pos = charPos, CharId = charId, OtherTeamIdx = otherTeamIdx, OtherTeamPos = otherTeamPos})
            end
        end
    end

    -- 如果没有冲突，直接完成
    if #indexList == 0 then
        return
    end

    ------------------------------------------------------------
    -- 有冲突：递归弹窗处理
    ------------------------------------------------------------
    local function ShowNextConflict(idx)
        if idx > #indexList then
            -- 所有弹窗处理完，更新队伍并回调
            self.Team:UpdateEntityIds(teamData)
            self.Team:UpdateCaptainPos(teamInfoData.CaptainPos)
            self.Team:UpdateFirstFightPos(teamInfoData.FirstFightPos)
            XEventManager.DispatchEvent(XEventId.EVENT_BFRT_TEAM_UPDATE)
            if finishCb then finishCb() end
            return
        end

        local info = indexList[idx]
        local showCharacterId = XRobotManager.GetCharacterId(info.CharId)
        local characterName = XMVCA.XCharacter:GetCharacterName(showCharacterId)
        local echelonType = XDataCenter.BfrtManager.GetCurSelectFightType()
        local oldTeamName = XDataCenter.BfrtManager.GetEchelonNameTxt(echelonType, info.OtherTeamIdx)
        local curSelectTeamIdx = XDataCenter.BfrtManager.GetCurSelectTeamIdx()
        local newTeamName = XDataCenter.BfrtManager.GetEchelonNameTxt(echelonType, curSelectTeamIdx)
        local title = CsXTextManager.GetText("BfrtDeployTipTitle")
        local content = CsXTextManager.GetText("BfrtDeployTipContent", characterName, oldTeamName, newTeamName)

        -- 打开提示弹窗（纯回调）
        XUiManager.DialogTip(title, content,
            XUiManager.DialogType.Normal,
            function() -- 取消
                teamData[info.Pos] = 0
                self.Team:UpdateEntityIds(teamData)
                XEventManager.DispatchEvent(XEventId.EVENT_TEAM_PREFAB_ENTITY_CHANGE)
                ShowNextConflict(idx + 1)
            end,
            function() -- 确定
                XDataCenter.BfrtManager.SetViewGroupFightTeamData(info.OtherTeamIdx, info.OtherTeamPos, 0)
                -- 同步被替换的队伍对象，确保逻辑层数据一致
                local replacedTeam = XDataCenter.BfrtManager.GetGirdEchelonIndexTempTeam and 
                XDataCenter.BfrtManager.GetGirdEchelonIndexTempTeam(info.OtherTeamIdx)
                if replacedTeam then
                    replacedTeam:UpdateEntityTeamPos(info.CharId, info.OtherTeamPos, false)
                else
                    XLog.Warning(string.format("[BfrtProxy] 未找到被替换队伍：%s", tostring(info.OtherTeamIdx)))
                end
                self.Team:UpdateEntityIds(teamData)
                XEventManager.DispatchEvent(XEventId.EVENT_TEAM_PREFAB_ENTITY_CHANGE)
                ShowNextConflict(idx + 1)
            end
        )
    end

    ShowNextConflict(1)
end

function XUiBfrtBattleRoleRoomProxy:FilterPresetTeamEntitiyIds(teamInfoData)
    --self._ReplaceTeamData = {}
    local teamInfoDataClone = XTool.Clone(teamInfoData)
    local teamData = teamInfoDataClone.TeamData

    local asyncDialogTip = asynTask(handler(self, self._DialogTipCharacterSame))

    for charPos, charId in pairs(teamData) do
        if XTool.IsNumberValid(charId) then
            local otherTeamIdx, otherTeamPos = self:_CheckCharacterSameToOtherTeam(charId)
            if otherTeamIdx > 0 then
                asyncDialogTip(teamData, otherTeamIdx, otherTeamPos, charId, charPos)
            end
        end
    end

    return teamInfoDataClone
end

function XUiBfrtBattleRoleRoomProxy:_CheckCharacterSameToOtherTeam(characterId)
    local viewGroupTeamData = XDataCenter.BfrtManager.GetViewGroupFightTeams()
    local curSelectTeamIdx = XDataCenter.BfrtManager.GetCurSelectTeamIdx()
    for teamIdx, teamData in pairs(viewGroupTeamData) do
        if curSelectTeamIdx ~= teamIdx then
            for charPos, charId in pairs(teamData) do
                if charId == characterId then
                    return teamIdx, charPos
                end
            end
        end
    end

    return 0, 0
end

function XUiBfrtBattleRoleRoomProxy:_DialogTipCharacterSame(teamData, otherTeamIdx, otherTeamPos, characterId, charPos, cb)
    local title = CsXTextManager.GetText("BfrtDeployTipTitle")
    local showCharacterId = XRobotManager.GetCharacterId(characterId)
    local characterName = XMVCA.XCharacter:GetCharacterName(showCharacterId)
    local echelonType = XDataCenter.BfrtManager.GetCurSelectFightType()
    local oldTeamName = XDataCenter.BfrtManager.GetEchelonNameTxt(echelonType, otherTeamIdx)
    local curSelectTeamIdx = XDataCenter.BfrtManager.GetCurSelectTeamIdx()
    local newTeamName = XDataCenter.BfrtManager.GetEchelonNameTxt(echelonType, curSelectTeamIdx)
    local content = CsXTextManager.GetText("BfrtDeployTipContent", characterName, oldTeamName, newTeamName)
    XUiManager.DialogTip(title, content, XUiManager.DialogType.Normal, function()
        -- 如果不替换就保留原来的数据
        -- 判断编队是否改变了原来的成员位置
        self:_CloseCallback(teamData, charPos)
        cb()
    end, function()
        local inEchelonIndex, inEchelonType = XDataCenter.BfrtManager.CheckIsInTeamList(characterId)
        if inEchelonIndex and inEchelonType then
            local groupId = XDataCenter.BfrtManager.GetViewGroupId()
            local stageIdList = XDataCenter.BfrtManager.GetStageIdList(groupId)
            if XDataCenter.BfrtManager.CheckIsGroupStageRecordStage(groupId, stageIdList[inEchelonIndex]) then
                self:_CloseCallback(teamData, charPos)
                XDataCenter.BfrtManager.TipStageIsPass()
            else
                teamData[charPos] = characterId
                -- 缓存被替换的数据
                --tableInsert(self._ReplaceTeamData, { TeamIdx = otherTeamIdx, TeamPos = otherTeamPos })
                XDataCenter.BfrtManager.SetViewGroupFightTeamData(otherTeamIdx, otherTeamPos, 0)
            end
        end
        cb()
    end)
end

function XUiBfrtBattleRoleRoomProxy:_CloseCallback(teamData, charPos)
    local oldCharacterId = XDataCenter.BfrtManager.GetCharacterIdByTeamIdxAndPos(XDataCenter.BfrtManager.GetCurSelectTeamIdx(), charPos)
    if self:_CheckTeamDataHasCharacterWithoutPos(teamData, oldCharacterId, charPos) then
        teamData[charPos] = 0
    else
        teamData[charPos] = oldCharacterId
    end
end

function XUiBfrtBattleRoleRoomProxy:_CheckTeamDataHasCharacterWithoutPos(teamData, characterId, withoutPos)
    for pos, charId in pairs(teamData) do
        if withoutPos ~= pos then
            if charId == characterId then
                return true
            end
        end
    end

    return false
end

return XUiBfrtBattleRoleRoomProxy