--[[
-- XUiPBRCommonSkillListPanel.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-01-12 15:30:10
--]]

---@class XUiPBRCommonSkillListPanel : XUiNode
---@field _Control XPBRGameControl
local XUiPBRCommonSkillListPanel = XClass(XUiNode, "XUiPBRCommonSkillListPanel")

function XUiPBRCommonSkillListPanel:OnStart(...)
    self:InitComponents()
end

function XUiPBRCommonSkillListPanel:OnEnable()
end

function XUiPBRCommonSkillListPanel:OnDisable()
end

function XUiPBRCommonSkillListPanel:OnDestroy()
    
end

function XUiPBRCommonSkillListPanel:InitComponents()
    self.GridSkill.gameObject:SetActiveEx(false)

    -- 预生成固定格子
    local slotSkillCount = self._Control:GetClientPBRNumber('SettleSkillSlotCount')

    self.GridSkillList = {}

    for i = 1, slotSkillCount do
        local go = XUiHelper.Instantiate(self.GridSkill, self.ListSkill)

        self.GridSkillList[i] = self:GetSkillGridCls().New(go, self)
        self.GridSkillList[i]:Open()
    end
end

--- 根据传入的道具Id列表刷新Id显示，如果列表为空则显示“无”的提示
---@param itemDatas PbrItem[]
function XUiPBRCommonSkillListPanel:RefreshItemShow(itemDatas)
    for index, grid in pairs(self.GridSkillList) do
        local itemData = itemDatas and itemDatas[index] or nil
        grid:UpdateItem(itemData)
    end
end

--- 子类可重写
function XUiPBRCommonSkillListPanel:GetSkillGridCls()
    return require("XUi/XUiPBRGame/CommonUiTemplate/ItemShowListPanel/XUiPBRCommonSkillGrid")
end

return XUiPBRCommonSkillListPanel
