--[[
-- XUiPBRTask.lua
-- Auto generated by XUiLuaCodeGenerator
-- Generated at: 2026-02-04 12:30:16
--]]

local XUiPBRTaskGridTask = require("XUi/XUiPBRGame/XUiPBRTask/XUiPBRTaskGridTask")

---@class XUiPBRTask : XLuaUi
---@field _Control XPBRGameControl
---@field BtnBack XUiButton
---@field BtnMainUi XUiButton
---@field ImgEmpty UnityEngine.UI.Image
---@field BtnTabTask1 XUiButton
---@field BtnTabTask2 XUiButton
---@field TaskList UnityEngine.RectTransform
---@field GridTask UnityEngine.RectTransform
---@field BtnGroup XUiButtonGroup
---@field AnimRefresh PlayableDirector
local XUiPBRTask = XLuaUiManager.Register(XLuaUi, "UiPBRTask")

function XUiPBRTask:OnAwake()
    self:InitComponents()
end

function XUiPBRTask:InitComponents()
    -- Back Mainui Help
    self:BindExitBtns()
    
    self:InitTabGroup()
    self.GridTask.gameObject:SetActiveEx(false)
    self.DynamicTable = XUiHelper.DynamicTableNormal(self, self.TaskList, XUiPBRTaskGridTask)
end

function XUiPBRTask:OnStart(...)
    -- 默认选中第一个页签
    self.BtnGroup:SelectIndex(1)
end

function XUiPBRTask:OnEnable()
    XEventManager.AddEventListener(XEventId.EVENT_FINISH_TASK, self.RefreshCurTabTasks, self)
    XEventManager.AddEventListener(XEventId.EVENT_TASK_SYNC, self.RefreshCurTabTasks, self)
    self:RefreshTabReddot()
end

function XUiPBRTask:OnDisable()
    XEventManager.RemoveEventListener(XEventId.EVENT_FINISH_TASK, self.RefreshCurTabTasks, self)
    XEventManager.RemoveEventListener(XEventId.EVENT_TASK_SYNC, self.RefreshCurTabTasks, self)
end

function XUiPBRTask:OnDestroy()
end

function XUiPBRTask:InitTabGroup()
    -- 收集页签
    local tabButtonList = {}

    for i = 1, 10 do
        local ui = self["BtnTabTask" .. i]
        if ui then
            table.insert(tabButtonList, ui)
        else
            -- Ui一般都是连续的
            break
        end
    end

    -- 获取当前活动配置，隐藏多余的页签
    local taskGroupIds = self._Control.TaskControl:GetCurActivityTaskGroupIds()
    
    local beginHideIndex = taskGroupIds and (#taskGroupIds + 1) or 1
    
    for i = 1, #tabButtonList do
        if i < beginHideIndex then
            tabButtonList[i].gameObject:SetActiveEx(true)
            
            local taskGroupCfg = self._Control.TaskControl:GetTablePBRTaskGroupCfgById(taskGroupIds[i])

            if taskGroupCfg then
                tabButtonList[i]:SetNameByGroup(0, taskGroupCfg.Name)
            end
        else
            tabButtonList[i].gameObject:SetActiveEx(false)
        end
    end
    
    self.BtnGroup:Init(tabButtonList, handler(self, self.OnTabGroupSelect), 1)
    
    -- 缓存页签列表，用于蓝点等控制
    self.TabButtonList = tabButtonList
    self.TaskGroupIds = taskGroupIds
end

function XUiPBRTask:OnTabGroupSelect(index)
    if self.CurTabIndex == index then
        return
    end
    
    self.CurTabIndex = index
    
    self:RefreshCurTabTasks()
end

function XUiPBRTask:RefreshCurTabTasks()
    self:RefreshTabReddot()

    --- 刷新显示任务列表
    local taskGroupId = self.TaskGroupIds and self.TaskGroupIds[self.CurTabIndex]

    if XTool.IsNumberValidEx(taskGroupId) then
        local taskDataList = self._Control.TaskControl:GetTaskDataListByGroupId(taskGroupId, true)

        if not XTool.IsTableEmpty(taskDataList) then
            self.DynamicTable:SetDataSource(taskDataList)
            self.DynamicTable:ReloadDataASync(1)
            self.ImgEmpty.gameObject:SetActiveEx(false)
            return
        end
    end

    self.DynamicTable:SetDataSource(nil)
    self.DynamicTable:RecycleAllTableGrid()
    self.ImgEmpty.gameObject:SetActiveEx(true)
end

function XUiPBRTask:RefreshTabReddot()
    if not self.TabButtonList or not self.TaskGroupIds then
        return
    end

    for i, btn in ipairs(self.TabButtonList) do
        local taskGroupId = self.TaskGroupIds[i]

        if XTool.IsNumberValidEx(taskGroupId) then
            local isRed = XMVCA.XPBRGame:ReddotIsTaskGroupAchieved(taskGroupId)
            btn:ShowReddot(isRed)
        end
    end
end

---@param grid XUiPBRTaskGridTask
function XUiPBRTask:OnDynamicTableEvent(event, index, grid)
    if event == DYNAMIC_DELEGATE_EVENT.DYNAMIC_GRID_ATINDEX then
        local taskData = self.DynamicTable.DataSource[index]

        if XTool.IsNumberValidEx(taskData) then
            -- 是任务Id
            taskData = XDataCenter.TaskManager.GetTaskDataById(taskData)
        end

        grid:ResetData(taskData)
    end
end

return XUiPBRTask
