---
--- 空花2.0生态构造体系统管控的AI 状态基础脚本
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2026/3/15 21:17
---

local Base = require("Character/BigWorld/XEcologyCharAI/XEcologyCharAIBaseState")

---@class XEcologyConstructAIBaseState: XEcologyCharAIBaseState
---@field StateConfig XEcologyCharAIStateConfig
local XEcologyConstructAIBaseState = XClass(Base, "XEcologyConstructAIBaseState")

---@overload
---状态进入时
---@param lastStateEnum number 上个状态
function XEcologyConstructAIBaseState:OnStateEnter(lastStateEnum)
    if self.StateConfig == nil then
        XScriptTool.EcologyError(self, "生态AI没有初始化数据")
        return
    end
    self._proxy:OnEcologyConstructCmpChangeState(self._placeId, self.StateConfig.StateEnum)
    self:RegisterWorldEvent()
    self:InitAiBubble()
    self:UpdateOptionActive()
    self:PlayPerformAnim()
end

---@overload
---状态进入时
---@param nextStateEnum number 下个状态
function XEcologyConstructAIBaseState:OnStateLeave(nextStateEnum)
    self:UnRegisterWorldEvent()
end

---@overload
---状态进行时（每帧更新)
function XEcologyConstructAIBaseState:OnStateUpdate(dt)
    if self.StateConfig == nil then
        return
    end
    self:UpdateAiBubble(dt)
end

---@overload
---额外事件监听
---@param eventType number EWorldEvent
---@param eventArgs table 对应时间参数
function XEcologyConstructAIBaseState:HandleEvent(eventType, eventArgs)
    if self.StateConfig == nil then
        return
    end
    if eventType == EWorldEvent.ActorTrigger then
        self:OnActorTrigger(eventArgs)
    elseif eventType == EWorldEvent.NpcInteractStart then
        self:OnNpcInteractStart(eventArgs)
    elseif eventType == EWorldEvent.NpcInteractComplete then
        self:OnNpcInteractComplete(eventArgs)
    end
end

return XEcologyConstructAIBaseState